var pokemonList = [
  new Pokemon(722, 'Rowlet', ['Grass', 'Flying']),
  new Pokemon(723, 'Dartrix', ['Grass', 'Flying']),
  new Pokemon(724, 'Decidueye', ['Grass', 'Ghost']),
  new Pokemon(725, 'Litten', ['Fire']),
  new Pokemon(726, 'Torracat', ['Fire']),
  new Pokemon(727, 'Incineroar', ['Fire', 'Dark']),
  new Pokemon(728, 'Popplio', ['Water']),
  new Pokemon(729, 'Brionne', ['Water']),
  new Pokemon(730, 'Primarina', ['Water', 'Fairy']),
  new Pokemon(731, 'Pikipek', ['Normal', 'Flying']),
  new Pokemon(732, 'Trumbeak', ['Normal', 'Flying']),
  new Pokemon(733, 'Toucannon', ['Normal', 'Flying']),
  new Pokemon(734, 'Yungoos', ['Normal']),
  new Pokemon(735, 'Gumshoos', ['Normal']),
  new Pokemon(19, 'Rattata', ['Normal']),
  new Pokemon(20, 'Raticate', ['Normal']),
  new Pokemon(10, 'Caterpie', ['Bug']),
  new Pokemon(11, 'Metapod', ['Bug']),
  new Pokemon(12, 'Butterfree', ['Bug', 'Flying']),
  new Pokemon(165, 'Ledyba', ['Bug', 'Flying']),
  new Pokemon(166, 'Ledian', ['Bug', 'Flying']),
  new Pokemon(167, 'Spinarak', ['Bug', 'Poison']),
  new Pokemon(168, 'Ariados', ['Bug', 'Poison']),
  new Pokemon(427, 'Buneary', ['Normal']),
  new Pokemon(428, 'Lopunny', ['Normal']),
  new Pokemon(686, 'Inkay', ['Dark', 'Psychic']),
  new Pokemon(687, 'Malamar', ['Dark', 'Psychic']),
  new Pokemon(570, 'Zorua', ['Dark']),
  new Pokemon(571, 'Zoroark', ['Dark']),
  new Pokemon(676, 'Furfrou', ['Normal']),
  new Pokemon(172, 'Pichu', ['Electric']),
  new Pokemon(25, 'Pikachu', ['Electric']),
  new Pokemon(26, 'Raichu', ['Electric']),
  new Pokemon(736, 'Grubbin', ['Bug']),
  new Pokemon(737, 'Charjabug', ['Bug', 'Electric']),
  new Pokemon(738, 'Vikavolt', ['Bug', 'Electric']),
  new Pokemon(438, 'Bonsly', ['Rock']),
  new Pokemon(185, 'Sudowoodo', ['Rock']),
  new Pokemon(440, 'Happiny', ['Normal']),
  new Pokemon(113, 'Chansey', ['Normal']),
  new Pokemon(242, 'Blissey', ['Normal']),
  new Pokemon(446, 'Munchlax', ['Water']),
  new Pokemon(143, 'Snorlax', ['Water']),
  new Pokemon(79, 'Slowpoke', ['Water', 'Psychic']),
  new Pokemon(80, 'Slowbro', ['Water', 'Psychic']),
  new Pokemon(199, 'Slowking', ['Water', 'Psychic']),
  new Pokemon(278, 'Wingull', ['Water', 'Flying']),
  new Pokemon(279, 'Pelipper', ['Water', 'Flying']),
  new Pokemon(63, 'Abra', ['Psychic']),
  new Pokemon(64, 'Kadabra', ['Psychic']),
  new Pokemon(65, 'Alakazam', ['Psychic']),
  new Pokemon(52, 'Meowth', ['Normal']),
  new Pokemon(53, 'Persian', ['Normal']),
  new Pokemon(81, 'Magnemite', ['Electric', 'Steel']),
  new Pokemon(82, 'Magneton', ['Electric', 'Steel']),
  new Pokemon(462, 'Magnezone', ['Electric', 'Steel']),
  new Pokemon(88, 'Grimer', ['Poison']),
  new Pokemon(89, 'Muk', ['Poison']),
  new Pokemon(439, 'Mime Jr.', ['Psychic', 'Fairy']),
  new Pokemon(122, 'Mr. Mime', ['Psychic', 'Fairy']),
  new Pokemon(23, 'Ekans', ['Poison']),
  new Pokemon(24, 'Arbok', ['Poison']),
  new Pokemon(206, 'Dunsparce', ['Normal']),
  new Pokemon(58, 'Growlithe', ['Fire']),
  new Pokemon(59, 'Arcanine', ['Fire']),
  new Pokemon(96, 'Drowzee', ['Psychic']),
  new Pokemon(97, 'Hypno', ['Psychic']),
  new Pokemon(296, 'Makuhita', ['Fighting']),
  new Pokemon(297, 'Hariyama', ['Fighting']),
  new Pokemon(235, 'Smeargle', ['Normal']),
  new Pokemon(739, 'Crabrawler', ['Fighting']),
  new Pokemon(740, 'Crabominable', ['Fighting', 'Ice']),
  new Pokemon(92, 'Gastly', ['Ghost', 'Poison']),
  new Pokemon(93, 'Haunter', ['Ghost', 'Poison']),
  new Pokemon(94, 'Gengar', ['Ghost', 'Poison']),
  new Pokemon(425, 'Drifloon', ['Ghost', 'Flying']),
  new Pokemon(426, 'Drifblim', ['Ghost', 'Flying']),
  new Pokemon(198, 'Murkrow', ['Dark', 'Flying']),
  new Pokemon(430, 'Honchkrow', ['Dark', 'Flying']),
  new Pokemon(41, 'Zubat', ['Poison', 'Flying']),
  new Pokemon(42, 'Golbat', ['Poison', 'Flying']),
  new Pokemon(169, 'Crobat', ['Poison', 'Flying']),
  new Pokemon(714, 'Noibat', ['Flying', 'Dragon']),
  new Pokemon(715, 'Noivern', ['Flying', 'Dragon']),
  new Pokemon(50, 'Diglett', ['Ground']),
  new Pokemon(51, 'Dugtrio', ['Ground']),
  new Pokemon(21, 'Spearow', ['Normal', 'Flying']),
  new Pokemon(22, 'Fearow', ['Normal', 'Flying']),
  new Pokemon(627, 'Rufflet', ['Normal', 'Flying']),
  new Pokemon(628, 'Braviary', ['Normal', 'Flying']),
  new Pokemon(629, 'Vullaby', ['Dark', 'Flying']),
  new Pokemon(630, 'Mandibuzz', ['Dark', 'Flying']),
  new Pokemon(56, 'Mankey', ['Fighting']),
  new Pokemon(57, 'Primeape', ['Fighting']),
  new Pokemon(225, 'Delibird', ['Ice', 'Flying']),
  new Pokemon(701, 'Hawlucha', ['Fighting', 'Flying']),
  new Pokemon(741, 'Oricorio', ['Fire', 'Flying']),
  new Pokemon(742, 'Cutiefly', ['Bug', 'Fairy']),
  new Pokemon(743, 'Ribombee', ['Bug', 'Fairy']),
  new Pokemon(669, 'Flabébé', ['Fairy']),
  new Pokemon(670, 'Floette', ['Fairy']),
  new Pokemon(671, 'Florges', ['Fairy']),
  new Pokemon(548, 'Petilil', ['Grass']),
  new Pokemon(549, 'Lilligant', ['Grass']),
  new Pokemon(546, 'Cottonee', ['Grass', 'Fairy']),
  new Pokemon(547, 'Whimsicott', ['Grass', 'Fairy']),
  new Pokemon(54, 'Psyduck', ['Water']),
  new Pokemon(55, 'Golduck', ['Water']),
  new Pokemon(238, 'Smoochum', ['Ice', 'Psychic']),
  new Pokemon(124, 'Jynx', ['Ice', 'Psychic']),
  new Pokemon(129, 'Magikarp', ['Water']),
  new Pokemon(130, 'Gyarados', ['Water', 'Flying']),
  new Pokemon(339, 'Barboach', ['Water', 'Ground']),
  new Pokemon(340, 'Whiscash', ['Water', 'Ground']),
  new Pokemon(86, 'Seel', ['Water']),
  new Pokemon(87, 'Dewgong', ['Water', 'Ice']),
  new Pokemon(66, 'Machop', ['Fighting']),
  new Pokemon(67, 'Machoke', ['Fighting']),
  new Pokemon(68, 'Machamp', ['Fighting']),
  new Pokemon(524, 'Roggenrola', ['Rock']),
  new Pokemon(525, 'Boldore', ['Rock']),
  new Pokemon(526, 'Gigalith', ['Rock']),
  new Pokemon(703, 'Carbink', ['Rock', 'Fairy']),
  new Pokemon(302, 'Sableye', ['Dark', 'Ghost']),
  new Pokemon(303, 'Mawile', ['Steel', 'Fairy']),
  new Pokemon(744, 'Rockruff', ['Rock']),
  new Pokemon(745, 'Lycanroc', ['Rock']),
  new Pokemon(327, 'Spinda', ['Normal']),
  new Pokemon(72, 'Tentacool', ['Water', 'Poison']),
  new Pokemon(73, 'Tentacruel', ['Water', 'Poison']),
  new Pokemon(456, 'Finneon', ['Water']),
  new Pokemon(457, 'Lumineon', ['Water']),
  new Pokemon(746, 'Wishiwashi', ['Water']),
  new Pokemon(370, 'Luvdisc', ['Water']),
  new Pokemon(222, 'Corsola', ['Water', 'Rock']),
  new Pokemon(747, 'Mareanie', ['Poison', 'Water']),
  new Pokemon(748, 'Toxapex', ['Poison', 'Water']),
  new Pokemon(90, 'Shellder', ['Water']),
  new Pokemon(91, 'Cloyster', ['Water', 'Ice']),
  new Pokemon(366, 'Clamperl', ['Water']),
  new Pokemon(367, 'Huntail', ['Water']),
  new Pokemon(368, 'Gorebyss', ['Water']),
  new Pokemon(223, 'Remoraid', ['Water']),
  new Pokemon(224, 'Octillery', ['Water']),
  new Pokemon(458, 'Mantyke', ['Water', 'Flying']),
  new Pokemon(226, 'Mantine', ['Water', 'Flying']),
  new Pokemon(371, 'Bagon', ['Dragon']),
  new Pokemon(372, 'Shelgon', ['Dragon']),
  new Pokemon(373, 'Salamence', ['Dragon', 'Flying']),
  new Pokemon(506, 'Lillipup', ['Normal']),
  new Pokemon(507, 'Herdier', ['Normal']),
  new Pokemon(508, 'Stoutland', ['Normal']),
  new Pokemon(133, 'Eevee', ['Normal']),
  new Pokemon(134, 'Vaporeon', ['Water']),
  new Pokemon(135, 'Jolteon', ['Electric']),
  new Pokemon(136, 'Flareon', ['Fire']),
  new Pokemon(196, 'Espeon', ['Psychic']),
  new Pokemon(197, 'Umbreon', ['Dark']),
  new Pokemon(470, 'Leafeon', ['Grass']),
  new Pokemon(471, 'Glaceon', ['Ice']),
  new Pokemon(700, 'Sylveon', ['Fairy']),
  new Pokemon(179, 'Mareep', ['Electric']),
  new Pokemon(180, 'Flaaffy', ['Electric']),
  new Pokemon(181, 'Ampharos', ['Electric']),
  new Pokemon(749, 'Mudbray', ['Ground']),
  new Pokemon(750, 'Mudsdale', ['Ground']),
  new Pokemon(174, 'Igglybuff', ['Normal', 'Fairy']),
  new Pokemon(39, 'Jigglypuff', ['Normal', 'Fairy']),
  new Pokemon(40, 'Wigglytuff', ['Normal', 'Fairy']),
  new Pokemon(128, 'Tauros', ['Normal']),
  new Pokemon(241, 'Miltank', ['Normal']),
  new Pokemon(283, 'Surskit', ['Bug', 'Water']),
  new Pokemon(284, 'Masquerain', ['Bug', 'Flying']),
  new Pokemon(751, 'Dewpider', ['Water', 'Bug']),
  new Pokemon(752, 'Araquanid', ['Water', 'Bug']),
  new Pokemon(753, 'Fomantis', ['Grass']),
  new Pokemon(754, 'Lurantis', ['Grass']),
  new Pokemon(755, 'Morelull', ['Grass', 'Fairy']),
  new Pokemon(756, 'Shiinotic', ['Grass', 'Fairy']),
  new Pokemon(46, 'Paras', ['Bug', 'Grass']),
  new Pokemon(47, 'Parasect', ['Bug', 'Grass']),
  new Pokemon(60, 'Poliwag', ['Water']),
  new Pokemon(61, 'Poliwhirl', ['Water']),
  new Pokemon(62, 'Poliwrath', ['Water', 'Fighting']),
  new Pokemon(186, 'Politoed', ['Water']),
  new Pokemon(118, 'Goldeen', ['Water']),
  new Pokemon(119, 'Seaking', ['Water']),
  new Pokemon(550, 'Basculin', ['Water']),
  new Pokemon(349, 'Feebas', ['Water']),
  new Pokemon(350, 'Milotic', ['Water']),
  new Pokemon(594, 'Alomomola', ['Water']),
  new Pokemon(661, 'Fletchling', ['Normal', 'Flying']),
  new Pokemon(662, 'Fletchinder', ['Fire', 'Flying']),
  new Pokemon(663, 'Talonflame', ['Fire', 'Flying']),
  new Pokemon(757, 'Salandit', ['Poison', 'Fire']),
  new Pokemon(758, 'Salazzle', ['Poison', 'Fire']),
  new Pokemon(104, 'Cubone', ['Ground']),
  new Pokemon(105, 'Marowak', ['Ground']),
  new Pokemon(115, 'Kangaskhan', ['Normal']),
  new Pokemon(240, 'Magby', ['Fire']),
  new Pokemon(126, 'Magmar', ['Fire']),
  new Pokemon(467, 'Magmortar', ['Fire']),
  new Pokemon(636, 'Larvesta', ['Bug', 'Fire']),
  new Pokemon(637, 'Volcarona', ['Bug', 'Fire']),
  new Pokemon(759, 'Stufful', ['Normal', 'Fighting']),
  new Pokemon(760, 'Bewear', ['Normal', 'Fighting']),
  new Pokemon(761, 'Bounsweet', ['Grass']),
  new Pokemon(762, 'Steenee', ['Grass']),
  new Pokemon(763, 'Tsareena', ['Grass']),
  new Pokemon(764, 'Comfey', ['Fairy']),
  new Pokemon(127, 'Pinsir', ['Bug']),
  new Pokemon(163, 'Hoothoot', ['Normal', 'Flying']),
  new Pokemon(164, 'Noctowl', ['Normal', 'Flying']),
  new Pokemon(352, 'Kecleon', ['Normal']),
  new Pokemon(765, 'Oranguru', ['Normal']),
  new Pokemon(766, 'Passimian', ['Steel', 'Fairy']),
  new Pokemon(704, 'Goomy', ['Rock', 'Dragon']),
  new Pokemon(705, 'Sliggoo', ['Rock', 'Dragon']),
  new Pokemon(706, 'Goodra', ['Rock', 'Ice']),
  new Pokemon(351, 'Castform', ['Rock', 'Ice']),
  new Pokemon(767, 'Wimpod', ['Rock', 'Flying']),
  new Pokemon(768, 'Golisopod', ['Grass', 'Steel']),
  new Pokemon(120, 'Staryu', ['Grass', 'Steel']),
  new Pokemon(121, 'Starmie', ['Fairy']),
  new Pokemon(769, 'Sandygast', ['Fairy']),
  new Pokemon(770, 'Palossand', ['Electric']),
  new Pokemon(138, 'Omanyte', ['Electric']),
  new Pokemon(139, 'Omastar', ['Dark', 'Fire']),
  new Pokemon(140, 'Kabuto', ['Dark', 'Fire']),
  new Pokemon(141, 'Kabutops', ['Normal']),
  new Pokemon(345, 'Lileep', ['Water']),
  new Pokemon(346, 'Cradily', ['Electric']),
  new Pokemon(347, 'Anorith', ['Fire']),
  new Pokemon(348, 'Armaldo', ['Psychic']),
  new Pokemon(408, 'Cranidos', ['Dark']),
  new Pokemon(409, 'Rampardos', ['Grass']),
  new Pokemon(410, 'Shieldon', ['Ice']),
  new Pokemon(411, 'Bastiodon', ['Fairy']),
  new Pokemon(566, 'Archen', ['Electric', 'Flying']),
  new Pokemon(567, 'Archeops', ['Bug', 'Flying']),
  new Pokemon(564, 'Tirtouga', ['Bug', 'Flying']),
  new Pokemon(565, 'Carracosta', ['Fighting', 'Flying']),
  new Pokemon(696, 'Tyrunt', ['Psychic', 'Flying']),
  new Pokemon(697, 'Tyrantrum', ['Ground', 'Ghost']),
  new Pokemon(698, 'Amaura', ['Ground', 'Ghost']),
  new Pokemon(699, 'Aurorus', ['Rock']),
  new Pokemon(246, 'Larvitar', ['Rock', 'Steel']),
  new Pokemon(247, 'Pupitar', ['Fighting']),
  new Pokemon(248, 'Tyranitar', ['Fighting']),
  new Pokemon(708, 'Phantump', ['Fighting']),
  new Pokemon(709, 'Trevenant', ['Fighting']),
  new Pokemon(177, 'Natu', ['Normal', 'Flying']),
  new Pokemon(178, 'Xatu', ['Normal', 'Flying']),
  new Pokemon(299, 'Nosepass', ['Normal', 'Flying']),
  new Pokemon(476, 'Probopass', ['Poison', 'Dark']),
  new Pokemon(771, 'Pyukumuku', ['Poison', 'Dark']),
  new Pokemon(170, 'Chinchou', ['Poison']),
  new Pokemon(171, 'Lanturn', ['Poison']),
  new Pokemon(772, 'Type꞉ Null', ['Normal']),
  new Pokemon(773, 'Silvally', ['Poison']),
  new Pokemon(803, 'Poipole', ['Poison']),
  new Pokemon(804, 'Naganadel', ['Poison', 'Ground']),
  new Pokemon(718, 'Zygarde', ['Electric', 'Fairy']),
  new Pokemon(568, 'Trubbish', ['Psychic']),
  new Pokemon(569, 'Garbodor', ['Psychic']),
  new Pokemon(572, 'Minccino', ['Psychic', 'Fairy']),
  new Pokemon(573, 'Cinccino', ['Psychic', 'Fairy']),
  new Pokemon(204, 'Pineco', ['Psychic']),
  new Pokemon(205, 'Forretress', ['Psychic']),
  new Pokemon(227, 'Skarmory', ['Psychic']),
  new Pokemon(132, 'Ditto', ['Psychic']),
  new Pokemon(173, 'Cleffa', ['Psychic']),
  new Pokemon(35, 'Clefairy', ['Rock']),
  new Pokemon(36, 'Clefable', ['Rock']),
  new Pokemon(605, 'Elgyem', ['Rock']),
  new Pokemon(606, 'Beheeyem', ['Dark', 'Ghost']),
  new Pokemon(774, 'Minior', ['Rock', 'Fairy']),
  new Pokemon(374, 'Beldum', ['Normal']),
  new Pokemon(375, 'Metang', ['Normal']),
  new Pokemon(376, 'Metagross', ['Electric']),
  new Pokemon(137, 'Porygon', ['Electric']),
  new Pokemon(233, 'Porygon2', ['Electric']),
  new Pokemon(474, 'Porygon-Z', ['Bug']),
  new Pokemon(674, 'Pancham', ['Bug', 'Fighting']),
  new Pokemon(675, 'Pangoro', ['Electric']),
  new Pokemon(775, 'Komala', ['Water', 'Psychic']),
  new Pokemon(324, 'Torkoal', ['Water', 'Psychic']),
  new Pokemon(776, 'Turtonator', ['Water', 'Psychic']),
  new Pokemon(228, 'Houndour', ['Grass', 'Psychic']),
  new Pokemon(229, 'Houndoom', ['Grass', 'Psychic']),
  new Pokemon(702, 'Dedenne', ['Normal', 'Flying']),
  new Pokemon(777, 'Togedemaru', ['Water', 'Flying']),
  new Pokemon(309, 'Electrike', ['Water', 'Flying']),
  new Pokemon(310, 'Manectric', ['Water']),
  new Pokemon(239, 'Elekid', ['Water']),
  new Pokemon(125, 'Electabuzz', ['Water']),
  new Pokemon(466, 'Electivire', ['Water']),
  new Pokemon(74, 'Geodude', ['Water']),
  new Pokemon(75, 'Graveler', ['Water', 'Rock']),
  new Pokemon(76, 'Golem', ['Water', 'Electric']),
  new Pokemon(551, 'Sandile', ['Water', 'Electric']),
  new Pokemon(552, 'Krokorok', ['Water']),
  new Pokemon(553, 'Krookodile', ['Water', 'Ice']),
  new Pokemon(328, 'Trapinch', ['Ice', 'Flying']),
  new Pokemon(329, 'Vibrava', ['Electric', 'Flying']),
  new Pokemon(330, 'Flygon', ['Fire', 'Flying']),
  new Pokemon(443, 'Gible', ['Ground']),
  new Pokemon(444, 'Gabite', ['Ground']),
  new Pokemon(445, 'Garchomp', ['Ground']),
  new Pokemon(343, 'Baltoy', ['Ground', 'Dragon']),
  new Pokemon(344, 'Claydol', ['Ground', 'Dragon']),
  new Pokemon(622, 'Golett', ['Dragon', 'Ground']),
  new Pokemon(623, 'Golurk', ['Dragon', 'Ground']),
  new Pokemon(707, 'Klefki', ['Dragon', 'Ground']),
  new Pokemon(778, 'Mimikyu', ['Rock', 'Ground']),
  new Pokemon(353, 'Shuppet', ['Rock', 'Ground']),
  new Pokemon(354, 'Banette', ['Rock', 'Ground']),
  new Pokemon(592, 'Frillish', ['Fire']),
  new Pokemon(593, 'Jellicent', ['Fire', 'Rock']),
  new Pokemon(779, 'Bruxish', ['Bug', 'Rock']),
  new Pokemon(780, 'Drampa', ['Poison', 'Dark']),
  new Pokemon(359, 'Absol', ['Poison', 'Dark']),
  new Pokemon(361, 'Snorunt', ['Water', 'Ground']),
  new Pokemon(362, 'Glalie', ['Water', 'Ground']),
  new Pokemon(478, 'Froslass', ['Dragon']),
  new Pokemon(215, 'Sneasel', ['Dragon']),
  new Pokemon(461, 'Weavile', ['Dragon']),
  new Pokemon(27, 'Sandshrew', ['Bug']),
  new Pokemon(28, 'Sandslash', ['Bug', 'Steel']),
  new Pokemon(37, 'Vulpix', ['Water']),
  new Pokemon(38, 'Ninetales', ['Water']),
  new Pokemon(582, 'Vanillite', ['Grass', 'Poison']),
  new Pokemon(583, 'Vanillish', ['Grass', 'Poison']),
  new Pokemon(584, 'Vanilluxe', ['Grass', 'Poison']),
  new Pokemon(559, 'Scraggy', ['Grass']),
  new Pokemon(560, 'Scrafty', ['Ghost', 'Poison']),
  new Pokemon(624, 'Pawniard', ['Ghost', 'Poison']),
  new Pokemon(625, 'Bisharp', ['Ghost', 'Poison']),
  new Pokemon(209, 'Snubbull', ['Water']),
  new Pokemon(210, 'Granbull', ['Water']),
  new Pokemon(422, 'Shellos', ['Water', 'Fighting']),
  new Pokemon(423, 'Gastrodon', ['Water']),
  new Pokemon(369, 'Relicanth', ['Poison']),
  new Pokemon(781, 'Dhelmise', ['Poison']),
  new Pokemon(318, 'Carvanha', ['Ground', 'Electric']),
  new Pokemon(319, 'Sharpedo', ['Water', 'Ground']),
  new Pokemon(690, 'Skrelp', ['Water', 'Ground']),
  new Pokemon(691, 'Dragalge', ['Dark']),
  new Pokemon(692, 'Clauncher', ['Dark']),
  new Pokemon(693, 'Clawitzer', ['Dark']),
  new Pokemon(320, 'Wailmer', ['Dark']),
  new Pokemon(321, 'Wailord', ['Normal']),
  new Pokemon(131, 'Lapras', ['Normal']),
  new Pokemon(357, 'Tropius', ['Dark', 'Steel']),
  new Pokemon(102, 'Exeggcute', ['Dark', 'Steel']),
  new Pokemon(103, 'Exeggutor', ['Steel', 'Fairy']),
  new Pokemon(341, 'Corphish', ['Dark', 'Flying']),
  new Pokemon(342, 'Crawdaunt', ['Dark', 'Flying']),
  new Pokemon(619, 'Mienfoo', ['Grass', 'Poison']),
  new Pokemon(620, 'Mienshao', ['Grass', 'Poison']),
  new Pokemon(782, 'Jangmo-o', ['Water', 'Grass']),
  new Pokemon(783, 'Hakamo-o', ['Water', 'Grass']),
  new Pokemon(784, 'Kommo-o', ['Water', 'Grass']),
  new Pokemon(587, 'Emolga', ['Water']),
  new Pokemon(123, 'Scyther', ['Water']),
  new Pokemon(212, 'Scizor', ['Water']),
  new Pokemon(214, 'Heracross', ['Ghost', 'Grass']),
  new Pokemon(190, 'Aipom', ['Ghost', 'Grass']),
  new Pokemon(424, 'Ambipom', ['Ghost', 'Grass']),
  new Pokemon(667, 'Litleo', ['Ghost', 'Grass']),
  new Pokemon(668, 'Pyroar', ['Ghost', 'Fire']),
  new Pokemon(200, 'Misdreavus', ['Ghost', 'Fire']),
  new Pokemon(429, 'Mismagius', ['Ghost', 'Fire']),
  new Pokemon(621, 'Druddigon', ['Electric', 'Ghost']),
  new Pokemon(108, 'Lickitung', ['Electric', 'Steel']),
  new Pokemon(463, 'Lickilicky', ['Electric', 'Steel']),
  new Pokemon(447, 'Riolu', ['Electric', 'Steel']),
  new Pokemon(448, 'Lucario', ['Electric']),
  new Pokemon(147, 'Dratini', ['Electric']),
  new Pokemon(148, 'Dragonair', ['Poison']),
  new Pokemon(149, 'Dragonite', ['Poison']),
  new Pokemon(142, 'Aerodactyl', ['Ice', 'Ground']),
  new Pokemon(785, 'Tapu Koko', ['Ice', 'Ground']),
  new Pokemon(786, 'Tapu Lele', ['Ice', 'Ground']),
  new Pokemon(787, 'Tapu Bulu', ['Ice']),
  new Pokemon(788, 'Tapu Fini', ['Ice']),
  new Pokemon(789, 'Cosmog', ['Ice']),
  new Pokemon(790, 'Cosmoem', ['Ice']),
  new Pokemon(791, "Solgaleo", ['Ice', 'Psychic']),
  new Pokemon(792, 'Lunala', ['Ice', 'Psychic']),
  new Pokemon(793, 'Nihilego', ['Ice']),
  new Pokemon(805, 'Stakataka', ['Ice']),
  new Pokemon(806, 'Blacephalon', ['Ice']),
  new Pokemon(794, 'Buzzwole', ['Grass', 'Ice']),
  new Pokemon(795, 'Pheromosa', ['Grass', 'Ice']),
  new Pokemon(796, 'Xurkitree', ['Ice', 'Flying']),
  new Pokemon(797, 'Celesteela', ['Dark', 'Ice']),
  new Pokemon(798, 'Kartana', ['Dark', 'Ice']),
  new Pokemon(799, 'Guzzlord', ['Fighting']),
  new Pokemon(800, 'Necrozma', ['Fighting']),
  new Pokemon(801, 'Magearna', ['Fighting']),
  new Pokemon(802, 'Marshadow', ['Fire']),
  new Pokemon(807, 'Zeraora', ['Electric'])
]

function loadAlola() {
  $('#Center').text("The Alolan Pokémon List by Pokédex Number");
  $('#pokemon-container').empty();

  for (var j = 0; j < pokemonList.length; j++) {
    pokemonList[j].loadToPage();
    pokemonList[j].ShowTypes();
  }

}
