var hoennPokemonList = [
  new Pokemon(1, 252, 'Treecko', ['Grass'], 'Treecko Image'),
  new Pokemon(2, 253, 'Grovyle', ['Grass'], 'Grovyle Image'),
  new Pokemon(3, 254, 'Sceptile', ['Grass'], 'Sceptile Image'),
  new Pokemon(4, 255, 'Torchic', ['Fire'], 'Torchic Image'),
  new Pokemon(5, 256, 'Combusken', ['Fire', 'Fighting'], 'Combusken Image'),
  new Pokemon(6, 257, 'Blaziken', ['Fire', 'Fighting'], 'Blaziken Image'),
  new Pokemon(7, 258, 'Mudkip', ['Water'], 'Mudkip Image'),
  new Pokemon(8, 259, 'Marshtomp', ['Water', 'Ground'], 'Marshtomp Image'),
  new Pokemon(9, 260, 'Swampert', ['Water', 'Ground'], 'Swampert Image'),
  new Pokemon(10, 261, 'Poochyena', ['Dark'], 'Poochyena Image'),
  new Pokemon(11, 262, 'Mightyena', ['Dark'], 'Mightyena Image'),
  new Pokemon(12, 263, 'Zigzagoon', ['Normal'], 'Zigzagoon Image'),
  new Pokemon(13, 264, 'Linoone', ['Normal'], 'Linoone Image'),
  new Pokemon(14, 265, 'Wurmple', ['Bug'], 'Wurmple Image'),
  new Pokemon(15, 266, 'Silcoon', ['Bug'], 'Silcoon Image'),
  new Pokemon(16, 267, 'Beautifly', ['Bug', 'Flying'], 'Beautifly Image'),
  new Pokemon(17, 268, 'Cascoon', ['Bug'], 'Cascoon Image'),
  new Pokemon(18, 269, 'Dustox', ['Bug', 'Poison'], 'Dustox Image'),
  new Pokemon(19, 270, 'Lotad', ['Water', 'Grass'], 'Lotad Image'),
  new Pokemon(20, 271, 'Lombre', ['Water', 'Grass'], 'Lombre Image'),
  new Pokemon(21, 272, 'Ludicolo', ['Water', 'Grass'], 'Ludicolo Image'),
  new Pokemon(22, 273, 'Seedot', ['Grass'], 'Seedot Image'),
  new Pokemon(23, 274, 'Nuzleaf', ['Grass', 'Dark'], 'Nuzleaf Image'),
  new Pokemon(24, 275, 'Shiftry', ['Grass', 'Dark'], 'Shiftry Image'),
  new Pokemon(25, 276, 'Taillow', ['Normal', 'Flying'], 'Taillow Image'),
  new Pokemon(26, 277, 'Swellow', ['Normal', 'Flying'], 'Swellow Image'),
  new Pokemon(27, 278, 'Wingull', ['Water', 'Flying'], 'Wingull Image'),
  new Pokemon(28, 279, 'Pelipper', ['Water', 'Flying'], 'Pelipper Image'),
  new Pokemon(29, 280, 'Ralts', ['Psychic', 'Fairy'], 'Ralts Image'),
  new Pokemon(30, 281, 'Kirlia', ['Psychic', 'Fairy'], 'Kirlia Image'),
  new Pokemon(31, 282, 'Gardevoir', ['Psychic', 'Fairy'], 'Gardevoir Image'),
  new Pokemon(32, 475, 'Gallade', ['Psychic', 'Fighting'], 'Gallade Image'),
  new Pokemon(33, 283, 'Surskit', ['Bug', 'Water'], 'Surskit Image'),
  new Pokemon(34, 284, 'Masquerain', ['Bug', 'Flying'], 'Masquerain Image'),
  new Pokemon(35, 285, 'Shroomish', ['Grass'], 'Shroomish Image'),
  new Pokemon(36, 286, 'Breloom', ['Grass', 'Fighting'], 'Breloom Image'),
  new Pokemon(37, 287, 'Slakoth', ['Normal'], 'Slakoth Image'),
  new Pokemon(38, 288, 'Vigoroth', ['Normal'], 'Vigoroth Image'),
  new Pokemon(39, 289, 'Slaking', ['Normal'], 'Slaking Image'),
  new Pokemon(40, 63, 'Abra', ['Psychic'], 'Abra Image'),
  new Pokemon(41, 64, 'Kadabra', ['Psychic'], 'Kadabra Image'),
  new Pokemon(42, 65, 'Alakazam', ['Psychic'], 'Alakazam Image'),
  new Pokemon(43, 290, 'Nincada', ['Bug', 'Ground'], 'Nincada Image'),
  new Pokemon(44, 291, 'Ninjask', ['Bug', 'Flying'], 'Ninjask Image'),
  new Pokemon(45, 292, 'Shedinja', ['Bug', 'Ghost'], 'Shedinja Image'),
  new Pokemon(46, 293, 'Whismur', ['Normal'], 'Whismur Image'),
  new Pokemon(47, 294, 'Loudred', ['Normal'], 'Loudred Image'),
  new Pokemon(48, 295, 'Exploud', ['Normal'], 'Exploud Image'),
  new Pokemon(49, 296, 'Makuhita', ['Fighting'], 'Makuhita Image'),
  new Pokemon(50, 297, 'Hariyama', ['Fighting'], 'Hariyama Image'),
  new Pokemon(51, 118, 'Goldeen', ['Water'], 'Goldeen Image'),
  new Pokemon(52, 119, 'Seaking', ['Water'], 'Seaking Image'),
  new Pokemon(53, 129, 'Magikarp', ['Water'], 'Magikarp Image'),
  new Pokemon(54, 130, 'Gyarados', ['Water', 'Flying'], 'Gyarados Image'),
  new Pokemon(55, 298, 'Azurill', ['Normal', 'Fairy'], 'Azurill Image'),
  new Pokemon(56, 183, 'Marill', ['Water', 'Fairy'], 'Marill Image'),
  new Pokemon(57, 184, 'Azumarill', ['Water', 'Fairy'], 'Azumarill Image'),
  new Pokemon(58, 74, 'Geodude', ['Rock', 'Ground'], 'Geodude Image'),
  new Pokemon(59, 75, 'Graveler', ['Rock', 'Ground'], 'Graveler Image'),
  new Pokemon(60, 76, 'Golem', ['Rock', 'Ground'], 'Golem Image'),
  new Pokemon(61, 299, 'Nosepass', ['Rock'], 'Nosepass Image'),
  new Pokemon(62, 476, 'Probopass', ['Rock', 'Steel'], 'Probopass Image'),
  new Pokemon(63, 300, 'Skitty', ['Normal'], 'Skitty Image'),
  new Pokemon(64, 301, 'Delcatty', ['Normal'], 'Delcatty Image'),
  new Pokemon(65, 41, 'Zubat', ['Poison', 'Flying'], 'Zubat Image'),
  new Pokemon(66, 42, 'Golbat', ['Poison', 'Flying'], 'Golbat Image'),
  new Pokemon(67, 169, 'Crobat', ['Poison', 'Flying'], 'Crobat Image'),
  new Pokemon(68, 72, 'Tentacool', ['Water', 'Poison'], 'Tentacool Image'),
  new Pokemon(69, 73, 'Tentacruel', ['Water', 'Poison'], 'Tentacruel Image'),
  new Pokemon(70, 302, 'Sableye', ['Dark', 'Ghost'], 'Sableye Image'),
  new Pokemon(71, 303, 'Mawile', ['Steel', 'Fairy'], 'Mawile Image'),
  new Pokemon(72, 304, 'Aron', ['Steel', 'Rock'], 'Aron Image'),
  new Pokemon(73, 305, 'Lairon', ['Steel', 'Rock'], 'Lairon Image'),
  new Pokemon(74, 306, 'Aggron', ['Steel', 'Rock'], 'Aggron Image'),
  new Pokemon(75, 66, 'Machop', ['Fighting'], 'Machop Image'),
  new Pokemon(76, 67, 'Machoke', ['Fighting'], 'Machoke Image'),
  new Pokemon(77, 68, 'Machamp', ['Fighting'], 'Machamp Image'),
  new Pokemon(78, 307, 'Meditite', ['Fighting', 'Psychic'], 'Meditite Image'),
  new Pokemon(79, 308, 'Medicham', ['Fighting', 'Psychic'], 'Medicham Image'),
  new Pokemon(80, 309, 'Electrike', ['Electric'], 'Electrike Image'),
  new Pokemon(81, 310, 'Manectric', ['Electric'], 'Manectric Image'),
  new Pokemon(82, 311, 'Plusle', ['Electric'], 'Plusle Image'),
  new Pokemon(83, 312, 'Minun', ['Electric'], 'Minun Image'),
  new Pokemon(84, 81, 'Magnemite', ['Electric', 'Steel'], 'Magnemite Image'),
  new Pokemon(85, 82, 'Magneton', ['Electric', 'Steel'], 'Magneton Image'),
  new Pokemon(86, 462, 'Magnezone', ['Electric', 'Steel'], 'Magnezone Image'),
  new Pokemon(87, 100, 'Voltorb', ['Electric'], 'Voltorb Image'),
  new Pokemon(88, 101, 'Electrode', ['Electric'], 'Electrode Image'),
  new Pokemon(89, 313, 'Volbeat', ['Bug'], 'Volbeat Image'),
  new Pokemon(90, 314, 'Illumise', ['Bug'], 'Illumise Image'),
  new Pokemon(91, 43, 'Oddish', ['Grass', 'Poison'], 'Oddish Image'),
  new Pokemon(92, 44, 'Gloom', ['Grass', 'Poison'], 'Gloom Image'),
  new Pokemon(93, 45, 'Vileplume', ['Grass', 'Poison'], 'Vileplume Image'),
  new Pokemon(94, 182, 'Bellossom', ['Grass'], 'Bellossom Image'),
  new Pokemon(95, 84, 'Doduo', ['Normal', 'Flying'], 'Doduo Image'),
  new Pokemon(96, 85, 'Dodrio', ['Normal', 'Flying'], 'Dodrio Image'),
  new Pokemon(97, 406, 'Budew', ['Grass', 'Poison'], 'Budew Image'),
  new Pokemon(98, 315, 'Roselia', ['Grass', 'Poison'], 'Roselia Image'),
  new Pokemon(99, 407, 'Roserade', ['Grass', 'Poison'], 'Roserade Image'),
  new Pokemon(100, 316, 'Gulpin', ['Poison'], 'Gulpin Image'),
  new Pokemon(101, 317, 'Swalot', ['Poison'], 'Swalot Image'),
  new Pokemon(102, 318, 'Carvanha', ['Water', 'Dark'], 'Carvanha Image'),
  new Pokemon(103, 319, 'Sharpedo', ['Water', 'Dark'], 'Sharpedo Image'),
  new Pokemon(104, 320, 'Wailmer', ['Water'], 'Wailmer Image'),
  new Pokemon(105, 321, 'Wailord', ['Water'], 'Wailord Image'),
  new Pokemon(106, 322, 'Numel', ['Fire', 'Ground'], 'Numel Image'),
  new Pokemon(107, 323, 'Camerupt', ['Fire', 'Ground'], 'Camerupt Image'),
  new Pokemon(108, 218, 'Slugma', ['Fire'], 'Slugma Image'),
  new Pokemon(109, 219, 'Magcargo', ['Fire', 'Rock'], 'Magcargo Image'),
  new Pokemon(110, 324, 'Torkoal', ['Fire'], 'Torkoal Image'),
  new Pokemon(111, 88, 'Grimer', ['Poison'], 'Grimer Image'),
  new Pokemon(112, 89, 'Muk', ['Poison'], 'Muk Image'),
  new Pokemon(113, 109, 'Koffing', ['Poison'], 'Koffing Image'),
  new Pokemon(114, 110, 'Weezing', ['Poison'], 'Weezing Image'),
  new Pokemon(115, 325, 'Spoink', ['Psychic'], 'Spoink Image'),
  new Pokemon(116, 326, 'Grumpig', ['Psychic'], 'Grumpig Image'),
  new Pokemon(117, 27, 'Sandshrew', ['Ground'], 'Sandshrew Image'),
  new Pokemon(118, 28, 'Sandslash', ['Ground'], 'Sandslash Image'),
  new Pokemon(119, 327, 'Spinda', ['Normal'], 'Spinda Image'),
  new Pokemon(120, 227, 'Skarmory', ['Steel', 'Flying'], 'Skarmory Image'),
  new Pokemon(121, 328, 'Trapinch', ['Ground'], 'Trapinch Image'),
  new Pokemon(122, 329, 'Vibrava', ['Ground', 'Dragon'], 'Vibrava Image'),
  new Pokemon(123, 330, 'Flygon', ['Ground', 'Dragon'], 'Flygon Image'),
  new Pokemon(124, 331, 'Cacnea', ['Grass'], 'Cacnea Image'),
  new Pokemon(125, 332, 'Cacturne', ['Grass', 'Dark'], 'Cacturne Image'),
  new Pokemon(126, 333, 'Swablu', ['Normal', 'Flying'], 'Swablu Image'),
  new Pokemon(127, 334, 'Altaria', ['Dragon', 'Flying'], 'Altaria Image'),
  new Pokemon(128, 335, 'Zangoose', ['Normal'], 'Zangoose Image'),
  new Pokemon(129, 336, 'Seviper', ['Poison'], 'Seviper Image'),
  new Pokemon(130, 337, 'Lunatone', ['Rock', 'Psychic'], 'Lunatone Image'),
  new Pokemon(131, 338, 'Solrock', ['Rock', 'Psychic'], 'Solrock Image'),
  new Pokemon(132, 339, 'Barboach', ['Water', 'Ground'], 'Barboach Image'),
  new Pokemon(133, 340, 'Whiscash', ['Water', 'Ground'], 'Whiscash Image'),
  new Pokemon(134, 341, 'Corphish', ['Water'], 'Corphish Image'),
  new Pokemon(135, 342, 'Crawdaunt', ['Water', 'Dark'], 'Crawdaunt Image'),
  new Pokemon(136, 343, 'Baltoy', ['Ground', 'Psychic'], 'Baltoy Image'),
  new Pokemon(137, 344, 'Claydol', ['Ground', 'Psychic'], 'Claydol Image'),
  new Pokemon(138, 345, 'Lileep', ['Rock', 'Grass'], 'Lileep Image'),
  new Pokemon(139, 346, 'Cradily', ['Rock', 'Grass'], 'Cradily Image'),
  new Pokemon(140, 347, 'Anorith', ['Rock', 'Bug'], 'Anorith Image'),
  new Pokemon(141, 348, 'Armaldo', ['Rock', 'Bug'], 'Armaldo Image'),
  new Pokemon(142, 174, 'Igglybuff', ['Normal', 'Fairy'], 'Igglybuff Image'),
  new Pokemon(143, 39, 'Jigglypuff', ['Normal', 'Fairy'], 'Jigglypuff Image'),
  new Pokemon(144, 40, 'Wigglytuff', ['Normal', 'Fairy'], 'Wigglytuff Image'),
  new Pokemon(145, 349, 'Feebas', ['Water'], 'Feebas Image'),
  new Pokemon(146, 350, 'Milotic', ['Water'], 'Milotic Image'),
  new Pokemon(147, 351, 'Castform', ['Normal'], 'Castform Image'),
  new Pokemon(148, 120, 'Staryu', ['Water'], 'Staryu Image'),
  new Pokemon(149, 121, 'Starmie', ['Water', 'Psychic'], 'Starmie Image'),
  new Pokemon(150, 352, 'Kecleon', ['Normal'], 'Kecleon Image'),
  new Pokemon(151, 353, 'Shuppet', ['Ghost'], 'Shuppet Image'),
  new Pokemon(152, 354, 'Banette', ['Ghost'], 'Banette Image'),
  new Pokemon(153, 355, 'Duskull', ['Ghost'], 'Duskull Image'),
  new Pokemon(154, 356, 'Dusclops', ['Ghost'], 'Dusclops Image'),
  new Pokemon(155, 477, 'Dusknoir', ['Ghost'], 'Dusknoir Image'),
  new Pokemon(156, 357, 'Tropius', ['Grass', 'Flying'], 'Tropius Image'),
  new Pokemon(157, 433, 'Chingling', ['Psychic'], 'Chingling Image'),
  new Pokemon(158, 358, 'Chimecho', ['Psychic'], 'Chimecho Image'),
  new Pokemon(159, 359, 'Absol', ['Dark'], 'Absol Image'),
  new Pokemon(160, 37, 'Vulpix', ['Fire'], 'Vulpix Image'),
  new Pokemon(161, 38, 'Ninetales', ['Fire'], 'Ninetales Image'),
]


function loadHoenn(){
  $('#Center').text("Hoenn Pokémon List by Pokédex Number");
  $('#pokemon-container').empty();
  for(var display of hoennPokemonList){
    display.loadToPage();
    display.ShowTypes();
  }
}
