var hoennPokemonList = [
  new Pokemon(1, 252, 'Treecko', ['Grass'], 'Treecko Image'),
  new Pokemon(2, 253, 'Grovyle', ['Grass'], 'Grovyle Image'),
  new Pokemon(3, 254, 'Sceptile', ['Grass'], 'Sceptile Image'),
  new Pokemon(4, 255, 'Torchic', ['Fire'], 'Torchic Image'),
  new Pokemon(5, 256, 'Combusken', ['Fire', 'Fighting'], 'Combusken Image'),
  new Pokemon(6, 257, 'Blaziken', ['Fire', 'Fighting'], 'Blaziken Image'),
  new Pokemon(7, 258, 'Mudkip', ['Water'], 'Mudkip Image'),
  new Pokemon(8, 259, 'Marshtomp', ['Water', 'Ground'], 'Marshtomp Image'),
  new Pokemon(9, 260, 'Swampert', ['Water', 'Ground'], 'Swampert Image'),
  new Pokemon(10, 261, 'Poochyena', ['Dark'], 'Poochyena Image'),
  new Pokemon(11, 262, 'Mightyena', ['Dark'], 'Mightyena Image'),
  new Pokemon(12, 263, 'Zigzagoon', ['Normal'], 'Zigzagoon Image'),
  new Pokemon(13, 264, 'Linoone', ['Normal'], 'Linoone Image'),
  new Pokemon(14, 265, 'Wurmple', ['Bug'], 'Wurmple Image'),
  new Pokemon(15, 266, 'Silcoon', ['Bug'], 'Silcoon Image'),
  new Pokemon(16, 267, 'Beautifly', ['Bug', 'Flying'], 'Beautifly Image'),
  new Pokemon(17, 268, 'Cascoon', ['Bug'], 'Cascoon Image'),
  new Pokemon(18, 269, 'Dustox', ['Bug', 'Poison'], 'Dustox Image'),
  new Pokemon(19, 270, 'Lotad', ['Water', 'Grass'], 'Lotad Image'),
  new Pokemon(20, 271, 'Lombre', ['Water', 'Grass'], 'Lombre Image'),
  new Pokemon(21, 272, 'Ludicolo', ['Water', 'Grass'], 'Ludicolo Image'),
  new Pokemon(22, 273, 'Seedot', ['Grass'], 'Seedot Image'),
  new Pokemon(23, 274, 'Nuzleaf', ['Grass', 'Dark'], 'Nuzleaf Image'),
  new Pokemon(24, 275, 'Shiftry', ['Grass', 'Dark'], 'Shiftry Image'),
  new Pokemon(25, 276, 'Taillow', ['Normal', 'Flying'], 'Taillow Image'),
  new Pokemon(26, 277, 'Swellow', ['Normal', 'Flying'], 'Swellow Image'),
  new Pokemon(27, 278, 'Wingull', ['Water', 'Flying'], 'Wingull Image'),
  new Pokemon(28, 279, 'Pelipper', ['Water', 'Flying'], 'Pelipper Image'),
  new Pokemon(29, 280, 'Ralts', ['Psychic', 'Fairy'], 'Ralts Image'),
  new Pokemon(30, 281, 'Kirlia', ['Psychic', 'Fairy'], 'Kirlia Image'),
  new Pokemon(31, 282, 'Gardevoir', ['Psychic', 'Fairy'], 'Gardevoir Image'),
  new Pokemon(32, 475, 'Gallade', ['Psychic', 'Fighting'], 'Gallade Image'),
  new Pokemon(33, 283, 'Surskit', ['Bug', 'Water'], 'Surskit Image'),
  new Pokemon(34, 284, 'Masquerain', ['Bug', 'Flying'], 'Masquerain Image'),
  new Pokemon(35, 285, 'Shroomish', ['Grass'], 'Shroomish Image'),
  new Pokemon(36, 286, 'Breloom', ['Grass', 'Fighting'], 'Breloom Image'),
  new Pokemon(37, 287, 'Slakoth', ['Normal'], 'Slakoth Image'),
  new Pokemon(38, 123, 'Vigoroth', ['Normal'], 'Vigoroth Image'),
  new Pokemon(39, 252, 'Slaking', ['Normal'], 'Slaking Image'),
  new Pokemon(40, 63, 'Abra', ['Psychic'], 'Abra Image'),
  new Pokemon(41, 64, 'Kadabra', ['Psychic'], 'Kadabra Image'),
  new Pokemon(42, 65, 'Alakazam', ['Psychic'], 'Alakazam Image'),
  new Pokemon(43, 290, 'Nincada', ['Bug', 'Ground'], 'Nincada Image'),
  new Pokemon(44, 291, 'Ninjask', ['Bug', 'Flying'], 'Ninjask Image'),
  new Pokemon(45, 292, 'Shedinja', ['Bug', 'Ghost'], 'Shedinja Image'),
  new Pokemon(46, 293, 'Whismur', ['Normal'], 'Whismur Image'),
  new Pokemon(47, 294, 'Loudred', ['Normal'], 'Loudred Image'),
  new Pokemon(48, 295, 'Exploud', ['Normal'], 'Exploud Image'),
  new Pokemon(49, 296, 'Makuhita', ['Fighting'], 'Makuhita Image'),
  new Pokemon(50, 297, 'Hariyama', ['Fighting'], 'Hariyama Image'),
  new Pokemon(51, 252, 'Treecko', ['Grass'], 'Treecko Image'),
  new Pokemon(52, 123, 'Grovyle', ['Grass'], 'Grovyle Image'),
  new Pokemon(53, 252, 'Treecko', ['Grass'], 'Treecko Image'),
  new Pokemon(54, 123, 'Grovyle', ['Grass'], 'Grovyle Image'),
  new Pokemon(55, 252, 'Treecko', ['Grass'], 'Treecko Image'),
  new Pokemon(56, 123, 'Grovyle', ['Grass'], 'Grovyle Image'),
  new Pokemon(57, 252, 'Treecko', ['Grass'], 'Treecko Image'),
  new Pokemon(58, 123, 'Grovyle', ['Grass'], 'Grovyle Image'),
  new Pokemon(59, 252, 'Treecko', ['Grass'], 'Treecko Image'),
  new Pokemon(60, 123, 'Grovyle', ['Grass'], 'Grovyle Image'),
  new Pokemon(61, 252, 'Treecko', ['Grass'], 'Treecko Image'),
  new Pokemon(62, 123, 'Grovyle', ['Grass'], 'Grovyle Image'),
  new Pokemon(63, 252, 'Treecko', ['Grass'], 'Treecko Image'),
  new Pokemon(64, 123, 'Grovyle', ['Grass'], 'Grovyle Image'),
  new Pokemon(65, 252, 'Treecko', ['Grass'], 'Treecko Image'),
  new Pokemon(66, 123, 'Grovyle', ['Grass'], 'Grovyle Image'),
  new Pokemon(67, 252, 'Treecko', ['Grass'], 'Treecko Image'),
  new Pokemon(68, 123, 'Grovyle', ['Grass'], 'Grovyle Image'),
  new Pokemon(69, 252, 'Treecko', ['Grass'], 'Treecko Image'),
  new Pokemon(70, 123, 'Grovyle', ['Grass'], 'Grovyle Image'),
  new Pokemon(71, 252, 'Treecko', ['Grass'], 'Treecko Image'),
  new Pokemon(72, 123, 'Grovyle', ['Grass'], 'Grovyle Image'),
  new Pokemon(73, 252, 'Treecko', ['Grass'], 'Treecko Image'),
  new Pokemon(74, 123, 'Grovyle', ['Grass'], 'Grovyle Image'),
  new Pokemon(75, 252, 'Treecko', ['Grass'], 'Treecko Image'),
  new Pokemon(76, 123, 'Grovyle', ['Grass'], 'Grovyle Image'),
  new Pokemon(77, 252, 'Treecko', ['Grass'], 'Treecko Image'),
  new Pokemon(78, 123, 'Grovyle', ['Grass'], 'Grovyle Image'),
  new Pokemon(79, 252, 'Treecko', ['Grass'], 'Treecko Image'),
  new Pokemon(80, 123, 'Grovyle', ['Grass'], 'Grovyle Image'),
  new Pokemon(81, 252, 'Treecko', ['Grass'], 'Treecko Image'),
  new Pokemon(82, 123, 'Grovyle', ['Grass'], 'Grovyle Image'),
  new Pokemon(83, 252, 'Treecko', ['Grass'], 'Treecko Image'),
  new Pokemon(84, 123, 'Grovyle', ['Grass'], 'Grovyle Image'),
  new Pokemon(85, 252, 'Treecko', ['Grass'], 'Treecko Image'),
  new Pokemon(86, 123, 'Grovyle', ['Grass'], 'Grovyle Image'),
  new Pokemon(87, 252, 'Treecko', ['Grass'], 'Treecko Image'),
  new Pokemon(88, 123, 'Grovyle', ['Grass'], 'Grovyle Image'),
  new Pokemon(89, 252, 'Treecko', ['Grass'], 'Treecko Image'),
  new Pokemon(90, 123, 'Grovyle', ['Grass'], 'Grovyle Image'),
  new Pokemon(91, 252, 'Treecko', ['Grass'], 'Treecko Image'),
  new Pokemon(92, 123, 'Grovyle', ['Grass'], 'Grovyle Image'),
  new Pokemon(93, 252, 'Treecko', ['Grass'], 'Treecko Image'),
  new Pokemon(94, 123, 'Grovyle', ['Grass'], 'Grovyle Image'),
  new Pokemon(95, 252, 'Treecko', ['Grass'], 'Treecko Image'),
  new Pokemon(96, 123, 'Grovyle', ['Grass'], 'Grovyle Image'),
  new Pokemon(97, 252, 'Treecko', ['Grass'], 'Treecko Image'),
  new Pokemon(98, 123, 'Grovyle', ['Grass'], 'Grovyle Image'),
  new Pokemon(99, 252, 'Treecko', ['Grass'], 'Treecko Image'),
  new Pokemon(100, 123, 'Grovyle', ['Grass'], 'Grovyle Image'),
  new Pokemon(101, 252, 'Treecko', ['Grass'], 'Treecko Image'),
  new Pokemon(102, 123, 'Grovyle', ['Grass'], 'Grovyle Image'),
  new Pokemon(103, 252, 'Treecko', ['Grass'], 'Treecko Image'),
  new Pokemon(104, 123, 'Grovyle', ['Grass'], 'Grovyle Image'),
  new Pokemon(105, 252, 'Treecko', ['Grass'], 'Treecko Image'),
  new Pokemon(106, 123, 'Grovyle', ['Grass'], 'Grovyle Image'),
  new Pokemon(107, 252, 'Treecko', ['Grass'], 'Treecko Image'),
  new Pokemon(108, 123, 'Grovyle', ['Grass'], 'Grovyle Image'),
  new Pokemon(109, 252, 'Treecko', ['Grass'], 'Treecko Image'),
  new Pokemon(110, 123, 'Grovyle', ['Grass'], 'Grovyle Image'),
  new Pokemon(111, 252, 'Treecko', ['Grass'], 'Treecko Image'),
  new Pokemon(112, 123, 'Grovyle', ['Grass'], 'Grovyle Image'),
  new Pokemon(113, 252, 'Treecko', ['Grass'], 'Treecko Image'),
  new Pokemon(114, 123, 'Grovyle', ['Grass'], 'Grovyle Image'),
  new Pokemon(115, 252, 'Treecko', ['Grass'], 'Treecko Image'),
  new Pokemon(116, 123, 'Grovyle', ['Grass'], 'Grovyle Image'),
  new Pokemon(117, 252, 'Treecko', ['Grass'], 'Treecko Image'),
  new Pokemon(118, 123, 'Grovyle', ['Grass'], 'Grovyle Image'),
  new Pokemon(119, 252, 'Treecko', ['Grass'], 'Treecko Image'),
  new Pokemon(120, 123, 'Grovyle', ['Grass'], 'Grovyle Image'),
  new Pokemon(121, 252, 'Treecko', ['Grass'], 'Treecko Image'),
  new Pokemon(122, 123, 'Grovyle', ['Grass'], 'Grovyle Image'),
  new Pokemon(123, 252, 'Treecko', ['Grass'], 'Treecko Image'),
  new Pokemon(124, 123, 'Grovyle', ['Grass'], 'Grovyle Image'),
  new Pokemon(125, 252, 'Treecko', ['Grass'], 'Treecko Image'),
  new Pokemon(126, 123, 'Grovyle', ['Grass'], 'Grovyle Image'),
  new Pokemon(127, 252, 'Treecko', ['Grass'], 'Treecko Image'),
  new Pokemon(128, 123, 'Grovyle', ['Grass'], 'Grovyle Image'),
  new Pokemon(129, 252, 'Treecko', ['Grass'], 'Treecko Image'),
  new Pokemon(130, 123, 'Grovyle', ['Grass'], 'Grovyle Image'),
]


function loadHoenn(){
  $('#Center').text("Hoenn Pokémon List by Pokédex Number");
  $('#pokemon-container').empty();
  for(var display of hoennPokemonList){
    display.loadToPage();
    display.ShowTypes();
  }
}
