/* eslint-disable no-unused-vars */
const pokemonList = [
  new Pokemon(252, 'Treecko', ['Grass']),
  new Pokemon(253, 'Grovyle', ['Grass']),
  new Pokemon(254, 'Sceptile', ['Grass']),
  new Pokemon(255, 'Torchic', ['Fire']),
  new Pokemon(256, 'Combusken', ['Fire', 'Fighting']),
  new Pokemon(257, 'Blaziken', ['Fire', 'Fighting']),
  new Pokemon(258, 'Mudkip', ['Water']),
  new Pokemon(259, 'Marshtomp', ['Water', 'Ground']),
  new Pokemon(260, 'Swampert', ['Water', 'Ground']),
  new Pokemon(261, 'Poochyena', ['Dark']),
  new Pokemon(262, 'Mightyena', ['Dark']),
  new Pokemon(263, 'Zigzagoon', ['Normal']),
  new Pokemon(264, 'Linoone', ['Normal']),
  new Pokemon(265, 'Wurmple', ['Bug']),
  new Pokemon(266, 'Silcoon', ['Bug']),
  new Pokemon(267, 'Beautifly', ['Bug', 'Flying']),
  new Pokemon(268, 'Cascoon', ['Bug']),
  new Pokemon(269, 'Dustox', ['Bug', 'Poison']),
  new Pokemon(270, 'Lotad', ['Water', 'Grass']),
  new Pokemon(271, 'Lombre', ['Water', 'Grass']),
  new Pokemon(272, 'Ludicolo', ['Water', 'Grass']),
  new Pokemon(273, 'Seedot', ['Grass']),
  new Pokemon(274, 'Nuzleaf', ['Grass', 'Dark']),
  new Pokemon(275, 'Shiftry', ['Grass', 'Dark']),
  new Pokemon(276, 'Taillow', ['Normal', 'Flying']),
  new Pokemon(277, 'Swellow', ['Normal', 'Flying']),
  new Pokemon(278, 'Wingull', ['Water', 'Flying']),
  new Pokemon(279, 'Pelipper', ['Water', 'Flying']),
  new Pokemon(280, 'Ralts', ['Psychic', 'Fairy']),
  new Pokemon(281, 'Kirlia', ['Psychic', 'Fairy']),
  new Pokemon(282, 'Gardevoir', ['Psychic', 'Fairy']),
  new Pokemon(475, 'Gallade', ['Psychic', 'Fighting']),
  new Pokemon(283, 'Surskit', ['Bug', 'Water']),
  new Pokemon(284, 'Masquerain', ['Bug', 'Flying']),
  new Pokemon(285, 'Shroomish', ['Grass']),
  new Pokemon(286, 'Breloom', ['Grass', 'Fighting']),
  new Pokemon(287, 'Slakoth', ['Normal']),
  new Pokemon(288, 'Vigoroth', ['Normal']),
  new Pokemon(289, 'Slaking', ['Normal']),
  new Pokemon(63, 'Abra', ['Psychic']),
  new Pokemon(64, 'Kadabra', ['Psychic']),
  new Pokemon(65, 'Alakazam', ['Psychic']),
  new Pokemon(290, 'Nincada', ['Bug', 'Ground']),
  new Pokemon(291, 'Ninjask', ['Bug', 'Flying']),
  new Pokemon(292, 'Shedinja', ['Bug', 'Ghost']),
  new Pokemon(293, 'Whismur', ['Normal']),
  new Pokemon(294, 'Loudred', ['Normal']),
  new Pokemon(295, 'Exploud', ['Normal']),
  new Pokemon(296, 'Makuhita', ['Fighting']),
  new Pokemon(297, 'Hariyama', ['Fighting']),
  new Pokemon(118, 'Goldeen', ['Water']),
  new Pokemon(119, 'Seaking', ['Water']),
  new Pokemon(129, 'Magikarp', ['Water']),
  new Pokemon(130, 'Gyarados', ['Water', 'Flying']),
  new Pokemon(298, 'Azurill', ['Normal', 'Fairy']),
  new Pokemon(183, 'Marill', ['Water', 'Fairy']),
  new Pokemon(184, 'Azumarill', ['Water', 'Fairy']),
  new Pokemon(74, 'Geodude', ['Rock', 'Ground']),
  new Pokemon(75, 'Graveler', ['Rock', 'Ground']),
  new Pokemon(76, 'Golem', ['Rock', 'Ground']),
  new Pokemon(299, 'Nosepass', ['Rock']),
  new Pokemon(476, 'Probopass', ['Rock', 'Steel']),
  new Pokemon(300, 'Skitty', ['Normal']),
  new Pokemon(301, 'Delcatty', ['Normal']),
  new Pokemon(41, 'Zubat', ['Poison', 'Flying']),
  new Pokemon(42, 'Golbat', ['Poison', 'Flying']),
  new Pokemon(169, 'Crobat', ['Poison', 'Flying']),
  new Pokemon(72, 'Tentacool', ['Water', 'Poison']),
  new Pokemon(73, 'Tentacruel', ['Water', 'Poison']),
  new Pokemon(302, 'Sableye', ['Dark', 'Ghost']),
  new Pokemon(303, 'Mawile', ['Steel', 'Fairy']),
  new Pokemon(304, 'Aron', ['Steel', 'Rock']),
  new Pokemon(305, 'Lairon', ['Steel', 'Rock']),
  new Pokemon(306, 'Aggron', ['Steel', 'Rock']),
  new Pokemon(66, 'Machop', ['Fighting']),
  new Pokemon(67, 'Machoke', ['Fighting']),
  new Pokemon(68, 'Machamp', ['Fighting']),
  new Pokemon(307, 'Meditite', ['Fighting', 'Psychic']),
  new Pokemon(308, 'Medicham', ['Fighting', 'Psychic']),
  new Pokemon(309, 'Electrike', ['Electric']),
  new Pokemon(310, 'Manectric', ['Electric']),
  new Pokemon(311, 'Plusle', ['Electric']),
  new Pokemon(312, 'Minun', ['Electric']),
  new Pokemon(81, 'Magnemite', ['Electric', 'Steel']),
  new Pokemon(82, 'Magneton', ['Electric', 'Steel']),
  new Pokemon(462, 'Magnezone', ['Electric', 'Steel']),
  new Pokemon(100, 'Voltorb', ['Electric']),
  new Pokemon(101, 'Electrode', ['Electric']),
  new Pokemon(313, 'Volbeat', ['Bug']),
  new Pokemon(314, 'Illumise', ['Bug']),
  new Pokemon(43, 'Oddish', ['Grass', 'Poison']),
  new Pokemon(44, 'Gloom', ['Grass', 'Poison']),
  new Pokemon(45, 'Vileplume', ['Grass', 'Poison']),
  new Pokemon(182, 'Bellossom', ['Grass']),
  new Pokemon(84, 'Doduo', ['Normal', 'Flying']),
  new Pokemon(85, 'Dodrio', ['Normal', 'Flying']),
  new Pokemon(406, 'Budew', ['Grass', 'Poison']),
  new Pokemon(315, 'Roselia', ['Grass', 'Poison']),
  new Pokemon(407, 'Roserade', ['Grass', 'Poison']),
  new Pokemon(316, 'Gulpin', ['Poison']),
  new Pokemon(317, 'Swalot', ['Poison']),
  new Pokemon(318, 'Carvanha', ['Water', 'Dark']),
  new Pokemon(319, 'Sharpedo', ['Water', 'Dark']),
  new Pokemon(320, 'Wailmer', ['Water']),
  new Pokemon(321, 'Wailord', ['Water']),
  new Pokemon(322, 'Numel', ['Fire', 'Ground']),
  new Pokemon(323, 'Camerupt', ['Fire', 'Ground']),
  new Pokemon(218, 'Slugma', ['Fire']),
  new Pokemon(219, 'Magcargo', ['Fire', 'Rock']),
  new Pokemon(324, 'Torkoal', ['Fire']),
  new Pokemon(88, 'Grimer', ['Poison']),
  new Pokemon(89, 'Muk', ['Poison']),
  new Pokemon(109, 'Koffing', ['Poison']),
  new Pokemon(110, 'Weezing', ['Poison']),
  new Pokemon(325, 'Spoink', ['Psychic']),
  new Pokemon(326, 'Grumpig', ['Psychic']),
  new Pokemon(27, 'Sandshrew', ['Ground']),
  new Pokemon(28, 'Sandslash', ['Ground']),
  new Pokemon(327, 'Spinda', ['Normal']),
  new Pokemon(227, 'Skarmory', ['Steel', 'Flying']),
  new Pokemon(328, 'Trapinch', ['Ground']),
  new Pokemon(329, 'Vibrava', ['Ground', 'Dragon']),
  new Pokemon(330, 'Flygon', ['Ground', 'Dragon']),
  new Pokemon(331, 'Cacnea', ['Grass']),
  new Pokemon(332, 'Cacturne', ['Grass', 'Dark']),
  new Pokemon(333, 'Swablu', ['Normal', 'Flying']),
  new Pokemon(334, 'Altaria', ['Dragon', 'Flying']),
  new Pokemon(335, 'Zangoose', ['Normal']),
  new Pokemon(336, 'Seviper', ['Poison']),
  new Pokemon(337, 'Lunatone', ['Rock', 'Psychic']),
  new Pokemon(338, 'Solrock', ['Rock', 'Psychic']),
  new Pokemon(339, 'Barboach', ['Water', 'Ground']),
  new Pokemon(340, 'Whiscash', ['Water', 'Ground']),
  new Pokemon(341, 'Corphish', ['Water']),
  new Pokemon(342, 'Crawdaunt', ['Water', 'Dark']),
  new Pokemon(343, 'Baltoy', ['Ground', 'Psychic']),
  new Pokemon(344, 'Claydol', ['Ground', 'Psychic']),
  new Pokemon(345, 'Lileep', ['Rock', 'Grass']),
  new Pokemon(346, 'Cradily', ['Rock', 'Grass']),
  new Pokemon(347, 'Anorith', ['Rock', 'Bug']),
  new Pokemon(348, 'Armaldo', ['Rock', 'Bug']),
  new Pokemon(174, 'Igglybuff', ['Normal', 'Fairy']),
  new Pokemon(39, 'Jigglypuff', ['Normal', 'Fairy']),
  new Pokemon(40, 'Wigglytuff', ['Normal', 'Fairy']),
  new Pokemon(349, 'Feebas', ['Water']),
  new Pokemon(350, 'Milotic', ['Water']),
  new Pokemon(351, 'Castform', ['Normal']),
  new Pokemon(120, 'Staryu', ['Water']),
  new Pokemon(121, 'Starmie', ['Water', 'Psychic']),
  new Pokemon(352, 'Kecleon', ['Normal']),
  new Pokemon(353, 'Shuppet', ['Ghost']),
  new Pokemon(354, 'Banette', ['Ghost']),
  new Pokemon(355, 'Duskull', ['Ghost']),
  new Pokemon(356, 'Dusclops', ['Ghost']),
  new Pokemon(477, 'Dusknoir', ['Ghost']),
  new Pokemon(357, 'Tropius', ['Grass', 'Flying']),
  new Pokemon(433, 'Chingling', ['Psychic']),
  new Pokemon(358, 'Chimecho', ['Psychic']),
  new Pokemon(359, 'Absol', ['Dark']),
  new Pokemon(37, 'Vulpix', ['Fire']),
  new Pokemon(38, 'Ninetales', ['Fire']),
  new Pokemon(172, 'Pichu', ['Electric']),
  new Pokemon(25, 'Pikachu', ['Electric']),
  new Pokemon(26, 'Raichu', ['Electric']),
  new Pokemon(54, 'Psyduck', ['Water']),
  new Pokemon(55, 'Golduck', ['Water']),
  new Pokemon(360, 'Wynaut', ['Psychic']),
  new Pokemon(202, 'Wobbuffet', ['Psychic']),
  new Pokemon(177, 'Natu', ['Psychic', 'Flying']),
  new Pokemon(178, 'Xatu', ['Psychic', 'Flying']),
  new Pokemon(203, 'Girafarig', ['Normal', 'Psychic']),
  new Pokemon(231, 'Phanpy', ['Ground']),
  new Pokemon(232, 'Donphan', ['Ground']),
  new Pokemon(127, 'Pinsir', ['Bug']),
  new Pokemon(214, 'Heracross', ['Bug', 'Fighting']),
  new Pokemon(111, 'Rhyhorn', ['Ground', 'Rock']),
  new Pokemon(112, 'Rhydon', ['Ground', 'Rock']),
  new Pokemon(464, 'Rhyperior', ['Ground', 'Rock']),
  new Pokemon(361, 'Snorunt', ['Ice']),
  new Pokemon(362, 'Glalie', ['Ice']),
  new Pokemon(478, 'Froslass', ['Ice', 'Ghost']),
  new Pokemon(363, 'Spheal', ['Ice', 'Water']),
  new Pokemon(364, 'Sealeo', ['Ice', 'Water']),
  new Pokemon(365, 'Walrein', ['Ice', 'Water']),
  new Pokemon(366, 'Clamperl', ['Water']),
  new Pokemon(367, 'Huntail', ['Water']),
  new Pokemon(368, 'Gorebyss', ['Water']),
  new Pokemon(369, 'Relicanth', ['Water', 'Rock']),
  new Pokemon(222, 'Corsola', ['Water', 'Rock']),
  new Pokemon(170, 'Chinchou', ['Water', 'Electric']),
  new Pokemon(171, 'Lanturn', ['Water', 'Electric']),
  new Pokemon(370, 'Luvdisc', ['Water']),
  new Pokemon(116, 'Horsea', ['Water']),
  new Pokemon(117, 'Seadra', ['Water']),
  new Pokemon(230, 'Kingdra', ['Water', 'Dragon']),
  new Pokemon(371, 'Bagon', ['Dragon']),
  new Pokemon(372, 'Shelgon', ['Dragon']),
  new Pokemon(373, 'Salamence', ['Dragon', 'Flying']),
  new Pokemon(374, 'Beldum', ['Steel', 'Psychic']),
  new Pokemon(375, 'Metang', ['Steel', 'Psychic']),
  new Pokemon(376, 'Metagross', ['Steel', 'Psychic']),
  new Pokemon(377, 'Regirock', ['Rock']),
  new Pokemon(378, 'Regice', ['Ice']),
  new Pokemon(379, 'Registeel', ['Steel']),
  new Pokemon(380, 'Latias', ['Dragon', 'Psychic']),
  new Pokemon(381, 'Latios', ['Dragon', 'Psychic']),
  new Pokemon(382, 'Kyogre', ['Water']),
  new Pokemon(383, 'Groudon', ['Ground']),
  new Pokemon(384, 'Rayquaza', ['Dragon', 'Flying']),
  new Pokemon(385, 'Jirachi', ['Steel', 'Psychic']),
  new Pokemon(386, 'Deoxys', ['Psychic']),
];


function loadHoenn() {
  $('#Center').text('The Hoenn Pokémon List by Pokédex Number');
  $('#myInput').val('');
  $('#pokemon-container').empty();
  for (const display of pokemonList) {
    display.loadToPage();
    display.showTypes();
  }
}
