/* eslint-disable no-unused-vars */
const itemList = [
  new Items('Ability Capsule', 'VI', 'Medicine', 'A capsule that allows a Pokémon with two Abilities to switch between these Abilities when it is used.'),
  new Items('Ability Urge', 'V', 'Battle Items', 'When used, it activates the Ability of an ally Pokémon.'),
  new Items('Abomasite', 'VI', 'Hold Items', 'Enables Abomasnow to Mega Evolve during battle.'),
  new Items('Absolite', 'VI', 'Hold Items', 'Enables Absol to Mega Evolve during battle.'),
  new Items('Absorb Bulb', 'V', 'Hold Items', 'A consumable bulb. If the holder is hit by a Water-type move, its Sp. Atk will rise.'),
  new Items('Acro Bike', 'III', 'Key Items', 'A bicycle with which the player can do tricks such as jump sideways.'),
  new Items('Adamant Orb', 'IV', 'Hold Items', 'Increases the power of Dragon- and Steel-type moves when held by Dialga.'),
  new Items('Adrenaline Orb', 'VII', 'Hold Items', 'Using it makes wild Pokémon more likely to call for help. If held by a Pokémon, it boosts Speed when intimidated. It can be used only once.'),
  new Items('Adventure Rules', 'VI', 'Key Items', 'Contains information new Trainers should know.'),
  new Items('Aerodactylite', 'VI', 'Hold Items', 'Enables Aerodactyl to Mega Evolve during battle.'),
  new Items('Aggronite', 'VI', 'Hold Items', 'Enables Aggron to Mega Evolve during battle.'),
  new Items('Aguav Berry', 'III', 'Berries', 'Restores HP if it\'s low, but may cause confusion.'),
  new Items('Air Balloon', 'V', 'Hold Items', 'When held by a Pokémon, the Pokémon will float into the air. When the holder is attacked, this item will burst.'),
  new Items('Alakazite', 'VI', 'Hold Items', 'Enables Alakazam to Mega Evolve during battle.'),
  new Items('Aloraichium Z', 'VII', 'Hold Items', 'Allows Alolan Raichu to upgrade Thunderbolt to a Z-Move, Stoked Sparksurfer.'),
  new Items('Altarianite', 'VI', 'Hold Items', 'Enables Altaria to Mega Evolve during battle.'),
  new Items('Ampharosite', 'VI', 'Hold Items', 'Enables Ampharos to Mega Evolve during battle.'),
  new Items('Amulet Coin', 'II', 'Hold Items', 'An item to be held by a Pokémon. It doubles a battle’s prize money if the holding Pokémon joins in.'),
  new Items('Antidote', 'I', 'Medicine', 'A spray-type medicine. It lifts the effect of poison from one Pokémon.'),
  new Items('Apicot Berry', 'III', 'Berries', 'Raises Special Defense when HP is low.'),
  new Items('Armor Fossil', 'IV', 'General Items', 'A fossil from a prehistoric Pokémon that lived on the land. It appears to be part of a collar.'),
  new Items('Aspear Berry', 'III', 'Berries', 'If held by a Pokémon, it defrosts it.'),
  new Items('Assault Vest', 'VI', 'Hold Items', 'Raises Special Defense but prevents the use of status moves.'),
  new Items('Audinite', 'VI', 'Hold Items', 'Enables Audino to Mega Evolve during battle.'),
  new Items('Autograph', 'VII', 'Key Items', 'The Autograph serves no practical purpose.'),
  new Items('Awakening', 'I', 'Medicine', 'A spray-type medicine. It awakens a Pokémon from the clutches of sleep.'),
  new Items('Babiri Berry', 'IV', 'Berries', 'Weakens a supereffective Steel-type attack against the holding Pokémon.'),
  new Items('Balm Mushroom', 'V', 'General Items', 'A rare mushroom which gives off a nice fragrance. A maniac will buy it for a high price.'),
  new Items('Banettite', 'VI', 'Hold Items', 'Enables Banette to Mega Evolve during battle.'),
  new Items('Beach Glass', 'VII', 'General Items', 'A piece of colored glass. Waves have rounded its edges. It\'s slightly rough to the touch.'),
  new Items('Beast Ball', 'VII', 'Pokeballs', 'A special Poké Ball designed to catch Ultra Beasts. It has a low success rate for catching others.'),
  new Items('Beedrillite', 'VI', 'Hold Items', 'Enables Beedrill to Mega Evolve during battle.'),
  new Items('Belue Berry', 'III', 'Berries', 'A Berry which is very rare in the Unova region. A maniac will buy it for a high price.'),
  new Items('Berry Juice', 'II', 'Medicine', 'A 100% pure juice made of Berries. It restores the HP of one Pokémon by just 20 points.'),
  new Items('Big Malasada', 'VII', 'Medicine', 'Heals all major status conditions.'),
  new Items('Big Mushroom', 'II', 'General Items', 'A large and rare mushroom. It is sought after by collectors.'),
  new Items('Big Nugget', 'V', 'General Items', 'A big nugget of pure gold that gives off a lustrous gleam. A maniac will buy it for a high price.'),
  new Items('Big Pearl', 'II', 'General Items', 'A quite-large pearl that sparkles in a pretty silver color. It can be sold at a high price to shops.'),
  new Items('Big Root', 'IV', 'Hold Items', 'Recovers more HP from HP-stealing moves.'),
  new Items('Binding Band', 'V', 'Hold Items', 'A band that increases the power of binding moves when held.'),
  new Items('Black Apricorn', 'II', 'General Items', 'A black Apricorn It has an indescribable scent.'),
  new Items('Black Belt', 'II', 'Hold Items', 'Increases the power of Fighting-type moves.'),
  new Items('Black Flute', 'III', 'General Items', 'A toy flute made from black glass. A maniac will buy it for a high price.'),
  new Items('Black Glasses', 'II', 'Hold Items', 'Increases the power of Dark-type moves.'),
  new Items('Black Sludge', 'IV', 'Hold Items', 'A held item that gradually restores the HP of Poison-type Pokémon. It inflicts damage on all other types.'),
  new Items('Blastoisinite', 'VI', 'Hold Items', 'Enables Blastoise to Mega Evolve during battle.'),
  new Items('Blazikenite', 'VI', 'Hold Items', 'Enables Blaziken to Mega Evolve during battle.'),
  new Items('Blue Apricorn', 'II', 'General Items', 'A blue Apricorn. It smells a bit like grass.'),
  new Items('Blue Flute', 'III', 'General Items', 'A toy flute made from blue glass. A maniac will buy it for a high price.'),
  new Items('Blue Scarf', 'III', 'General Items', 'Raises holder\'s Beauty aspect in a Contest.'),
  new Items('Blue Shard', 'III', 'General Items', 'A small blue shard. It appears to be from some sort of implement made long ago.'),
  new Items('Bluk Berry', 'III', 'Berries', 'A Berry which is very rare in the Unova region. A maniac will buy it for a high price.'),
  new Items('Bottle Cap', 'VII', 'General Items', 'Maximizes one IV stat in Hyper Training.'),
  new Items('Bright Powder', 'II', 'Hold Items', 'Lowers the opponent’s accuracy.'),
  new Items('Bug Gem', 'V', 'Hold Items', 'Increases the power of a Bug-type move only once.'),
  new Items('Bug Memory', 'VII', 'Hold Items', 'Changes Silvally and its move Multi-Attack to Bug type.'),
  new Items('Buginium Z', 'VII', 'Hold Items', 'Allows the use of Savage Spin-Out, the Bug type Z-Move.'),
  new Items('Burn Drive', 'V', 'Hold Items', 'Changes Techno Blast to a Fire-type move when held by Genesect.'),
  new Items('Burn Heal', 'I', 'Medicine', 'A spray-type medicine. It heals a single Pokémon that is suffering from a burn.'),
  new Items('Calcium', 'I', 'Medicine', 'Increases Special Attack EVs by 10.'),
  new Items('Cameruptite', 'VI', 'Hold Items', 'Enables Camerupt to Mega Evolve during battle.'),
  new Items('Carbos', 'I', 'Medicine', 'Increases Speed EVs by 10.'),
  new Items('Casteliacone', 'V', 'Medicine', 'Heals all major status conditions.'),
  new Items('Cell Battery', 'V', 'Hold Items', 'A consumable battery. If the holder is hit by an Electric-type move, its Attack will rise.'),
  new Items('Chalky Stone', 'VII', 'General Items', 'A small whitish stone picked up at the edge of the road.'),
  new Items('Charcoal', 'II', 'Hold Items', 'Increases the power of Fire-type moves.'),
  new Items('Charizardite X', 'VI', 'Hold Items', 'Enables Charizard to Mega Evolve during battle.'),
  new Items('Charizardite Y', 'VI', 'Hold Items', 'Enables Charizard to Mega Evolve during battle.'),
  new Items('Charti Berry', 'IV', 'Berries', 'Weakens a supereffective Rock-type attack against the holding Pokémon.'),
  new Items('Cheri Berry', 'III', 'Berries', 'If held by a Pokémon, it recovers from paralysis.'),
  new Items('Cherish Ball', 'IV', 'Pokeballs', 'A quite rare Poké Ball that has been specially crafted to commemorate an occasion of some sort.'),
  new Items('Chesto Berry', 'III', 'Berries', 'If held by a Pokémon, it recovers from sleep.'),
  new Items('Chilan Berry', 'V', 'Berries', 'Weakens a Normal-type attack against the Pokémon holding this berry.'),
  new Items('Chill Drive', 'V', 'Hold Items', 'Changes Techno Blast to an Ice-type move when held by Genesect.'),
  new Items('Choice Band', 'III', 'Hold Items', 'Raises Attack, but only one move can be used.'),
  new Items('Choice Scarf', 'IV', 'Hold Items', 'Raises Speed, but only one move can be used.'),
  new Items('Choice Specs', 'IV', 'Hold Items', 'Raises Special Attack, but only one move can be used.'),
  new Items('Chople Berry', 'IV', 'Berries', 'Weakens a supereffective Fighting-type attack against the holding Pokémon.'),
  new Items('Claw Fossil', 'III', 'General Items', 'A fossil of an ancient Pokémon that lived in the sea. It appears to be part of a claw.'),
  new Items('Cleanse Tag', 'III', 'Hold Items', 'An item to be held by a Pokémon. It helps keep wild Pokémon away if the holder is the first one in the party.'),
  new Items('Clever Wing', 'V', 'Medicine', 'Increases Special Defense EVs by 1.'),
  new Items('Coba Berry', 'IV', 'Berries', 'Weakens a supereffective Flying-type attack against the holding Pokémon.'),
  new Items('Colbur Berry', 'IV', 'Berries', 'Weakens a supereffective Dark-type attack against the holding Pokémon.'),
  new Items('Colress Machine', 'V', 'Hold Items', 'A special device that wrings out the potential of Pokémon. It is an imperfect prototype.'),
  new Items('Comet Shard', 'V', 'General Items', 'A shard which fell to the ground when a comet approached. A maniac will buy it for a high price.'),
  new Items('Cornn Berry', 'III', 'Berries', 'A Berry which is very rare in the Unova region. A maniac will buy it for a high price.'),
  new Items('Courage Candy', 'VII', 'Medicine', 'Increases a Pokémon\'s Special Defense stat by 1.'),
  new Items('Courage Candy L', 'VII', 'Medicine', 'Increases a Pokémon\'s Special Defense stat by 1. The Pokémon must be level 30.'),
  new Items('Courage Candy XL', 'VII', 'Medicine', 'Increases a Pokémon\'s Special Defense stat by 1. The Pokémon must be level 60.'),
  new Items('Cover Fossil', 'V', 'General Items', 'A fossil of an ancient Pokémon that lived in the sea in ancient times. It appears to be part of its back.'),
  new Items('Custap Berry', 'IV', 'Berries', 'Holder can move first when HP is low.'),
  new Items('Damp Mulch', 'IV', 'General Items', 'A fertilizer to be spread on soft soil in regions where Berries are grown. A maniac will buy it for a high price.'),
  new Items('Damp Rock', 'IV', 'Hold Items', 'A Pokémon held item that extends the duration of the move Rain Dance used by the holder.'),
  new Items('Dark Gem', 'V', 'Hold Items', 'Increases the power of a Dark-type move only once.'),
  new Items('Dark Memory', 'VII', 'Hold Items', 'Changes Silvally and its move Multi-Attack to Dark type.'),
  new Items('Darkinium Z', 'VII', 'Hold Items', 'Allows the use of Black Hole Eclipse, the Dark type Z-Move.'),
  new Items('Dawn Stone', 'IV', 'General Items', 'A peculiar stone that makes certain species of Pokémon evolve. It sparkles like eyes.'),
  new Items('Decidium Z', 'VII', 'Hold Items', 'Allows Decidueye to upgrade Spirit Shackle to a Z-Move, Sinister Arrow Raid.'),
  new Items('Deep Sea Scale', 'III', 'Hold Items', 'Increases Special Defense when held by Clamperl.'),
  new Items('Deep Sea Tooth', 'III', 'Hold Items', 'Increases Special Attack when held by Clamperl.'),
  new Items('Destiny Knot', 'IV', 'Hold Items', 'A long, thin, bright-red string to be held by a Pokémon. If the holder becomes infatuated, the foe does too.'),
  new Items('Diancite', 'VI', 'Hold Items', 'Enables Diancie to Mega Evolve during battle.'),
  new Items('Dire Hit', 'I', 'Battle Items', 'Raises critical-hit ratio of a Pokémon in battle.'),
  new Items('Dire Hit 2', 'V', 'Battle Items', 'Raises a Pokémon\'s critical-hit ratio in battle.'),
  new Items('Dire Hit 3', 'V', 'Battle Items', 'Greatly raises a Pokémon\'s critical-hit ratio in battle.'),
  new Items('Discount Coupon', 'VI', 'General Items', 'This special coupon allows you to buy items at a discount when you are shopping at a boutique.'),
  new Items('Dive Ball', 'III', 'Pokeballs', 'A somewhat different Poké Ball that works especially well on Pokémon that live underwater.'),
  new Items('DNA Splicers', 'V', 'General Items', 'A splicer that fuses Kyurem and a certain Pokémon. They are said to have been one in the beginning.'),
  new Items('Dome Fossil', 'III', 'General Items', 'A fossil of an ancient Pokémon that lived in the sea. It appears to be part of a shell.'),
  new Items('Douse Drive', 'V', 'Hold Items', 'Changes Techno Blast to a Water-type move when held by Genesect.'),
  new Items('Draco Plate', 'IV', 'Hold Items', 'Increases power of Dragon-type moves. Changes Arceus\' type to Dragon.'),
  new Items('Dragon Fang', 'II', 'Hold Items', 'Increases the power of Dragon-type moves.'),
  new Items('Dragon Gem', 'V', 'Hold Items', 'Increases the power of a Dragon-type move only once.'),
  new Items('Dragon Memory', 'VII', 'Hold Items', 'Changes Silvally and its move Multi-Attack to Dragon type.'),
  new Items('Dragon Scale', 'II', 'General Items', 'A thick and tough scale. Dragon-type Pokémon may be holding this item when caught.'),
  new Items('Dragonium Z', 'VII', 'Hold Items', 'Allows the use of Devastating Drake, the Dragon type Z-Move.'),
  new Items('Dread Plate', 'IV', 'Hold Items', 'Increases power of Dark-type moves. Changes Arceus\' type to Dark.'),
  new Items('Dream Ball', 'V', 'Pokeballs', 'A special Poké Ball that appears out of nowhere in a bag at the Entree Forest. It can catch any Pokémon.'),
  new Items('Dropped Item', 'V', 'Hold Items', 'The Xtransceiver found at the Nimbasa City amusement park. It seems it belongs to a boy.'),
  new Items('Dubious Disc', 'IV', 'General Items', 'A transparent device overflowing with dubious data. Its producer is unknown.'),
  new Items('Durin Berry', 'III', 'Berries', 'A Berry which is very rare in the Unova region. A maniac will buy it for a high price.'),
  new Items('Dusk Ball', 'IV', 'Pokeballs', 'A somewhat different Poké Ball that makes it easier to catch wild Pokémon at night or in dark places like caves.'),
  new Items('Dusk Stone', 'IV', 'General Items', 'A peculiar stone that makes certain species of Pokémon evolve. It is as dark as dark can be.'),
  new Items('Earth Plate', 'IV', 'Hold Items', 'Increases power of Ground-type moves. Changes Arceus\' type to Ground.'),
  new Items('Eevium Z', 'VII', 'Hold Items', 'Allows Eevee to upgrade Last Resort to a Z-Move, Extreme Evoboost.'),
  new Items('Eject Button', 'V', 'Hold Items', 'If the holder is hit by an attack, it will switch with another Pokémon in your party.'),
  new Items('Electirizer', 'IV', 'General Items', 'A box packed with a tremendous amount of electric energy. It is loved by a certain Pokémon.'),
  new Items('Electric Gem', 'V', 'Hold Items', 'Increases the power of an Electric-type move only once.'),
  new Items('Electric Memory', 'VII', 'Hold Items', 'Changes Silvally and its move Multi-Attack to Electric type.'),
  new Items('Electric Seed', 'VII', 'Hold Items', 'An item to be held by a Pokémon. It boosts Defense on Electric Terrain. It can only be used once.'),
  new Items('Electrium Z', 'VII', 'Hold Items', 'Allows the use of Gigavolt Havoc, the Electric type Z-Move.'),
  new Items('Elevator Key', 'VI', 'Hold Items', 'A card key that activates the elevator in Lysandre Labs. It is emblazoned with Team Flare’s logo.'),
  new Items('Elixir', 'I', 'Medicine', 'It restores the PP of all the moves learned by the targeted Pokémon by 10 points each.'),
  new Items('Energy Powder', 'II', 'Medicine', 'Restores 60 HP but lowers Friendship.'),
  new Items('Energy Root', 'II', 'Medicine', 'Restores 120 HP but lowers Friendship.'),
  new Items('Enigma Berry', 'III', 'Berries', 'If held by a Pokémon, it restores its HP if it is hit by any supereffective attack.'),
  new Items('Escape Rope', 'I', 'General Items', 'A long, durable rope. Use it to escape instantly from a cave or a dungeon.'),
  new Items('Ether', 'I', 'Medicine', 'It restores the PP of a Pokémon’s selected move by a maximum of 10 points.'),
  new Items('Everstone', 'II', 'Hold Items', 'An item to be held by a Pokémon. The Pokémon holding this peculiar stone is prevented from evolving.'),
  new Items('Eviolite', 'V', 'Hold Items', 'A mysterious evolutionary lump. When held, it raises the Defense and Sp. Def of a Pokémon that can still evolve.'),
  new Items('Exp. Share', 'I', 'Hold Items', 'An item to be held by a Pokémon. The holder gets a share of a battle’s Exp. Points without battling.'),
  new Items('Expert Belt', 'IV', 'Hold Items', 'Increases the power of super-effective moves.'),
  new Items('Fairium Z', 'VII', 'Hold Items', 'Allows the use of Twinkle Tackle, the Fairy type Z-Move.'),
  new Items('Fairy Gem', 'VI', 'Hold Items', 'Increases the power of a Fairy-type move only once.'),
  new Items('Fairy Memory', 'VII', 'Hold Items', 'Changes Silvally and its move Multi-Attack to Fairy type.'),
  new Items('Fast Ball', 'II', 'Pokeballs', 'A Poké Ball that makes it easier to catch Pokémon which are quick to run away.'),
  new Items('Festival Ticket', 'VII', 'General Items', 'A ticket that allows you to host a mission in Festival Plaza.'),
  new Items('Fighting Gem', 'V', 'Hold Items', 'Increases the power of a Fighting-type move only once.'),
  new Items('Fighting Memory', 'VII', 'Hold Items', 'Changes Silvally and its move Multi-Attack to Fighting type.'),
  new Items('Fightinium Z', 'VII', 'Hold Items', 'Allows the use of All-Out Pummeling, the Fighting type Z-Move.'),
  new Items('Figy Berry', 'III', 'Berries', 'Restores HP if it\'s low, but may cause confusion.'),
  new Items('Fire Gem', 'V', 'Hold Items', 'Increases the power of a Fire-type move only once.'),
  new Items('Fire Memory', 'VII', 'Hold Items', 'Changes Silvally and its move Multi-Attack to Fire type.'),
  new Items('Fire Stone', 'I', 'General Items', 'A peculiar stone that makes certain species of Pokémon evolve. It is colored orange.'),
  new Items('Firium Z', 'VII', 'Hold Items', 'Allows the use of Inferno Overdrive, the Fire type Z-Move.'),
  new Items('Fist Plate', 'IV', 'Hold Items', 'Increases power of Fighting-type moves. Changes Arceus\' type to Fighting.'),
  new Items('Flame Orb', 'IV', 'Hold Items', 'An item to be held by a Pokémon. It is a bizarre orb that inflicts a burn on the holder in battle.'),
  new Items('Flame Plate', 'IV', 'Hold Items', 'Increases power of Fire-type moves. Changes Arceus\' type to Fire.'),
  new Items('Float Stone', 'V', 'Hold Items', 'A very light stone. It reduces the weight of a Pokémon when held.'),
  new Items('Fluffy Tail', 'III', 'General Items', 'An item that attracts Pokémon. Use it to flee from any battle with a wild Pokémon.'),
  new Items('Flying Gem', 'V', 'Hold Items', 'Increases the power of a Flying-type move only once.'),
  new Items('Flying Memory', 'VII', 'Hold Items', 'Changes Silvally and its move Multi-Attack to Flying type.'),
  new Items('Flyinium Z', 'VII', 'Hold Items', 'Allows the use of Supersonic Skystrike, the Flying type Z-Move.'),
  new Items('Focus Band', 'II', 'Hold Items', 'An item to be held by a Pokémon. The holder may endure a potential KO attack, leaving it with just 1 HP.'),
  new Items('Focus Sash', 'IV', 'Hold Items', 'An item to be held by a Pokémon. If it has full HP, the holder will endure one potential KO attack, leaving 1 HP.'),
  new Items('Fresh Water', 'I', 'Medicine', 'Restores 30 HP.'),
  new Items('Friend Ball', 'II', 'Pokeballs', 'A Poké Ball that makes caught Pokémon more friendly.'),
  new Items('Full Heal', 'I', 'Medicine', 'A spray-type medicine. It heals all the status problems of a single Pokémon.'),
  new Items('Full Incense', 'IV', 'Hold Items', 'An item to be held by a Pokémon. It is an exotic-smelling incense that makes the holder bloated and slow moving.'),
  new Items('Full Restore', 'I', 'Medicine', 'A medicine that fully restores the HP and heals any status problems of a single Pokémon.'),
  new Items('Galladite', 'VI', 'Hold Items', 'Enables Gallade to Mega Evolve during battle.'),
  new Items('Ganlon Berry', 'III', 'Berries', 'Raises Defense when HP is low.'),
  new Items('Garchompite', 'VI', 'Hold Items', 'Enables Garchomp to Mega Evolve during battle.'),
  new Items('Gardevoirite', 'VI', 'Hold Items', 'Enables Gardevoir to Mega Evolve during battle.'),
  new Items('Gengarite', 'VI', 'Hold Items', 'Enables Gengar to Mega Evolve during battle.'),
  new Items('Genius Wing', 'V', 'Medicine', 'Increases Special Attack EVs by 1.'),
  new Items('Ghost Gem', 'V', 'Hold Items', 'Increases the power of a Ghost-type move only once.'),
  new Items('Ghost Memory', 'VII', 'Hold Items', 'Changes Silvally and its move Multi-Attack to Ghost type.'),
  new Items('Ghostium Z', 'VII', 'Hold Items', 'Allows the use of Never-Ending Nightmare, the Ghost type Z-Move.'),
  new Items('Glalitite', 'VI', 'Hold Items', 'Enables Glalie to Mega Evolve during battle.'),
  new Items('Gold Bottle Cap', 'VII', 'General Items', 'Maximizes all of a Pokémon\'s IV stats in Hyper Training.'),
  new Items('Gold Leaf', 'II', 'General Items', 'A mysterious gold leaf. No trees with this leaf have been found yet.'),
  new Items('Golden Nanab Berry', 'VII', 'Berries', 'Drastically calms a Pokémon in battle, in Let\'s Go.'),
  new Items('Golden Pinap Berry', 'VII', 'Berries', 'Drastically increases chance of getting items when a Pokémon is caught, in Pokémon Let\'s Go.'),
  new Items('Golden Razz Berry', 'VII', 'Berries', 'Makes a Pokémon easier to catch in Pokémon Let\'s Go.'),
  new Items('Gooey Mulch', 'IV', 'General Items', 'A fertilizer to be spread on soft soil in regions where Berries are grown. A maniac will buy it for a high price.'),
  new Items('Grass Gem', 'V', 'Hold Items', 'Increases the power of a Grass-type move only once.'),
  new Items('Grass Memory', 'VII', 'Hold Items', 'Changes Silvally and its move Multi-Attack to Grass type.'),
  new Items('Grassium Z', 'VII', 'Hold Items', 'Allows the use of Bloom Doom, the Grass type Z-Move.'),
  new Items('Grassy Seed', 'VII', 'Hold Items', 'An item to be held by a Pokémon. It boosts Defense on Grassy Terrain. It can only be used once.'),
  new Items('Great Ball', 'I', 'Pokeballs', 'A good, high-performance Ball that provides a higher Pokémon catch rate than a standard Poké Ball.'),
  new Items('Green Apricorn', 'II', 'General Items', 'A green Apricorn. It has a mysterious, aromatic scent.'),
  new Items('Green Scarf', 'III', 'General Items', 'Raises holder\'s Smart aspect in a Contest.'),
  new Items('Green Shard', 'III', 'General Items', 'A small green shard. It appears to be from some sort of implement made long ago.'),
  new Items('Grepa Berry', 'III', 'Berries', 'Increases Friendship but lowers Special Defense EVs.'),
  new Items('Grip Claw', 'IV', 'Hold Items', 'A Pokémon held item that extends the duration of multiturn attacks like Bind and Wrap.'),
  new Items('Griseous Orb', 'IV', 'Hold Items', 'Increases the power of Dragon- and Ghost-type moves when held by Giratina, and changes it to Origin Forme.'),
  new Items('Ground Gem', 'V', 'Hold Items', 'Increases the power of a Ground-type move only once.'),
  new Items('Ground Memory', 'VII', 'Hold Items', 'Changes Silvally and its move Multi-Attack to Ground type.'),
  new Items('Groundium Z', 'VII', 'Hold Items', 'Allows the use of Tectonic Rage, the Ground type Z-Move.'),
  new Items('Growth Mulch', 'IV', 'General Items', 'A fertilizer to be spread on soft soil in regions where Berries are grown. A maniac will buy it for a high price.'),
  new Items('Grubby Hanky', 'V', 'Hold Items', 'A handkerchief dropped by a regular at Café Warehouse. It smells faintly like a Pokémon.'),
  new Items('Guard Spec.', 'I', 'Battle Items', 'Prevents stat reduction for five turns.'),
  new Items('Gyaradosite', 'VI', 'Hold Items', 'Enables Gyarados to Mega Evolve during battle.'),
  new Items('Haban Berry', 'IV', 'Berries', 'Weakens a supereffective Dragon-type attack against the holding Pokémon.'),
  new Items('Hard Stone', 'II', 'Hold Items', 'Increases the power of Rock-type moves.'),
  new Items('Heal Ball', 'IV', 'Pokeballs', 'A remedial Poké Ball that restores the caught Pokémon’s HP and eliminates any status problem.'),
  new Items('Heal Powder', 'II', 'Medicine', 'Heals all status problems, but lowers Friendship.'),
  new Items('Health Candy', 'VII', 'Medicine', 'Increases a Pokémon\'s HP stat by 1.'),
  new Items('Health Candy L', 'VII', 'Medicine', 'Increases a Pokémon\'s HP stat by 1. The Pokémon must be level 30.'),
  new Items('Health Candy XL', 'VII', 'Medicine', 'Increases a Pokémon\'s HP stat by 1. The Pokémon must be level 60.'),
  new Items('Health Wing', 'V', 'Medicine', 'Increases HP EVs by 1.'),
  new Items('Heart Scale', 'III', 'General Items', 'A pretty, heart-shaped scale that is extremely rare. It glows faintly in the colors of the rainbow.'),
  new Items('Heat Rock', 'IV', 'Hold Items', 'A Pokémon held item that extends the duration of the move Sunny Day used by the holder.'),
  new Items('Heavy Ball', 'II', 'Pokeballs', 'A Poké Ball for catching very heavy Pokémon.'),
  new Items('Helix Fossil', 'I', 'General Items', 'A fossil of an ancient Pokémon that lived in the sea. It appears to be part of a seashell.'),
  new Items('Heracronite', 'VI', 'Hold Items', 'Enables Heracross to Mega Evolve during battle.'),
  new Items('HM01', 'I', 'Machines', 'Teaches the move Cut.'),
  new Items('HM02', 'I', 'Machines', 'Teaches the move Fly.'),
  new Items('HM03', 'I', 'Machines', 'Teaches the move Surf.'),
  new Items('HM04', 'I', 'Machines', 'Teaches the move Strength.'),
  new Items('HM05', 'I', 'Machines', 'Teaches the move Flash/Defog/Whirlpool/Waterfall.'),
  new Items('HM06', 'I', 'Machines', 'Teaches the move Whirlpool/Rock Smash/Dive.'),
  new Items('HM07', 'I', 'Machines', 'Teaches the move Waterfall.'),
  new Items('HM08', 'I', 'Machines', 'Teaches the move Dive/Rock Climb.'),
  new Items('Hondew Berry', 'III', 'Berries', 'Increases Friendship but lowers Special Attack EVs.'),
  new Items('Honey', 'IV', 'General Items', 'A sweet honey with a lush aroma that attracts wild Pokémon when it is used in grass, caves, or on special trees.'),
  new Items('Honor Of Kalos', 'VI', 'Key Items', 'A precious symbol that is awarded only to an individual who has done great things for the Kalos region.'),
  new Items('Houndoominite', 'VI', 'Hold Items', 'Enables Houndoom to Mega Evolve during battle.'),
  new Items('HP Up', 'I', 'Medicine', 'Increases HP EVs by 10.'),
  new Items('Hyper Potion', 'I', 'Medicine', 'Restores 120 HP.'),
  new Items('Iapapa Berry', 'III', 'Berries', 'Restores HP if it\'s low, but may cause confusion.'),
  new Items('Ice Gem', 'V', 'Hold Items', 'Increases the power of an Ice-type move only once.'),
  new Items('Ice Heal', 'I', 'Medicine', 'A spray-type medicine. It defrosts a Pokémon that has been frozen solid.'),
  new Items('Ice Memory', 'VII', 'Hold Items', 'Changes Silvally and its move Multi-Attack to Ice type.'),
  new Items('Ice Stone', 'VII', 'General Items', 'A peculiar stone that can make certain species of Pokémon evolve. It has an unmistakable snowflake pattern.'),
  new Items('Icicle Plate', 'IV', 'Hold Items', 'Increases power of Ice-type moves. Changes Arceus\' type to Ice.'),
  new Items('Icium Z', 'VII', 'Hold Items', 'Allows the use of Subzero Slammer, the Ice type Z-Move.'),
  new Items('Icy Rock', 'IV', 'Hold Items', 'A Pokémon held item that extends the duration of the move Hail used by the holder.'),
  new Items('Incinium Z', 'VII', 'Hold Items', 'Allows Incineroar to upgrade Darkest Lariat to a Z-Move, Malicious Moonsault.'),
  new Items('Insect Plate', 'IV', 'Hold Items', 'Increases power of Bug-type moves. Changes Arceus\' type to Bug.'),
  new Items('Intriguing Stone', 'VI', 'Hold Items', 'A rather curious stone that might appear to be valuable to some. It’s all in the eye of the beholder.'),
  new Items('Iron', 'I', 'Medicine', 'Increases Defense EVs by 10.'),
  new Items('Iron Ball', 'IV', 'Hold Items', 'A Pokémon held item that cuts Speed. It makes Flying-type and levitating holders susceptible to Ground moves.'),
  new Items('Iron Plate', 'IV', 'Hold Items', 'Increases power of Steel-type moves. Changes Arceus\' type to Steel.'),
  new Items('Item Drop', 'V', 'Batle Items', 'When used, it causes an ally Pokémon to drop a held item.'),
  new Items('Item Urge', 'V', 'Battle Items', 'When used, it causes an ally Pokémon to use its held item.'),
  new Items('Jaboca Berry', 'IV', 'Berries', 'If held by a Pokémon and a physical attack lands, the attacker also takes damage.'),
  new Items('Kangaskhanite', 'VI', 'Hold Items', 'Enables Kangaskhan to Mega Evolve during battle.'),
  new Items('Kasib Berry', 'IV', 'Berries', 'Weakens a supereffective Ghost-type attack against the holding Pokémon.'),
  new Items('Kebia Berry', 'IV', 'Berries', 'Weakens a supereffective Poison-type attack against the holding Pokémon.'),
  new Items('Kee Berry', 'VI', 'Berries', 'If held by a Pokémon, this Berry will increase the holder’s Defense if it’s hit with a physical move.'),
  new Items('Kelpsy Berry', 'III', 'Berries', 'Increases Friendship but lowers Attack EVs.'),
  new Items('King\'s Rock', 'II', 'Hold Items', 'An item to be held by a Pokémon. When the holder inflicts damage, the target may flinch.'),
  new Items('Kommonium Z', 'VII', 'Hold Items', 'Allows Kommo-o to upgrade Clanging Scales to a Z-Move, Clangorous Soulblaze.'),
  new Items('Lagging Tail', 'IV', 'Hold Items', 'An item to be held by a Pokémon. It is tremendously heavy and makes the holder move slower than usual.'),
  new Items('Lansat Berry', 'III', 'Berries', 'Increases critical-hit ratio when HP is low.'),
  new Items('Latiasite', 'VI', 'Hold Items', 'Enables Latias to Mega Evolve during battle.'),
  new Items('Latiosite', 'VI', 'Hold Items', 'Enables Latios to Mega Evolve during battle.'),
  new Items('Lava Cookie', 'III', 'Medicine', 'Heals all major status conditions.'),
  new Items('Lax Incense', 'III', 'Hold Items', 'An item to be held by a Pokémon. The tricky aroma of this incense may make attacks miss the holder.'),
  new Items('Leaf Letter', 'VII', 'General Items', 'A letter written on a leaf. Something is written using Eevee\'s footprints.'),
  new Items('Leaf Stone', 'I', 'General Items', 'A peculiar stone that makes certain species of Pokémon evolve. It has a leaf pattern.'),
  new Items('Leftovers', 'II', 'Hold Items', 'An item to be held by a Pokémon. The holder’s HP is gradually restored during battle.'),
  new Items('Lemonade', 'I', 'Medicine', 'Restores 70 HP.'),
  new Items('Leppa Berry', 'III', 'Berries', 'If held by a Pokémon, it restores a move’s PP by 10.'),
  new Items('Level Ball', 'II', 'Pokeballs', 'A Poké Ball for catching Pokémon that are a lower level than your own.'),
  new Items('Liechi Berry', 'III', 'Berries', 'Raises Attack when HP is low.'),
  new Items('Life Orb', 'IV', 'Hold Items', 'Increases the power of moves, but loses HP each turn.'),
  new Items('Light Ball', 'II', 'Hold Items', 'An item to be held by Pikachu. It is a puzzling orb that raises the Attack and Sp. Atk stat.'),
  new Items('Light Clay', 'IV', 'Hold Items', 'A Pokémon held item that extends the duration of barrier moves like Light Screen and Reflect used by the holder.'),
  new Items('Lone Earring', 'VII', 'General Items', 'A single earring that somebody dropped.'),
  new Items('Looker Ticket', 'VI', 'Key Items', 'A ticket that was handmade by Looker. It’s decorated with a liberal amount of glittery paint.'),
  new Items('Lopunnite', 'VI', 'Hold Items', 'Enables Lopunny to Mega Evolve during battle.'),
  new Items('Love Ball', 'II', 'Pokeballs', 'Poké Ball for catching Pokémon that are the opposite gender of your Pokémon.'),
  new Items('Lucarionite', 'VI', 'Hold Items', 'Enables Lucario to Mega Evolve during battle.'),
  new Items('Luck Incense', 'IV', 'Hold Items', 'An item to be held by a Pokémon. It doubles a battle’s prize money if the holding Pokémon joins in.'),
  new Items('Lucky Egg', 'II', 'Hold Items', 'An item to be held by a Pokémon. It is an egg filled with happiness that earns extra Exp. Points in battle.'),
  new Items('Lucky Punch', 'III', 'Hold Items', 'Increases critical-hit ratio when held by Chansey.'),
  new Items('Lum Berry', 'III', 'Berries', 'If held by a Pokémon, it recovers from any status problem.'),
  new Items('Luminous Moss', 'VI', 'Hold Items', 'Raises Special Defense if hit by a Water-type move.'),
  new Items('Lumiose Galette', 'VI', 'Medicine', 'Heals all major status conditions.'),
  new Items('Lunalium Z', 'VII', 'Hold Items', 'Allows Lunala to upgrade Moongeist Beam to a Z-Move, Menacing Moonraze Maelstrom.'),
  new Items('Lure', 'VII', 'General Items', 'Attracts Pokémon in the wild.'),
  new Items('Lure Ball', 'II', 'Pokeballs', 'A Poké Ball for catching Pokémon hooked by a Rod when fishing.'),
  new Items('Lustrous Orb', 'IV', 'Hold Items', 'Increases the power of Dragon-type and Water-type moves when held by Palkia.'),
  new Items('Luxury Ball', 'III', 'Pokeballs', 'A comfortable Poké Ball that makes a caught wild Pokémon quickly grow friendly.'),
  new Items('Lycanium Z', 'VII', 'Hold Items', 'Allows Lycanroc to upgrade Stone Edge to a Z-Move, Splintered Stormshards.'),
  new Items('Macho Brace', 'III', 'Hold Items', 'An item to be held by a Pokémon. It is a stiff and heavy brace that promotes strong growth but lowers Speed.'),
  new Items('Magmarizer', 'IV', 'General Items', 'A box packed with a tremendous amount of magma energy. It is loved by a certain Pokémon.'),
  new Items('Magnet', 'II', 'Hold Items', 'Increases the power of Electric-type moves.'),
  new Items('Mago Berry', 'III', 'Berries', 'Restores HP if it\'s low, but may cause confusion.'),
  new Items('Magost Berry', 'III', 'Berries', 'A Berry which is very rare in the Unova region. A maniac will buy it for a high price.'),
  new Items('Manectite', 'VI', 'Hold Items', 'Enables Manectric to Mega Evolve during battle.'),
  new Items('Maranga Berry', 'VI', 'Berries', 'If held by a Pokémon, this Berry will increase the holder’s Sp. Def if it’s hit with a special move.'),
  new Items('Marble', 'VII', 'General Items', 'A round glass marble. You can see colored glass inside the transparent marble.'),
  new Items('Marshadium Z', 'VII', 'Hold Items', 'Allows Marshadow to upgrade Spectral Thief to a Z-Move, Soul-Stealing 7-Star Strike.'),
  new Items('Master Ball', 'I', 'Pokeballs', 'The best Ball with the ultimate level of performance. It will catch any wild Pokémon without fail.'),
  new Items('Mawilite', 'VI', 'Hold Items', 'Enables Mawile to Mega Evolve during battle.'),
  new Items('Max Elixir', 'I', 'Medicine', 'It fully restores the PP of all the moves learned by the targeted Pokémon.'),
  new Items('Max Ether', 'I', 'Medicine', 'It fully restores the PP of a single selected move that has been learned by the target Pokémon.'),
  new Items('Max Lure', 'VII', 'General Items', 'A glass bottle of perfume that makes rare Pokémon more likely to appear. It lasts longer than a Super Lure.'),
  new Items('Max Potion', 'I', 'Medicine', 'Fully restores HP.'),
  new Items('Max Repel', 'I', 'General Items', 'An item that prevents weak wild Pokémon from appearing for 250 steps after its use.'),
  new Items('Max Revive', 'I', 'Medicine', 'A medicine that revives a fainted Pokémon. It fully restores the Pokémon’s HP.'),
  new Items('Meadow Plate', 'IV', 'Hold Items', 'Increases power of Grass-type moves. Changes Arceus\' type to Grass.'),
  new Items('Medichamite', 'VI', 'Hold Items', 'Enables Medicham to Mega Evolve during battle.'),
  new Items('Mental Herb', 'III', 'Hold Items', 'An item to be held by a Pokémon. It snaps the holder out of infatuation. It can be used only once.'),
  new Items('Metagrossite', 'VI', 'Hold Items', 'Enables Metagross to Mega Evolve during battle.'),
  new Items('Metal Coat', 'II', 'Hold Items', 'Increases the power of Steel-type moves.'),
  new Items('Metal Powder', 'II', 'Hold Items', 'Increases Defense when held by Ditto.'),
  new Items('Metronome', 'IV', 'Hold Items', 'Increases the power of moves used consecutively.'),
  new Items('Mewnium Z', 'VII', 'Hold Items', 'Allows Mew to upgrade Psychic to a Z-Move, Genesis Supernova.'),
  new Items('Mewtwonite X', 'VI', 'Hold Items', 'Enables Mewtwo to Mega Evolve during battle.'),
  new Items('Mewtwonite Y', 'VI', 'Hold Items', 'Enables Mewtwo to Mega Evolve during battle.'),
  new Items('Micle Berry', 'IV', 'Berries', 'Increases a move\'s accuracy when HP is low.'),
  new Items('Mighty Candy', 'VII', 'Medicine', 'Increases a Pokémon\'s Attack stat by 1.'),
  new Items('Mighty Candy L', 'VII', 'Medicine', 'Increases a Pokémon\'s Attack stat by 1. The Pokémon must be level 30.'),
  new Items('Mighty Candy XL', 'VII', 'Medicine', 'Increases a Pokémon\'s Attack stat by 1. The Pokémon must be level 60.'),
  new Items('Mimikium Z', 'VII', 'Hold Items', 'Allows Mimikyu to upgrade Play Rough to a Z-Move.'),
  new Items('Mind Plate', 'IV', 'Hold Items', 'Increases power of Psychic-type moves. Changes Arceus\' type to Psychic.'),
  new Items('Miracle Seed', 'II', 'Hold Items', 'Increases the power of Grass-type moves.'),
  new Items('Misty Seed', 'VII', 'Hold Items', 'An item to be held by a Pokémon. It boosts Sp. Def on Misty Terrain. It can only be used once.'),
  new Items('Moomoo Milk', 'II', 'Medicine', 'Milk with a very high nutrition content. It restores the HP of one Pokémon by 100 points.'),
  new Items('Moon Ball', 'II', 'Pokeballs', 'A Poké Ball for catching Pokémon that evolve using the Moon Stone.'),
  new Items('Moon Stone', 'I', 'General Items', 'A peculiar stone that makes certain species of Pokémon evolve. It is as black as the night sky.'),
  new Items('Muscle Band', 'IV', 'Hold Items', 'Increases the power of Physical-category moves.'),
  new Items('Muscle Wing', 'V', 'Medicine', 'Increases Attack EVs by 1.'),
  new Items('Mystic Water', 'II', 'Hold Items', 'Increases the power of Water-type moves.'),
  new Items('Nanab Berry', 'III', 'Berries', 'Feed this to a Pokémon to calm it down, making it less erratic.'),
  new Items('Nest Ball', 'III', 'Pokeballs', 'A somewhat different Poké Ball that works especially well on weaker Pokémon in the wild.'),
  new Items('Net Ball', 'III', 'Pokeballs', 'A somewhat different Poké Ball that works especially well on Water- and Bug-type Pokémon.'),
  new Items('Never-Melt Ice', 'II', 'Hold Items', 'Increases the power of Ice-type moves.'),
  new Items('Nomel Berry', 'III', 'Berries', 'A Berry which is very rare in the Unova region. A maniac will buy it for a high price.'),
  new Items('Normal Gem', 'V', 'Hold Items', 'Increases the power of a Normal-type move only once.'),
  new Items('Normalium Z', 'VII', 'Hold Items', 'Allows the use of Breakneck Blitz, the Normal type Z-Move.'),
  new Items('Nugget', 'I', 'General Items', 'A nugget of pure gold that gives off a lustrous gleam. It can be sold at a high price to shops.'),
  new Items('Occa Berry', 'IV', 'Berries', 'Weakens a supereffective Fire-type attack against the holding Pokémon.'),
  new Items('Odd Incense', 'IV', 'Hold Items', 'Increases the power of Psychic-type moves.'),
  new Items('Odd Keystone', 'IV', 'General Items', 'A vital item that is needed to keep a stone tower from collapsing. Voices can be heard from it occasionally.'),
  new Items('Old Amber', 'I', 'General Items', 'A piece of amber that contains the genetic material of an ancient Pokémon. It is clear with a reddish tint.'),
  new Items('Old Gateau', 'IV', 'Medicine', 'Heals all major status conditions.'),
  new Items('Oran Berry', 'III', 'Berries', 'If held by a Pokémon, it heals the user by just 10 HP.'),
  new Items('Oval Charm', 'V', 'Key Items', 'An oval charm said to increase the chance of Pokémon Eggs being found at the Day Care.'),
  new Items('Oval Stone', 'IV', 'General Items', 'A peculiar stone that makes certain species of Pokémon evolve. It is shaped like an egg.'),
  new Items('Pamtre Berry', 'III', 'Berries', 'A Berry which is very rare in the Unova region. A maniac will buy it for a high price.'),
  new Items('Paralyze Heal', 'I', 'Medicine', 'A spray-type medicine. It eliminates paralysis from a single Pokémon.'),
  new Items('Park Ball', 'IV', 'Pokeballs', 'A special Poké Ball for the Pal Park.'),
  new Items('Pass Orb', 'V', 'Hold Items', 'A mysterious orb containing the power of the Unova region, to be used when generating Pass Power.'),
  new Items('Passho Berry', 'IV', 'Berries', 'Weakens a supereffective Water-type attack against the holding Pokémon.'),
  new Items('Payapa Berry', 'IV', 'Berries', 'Weakens a supereffective Psychic-type attack against the holding Pokémon.'),
  new Items('Pearl', 'II', 'General Items', 'A somewhat-small pearl that sparkles in a pretty silver color. It can be sold cheaply to shops.'),
  new Items('Pearl String', 'V', 'General Items', 'Very large pearls that sparkle in a pretty silver color. A maniac will buy them for a high price.'),
  new Items('Pecha Berry', 'III', 'Berries', 'If held by a Pokémon, it recovers from poison.'),
  new Items('Permit', 'V', 'Key Items', 'A permit that is needed to enter the Nature Preserve. Not many know about it.'),
  new Items('Persim Berry', 'III', 'Berries', 'If held by a Pokémon, it recovers from confusion.'),
  new Items('Petaya Berry', 'III', 'Berries', 'Raises Special Attack when HP is low.'),
  new Items('Pewter Crunchies', 'VII', 'Medicine', 'Heals all major status conditions.'),
  new Items('Pidgeotite', 'VI', 'Hold Items', 'Enables Pidgeot to Mega Evolve during battle.'),
  new Items('Pikanium Z', 'VII', 'Hold Items', 'Allows Pikachu to upgrade Volt Tackle to a Z-Move, Catastropika.'),
  new Items('Pikashunium Z', 'VII', 'Hold Items', 'Allows Pikachu in a cap to upgrade Thunderbolt to a Z-Move, 10,000,000 Volt Thunderbolt.'),
  new Items('Pinap Berry', 'III', 'Berries', 'Makes wild Pokémon more likely to yield items when captured'),
  new Items('Pink Apricorn', 'II', 'General Items', 'A pink Apricorn. It has a nice, sweet scent.'),
  new Items('Pink Nectar', 'VII', 'Hold Items', 'The flower nectar obtained at the flowering shrubs on Royal Avenue. It changes the form of certain species of Pokémon.'),
  new Items('Pink Scarf', 'III', 'General Items', 'Raises holder\'s Cute aspect in a Contest.'),
  new Items('Pinsirite', 'VI', 'Hold Items', 'Enables Pinsir to Mega Evolve during battle.'),
  new Items('Pixie Plate', 'VI', 'Hold Items', 'Increases power of Fairy-type moves. Changes Arceus\' type to Fairy.'),
  new Items('Plasma Card', 'V', 'Key Items', 'A card key needed to enter the password inside the Plasma Frigate.'),
  new Items('Plume Fossil', 'V', 'General Items', 'A fossil of an ancient Pokémon that flew in the sky in ancient times. It appears to be part of its wing.'),
  new Items('Poison Barb', 'II', 'Hold Items', 'Increases the power of Poison-type moves.'),
  new Items('Poison Gem', 'V', 'Hold Items', 'Increases the power of a Poison-type move only once.'),
  new Items('Poison Memory', 'VII', 'Hold Items', 'Changes Silvally and its move Multi-Attack to Poison type.'),
  new Items('Poisonium Z', 'VII', 'Hold Items', 'Allows the use of Acid Downpour, the Poison type Z-Move.'),
  new Items('Poké Ball', 'I', 'Pokeballs', 'A device for catching wild Pokémon. It is thrown like a ball at the target. It is designed as a capsule system.'),
  new Items('Poké Doll', 'I', 'General Items', 'A doll that attracts Pokémon. Use it to flee from any battle with a wild Pokémon.'),
  new Items('Poké Toy', 'V', 'General Items', 'An item that attracts Pokémon. Use it to flee from any battle with a wild Pokémon.'),
  new Items('Polished Mud Ball', 'VII', 'General Items', 'A ball made of mud. It had been polished for such a long time that the surface is very shiny.'),
  new Items('Pomeg Berry', 'III', 'Berries', 'Increases Friendship but lowers HP EVs.'),
  new Items('Potion', 'I', 'Medicine', 'Restores 20 HP.'),
  new Items('Power Anklet', 'IV', 'Hold Items', 'A Pokémon held item that promotes Speed gain on leveling, but reduces the Speed stat.'),
  new Items('Power Band', 'IV', 'Hold Items', 'A Pokémon held item that promotes Sp. Def gain on leveling, but reduces the Speed stat.'),
  new Items('Power Belt', 'IV', 'Hold Items', 'A Pokémon held item that promotes Defense gain on leveling, but reduces the Speed stat.'),
  new Items('Power Bracer', 'IV', 'Hold Items', 'A Pokémon held item that promotes Attack gain on leveling, but reduces the Speed stat.'),
  new Items('Power Herb', 'IV', 'Hold Items', 'A single-use item to be held by a Pokémon. It allows the immediate use of a move that charges on the first turn.'),
  new Items('Power Lens', 'IV', 'Hold Items', 'A Pokémon held item that promotes Sp. Atk gain on leveling, but reduces the Speed stat.'),
  new Items('Power Plant Pass', 'VI', 'Key Items', 'This pass serves as an ID card for gaining access to the power plant that lies along Route 13.'),
  new Items('Power Weight', 'IV', 'Hold Items', 'A Pokémon held item that promotes HP gain on leveling, but reduces the Speed stat.'),
  new Items('PP Max', 'III', 'Medicine', 'It maximally raises the top PP of a selected move that has been learned by the target Pokémon.'),
  new Items('PP Up', 'I', 'Medicine', 'It slightly raises the maximum PP of a selected move that has been learned by the target Pokémon.'),
  new Items('Premier Ball', 'III', 'Pokeballs', 'A somewhat rare Poké Ball that has been specially made to commemorate an event of some sort.'),
  new Items('Pretty Wing', 'V', 'Medicine', 'Though this feather is beautiful, it’s just a regular feather and has no effect on Pokémon.'),
  new Items('Primarium Z', 'VII', 'Hold Items', 'Allows Primarina to upgrade Sparkling Aria to a Z-Move, Oceanic Operetta.'),
  new Items('Prism Scale', 'V', 'General Items', 'A mysterious scale that evolves certain Pokémon. It shines in rainbow colors.'),
  new Items('Prison Bottle', 'VI', 'Hold Items', 'Transforms Hoopa Confined to Hoopa Unbound.'),
  new Items('Prof\'s Letter', 'VI', 'Key Items', 'A letter that Professor Sycamore wrote to your mother. A faint but pleasant perfume seems to cling to the paper.'),
  new Items('Protective Pads', 'VII', 'Hold Items', 'An item to be held by a Pokémon. These pads protect the holder from effects caused by making direct contact with the target.'),
  new Items('Protector', 'IV', 'General Items', 'A protective item of some sort. It is extremely stiff and heavy. It is loved by a certain Pokémon.'),
  new Items('Protein', 'I', 'Medicine', 'Increases Attack EVs by 10.'),
  new Items('Psychic Gem', 'V', 'Hold Items', 'Increases the power of a Psychic-type move only once.'),
  new Items('Psychic Memory', 'VII', 'Hold Items', 'Changes Silvally and its move Multi-Attack to Psychic type.'),
  new Items('Psychic Seed', 'VII', 'Hold Items', 'An item to be held by a Pokémon. It boosts Sp. Def on Psychic Terrain. It can only be used once.'),
  new Items('Psychium Z', 'VII', 'Hold Items', 'Allows the use of Shattered Psyche, the Psychic type Z-Move.'),
  new Items('Pure Incense', 'IV', 'Hold Items', 'An item to be held by a Pokémon. It helps keep wild Pokémon away if the holder is the first one in the party.'),
  new Items('Purple Nectar', 'VII', 'Hold Items', 'A flower nectar obtained at Poni Meadow. It changes the form of certain species of Pokémon.'),
  new Items('Qualot Berry', 'III', 'Berries', 'Increases Friendship but lowers Defense EVs.'),
  new Items('Quick Ball', 'IV', 'Pokeballs', 'A somewhat different Poké Ball that provides a better catch rate if it is used at the start of a wild encounter.'),
  new Items('Quick Candy', 'VII', 'Medicine', 'Increases a Pokémon\'s Speed stat by 1.'),
  new Items('Quick Candy L', 'VII', 'Medicine', 'Increases a Pokémon\'s Speed stat by 1. The Pokémon must be level 30.'),
  new Items('Quick Candy XL', 'VII', 'Medicine', 'Increases a Pokémon\'s Speed stat by 1. The Pokémon must be level 60.'),
  new Items('Quick Claw', 'II', 'Hold Items', 'An item to be held by a Pokémon. A light, sharp claw that lets the bearer move first occasionally.'),
  new Items('Quick Powder', 'IV', 'Hold Items', 'Increases Speed when held by Ditto.'),
  new Items('Rabuta Berry', 'III', 'Berries', 'A Berry which is very rare in the Unova region. A maniac will buy it for a high price.'),
  new Items('Rage Candy Bar', 'II', 'Medicine', 'Heals all major status conditions.'),
  new Items('Rare Bone', 'IV', 'General Items', 'A bone that is extremely valuable for Pokémon archeology. It can be sold for a high price to shops.'),
  new Items('Rare Candy', 'I', 'Medicine', 'A candy that is packed with energy. It raises the level of a single Pokémon by one.'),
  new Items('Rawst Berry', 'III', 'Berries', 'If held by a Pokémon, it recovers from a burn.'),
  new Items('Razor Claw', 'IV', 'Hold Items', 'Increases critical-hit ratio.'),
  new Items('Razor Fang', 'IV', 'Hold Items', 'An item to be held by a Pokémon. It may make foes and allies flinch when the holder inflicts damage.'),
  new Items('Razz Berry', 'III', 'Berries', 'A Berry which is very rare in the Unova region. A maniac will buy it for a high price.'),
  new Items('Reaper Cloth', 'IV', 'General Items', 'A cloth imbued with horrifyingly strong spiritual energy. It is loved by a certain Pokémon.'),
  new Items('Red Apricorn', 'II', 'General Items', 'A red Apricorn. It assails your nostrils.'),
  new Items('Red Card', 'V', 'Hold Items', 'A card with a mysterious power. When the holder is struck by a foe, the attacker is removed from battle.'),
  new Items('Red Flute', 'III', 'General Items', 'A toy flute made from red glass. A maniac will buy it for a high price.'),
  new Items('Red Nectar', 'VII', 'Hold Items', 'A flower nectar obtained at Ula\'ula Meadow. It changes the form of certain species of Pokémon.'),
  new Items('Red Scarf', 'III', 'General Items', 'Raises holder\'s Cool aspect in a Contest.'),
  new Items('Red Shard', 'III', 'General Items', 'A small red shard. It appears to be from some sort of implement made long ago.'),
  new Items('Relic Band', 'V', 'General Items', 'A bracelet made in a civilization about 3,000 years ago. A maniac will buy it for a high price.'),
  new Items('Relic Copper', 'V', 'General Items', 'A copper coin used in a civilization about 3,000 years ago. A maniac will buy it for a high price.'),
  new Items('Relic Crown', 'V', 'General Items', 'A crown made in a civilization about 3,000 years ago. A maniac will buy it for a high price.'),
  new Items('Relic Gold', 'V', 'General Items', 'A gold coin used in a civilization about 3,000 years ago. A maniac will buy it for a high price.'),
  new Items('Relic Silver', 'V', 'General Items', 'A silver coin used in a civilization about 3,000 years ago. A maniac will buy it for a high price.'),
  new Items('Relic Statue', 'V', 'General Items', 'A stone figure made in a civilization about 3,000 years ago. A maniac will buy it for a high price.'),
  new Items('Relic Vase', 'V', 'General Items', 'A vase made in a civilization about 3,000 years ago. A maniac will buy it for a high price.'),
  new Items('Repeat Ball', 'III', 'Pokeballs', 'A somewhat different Poké Ball that works especially well on Pokémon species that were previously caught.'),
  new Items('Repel', 'I', 'General Items', 'An item that prevents weak wild Pokémon from appearing for 100 steps after its use.'),
  new Items('Reset Urge', 'V', 'Battle Items', 'When used, it restores any stat changes of an ally Pokémon.'),
  new Items('Resist Wing', 'V', 'Medicine', 'Increases Defense EVs by 1.'),
  new Items('Reveal Glass', 'V', 'General Items', 'A looking glass that reveals the truth. It’s a mysterious glass that returns a Pokémon to its original shape.'),
  new Items('Revival Herb', 'II', 'Medicine', 'Revives a Pokémon to max HP, but lowers Friendship.'),
  new Items('Revive', 'I', 'Medicine', 'A medicine that revives a fainted Pokémon. It restores half the Pokémon’s maximum HP.'),
  new Items('Rindo Berry', 'IV', 'Berries', 'Weakens a supereffective Grass-type attack against the holding Pokémon.'),
  new Items('Ring Target', 'V', 'Hold Items', 'Moves that would otherwise have no effect will land on the Pokémon that holds it.'),
  new Items('Rock Gem', 'V', 'Hold Items', 'Increases the power of a Rock-type move only once.'),
  new Items('Rock Incense', 'IV', 'Hold Items', 'Increases the power of Rock-type moves.'),
  new Items('Rock Memory', 'VII', 'Hold Items', 'Changes Silvally and its move Multi-Attack to Rock type.'),
  new Items('Rockium Z', 'VII', 'Hold Items', 'Allows the use of Continental Crush, the Rock type Z-Move.'),
  new Items('Rocky Helmet', 'V', 'Hold Items', 'If the holder of this item takes damage, the attacker will also be damaged upon contact.'),
  new Items('Roller Skates', 'VI', 'General Items', 'Attaches roller skates to the bottom of your shoes, allowing you to glide quickly around and perform tricks.'),
  new Items('Root Fossil', 'III', 'General Items', 'A fossil of an ancient Pokémon that lived in the sea. It appears to be part of a plant root.'),
  new Items('Rose Incense', 'IV', 'Hold Items', 'Increases the power of Grass-type moves.'),
  new Items('Roseli Berry', 'VI', 'Berries', 'If held by a Pokémon, this Berry will lessen the damage taken from one supereffective Fairy-type attack.'),
  new Items('Roto Bargain', 'VII', 'Battle Items', 'Reduces the prices of products at Poké Marts by half.'),
  new Items('Roto Boost', 'VII', 'Battle Items', 'Raises all stats of your battling Pokémon.'),
  new Items('Roto Catch', 'VII', 'Battle Items', 'Increases the chance to catch Pokémon a lot.'),
  new Items('Roto Encounter', 'VII', 'Battle Items', 'Increases the chance of encountering high-level wild Pokémon a lot for a certain period of time.'),
  new Items('Roto Exp. Points', 'VII', 'Battle Items', 'Increases the Exp. Points your Pokémon receive after battle a little.'),
  new Items('Roto Friendship', 'VII', 'Battle Items', 'Helps Pokémon in your party grow friendly faster.'),
  new Items('Roto Hatch', 'VII', 'Battle Items', 'Helps Eggs hatch faster.'),
  new Items('Roto HP Restore', 'VII', 'Battle Items', 'Fully restores the HP of your battling Pokémon.'),
  new Items('Roto PP Restore', 'VII', 'Battle Items', 'Fully restores the PP of your battling Pokémon.'),
  new Items('Roto Prize Money', 'VII', 'Battle Items', 'Triples the prize money you receive after battle.'),
  new Items('Roto Stealth', 'VII', 'Battle Items', 'Prevents you from encountering wild Pokémon for a certain period of time.'),
  new Items('Rowap Berry', 'IV', 'Berries', 'If held by a Pokémon and a special attack lands, the attacker also takes damage.'),
  new Items('Sablenite', 'VI', 'Hold Items', 'Enables Sableye to Mega Evolve during battle.'),
  new Items('Sachet', 'VI', 'General Items', 'A sachet filled with fragrant perfumes that are just slightly too overwhelming. Yet it’s loved by a certain Pokémon.'),
  new Items('Sacred Ash', 'II', 'Medicine', 'It revives all fainted Pokémon. In doing so, it also fully restores their HP.'),
  new Items('Safari Ball', 'I', 'Pokeballs', 'A special Poké Ball that is used only in the Great Marsh. It is decorated in a camouflage pattern.'),
  new Items('Safety Goggles', 'VI', 'Hold Items', 'Prevents damage from weather and powder.'),
  new Items('Salac Berry', 'III', 'Berries', 'Raises Speed when HP is low.'),
  new Items('Salamencite', 'VI', 'Hold Items', 'Enables Salamence to Mega Evolve during battle.'),
  new Items('Sceptilite', 'VI', 'Hold Items', 'Enables Sceptile to Mega Evolve during battle.'),
  new Items('Scizorite', 'VI', 'Hold Items', 'Enables Scizor to Mega Evolve during battle.'),
  new Items('Scope Lens', 'III', 'Hold Items', 'Increases critical-hit ratio.'),
  new Items('Sea Incense', 'III', 'Hold Items', 'Increases the power of Water-type moves.'),
  new Items('Shalour Sable', 'VI', 'Medicine', 'Heals all major status conditions.'),
  new Items('Sharp Beak', 'II', 'Hold Items', 'Increases the power of Flying-type moves.'),
  new Items('Sharpedonite', 'VI', 'Hold Items', 'Enables Sharpedo to Mega Evolve during battle.'),
  new Items('Shed Shell', 'IV', 'Hold Items', 'A tough, discarded carapace to be held by a Pokémon. It enables the holder to switch with a waiting Pokémon in battle.'),
  new Items('Shell Bell', 'III', 'Hold Items', 'An item to be held by a Pokémon. The holder’s HP is restored a little every time it inflicts damage.'),
  new Items('Shiny Charm', 'V', 'Key Items', 'A shiny charm said to increase the chance of finding a Shiny Pokémon in the wild.'),
  new Items('Shiny Stone', 'IV', 'General Items', 'A peculiar stone that makes certain species of Pokémon evolve. It shines with a dazzling light.'),
  new Items('Shoal Salt', 'III', 'General Items', 'Pure salt that can be discovered deep inside the Shoal Cave. A maniac will buy it for a high price.'),
  new Items('Shoal Shell', 'III', 'General Items', 'A pretty seashell that can be found deep inside the Shoal Cave. A maniac will buy it for a high price.'),
  new Items('Shock Drive', 'V', 'Hold Items', 'Changes Techno Blast to an Electric-type move when held by Genesect.'),
  new Items('Shuca Berry', 'IV', 'Berries', 'Weakens a supereffective Ground-type attack against the holding Pokémon.'),
  new Items('Silk Scarf', 'III', 'Hold Items', 'Increases the power of Normal-type moves.'),
  new Items('Silver Leaf', 'II', 'General Items', 'A strange, silver-colored leaf.'),
  new Items('Silver Nanab Berry', 'VII', 'Berries', 'Greatly calms a Pokémon in battle in Pokémon Let\'s Go.'),
  new Items('Silver Pinap Berry', 'VII', 'Berries', 'Greatly increases chance of getting items when a Pokémon is caught in Pokémon Let\'s Go.'),
  new Items('Silver Powder', 'II', 'Hold Items', 'Increases the power of Bug-type moves.'),
  new Items('Silver Razz Berry', 'VII', 'Berries', 'Makes a Pokémon easier to catch in Pokémon Let\'s Go.'),
  new Items('Sitrus Berry', 'III', 'Berries', 'If held by a Pokémon, it heals the user’s HP a little.'),
  new Items('Skull Fossil', 'IV', 'General Items', 'A fossil from a prehistoric Pokémon that lived on the land. It appears to be part of a head.'),
  new Items('Sky Plate', 'IV', 'Hold Items', 'Increases power of Flying-type moves. Changes Arceus\' type to Flying.'),
  new Items('Slowbronite', 'VI', 'Hold Items', 'Enables Slowbro to Mega Evolve during battle.'),
  new Items('Small Bouquet', 'VII', 'General Items', 'A gift from your partner in Pokémon Let\'s Go.'),
  new Items('Smart Candy', 'VII', 'Medicine', 'Increases a Pokémon\'s Special Attack stat by 1.'),
  new Items('Smart Candy L', 'VII', 'Medicine', 'Increases a Pokémon\'s Special Attack stat by 1. The Pokémon must be level 30.'),
  new Items('Smart Candy XL', 'VII', 'Medicine', 'Increases a Pokémon\'s Special Attack stat by 1. The Pokémon must be level 60.'),
  new Items('Smoke Ball', 'III', 'Pokeballs', 'An item to be held by a Pokémon. It enables the holder to flee from any wild Pokémon without fail.'),
  new Items('Smooth Rock', 'IV', 'Hold Items', 'A Pokémon held item that extends the duration of the move Sandstorm used by the holder.'),
  new Items('Snorlium Z', 'VII', 'Hold Items', 'Allows Snorlax to upgrade Giga Impact to a Z-Move, Pulverizing Pancake.'),
  new Items('Snowball', 'VI', 'Hold Items', 'Raises Attack if hit by an Ice-type move.'),
  new Items('Soda Pop', 'I', 'Medicine', 'Restores 50 HP.'),
  new Items('Soft Sand', 'II', 'Hold Items', 'Increases the power of Ground-type moves.'),
  new Items('Solganium Z', 'VII', 'Hold Items', 'Allows Solgaleo to upgrade Sunsteel Strike to a Z-Move, Searing Sunraze Smash.'),
  new Items('Soothe Bell', 'II', 'Hold Items', 'An item to be held by a Pokémon. It is a bell with a comforting chime that calms the holder and makes it friendly.'),
  new Items('Soul Dew', 'III', 'Hold Items', 'Increases both Special Attack and Special Defense when held by Latios or Latias.'),
  new Items('Spell Tag', 'II', 'Hold Items', 'Increases the power of Ghost-type moves.'),
  new Items('Spelon Berry', 'III', 'Berries', 'A Berry which is very rare in the Unova region. A maniac will buy it for a high price.'),
  new Items('Splash Plate', 'IV', 'Hold Items', 'Increases power of Water-type moves. Changes Arceus\' type to Water.'),
  new Items('Spooky Plate', 'IV', 'Hold Items', 'Increases power of Ghost-type moves. Changes Arceus\' type to Ghost.'),
  new Items('Sport Ball', 'II', 'Pokeballs', 'A special Poké Ball for the Bug-Catching Contest.'),
  new Items('Sprinklotad', 'VI', 'Key Items', 'A watering can shaped like a Lotad. It helps promote the healthy growth of any Berries planted in good, soft soil.'),
  new Items('Stable Mulch', 'IV', 'General Items', 'A fertilizer to be spread on soft soil in regions where Berries are grown. A maniac will buy it for a high price.'),
  new Items('Star Piece', 'II', 'General Items', 'A shard of a pretty gem that sparkles in a red color. It can be sold at a high price to shops.'),
  new Items('Stardust', 'II', 'General Items', 'Lovely, red-colored sand with a loose, silky feel. It can be sold at a high price to shops.'),
  new Items('Starf Berry', 'III', 'Berries', 'Sharply raises a random stat when HP is low.'),
  new Items('Steel Gem', 'V', 'Hold Items', 'Increases the power of a Steel-type move only once.'),
  new Items('Steel Memory', 'VII', 'Hold Items', 'Changes Silvally and its move Multi-Attack to Steel type.'),
  new Items('Steelium Z', 'VII', 'Hold Items', 'Allows the use of Corkscrew Crash, the Steel type Z-Move.'),
  new Items('Steelixite', 'VI', 'Hold Items', 'Enables Steelix to Mega Evolve during battle.'),
  new Items('Stick', 'II', 'Hold Items', 'Increases critical-hit ratio when held by Farfetch\'d.'),
  new Items('Sticky Barb', 'IV', 'Hold Items', 'A held item that damages the holder on every turn. It may latch on to foes and allies that touch the holder.'),
  new Items('Stone Plate', 'IV', 'Hold Items', 'Increases power of Rock-type moves. Changes Arceus\' type to Rock.'),
  new Items('Strange Souvenir', 'VI', 'General Items', 'An ornament depicting a Pokémon that is venerated as a protector in some region far from Kalos.'),
  new Items('Stretchy Spring', 'VII', 'General Items', 'A thin small spring. It’s totally stretched out, and what it’s used for is unknown.'),
  new Items('Sun Stone', 'II', 'General Items', 'A peculiar stone that makes certain species of Pokémon evolve. It is as red as the sun.'),
  new Items('Super Lure', 'VII', 'General Items', 'A glass bottle of perfume that makes rare Pokémon more likely to appear. It lasts longer than a Lure.'),
  new Items('Super Potion', 'I', 'Medicine', 'Restores 60 HP.'),
  new Items('Super Repel', 'I', 'General Items', 'An item that prevents weak wild Pokémon from appearing for 200 steps after its use.'),
  new Items('Swampertite', 'VI', 'Hold Items', 'Enables Swampert to Mega Evolve during battle.'),
  new Items('Sweet Heart', 'V', 'Medicine', 'Very sweet chocolate. It restores the HP of one Pokémon by only 20 points.'),
  new Items('Swift Wing', 'V', 'Medicine', 'Increases Speed EVs by 1.'),
  new Items('Tamato Berry', 'III', 'Berries', 'Increases Friendship but lowers Speed EVs.'),
  new Items('Tanga Berry', 'III', 'Berries', 'Weakens a supereffective Bug-type attack against the holding Pokémon.'),
  new Items('Tapunium Z', 'VII', 'Hold Items', 'Allows the Tapus to upgrade Nature\'s Madness to a Z-Move, Guardian of Alola.'),
  new Items('Terrain Extender', 'VII', 'Hold Items', 'An item to be held by a Pokémon. It extends the duration of the terrain caused by the holder’s move or Ability.'),
  new Items('Thick Club', 'III', 'Hold Items', 'Increases Attack when held by Cubone or Marowak.'),
  new Items('Thunder Stone', 'I', 'General Items', 'A peculiar stone that makes certain species of Pokémon evolve. It has a thunderbolt pattern.'),
  new Items('Timer Ball', 'III', 'Pokeballs', 'A somewhat different BALL that becomes progressively better the more turns there are in a battle.'),
  new Items('Tiny Mushroom', 'II', 'General Items', 'A small and rare mushroom. It is sought after by collectors.'),
  new Items('TM01', 'I', 'Machines', 'Teaches the move Mega Punch/Dynamic Punch/Focus Punch/Hone Claws/Work Up/Headbutt.'),
  new Items('TM02', 'I', 'Machines', 'Teaches the move Razor Wind/Headbutt/Dragon Claw/Taunt.'),
  new Items('TM03', 'I', 'Machines', 'Teaches the move Swords Dance/Curse/Water Pulse/Psyshock/Helping Hand.'),
  new Items('TM04', 'I', 'Machines', 'Teaches the move Whirlwind/Rollout/Calm Mind/Teleport.'),
  new Items('TM05', 'I', 'Machines', 'Teaches the move Mega Kick/Roar/Rest.'),
  new Items('TM06', 'I', 'Machines', 'Teaches the move Toxic/Light Screen.'),
  new Items('TM07', 'I', 'Machines', 'Teaches the move Horn Drill/Zap Cannon/Hail/Protect.'),
  new Items('TM08', 'I', 'Machines', 'Teaches the move Body Slam/Rock Smash/Bulk Up/Substitute.'),
  new Items('TM09', 'I', 'Machines', 'Teaches the move Take Down/Psych Up/Bullet Seed/Venoshock/Reflect.'),
  new Items('TM10', 'I', 'Machines', 'Teaches the move Double-Edge/Hidden Power/Dig.'),
  new Items('TM11', 'I', 'Machines', 'Teaches the move BubbleBeam/Sunny Day/Will-O-Wisp.'),
  new Items('TM12', 'I', 'Machines', 'Teaches the move Water Gun/Sweet Scent/Taunt/Facade.'),
  new Items('TM13', 'I', 'Machines', 'Teaches the move Snore/Ice Beam/Brick Break.'),
  new Items('TM14', 'I', 'Machines', 'Teaches the move Blizzard/Fly.'),
  new Items('TM15', 'I', 'Machines', 'Teaches the move Hyper Beam/Seismic Toss.'),
  new Items('TM16', 'I', 'Machines', 'Teaches the move Pay Day/Icy Wind/Light Screen/Thunder Wave.'),
  new Items('TM17', 'I', 'Machines', 'Teaches the move Submission/Protect/Dragon Tail.'),
  new Items('TM18', 'I', 'Machines', 'Teaches the move Counter/Rain Dance/U-turn.'),
  new Items('TM19', 'I', 'Machines', 'Teaches the move Seismic Toss/Giga Drain/Telekinesis/Roost/Iron Tail.'),
  new Items('TM20', 'I', 'Machines', 'Teaches the move Rage/Endure/Safeguard/Dark Pulse.'),
  new Items('TM21', 'I', 'Machines', 'Teaches the move Mega Drain/Frustration/Foul Play.'),
  new Items('TM22', 'I', 'Machines', 'Teaches the move SolarBeam/Rock Slide.'),
  new Items('TM23', 'I', 'Machines', 'Teaches the move Dragon Rage/Iron Tail/Smack Down/Thunder Punch.'),
  new Items('TM24', 'I', 'Machines', 'Teaches the move Thunderbolt/DragonBreath/X-Scissor.'),
  new Items('TM25', 'I', 'Machines', 'Teaches the move Thunder/Waterfall.'),
  new Items('TM26', 'I', 'Machines', 'Teaches the move Earthquake/Poison Jab.'),
  new Items('TM27', 'I', 'Machines', 'Teaches the move Fissure/Return/Toxic.'),
  new Items('TM28', 'I', 'Machines', 'Teaches the move Dig/Leech Life/Tri Attack.'),
  new Items('TM29', 'I', 'Machines', 'Teaches the move Psychic/Scald.'),
  new Items('TM30', 'I', 'Machines', 'Teaches the move Teleport/Shadow Ball/Bulk Up.'),
  new Items('TM31', 'I', 'Machines', 'Teaches the move Mimic/Mud-Slap/Brick Break/Fire Punch.'),
  new Items('TM32', 'I', 'Machines', 'Teaches the move Double Team/Dazzling Gleam.'),
  new Items('TM33', 'I', 'Machines', 'Teaches the move Ice Punch/Reflect/Calm Mind.'),
  new Items('TM34', 'I', 'Machines', 'Teaches the move Bide/Swagger/Shock Wave/Sludge Wave/Dragon Pulse.'),
  new Items('TM35', 'I', 'Machines', 'Teaches the move Metronome/Sleep Talk/Flamethrower/Ice Punch.'),
  new Items('TM36', 'I', 'Machines', 'Teaches the move Selfdestruct/Sludge Bomb/Thunderbolt.'),
  new Items('TM37', 'I', 'Machines', 'Teaches the move Egg Bomb/Sandstorm/Flamethrower.'),
  new Items('TM38', 'I', 'Machines', 'Teaches the move Fire Blast/Thunder.'),
  new Items('TM39', 'I', 'Machines', 'Teaches the move Swift/Rock Tomb/Outrage.'),
  new Items('TM40', 'I', 'Machines', 'Teaches the move Skull Bash/Defense Curl/Aerial Ace/Psychic.'),
  new Items('TM41', 'I', 'Machines', 'Teaches the move Softboiled/ThunderPunch/Torment/Earthquake.'),
  new Items('TM42', 'I', 'Machines', 'Teaches the move Dream Eater/Facade/Self-Destruct.'),
  new Items('TM43', 'I', 'Machines', 'Teaches the move Sky Attack/Detect/Secret Power/Flame Charge/Shadow Ball.'),
  new Items('TM44', 'I', 'Machines', 'Teaches the move Rest/Play Rough.'),
  new Items('TM45', 'I', 'Machines', 'Teaches the move Thunder Wave/Attract/Solar Beam.'),
  new Items('TM46', 'I', 'Machines', 'Teaches the move Psywave/Thief/Fire Blast.'),
  new Items('TM47', 'I', 'Machines', 'Teaches the move Explosion/Steel Wing/Low Sweep/Surf.'),
  new Items('TM48', 'I', 'Machines', 'Teaches the move Rock Slide/Fire Punch/Skill Swap/Round/Hyper Beam.'),
  new Items('TM49', 'I', 'Machines', 'Teaches the move Tri Attack/Fury Cutter/Snatch/Echoed Voice/Superpower.'),
  new Items('TM50', 'IV', 'Machines', 'Teaches the move Substitute/Nightmare/Overheat/Roost.'),
  new Items('TM51', 'IV', 'Machines', 'Teaches the move Roost/Ally Switch/Steel Wing/Blizzard.'),
  new Items('TM52', 'IV', 'Machines', 'Teaches the move Focus Blast/Sludge Bomb.'),
  new Items('TM53', 'IV', 'Machines', 'Teaches the move Energy Ball/Mega Drain.'),
  new Items('TM54', 'IV', 'Machines', 'Teaches the move False Swipe/Flash Cannon.'),
  new Items('TM55', 'IV', 'Machines', 'Teaches the move Brine/Scald/Ice Beam.'),
  new Items('TM56', 'IV', 'Machines', 'Teaches the move Fling/Stealth Rock.'),
  new Items('TM57', 'IV', 'Machines', 'Teaches the move Charge Beam/Pay Day.'),
  new Items('TM58', 'IV', 'Machines', 'Teaches the move Endure/Sky Drop/Drill Run.'),
  new Items('TM59', 'IV', 'Machines', 'Teaches the move Dragon Pulse/Incinerate/Brutal Swing/Dream Eater.'),
  new Items('TM60', 'IV', 'Machines', 'Teaches the move Drain Punch/Quash/Megahorn.'),
  new Items('TM61', 'IV', 'Machines', 'Teaches the move Will-O-Wisp.'),
  new Items('TM62', 'IV', 'Machines', 'Teaches the move Silver Wind/Acrobatics.'),
  new Items('TM63', 'IV', 'Machines', 'Teaches the move Embargo.'),
  new Items('TM64', 'IV', 'Machines', 'Teaches the move Explosion.'),
  new Items('TM65', 'IV', 'Machines', 'Teaches the move Shadow Claw.'),
  new Items('TM66', 'IV', 'Machines', 'Teaches the move Payback.'),
  new Items('TM67', 'IV', 'Machines', 'Teaches the move Recycle/Retaliate/Smart Strike.'),
  new Items('TM68', 'IV', 'Machines', 'Teaches the move Giga Impact.'),
  new Items('TM69', 'IV', 'Machines', 'Teaches the move Rock Polish.'),
  new Items('TM70', 'IV', 'Machines', 'Teaches the move Flash/Aurora Veil.'),
  new Items('TM71', 'IV', 'Machines', 'Teaches the move Stone Edge.'),
  new Items('TM72', 'IV', 'Machines', 'Teaches the move Avalanche/Volt Switch.'),
  new Items('TM73', 'IV', 'Machines', 'Teaches the move Thunder Wave.'),
  new Items('TM74', 'IV', 'Machines', 'Teaches the move Gyro Ball.'),
  new Items('TM75', 'IV', 'Machines', 'Teaches the move Swords Dance.'),
  new Items('TM76', 'IV', 'Machines', 'Teaches the move Stealth Rock/Struggle Bug/Fly.'),
  new Items('TM77', 'IV', 'Machines', 'Teaches the move Psych Up.'),
  new Items('TM78', 'IV', 'Machines', 'Teaches the move Captivate/Bulldoze.'),
  new Items('TM79', 'IV', 'Machines', 'Teaches the move Dark Pulse/Frost Breath.'),
  new Items('TM80', 'IV', 'Machines', 'Teaches the move Rock Slide.'),
  new Items('TM81', 'IV', 'Machines', 'Teaches the move X-Scissor.'),
  new Items('TM82', 'IV', 'Machines', 'Teaches the move Sleep Talk/Dragon Tail.'),
  new Items('TM83', 'IV', 'Machines', 'Teaches the move Natural Gift/Work Up/Infestation.'),
  new Items('TM84', 'IV', 'Machines', 'Teaches the move Poison Jab.'),
  new Items('TM85', 'IV', 'Machines', 'Teaches the move Dream Eater.'),
  new Items('TM86', 'IV', 'Machines', 'Teaches the move Grass Knot.'),
  new Items('TM87', 'IV', 'Machines', 'Teaches the move Swagger.'),
  new Items('TM88', 'IV', 'Machines', 'Teaches the move Pluck/Sleep Talk.'),
  new Items('TM89', 'IV', 'Machines', 'Teaches the move U-turn.'),
  new Items('TM90', 'IV', 'Machines', 'Teaches the move Substitute.'),
  new Items('TM91', 'IV', 'Machines', 'Teaches the move Flash Cannon.'),
  new Items('TM92', 'IV', 'Machines', 'Teaches the move Trick Room.'),
  new Items('TM93', 'V', 'Machines', 'Teaches the move Wild Charge.'),
  new Items('TM94', 'V', 'Machines', 'Teaches the move Rock Smash/Surf.'),
  new Items('TM95', 'V', 'Machines', 'Teaches the move Snarl.'),
  new Items('TM96', 'VI', 'Machines', 'Teaches the move Nature Power.'),
  new Items('TM97', 'VI', 'Machines', 'Teaches the move Dark Pulse.'),
  new Items('TM98', 'VI', 'Machines', 'Teaches the move Power-Up Punch/Waterfall.'),
  new Items('TM99', 'VI', 'Machines', 'Teaches the move Dazzling Gleam.'),
  new Items('TM100', 'VI', 'Machines', 'Teaches the move Confide.'),
  new Items('TMV Pass', 'VI', 'Key Items', 'A commuter pass that allows the holder to ride the TMV between Lumiose City and Kiloude City at any time.'),
  new Items('Tough Candy', 'VII', 'Medicine', 'Increases a Pokémon\'s Defense stat by 1.'),
  new Items('Tough Candy L', 'VII', 'Medicine', 'Increases a Pokémon\'s Defense stat by 1. The Pokémon must be level 30.'),
  new Items('Tough Candy XL', 'VII', 'Medicine', 'Increases a Pokémon\'s Defense stat by 1. The Pokémon must be level 60.'),
  new Items('Toxic Orb', 'IV', 'Hold Items', 'An item to be held by a Pokémon. It is a bizarre orb that badly poisons the holder in battle.'),
  new Items('Toxic Plate', 'IV', 'Hold Items', 'Increases power of Poison-type moves. Changes Arceus\' type to Poison.'),
  new Items('Tropical Shell', 'VII', 'General Items', 'A beautiful white shell that may have drifted from a sea in a warm region.'),
  new Items('Twisted Spoon', 'II', 'Hold Items', 'Increases the power of Psychic-type moves.'),
  new Items('Tyranitarite', 'VI', 'Hold Items', 'Enables Tyranitar to Mega Evolve during battle.'),
  new Items('Ultra Ball', 'I', 'Pokeballs', 'An ultra-performance Ball that provides a higher Pokémon catch rate than a Great Ball.'),
  new Items('Ultranecrozium Z', 'VII', 'Hold Items', 'Allows Ultra Necrozma to upgrade Photon Geyser to a Z-Move, Light That Burns the Sky.'),
  new Items('Up-Grade', 'II', 'General Items', 'A transparent device filled with all sorts of data. It was produced by Silph Co.'),
  new Items('Venusaurite', 'VI', 'Hold Items', 'Enables Venusaur to Mega Evolve during battle.'),
  new Items('Wacan Berry', 'IV', 'Berries', 'Weakens a supereffective Electric-type attack against the holding Pokémon.'),
  new Items('Water Gem', 'V', 'Hold Items', 'Increases the power of a Water-type move only once.'),
  new Items('Water Memory', 'VII', 'Hold Items', 'Changes Silvally and its move Multi-Attack to Water type.'),
  new Items('Water Stone', 'I', 'General Items', 'A peculiar stone that makes certain species of Pokémon evolve. It is a clear, light blue.'),
  new Items('Waterium Z', 'VII', 'Hold Items', 'Allows the use of Hydro Vortex, the Water type Z-Move.'),
  new Items('Watmel Berry', 'III', 'Berries', 'A Berry which is very rare in the Unova region. A maniac will buy it for a high price.'),
  new Items('Wave Incense', 'IV', 'Hold Items', 'Increases the power of Water-type moves.'),
  new Items('Weakness Policy', 'VI', 'Hold Items', 'Sharply raises Attack and Special Attack if hit by a super-effective move.'),
  new Items('Wepear Berry', 'III', 'Berries', 'A Berry which is very rare in the Unova region. A maniac will buy it for a high price.'),
  new Items('Whipped Dream', 'VI', 'General Items', 'A soft and sweet treat made of fluffy, puffy, whipped and whirled cream. It’s loved by a certain Pokémon.'),
  new Items('White Apricorn', 'II', 'General Items', 'A white Apricorn. It doesn’t smell like anything.'),
  new Items('White Flute', 'III', 'General Items', 'A toy flute made from white glass. A maniac will buy it for a high price.'),
  new Items('White Herb', 'III', 'Hold Items', 'An item to be held by a Pokémon. It restores any lowered stat in battle. It can be used only once.'),
  new Items('Wide Lens', 'IV', 'Hold Items', 'Increases the accuracy of moves.'),
  new Items('Wiki Berry', 'III', 'Berries', 'Restores HP if it\'s low, but may cause confusion.'),
  new Items('Wise Glasses', 'IV', 'Hold Items', 'Increases the power of Special-category moves.'),
  new Items('X Accuracy', 'I', 'Battle Items', 'Raises Accuracy of a Pokémon in battle.'),
  new Items('X Accuracy 2', 'V', 'Battle Items', 'Sharply raises Accuracy of a Pokémon in battle.'),
  new Items('X Accuracy 3', 'V', 'Battle Items', 'Drastically raises Accuracy of a Pokémon in battle.'),
  new Items('X Accuracy 6', 'V', 'Battle Items', 'Immensely raises Accuracy of a Pokémon in battle.'),
  new Items('X Attack', 'I', 'Battle Items', 'Raises Attack of a Pokémon in battle.'),
  new Items('X Attack 2', 'V', 'Battle Items', 'Sharply raises Attack of a Pokémon in battle.'),
  new Items('X Attack 3', 'V', 'Battle Items', 'Drastically raises Attack of a Pokémon in battle.'),
  new Items('X Attack 6', 'V', 'Battle Items', 'Immensely raises Attack of a Pokémon in battle.'),
  new Items('X Defense', 'I', 'Battle Items', 'Raises Defense of a Pokémon in battle.'),
  new Items('X Defense 2', 'V', 'Battle Items', 'Sharply raises Defense of a Pokémon in battle.'),
  new Items('X Defense 3', 'V', 'Battle Items', 'Drastically raises Defense of a Pokémon in battle.'),
  new Items('X Defense 6', 'V', 'Battle Items', 'Immensely raises Defense of a Pokémon in battle.'),
  new Items('X Sp. Atk', 'I', 'Battle Items', 'Raises Special Attack of a Pokémon in battle.'),
  new Items('X Sp. Atk 2', 'V', 'Battle Items', 'Sharply raises Special Attack of a Pokémon in battle.'),
  new Items('X Sp. Atk 3', 'V', 'Battle Items', 'Drastically raises Special Attack of a Pokémon in battle.'),
  new Items('X Sp. Atk 6', 'V', 'Battle Items', 'Immensely raises Special Attack of a Pokémon in battle.'),
  new Items('X Sp. Def', 'II', 'Battle Items', 'Raises Special Defense of a Pokémon in battle.'),
  new Items('X Sp. Def 2', 'V', 'Battle Items', 'Sharply raises Special Defense of a Pokémon in battle.'),
  new Items('X Sp. Def 3', 'V', 'Battle Items', 'Drastically raises Special Defense of a Pokémon in battle.'),
  new Items('X Sp. Def 6', 'V', 'Battle Items', 'Immensely raises Special Defense of a Pokémon in battle.'),
  new Items('X Speed', 'I', 'Battle Items', 'Raises Speed of a Pokémon in battle.'),
  new Items('X Speed 2', 'V', 'Battle Items', 'Sharply raises Speed of a Pokémon in battle.'),
  new Items('X Speed 3', 'V', 'Battle Items', 'Drastically raises Speed of a Pokémon in battle.'),
  new Items('X Speed 6', 'V', 'Battle Items', 'Immensely raises Speed of a Pokémon in battle.'),
  new Items('Yache Berry', 'IV', 'Berries', 'Weakens a supereffective Ice-type attack against the holding Pokémon.'),
  new Items('Yellow Apricorn', 'II', 'General Items', 'A yellow Apricorn. It has an invigorating scent.'),
  new Items('Yellow Flute', 'III', 'General Items', 'A toy flute made from yellow glass. A maniac will buy it for a high price.'),
  new Items('Yellow Nectar', 'VII', 'Hold Items', 'A flower nectar obtained at Melemele Meadow. It changes the form of certain species of Pokémon.'),
  new Items('Yellow Scarf', 'III', 'General Items', 'Raises holder\'s Tough aspect in a Contest.'),
  new Items('Yellow Shard', 'III', 'General Items', 'A small yellow shard. It appears to be from some sort of implement made long ago.'),
  new Items('Zap Plate', 'IV', 'Hold Items', 'Increases power of Electric-type moves. Changes Arceus\' type to Electric.'),
  new Items('Zinc', 'III', 'Medicine', 'Increases Special Defense EVs by 10.'),
  new Items('Zoom Lens', 'IV', 'Hold Items', 'Raises a move\'s accuracy if the holder moves after its target.'),
];


function loadItems() {
  $('#Center').text('Pokémon Item List');
  $('#myInput').val('');
  $('#items-container').empty().append(`<div class="container mt-4"><div class="row"><div class="flex-row col-3"><h4 class="KalosTextStyle">
  Name</h4></div><div class="flex-row col-1"><h4 class="KalosTextStyle">Gen</h4></div><div class="flex-row col-3"><h4 style="font-style: italic;
  text-align: center;" class="pr-3">Category</h4></div><div class="flex-row col-5"><h4 class="KalosTextStyle pr-5">Description</h4></div></div></div>`);

  for (let j = 0; j < itemList.length; j++) {
    itemList[j].loadItemsToPage();
  }
}
