var itemList = [
  new Items('Ability Capsule', 'VI', 'Hold Items', 'A capsule that allows a Pokémon with two Abilities to switch between these Abilities when it is used.'),
  new Items('Ability Urge', 'V', 'Battle Items', 'When used, it activates the Ability of an ally Pokémon.'),
  new Items('Abomasite', 'VI', 'Hold Items', 'Enables Abomasnow to Mega Evolve during battle.'),
  new Items('Absolite', 'VI', 'Hold Items', 'Enables Absol to Mega Evolve during battle.'),
  new Items('Absorb Bulb', 'V', 'Hold Items', 'A consumable bulb. If the holder is hit by a Water-type move, its Sp. Atk will rise.'),
  new Items('Acro Bike', 'III', 'Key Items', 'A bicycle with which the player can do tricks such as jump sideways.'),
  new Items('Adamant Orb', 'IV', 'Hold Items', 'Increases the power of Dragon- and Steel-type moves when held by Dialga.'),
  new Items('Adrenaline Orb', 'VII', 'Hold Items', 'Using it makes wild Pokémon more likely to call for help. If held by a Pokémon, it boosts Speed when intimidated. It can be used only once.'),
  new Items('Adventure Rules', 'VI', 'Key Items', 'Contains information new Trainers should know.'),
  new Items('Aerodactylite', 'VI', 'Hold Items', 'Enables Aerodactyl to Mega Evolve during battle.'),
  new Items('Aggronite', 'VI', 'Hold Items', 'Enables Aggron to Mega Evolve during battle.'),
  new Items('Aguav Berry', 'III', 'Berries', 'Restores HP if it\'s low, but may cause confusion.'),
  new Items('Air Balloon', 'V', 'Hold Items', 'When held by a Pokémon, the Pokémon will float into the air. When the holder is attacked, this item will burst.'),
  new Items('Alakazite', 'VI', 'Hold Items', 'Enables Alakazam to Mega Evolve during battle.'),
  new Items('Aloraichium Z', 'VII', 'Hold Items', 'Allows Alolan Raichu to upgrade Thunderbolt to a Z-Move, Stoked Sparksurfer.'),
  new Items('Altarianite', 'VI', 'Hold Items', 'Enables Altaria to Mega Evolve during battle.'),
  new Items('Ampharosite', 'VI', 'Hold Items', 'Enables Ampharos to Mega Evolve during battle.'),
  new Items('Amulet Coin', 'II', 'Hold Items', 'An item to be held by a Pokémon. It doubles a battle’s prize money if the holding Pokémon joins in.'),
  new Items('Antidote', 'I', 'Medicine', 'A spray-type medicine. It lifts the effect of poison from one Pokémon.'),
  new Items('Apicot Berry', 'III', 'Berries', 'Raises Special Defense when HP is low.'),
  new Items('Armor Fossil', 'IV', 'General Items', 'A fossil from a prehistoric Pokémon that lived on the land. It appears to be part of a collar.'),
  new Items('Aspear Berry', 'III', 'Berries', 'If held by a Pokémon, it defrosts it.'),
  new Items('Assault Vest', 'VI', 'Hold Items', 'Raises Special Defense but prevents the use of status moves.'),
  new Items('Audinite', 'VI', 'Hold items', 'Enables Audino to Mega Evolve during battle.'),
  new Items('Autograph', 'VII', 'Key Items', 'The Autograph serves no practical purpose.'),
  new Items('Awakening', 'I', 'Medicine', 'A spray-type medicine. It awakens a Pokémon from the clutches of sleep.'),
  new Items('Babiri Berry', 'IV', 'Berries', 'Weakens a supereffective Steel-type attack against the holding Pokémon.'),
  new Items('Balm Mushroom', 'V', '', 'A rare mushroom which gives off a nice fragrance. A maniac will buy it for a high price.'),
  new Items('Banettite', 'VI', '', 'Enables Banette to Mega Evolve during battle.'),
  new Items('Beach Glass', 'VII', '', ''),
  new Items('Beast Ball', 'VII', '', 'A special Poké Ball designed to catch Ultra Beasts. It has a low success rate for catching others.'),
  new Items('Beedrillite', 'VI', '', 'Enables Beedrill to Mega Evolve during battle.'),
  new Items('Belue Berry', 'III', '', 'A Berry which is very rare in the Unova region. A maniac will buy it for a high price.'),
  new Items('Berry Juice', 'II', '', 'A 100% pure juice made of Berries. It restores the HP of one Pokémon by just 20 points.'),
  new Items('Big Malasada', 'VII', '', 'Heals all major status conditions.'),
  new Items('Big Mushroom', 'II', '', 'A large and rare mushroom. It is sought after by collectors.'),
  new Items('Big Nugget', 'V', '', 'A big nugget of pure gold that gives off a lustrous gleam. A maniac will buy it for a high price.'),
  new Items('Big Pearl', 'II', '', 'A quite-large pearl that sparkles in a pretty silver color. It can be sold at a high price to shops.'),
  new Items('Big Root', 'IV', '', 'Recovers more HP from HP-stealing moves.'),
  new Items('Binding Band', 'V', '', 'A band that increases the power of binding moves when held.'),
  new Items('Black Apricorn', 'II', '', 'A black Apricorn It has an indescribable scent.'),
  new Items('Black Belt', 'II', '', 'Increases the power of Fighting-type moves.'),
  new Items('Black Flute', 'III', '', 'A toy flute made from black glass. A maniac will buy it for a high price.'),
  new Items('Black Glasses', 'II', '', 'Increases the power of Dark-type moves.'),
  new Items('Black Sludge', 'IV', '', 'A held item that gradually restores the HP of Poison-type Pokémon. It inflicts damage on all other types.'),
  new Items('Blastoisinite', 'VI', '', 'Enables Blastoise to Mega Evolve during battle.'),
  new Items('Blazikenite', 'VI', '', 'Enables Blaziken to Mega Evolve during battle.'),
  new Items('Blue Apricorn', 'II', '', 'A blue Apricorn. It smells a bit like grass.'),
  new Items('Blue Flute', 'III', '', 'A toy flute made from blue glass. A maniac will buy it for a high price.'),
  new Items('Blue Scarf', 'III', '', 'Raises holder\'s Beauty aspect in a Contest.'),
  new Items('Blue Shard', 'III', '', 'A small blue shard. It appears to be from some sort of implement made long ago.'),
  new Items('Bluk Berry', 'III', '', 'A Berry which is very rare in the Unova region. A maniac will buy it for a high price.'),
  new Items('Bottle Cap', 'VII', '', 'Maximizes one IV stat in Hyper Training.'),
  new Items('Bright Powder', 'II', '', 'Lowers the opponent’s accuracy.'),
  new Items('Bug Gem', 'V', '', 'Increases the power of a Bug-type move only once.'),
  new Items('Bug Memory', 'VII', '', 'Changes Silvally and its move Multi-Attack to Bug type.'),
  new Items('Buginium Z', 'VII', '', 'Allows the use of Savage Spin-Out, the Bug type Z-Move.'),
  new Items('Burn Drive', 'V', '', 'Changes Techno Blast to a Fire-type move when held by Genesect.'),
  new Items('Burn Heal', 'I', '', 'A spray-type medicine. It heals a single Pokémon that is suffering from a burn.'),
  new Items('Calcium', 'I', '', 'Increases Special Attack EVs by 10.'),
  new Items('Cameruptite', 'VI', '', 'Enables Camerupt to Mega Evolve during battle.'),
  new Items('Carbos', 'I', '', 'Increases Speed EVs by 10.'),
  new Items('Casteliacone', 'V', '', 'Heals all major status conditions.'),
  new Items('Cell Battery', 'V', '', 'A consumable battery. If the holder is hit by an Electric-type move, its Attack will rise.'),
  new Items('Chalky Stone', 'VII', '', 'A small whitish stone picked up at the edge of the road.'),
  new Items('Charcoal', 'II', '', 'Increases the power of Fire-type moves.'),
  new Items('Charizardite X', 'VI', '', 'Enables Charizard to Mega Evolve during battle.'),
  new Items('Charizardite Y', 'VI', '', 'Enables Charizard to Mega Evolve during battle.'),
  new Items('Charti Berry', 'IV', '', 'Weakens a supereffective Rock-type attack against the holding Pokémon.'),
  new Items('Cheri Berry', 'III', '', 'If held by a Pokémon, it recovers from paralysis.'),
  new Items('Cherish Ball', 'IV', '', 'A quite rare Poké Ball that has been specially crafted to commemorate an occasion of some sort.'),
  new Items('Chesto Berry', 'III', '', 'If held by a Pokémon, it recovers from sleep.'),
  new Items('Chilan Berry', 'V', '', 'Weakens a Normal-type attack against the Pokémon holding this berry.'),
  new Items('Chill Drive', 'V', '', 'Changes Techno Blast to an Ice-type move when held by Genesect.'),
  new Items('Choice Band', 'III', '', 'Raises Attack, but only one move can be used.'),
  new Items('Choice Scarf', 'IV', '', 'Raises Speed, but only one move can be used.'),
  new Items('Choice Specs', 'IV', '', 'Raises Special Attack, but only one move can be used.'),
  new Items('Chople Berry', 'IV', '', 'Weakens a supereffective Fighting-type attack against the holding Pokémon.'),
  new Items('Claw Fossil', 'III', '', 'A fossil of an ancient Pokémon that lived in the sea. It appears to be part of a claw.'),
  new Items('Cleanse Tag', 'III', '', 'An item to be held by a Pokémon. It helps keep wild Pokémon away if the holder is the first one in the party.'),
  new Items('Clever Wing', 'V', '', 'Increases Special Defense EVs by 1.'),
  new Items('Coba Berry', 'IV', '', 'Weakens a supereffective Flying-type attack against the holding Pokémon.'),
  new Items('Colbur Berry', 'IV', '', 'Weakens a supereffective Dark-type attack against the holding Pokémon.'),
  new Items('Colress Machine', 'V', '', 'A special device that wrings out the potential of Pokémon. It is an imperfect prototype.'),
  new Items('Comet Shard', 'V', '', 'A shard which fell to the ground when a comet approached. A maniac will buy it for a high price.'),
  new Items('Cornn Berry', 'III', '', 'A Berry which is very rare in the Unova region. A maniac will buy it for a high price.'),
  new Items('Courage Candy', 'VII', '', 'Increases a Pokémon\'s Special Defense stat by 1.'),
  new Items('Courage Candy L', 'VII', '', 'Increases a Pokémon\'s Special Defense stat by 1. The Pokémon must be level 30.'),
  new Items('Courage Candy XL', 'VII', '', 'Increases a Pokémon\'s Special Defense stat by 1. The Pokémon must be level 60.'),
  new Items('Cover Fossil', 'V', '', 'A fossil of an ancient Pokémon that lived in the sea in ancient times. It appears to be part of its back.'),
  new Items('Custap Berry', 'IV', '', 'Holder can move first when HP is low.'),
  new Items('Damp Mulch', 'IV', '', 'A fertilizer to be spread on soft soil in regions where Berries are grown. A maniac will buy it for a high price.'),
  new Items('Damp Rock', 'IV', '', 'A Pokémon held item that extends the duration of the move Rain Dance used by the holder.'),
  new Items('Dark Gem', 'V', '', 'Increases the power of a Dark-type move only once.'),
  new Items('Dark Memory', 'VII', '', 'Changes Silvally and its move Multi-Attack to Dark type.'),
  new Items('Darkinium Z', 'VII', '', 'Allows the use of Black Hole Eclipse, the Dark type Z-Move.'),
  new Items('Dawn Stone', 'IV', '', 'A peculiar stone that makes certain species of Pokémon evolve. It sparkles like eyes.'),
  new Items('Decidium Z', 'VII', '', 'Allows Decidueye to upgrade Spirit Shackle to a Z-Move, Sinister Arrow Raid.'),
  new Items('Deep Sea Scale', 'III', '', 'Increases Special Defense when held by Clamperl.'),
  new Items('Deep Sea Tooth', 'III', '', 'Increases Special Attack when held by Clamperl.'),
  new Items('Destiny Knot', 'IV', '', 'A long, thin, bright-red string to be held by a Pokémon. If the holder becomes infatuated, the foe does too.'),
  new Items('Diancite', 'VI', '', 'Enables Diancie to Mega Evolve during battle.'),
  new Items('Dire Hit', 'I', '', 'Raises critical-hit ratio of a Pokémon in battle.'),
  new Items('Dire Hit 2', 'V', '', 'Raises a Pokémon\'s critical-hit ratio in battle.'),
  new Items('Dire Hit 3', 'V', '', 'Greatly raises a Pokémon\'s critical-hit ratio in battle.'),
  new Items('Discount Coupon', 'VI', '', 'This special coupon allows you to buy items at a discount when you are shopping at a boutique.'),
  new Items('Dive Ball', 'III', '', 'A somewhat different Poké Ball that works especially well on Pokémon that live underwater.'),
  new Items('DNA Splicers', 'V', '', 'A splicer that fuses Kyurem and a certain Pokémon. They are said to have been one in the beginning.'),
  new Items('Dome Fossil', 'III', '', '	A fossil of an ancient Pokémon that lived in the sea. It appears to be part of a shell.'),
  new Items('Douse Drive', 'V', '', 'Changes Techno Blast to a Water-type move when held by Genesect.'),
  new Items('Draco Plate', 'IV', '', 'Increases power of Dragon-type moves. Changes Arceus\' type to Dragon.'),
  new Items('Dragon Fang', 'II', '', 'Increases the power of Dragon-type moves.'),
  new Items('Dragon Gem', 'V', '', 'Increases the power of a Dragon-type move only once.'),
  new Items('Dragon Memory', 'VII', '', 'Changes Silvally and its move Multi-Attack to Dragon type.'),
  new Items('Dragon Scale', 'II', '', 'A thick and tough scale. Dragon-type Pokémon may be holding this item when caught.'),
  new Items('Dragonium Z', 'VII', '', 'Allows the use of Devastating Drake, the Dragon type Z-Move.'),
  new Items('Dread Plate', 'IV', '', 'Increases power of Dark-type moves. Changes Arceus\' type to Dark.'),
  new Items('Dream Ball', 'V', '', 'A special Poké Ball that appears out of nowhere in a bag at the Entree Forest. It can catch any Pokémon.'),
  new Items('Dropped Item', 'V', '', 'The Xtransceiver found at the Nimbasa City amusement park. It seems it belongs to a boy.'),
  new Items('Dubious Disc', 'IV', '', 'A transparent device overflowing with dubious data. Its producer is unknown.'),
  new Items('Durin Berry', 'III', '', 'A Berry which is very rare in the Unova region. A maniac will buy it for a high price.'),
  new Items('Dusk Ball', 'IV', '', 'A somewhat different Poké Ball that makes it easier to catch wild Pokémon at night or in dark places like caves.'),
  new Items('Dusk Stone', 'IV', '', 'A peculiar stone that makes certain species of Pokémon evolve. It is as dark as dark can be.'),
  new Items('Earth Plate', 'IV', '', 'Increases power of Ground-type moves. Changes Arceus\' type to Ground.'),
  new Items('Eevium Z', 'VII', '', 'Allows Eevee to upgrade Last Resort to a Z-Move, Extreme Evoboost.'),
  new Items('Eject Button', 'V', '', 'If the holder is hit by an attack, it will switch with another Pokémon in your party.'),
  new Items('Electirizer', 'IV', '', 'A box packed with a tremendous amount of electric energy. It is loved by a certain Pokémon.'),
  new Items('Electric Gem', 'V', '', 'Increases the power of an Electric-type move only once.'),
  new Items('Electric Memory', 'VII', '', 'Changes Silvally and its move Multi-Attack to Electric type.'),
  new Items('Electric Seed', 'VII', '', 'An item to be held by a Pokémon. It boosts Defense on Electric Terrain. It can only be used once.'),
  new Items('Electrium Z', 'VII', '', 'Allows the use of Gigavolt Havoc, the Electric type Z-Move.'),
  new Items('Elevator Key', 'VI', '', 'A card key that activates the elevator in Lysandre Labs. It is emblazoned with Team Flare’s logo.'),
  new Items('Elixir', 'I', '', 'It restores the PP of all the moves learned by the targeted Pokémon by 10 points each.'),
  new Items('Energy Powder', 'II', '', 'Restores 60 HP but lowers Friendship.'),
  new Items('Energy Root', 'II', '', 'Restores 120 HP but lowers Friendship.'),
  new Items('Enigma Berry', 'III', '', '	If held by a Pokémon, it restores its HP if it is hit by any supereffective attack.'),
  new Items('Escape Rope', 'I', '', 'A long, durable rope. Use it to escape instantly from a cave or a dungeon.'),
  new Items('Ether', 'I', '', 'It restores the PP of a Pokémon’s selected move by a maximum of 10 points.'),
  new Items('Everstone', 'II', '', 'An item to be held by a Pokémon. The Pokémon holding this peculiar stone is prevented from evolving.'),
  new Items('Eviolite', 'V', '', 'A mysterious evolutionary lump. When held, it raises the Defense and Sp. Def of a Pokémon that can still evolve.'),
  new Items('Exp. Share', 'I', '', 'An item to be held by a Pokémon. The holder gets a share of a battle’s Exp. Points without battling.'),
  new Items('Expert Belt', 'IV', '', 'Increases the power of super-effective moves.'),
  new Items('Fairium Z', 'VII', '', 'Allows the use of Twinkle Tackle, the Fairy type Z-Move.'),
  new Items('Fairy Gem', 'VI', '', 'Increases the power of a Fairy-type move only once.'),
  new Items('Fairy Memory', 'VII', '', 'Changes Silvally and its move Multi-Attack to Fairy type.'),
  new Items('Fast Ball', 'II', '', 'A Poké Ball that makes it easier to catch Pokémon which are quick to run away.'),
  new Items('Festival Ticket', 'VII', '', 'A ticket that allows you to host a mission in Festival Plaza.'),
  new Items('Fighting Gem', 'V', '', 'Increases the power of a Fighting-type move only once.'),
  new Items('Fighting Memory', 'VII', '', 'Changes Silvally and its move Multi-Attack to Fighting type.'),
  new Items('Fightinium Z', 'VII', '', 'Allows the use of All-Out Pummeling, the Fighting type Z-Move.'),
  new Items('Figy Berry', 'III', '', 'Restores HP if it\'s low, but may cause confusion.'),
  new Items('Fire Gem', 'V', '', '	Increases the power of a Fire-type move only once.'),
  new Items('Fire Memory', 'VII', '', 'Changes Silvally and its move Multi-Attack to Fire type.'),
  new Items('Fire Stone', 'I', '', 'A peculiar stone that makes certain species of Pokémon evolve. It is colored orange.'),
  new Items('Firium Z', 'VII', '', 'Allows the use of Inferno Overdrive, the Fire type Z-Move.'),
  new Items('Fist Plate', 'IV', '', 'Increases power of Fighting-type moves. Changes Arceus\' type to Fighting.'),
  new Items('Flame Orb', 'IV', '', 'An item to be held by a Pokémon. It is a bizarre orb that inflicts a burn on the holder in battle.'),
  new Items('Flame Plate', 'IV', '', 'Increases power of Fire-type moves. Changes Arceus\' type to Fire.'),
  new Items('Float Stone', 'V', '', 'A very light stone. It reduces the weight of a Pokémon when held.'),
  new Items('Fluffy Tail', 'III', '', 'An item that attracts Pokémon. Use it to flee from any battle with a wild Pokémon.'),
  new Items('Flying Gem', 'V', '', 'Increases the power of a Flying-type move only once.'),
  new Items('Flying Memory', 'VII', '', 'Changes Silvally and its move Multi-Attack to Flying type.'),
  new Items('Flyinium Z', 'VII', '', 'Allows the use of Supersonic Skystrike, the Flying type Z-Move.'),
  new Items('Focus Band', 'II', '', 'An item to be held by a Pokémon. The holder may endure a potential KO attack, leaving it with just 1 HP.'),
  new Items('Focus Sash', 'IV', '', 'An item to be held by a Pokémon. If it has full HP, the holder will endure one potential KO attack, leaving 1 HP.'),
  new Items('Fresh Water', 'I', '', 'Restores 30 HP.'),
  new Items('Friend Ball', 'II', '', 'A Poké Ball that makes caught Pokémon more friendly.'),
  new Items('Full Heal', 'I', '', 'A spray-type medicine. It heals all the status problems of a single Pokémon.'),
  new Items('Full Incense', 'IV', '', 'An item to be held by a Pokémon. It is an exotic-smelling incense that makes the holder bloated and slow moving.'),
  new Items('Full Restore', 'I', '', 'A medicine that fully restores the HP and heals any status problems of a single Pokémon.'),
  new Items('Galladite', 'VI', '', 'Enables Gallade to Mega Evolve during battle.'),
  new Items('Ganlon Berry', 'III', '', 'Raises Defense when HP is low.'),
  new Items('Garchompite', 'VI', '', 'Enables Garchomp to Mega Evolve during battle.'),
  new Items('Gardevoirite', 'VI', '', 'Enables Gardevoir to Mega Evolve during battle.'),
  new Items('Gengarite', 'VI', '', 'Enables Gengar to Mega Evolve during battle.'),
  new Items('Genius Wing', 'V', '', 'Increases Special Attack EVs by 1.'),
  new Items('Ghost Gem', 'V', '', 'Increases the power of a Ghost-type move only once.'),
  new Items('Ghost Memory', 'VII', '', 'Changes Silvally and its move Multi-Attack to Ghost type.'),
  new Items('Ghostium Z', 'VII', '', 'Allows the use of Never-Ending Nightmare, the Ghost type Z-Move.'),
  new Items('Glalitite', 'VI', '', 'Enables Glalie to Mega Evolve during battle.'),
  new Items('Gold Bottle Cap', 'VII', '', 'Maximizes all of a Pokémon\'s IV stats in Hyper Training.'),
  new Items('Gold Leaf', 'II', '', 'A mysterious gold leaf. No trees with this leaf have been found yet.'),
  new Items('Golden Nanab Berry', 'VII', '', 'Drastically calms a Pokémon in battle, in Let\'s Go.'),
  new Items('Golden Pinap Berry', 'VII', '', 'Drastically increases chance of getting items when a Pokémon is caught, in Pokémon Let\'s Go.'),
  new Items('Golden Razz Berry', 'VII', '', 'Makes a Pokémon easier to catch in Pokémon Let\'s Go.'),
  new Items('Gooey Mulch', 'IV', '', 'A fertilizer to be spread on soft soil in regions where Berries are grown. A maniac will buy it for a high price.'),
  new Items('Grass Gem', 'V', '', 'Increases the power of a Grass-type move only once.'),
  new Items('Grass Memory', 'VII', '', 'Changes Silvally and its move Multi-Attack to Grass type.'),
  new Items('Grassium Z', 'VII', '', 'Allows the use of Bloom Doom, the Grass type Z-Move.'),
  new Items('Grassy Seed', 'VII', '', 'An item to be held by a Pokémon. It boosts Defense on Grassy Terrain. It can only be used once.'),
  new Items('Great Ball', 'I', '', 'A good, high-performance Ball that provides a higher Pokémon catch rate than a standard Poké Ball.'),
  new Items('Green Apricorn', 'II', '', 'A green Apricorn. It has a mysterious, aromatic scent.'),
  new Items('Green Scarf', 'III', '', 'Raises holder\'s Smart aspect in a Contest.'),
  new Items('Green Shard', 'III', '', 'A small green shard. It appears to be from some sort of implement made long ago.'),
  new Items('Grepa Berry', 'III', '', 'Increases Friendship but lowers Special Defense EVs.'),
  new Items('Grip Claw', 'IV', '', 'A Pokémon held item that extends the duration of multiturn attacks like Bind and Wrap.'),
  new Items('Griseous Orb', 'IV', '', 'Increases the power of Dragon- and Ghost-type moves when held by Giratina, and changes it to Origin Forme.'),
  new Items('Ground Gem', 'V', '', '	Increases the power of a Ground-type move only once.'),
  new Items('Ground Memory', 'VII', '', 'Changes Silvally and its move Multi-Attack to Ground type.'),
  new Items('Groundium Z', 'VII', '', 'Allows the use of Tectonic Rage, the Ground type Z-Move.'),
  new Items('Growth Mulch', 'IV', '', 'A fertilizer to be spread on soft soil in regions where Berries are grown. A maniac will buy it for a high price.'),
  new Items('Grubby Hanky', 'V', '', 'A handkerchief dropped by a regular at Café Warehouse. It smells faintly like a Pokémon.'),
  new Items('Guard Spec.', 'I', '', 'Prevents stat reduction for five turns.'),
  new Items('Gyaradosite', 'VI', '', 'Enables Gyarados to Mega Evolve during battle.'),
  new Items('Haban Berry', 'IV', '', 'Weakens a supereffective Dragon-type attack against the holding Pokémon.'),
  new Items('Hard Stone', 'II', '', 'Increases the power of Rock-type moves.'),
  new Items('Heal Ball', 'IV', '', 'A remedial Poké Ball that restores the caught Pokémon’s HP and eliminates any status problem.'),
  new Items('Heal Powder', 'II', '', 'Heals all status problems, but lowers Friendship.'),
  new Items('Health Candy', 'VII', '', 'Increases a Pokémon\'s HP stat by 1.'),
  new Items('Health Candy L', 'VII', '', 'Increases a Pokémon\'s HP stat by 1. The Pokémon must be level 30.'),
  new Items('Health Candy XL', 'VII', '', 'Increases a Pokémon\'s HP stat by 1. The Pokémon must be level 60.'),
  new Items('Health Wing', 'V', '', 'Increases HP EVs by 1.'),
  new Items('Heart Scale', 'III', '', 'A pretty, heart-shaped scale that is extremely rare. It glows faintly in the colors of the rainbow.'),
  new Items('Heat Rock', 'IV', '', 'A Pokémon held item that extends the duration of the move Sunny Day used by the holder.'),
  new Items('Heavy Ball', 'II', '', 'A Poké Ball for catching very heavy Pokémon.'),
  new Items('Helix Fossil', 'I', '', 'A fossil of an ancient Pokémon that lived in the sea. It appears to be part of a seashell.'),
  new Items('Heracronite', 'VI', '', 'Enables Heracross to Mega Evolve during battle.'),
  new Items('HM01', 'I', '', 'Teaches the move Cut.'),
  new Items('HM02', 'I', '', 'Teaches the move Fly.'),
  new Items('HM03', 'I', '', 'Teaches the move Surf.'),
  new Items('HM04', 'I', '', 'Teaches the move Strength.'),
  new Items('HM05', 'I', '', 'Teaches the move Flash/Defog/Whirlpool/Waterfall.'),
  new Items('HM06', 'I', '', 'Teaches the move Whirlpool/Rock Smash/Dive.'),
  new Items('HM07', 'I', '', 'Teaches the move Waterfall.'),
  new Items('HM08', 'I', '', 'Teaches the move Dive/Rock Climb.'),
  new Items('Hondew Berry', 'III', '', 'Increases Friendship but lowers Special Attack EVs.'),
  new Items('Honey', 'IV', '', 'A sweet honey with a lush aroma that attracts wild Pokémon when it is used in grass, caves, or on special trees.'),
  new Items('Honor Of Kalos', 'VI', '', 'A precious symbol that is awarded only to an individual who has done great things for the Kalos region.'),
  new Items('Houndoominite', 'VI', '', 'Enables Houndoom to Mega Evolve during battle.'),
  new Items('HP Up', 'I', '', 'Increases HP EVs by 10.'),
  new Items('Hyper Potion', 'I', '', 'Restores 120 HP.'),
  new Items('Iapapa Berry', 'III', '', 'Restores HP if it\'s low, but may cause confusion.'),
  new Items('Ice Gem', 'V', '', 'Increases the power of an Ice-type move only once.'),
  new Items('Ice Heal', 'I', '', 'A spray-type medicine. It defrosts a Pokémon that has been frozen solid.'),
  new Items('Ice Memory', 'VII', '', 'Changes Silvally and its move Multi-Attack to Ice type.'),
  new Items('Ice Stone', 'VII', '', 'A peculiar stone that can make certain species of Pokémon evolve. It has an unmistakable snowflake pattern.'),
  new Items('Icicle Plate', 'IV', '', 'Increases power of Ice-type moves. Changes Arceus\' type to Ice.'),
  new Items('Icium Z', 'VII', '', 'Allows the use of Subzero Slammer, the Ice type Z-Move.'),
  new Items('Icy Rock', 'IV', '', 'A Pokémon held item that extends the duration of the move Hail used by the holder.'),
  new Items('Incinium Z', 'VII', '', 'Allows Incineroar to upgrade Darkest Lariat to a Z-Move, Malicious Moonsault.'),
  new Items('Insect Plate', 'IV', '', 'Increases power of Bug-type moves. Changes Arceus\' type to Bug.'),
  new Items('Intriguing Stone', 'VI', '', 'A rather curious stone that might appear to be valuable to some. It’s all in the eye of the beholder.'),
  new Items('Iron', 'I', '', 'Increases Defense EVs by 10.'),
  new Items('Iron Ball', 'IV', '', 'A Pokémon held item that cuts Speed. It makes Flying-type and levitating holders susceptible to Ground moves.'),
  new Items('Iron Plate', 'IV', '', 'Increases power of Steel-type moves. Changes Arceus\' type to Steel.'),
  new Items('Item Drop', 'V', '', 'When used, it causes an ally Pokémon to drop a held item.'),
  new Items('Item Urge', 'V', '', 'When used, it causes an ally Pokémon to use its held item.'),
  new Items('Jaboca Berry', 'IV', '', 'If held by a Pokémon and a physical attack lands, the attacker also takes damage.'),
  new Items('Kangaskhanite', 'VI', '', 'Enables Kangaskhan to Mega Evolve during battle.'),
  new Items('Kasib Berry', 'IV', '', 'Weakens a supereffective Ghost-type attack against the holding Pokémon.'),
  new Items('Kebia Berry', 'IV', '', 'Weakens a supereffective Poison-type attack against the holding Pokémon.'),
  new Items('Kee Berry', 'VI', '', 'If held by a Pokémon, this Berry will increase the holder’s Defense if it’s hit with a physical move.'),
  new Items('Kelpsy Berry', 'III', '', 'Increases Friendship but lowers Attack EVs.'),
  new Items('King\'s Rock', 'II', '', 'An item to be held by a Pokémon. When the holder inflicts damage, the target may flinch.'),
  new Items('Kommonium Z', 'VII', '', 'Allows Kommo-o to upgrade Clanging Scales to a Z-Move, Clangorous Soulblaze.'),
  new Items('Lagging Tail', 'IV', '', 'An item to be held by a Pokémon. It is tremendously heavy and makes the holder move slower than usual.'),
  new Items('Lansat Berry', 'III', '', 'Increases critical-hit ratio when HP is low.'),
  new Items('Latiasite', 'VI', '', 'Enables Latias to Mega Evolve during battle.'),
  new Items('Latiosite', 'VI', '', 'Enables Latios to Mega Evolve during battle.'),
  new Items('Lava Cookie', 'III', '', 'Heals all major status conditions.'),
  new Items('Lax Incense', 'III', '', 'An item to be held by a Pokémon. The tricky aroma of this incense may make attacks miss the holder.'),
  new Items('Leaf Letter', 'VII', '', 'A letter written on a leaf. Something is written using Eevee\'s footprints.'),
  new Items('Leaf Stone', 'I', '', 'A peculiar stone that makes certain species of Pokémon evolve. It has a leaf pattern.'),
  new Items('Leftovers', 'II', '', 'An item to be held by a Pokémon. The holder’s HP is gradually restored during battle.'),
  new Items('Lemonade', 'I', '', 'Restores 70 HP.'),
  new Items('Leppa Berry', 'III', '', 'If held by a Pokémon, it restores a move’s PP by 10.'),
  new Items('Level Ball', 'II', '', 'A Poké Ball for catching Pokémon that are a lower level than your own.'),
  new Items('Liechi Berry', 'III', '', 'Raises Attack when HP is low.'),
  new Items('Life Orb', 'IV', '', 'Increases the power of moves, but loses HP each turn.'),
  new Items('Light Ball', 'II', '', 'An item to be held by Pikachu. It is a puzzling orb that raises the Attack and Sp. Atk stat.'),
  new Items('Light Clay', 'IV', '', 'A Pokémon held item that extends the duration of barrier moves like Light Screen and Reflect used by the holder.'),
  new Items('Lone Earring', 'VII', '', 'A single earring that somebody dropped.'),
  new Items('Looker Ticket', 'VI', '', 'A ticket that was handmade by Looker. It’s decorated with a liberal amount of glittery paint.'),
  new Items('Lopunnite', 'VI', '', 'Enables Lopunny to Mega Evolve during battle.'),
  new Items('Love Ball', 'II', '', 'Poké Ball for catching Pokémon that are the opposite gender of your Pokémon.'),
  new Items('Lucarionite', 'VI', '', 'Enables Lucario to Mega Evolve during battle.'),
  new Items('Luck Incense', 'IV', '', 'An item to be held by a Pokémon. It doubles a battle’s prize money if the holding Pokémon joins in.'),
  new Items('Lucky Egg', 'II', '', 'An item to be held by a Pokémon. It is an egg filled with happiness that earns extra Exp. Points in battle.'),
  new Items('Lucky Punch', 'III', '', 'Increases critical-hit ratio when held by Chansey.'),
  new Items('Lum Berry', 'III', '', 'If held by a Pokémon, it recovers from any status problem.'),
  new Items('Luminous Moss', 'VI', '', 'Raises Special Defense if hit by a Water-type move.'),
  new Items('Lumiose Galette', 'VI', '', 'Heals all major status conditions.'),
  new Items('Lunalium Z', 'VII', '', 'Allows Lunala to upgrade Moongeist Beam to a Z-Move, Menacing Moonraze Maelstrom.'),
  new Items('Lure', 'VII', '', 'Attracts Pokémon in the wild.'),
  new Items('Lure Ball', 'II', '', 'A Poké Ball for catching Pokémon hooked by a Rod when fishing.'),
  new Items('Lustrous Orb', 'IV', '', 'Increases the power of Dragon-type and Water-type moves when held by Palkia.'),
  new Items('Luxury Ball', 'III', '', 'A comfortable Poké Ball that makes a caught wild Pokémon quickly grow friendly.'),
  new Items('Lycanium Z', 'VII', '', 'Allows Lycanroc to upgrade Stone Edge to a Z-Move, Splintered Stormshards.'),
  new Items('Macho Brace', 'III', '', 'An item to be held by a Pokémon. It is a stiff and heavy brace that promotes strong growth but lowers Speed.'),
  new Items('Magmarizer', 'IV', '', 'A box packed with a tremendous amount of magma energy. It is loved by a certain Pokémon.'),
  new Items('Magnet', 'II', '', 'Increases the power of Electric-type moves.'),
  new Items('Mago Berry', 'III', '', 'Restores HP if it\'s low, but may cause confusion.'),
  new Items('Magost Berry', 'III', '', 'A Berry which is very rare in the Unova region. A maniac will buy it for a high price.'),
  new Items('Manectite', 'VI', '', 'Enables Manectric to Mega Evolve during battle.'),
  new Items('Maranga Berry', 'VI', '', 'If held by a Pokémon, this Berry will increase the holder’s Sp. Def if it’s hit with a special move.'),
  new Items('Marble', 'VII', '', 'A round glass marble. You can see colored glass inside the transparent marble.'),
  new Items('Marshadium Z', 'VII', '', 'Allows Marshadow to upgrade Spectral Thief to a Z-Move, Soul-Stealing 7-Star Strike.'),
  new Items('Master Ball', 'I', '', 'The best Ball with the ultimate level of performance. It will catch any wild Pokémon without fail.'),
  new Items('Mawilite', 'VI', '', 'Enables Mawile to Mega Evolve during battle.'),
  new Items('Max Elixir', 'I', '', 'It fully restores the PP of all the moves learned by the targeted Pokémon.'),
  new Items('Max Ether', 'I', '', 'It fully restores the PP of a single selected move that has been learned by the target Pokémon.'),
  new Items('Max Lure', 'VII', '', 'A glass bottle of perfume that makes rare Pokémon more likely to appear. It lasts longer than a Super Lure.'),
  new Items('Max Potion', 'I', '', 'Fully restores HP.'),
  new Items('Max Repel', 'I', '', 'An item that prevents weak wild Pokémon from appearing for 250 steps after its use.'),
  new Items('Max Revive', 'I', '', 'A medicine that revives a fainted Pokémon. It fully restores the Pokémon’s HP.'),
  new Items('Meadow Plate', 'IV', '', 'Increases power of Grass-type moves. Changes Arceus\' type to Grass.'),
  new Items('Medichamite', 'VI', '', 'Enables Medicham to Mega Evolve during battle.'),
  new Items('Mental Herb', 'III', '', 'An item to be held by a Pokémon. It snaps the holder out of infatuation. It can be used only once.'),
  new Items('Metagrossite', 'VI', '', 'Enables Metagross to Mega Evolve during battle.'),
  new Items('Metal Coat', 'II', '', 'Increases the power of Steel-type moves.'),
  new Items('Metal Powder', 'II', '', 'Increases Defense when held by Ditto.'),
  new Items('Metronome', 'IV', '', 'Increases the power of moves used consecutively.'),
  new Items('Mewnium Z', 'VII', '', 'Allows Mew to upgrade Psychic to a Z-Move, Genesis Supernova.'),
  new Items('Mewtwonite X', 'VI', '', 'Enables Mewtwo to Mega Evolve during battle.'),
  new Items('Mewtwonite Y', 'VI', '', 'Enables Mewtwo to Mega Evolve during battle.'),
  new Items('Micle Berry', 'IV', '', 'Increases a move\'s accuracy when HP is low.'),
  new Items('Mighty Candy', 'VII', '', 'Increases a Pokémon\'s Attack stat by 1.'),
  new Items('Mighty Candy L', 'VII', '', 'Increases a Pokémon\'s Attack stat by 1. The Pokémon must be level 30.'),
  new Items('Mighty Candy XL', 'VII', '', 'Increases a Pokémon\'s Attack stat by 1. The Pokémon must be level 60.'),
  new Items('Mimikium Z', 'VII', '', 'Allows Mimikyu to upgrade Play Rough to a Z-Move.'),
  new Items('Mind Plate', 'IV', '', 'Increases power of Psychic-type moves. Changes Arceus\' type to Psychic.'),
  new Items('Miracle Seed', 'II', '', 'Increases the power of Grass-type moves.'),
  new Items('Misty Seed', 'VII', '', 'An item to be held by a Pokémon. It boosts Sp. Def on Misty Terrain. It can only be used once.'),
  new Items('Moomoo Milk', 'II', '', 'Milk with a very high nutrition content. It restores the HP of one Pokémon by 100 points.'),
  new Items('Moon Ball', 'II', '', 'A Poké Ball for catching Pokémon that evolve using the Moon Stone.'),
  new Items('Moon Stone', 'I', '', 'A peculiar stone that makes certain species of Pokémon evolve. It is as black as the night sky.'),
  new Items('Muscle Band', 'IV', '', 'Increases the power of Physical-category moves.'),
  new Items('Muscle Wing', 'V', '', '	Increases Attack EVs by 1.'),
  new Items('Mystic Water', 'II', '', 'Increases the power of Water-type moves.'),
  new Items('Nanab Berry', 'III', '', 'Feed this to a Pokémon to calm it down, making it less erratic.	'),
  new Items('Nest Ball', 'III', '', 'A somewhat different Poké Ball that works especially well on weaker Pokémon in the wild.'),
  new Items('Net Ball', 'III', '', 'A somewhat different Poké Ball that works especially well on Water- and Bug-type Pokémon.'),
  new Items('Never-Melt Ice', 'II', '', 'Increases the power of Ice-type moves.'),
  new Items('Nomel Berry', 'III', '', 'A Berry which is very rare in the Unova region. A maniac will buy it for a high price.'),
  new Items('Normal Gem', 'V', '', 'Increases the power of a Normal-type move only once.'),
  new Items('Normalium Z', 'VII', '', 'Allows the use of Breakneck Blitz, the Normal type Z-Move.'),
  new Items('Nugget', 'I', '', 'A nugget of pure gold that gives off a lustrous gleam. It can be sold at a high price to shops.'),
  new Items('Occa Berry', 'IV', '', 'Weakens a supereffective Fire-type attack against the holding Pokémon.'),
  new Items('Odd Incense', 'IV', '', 'Increases the power of Psychic-type moves.'),
  new Items('Odd Keystone', 'IV', '', 'A vital item that is needed to keep a stone tower from collapsing. Voices can be heard from it occasionally.'),
  new Items('Old Amber', 'I', '', 'A piece of amber that contains the genetic material of an ancient Pokémon. It is clear with a reddish tint.'),
  new Items('Old Gateau', 'IV', '', 'Heals all major status conditions.'),
  new Items('Oran Berry', 'III', '', 'If held by a Pokémon, it heals the user by just 10 HP.'),
  new Items('Oval Charm', 'V', '', 'An oval charm said to increase the chance of Pokémon Eggs being found at the Day Care.'),
  new Items('Oval Stone', 'IV', '', 'A peculiar stone that makes certain species of Pokémon evolve. It is shaped like an egg.'),
  new Items('Pamtre Berry', 'III', '', 'A Berry which is very rare in the Unova region. A maniac will buy it for a high price.'),
  new Items('Paralyze Heal', 'I', '', 'A spray-type medicine. It eliminates paralysis from a single Pokémon.'),
  new Items('Park Ball', 'IV', '', 'A special Poké Ball for the Pal Park.'),
  new Items('Pass Orb', 'V', '', 'A mysterious orb containing the power of the Unova region, to be used when generating Pass Power.'),
  new Items('Passho Berry', 'IV', '', 'Weakens a supereffective Water-type attack against the holding Pokémon.'),
  new Items('Payapa Berry', 'IV', '', 'Weakens a supereffective Psychic-type attack against the holding Pokémon.'),
  new Items('Pearl', 'II', '', 'A somewhat-small pearl that sparkles in a pretty silver color. It can be sold cheaply to shops.'),
  new Items('Pearl String', 'V', '', 'Very large pearls that sparkle in a pretty silver color. A maniac will buy them for a high price.'),
  new Items('Pecha Berry', 'III', '', 'If held by a Pokémon, it recovers from poison.'),
  new Items('Permit', 'V', '', 'A permit that is needed to enter the Nature Preserve. Not many know about it.'),
  new Items('Persim Berry', 'III', '', 'If held by a Pokémon, it recovers from confusion.'),
  new Items('Petaya Berry', 'III', '', 'Raises Special Attack when HP is low.'),
  new Items('Pewter Crunchies', 'VII', '', 'Heals all major status conditions.'),
  new Items('Pidgeotite', 'VI', '', 'Enables Pidgeot to Mega Evolve during battle.'),
  new Items('Pikanium Z', 'VII', '', 'Allows Pikachu to upgrade Volt Tackle to a Z-Move, Catastropika.'),
  new Items('Pikashunium Z', 'VII', '', 'Allows Pikachu in a cap to upgrade Thunderbolt to a Z-Move, 10,000,000 Volt Thunderbolt.'),
  new Items('Pinap Berry', 'III', '', 'Makes wild Pokémon more likely to yield items when captured'),
  new Items('Pink Apricorn', 'II', '', 'A pink Apricorn. It has a nice, sweet scent.'),
  new Items('Pink Nectar', 'VII', '', 'The flower nectar obtained at the flowering shrubs on Royal Avenue. It changes the form of certain species of Pokémon.'),
  new Items('Pink Scarf', 'III', '', 'Raises holder\'s Cute aspect in a Contest.'),
  new Items('Pinsirite', 'VI', '', 'Enables Pinsir to Mega Evolve during battle.'),
  new Items('Pixie Plate', 'VI', '', 'Increases power of Fairy-type moves. Changes Arceus\' type to Fairy.'),
  new Items('Plasma Card', 'V', '', 'A card key needed to enter the password inside the Plasma Frigate.'),
  new Items('Plume Fossil', 'V', '', 'A fossil of an ancient Pokémon that flew in the sky in ancient times. It appears to be part of its wing.'),
  new Items('Poison Barb', 'II', '', 'Increases the power of Poison-type moves.'),
  new Items('Poison Gem', 'V', '', 'Increases the power of a Poison-type move only once.'),
  new Items('Poison Memory', 'VII', '', 'Changes Silvally and its move Multi-Attack to Poison type.'),
  new Items('Poisonium Z', 'VII', '', 'Allows the use of Acid Downpour, the Poison type Z-Move.'),
  new Items('Poké Ball', 'I', '', 'A device for catching wild Pokémon. It is thrown like a ball at the target. It is designed as a capsule system.'),
  new Items('Poké Doll', 'I', '', 'A doll that attracts Pokémon. Use it to flee from any battle with a wild Pokémon.'),
  new Items('Poké Toy', 'V', '', 'An item that attracts Pokémon. Use it to flee from any battle with a wild Pokémon.'),
  new Items('Polished Mud Ball', 'VII', '', 'A ball made of mud. It had been polished for such a long time that the surface is very shiny.'),
  new Items('Pomeg Berry', 'III', '', 'Increases Friendship but lowers HP EVs.'),
  new Items('Potion', 'I', '', 'Restores 20 HP.'),
  new Items('Power Anklet', 'IV', '', 'A Pokémon held item that promotes Speed gain on leveling, but reduces the Speed stat.'),
  new Items('Power Band', 'IV', '', 'A Pokémon held item that promotes Sp. Def gain on leveling, but reduces the Speed stat.'),
  new Items('Power Belt', 'IV', '', 'A Pokémon held item that promotes Defense gain on leveling, but reduces the Speed stat.'),
  new Items('Power Bracer', 'IV', '', 'A Pokémon held item that promotes Attack gain on leveling, but reduces the Speed stat.'),
  new Items('Power Herb', 'IV', '', 'A single-use item to be held by a Pokémon. It allows the immediate use of a move that charges on the first turn.'),
  new Items('Power Lens', 'IV', '', 'A Pokémon held item that promotes Sp. Atk gain on leveling, but reduces the Speed stat.'),
  new Items('Power Plant Pass', 'VI', '', 'This pass serves as an ID card for gaining access to the power plant that lies along Route 13.'),
  new Items('Power Weight', 'IV', '', 'A Pokémon held item that promotes HP gain on leveling, but reduces the Speed stat.'),
  new Items('PP Max', 'III', '', 'It maximally raises the top PP of a selected move that has been learned by the target Pokémon.'),
  new Items('PP Up', 'I', '', 'It slightly raises the maximum PP of a selected move that has been learned by the target Pokémon.'),
  new Items('Premier Ball', 'III', '', 'A somewhat rare Poké Ball that has been specially made to commemorate an event of some sort.'),
  new Items('Pretty Wing', 'V', '', 'Though this feather is beautiful, it’s just a regular feather and has no effect on Pokémon.'),
  new Items('Primarium Z', 'VII', '', 'Allows Primarina to upgrade Sparkling Aria to a Z-Move, Oceanic Operetta.'),
  new Items('Prism Scale', 'V', '', 'A mysterious scale that evolves certain Pokémon. It shines in rainbow colors.'),
  new Items('Prison Bottle', 'VI', '', 'Transforms Hoopa Confined to Hoopa Unbound.'),
  new Items('Prof\'s Letter', 'VI', '', 'A letter that Professor Sycamore wrote to your mother. A faint but pleasant perfume seems to cling to the paper.'),
  new Items('Protective Pads', 'VII', '', 'An item to be held by a Pokémon. These pads protect the holder from effects caused by making direct contact with the target.'),
  new Items('Protector', 'IV', '', 'A protective item of some sort. It is extremely stiff and heavy. It is loved by a certain Pokémon.'),
  new Items('Protein', 'I', '', 'Increases Attack EVs by 10.'),
  new Items('Psychic Gem', '', '', 'Increases the power of a Psychic-type move only once.'),
  new Items('Psychic Memory', 'VII', '', 'Changes Silvally and its move Multi-Attack to Psychic type.'),
  new Items('Psychic Seed', 'VII', '', 'An item to be held by a Pokémon. It boosts Sp. Def on Psychic Terrain. It can only be used once.'),
  new Items('Psychium Z', 'VII', '', 'Allows the use of Shattered Psyche, the Psychic type Z-Move.'),
  new Items('Pure Incense', 'IV', '', 'An item to be held by a Pokémon. It helps keep wild Pokémon away if the holder is the first one in the party.'),
  new Items('Purple Nectar', 'VII', '', 'A flower nectar obtained at Poni Meadow. It changes the form of certain species of Pokémon.'),
  new Items('Qualot Berry', 'III', '', 'Increases Friendship but lowers Defense EVs.'),
  new Items('Quick Ball', 'IV', '', 'A somewhat different Poké Ball that provides a better catch rate if it is used at the start of a wild encounter.'),
  new Items('Quick Candy', 'VII', '', 'Increases a Pokémon\'s Speed stat by 1.'),
  new Items('Quick Candy L', 'VII', '', 'Increases a Pokémon\'s Speed stat by 1. The Pokémon must be level 30.'),
  new Items('Quick Candy XL', 'VII', '', 'Increases a Pokémon\'s Speed stat by 1. The Pokémon must be level 60.'),
  new Items('Quick Claw', 'II', '', 'An item to be held by a Pokémon. A light, sharp claw that lets the bearer move first occasionally.'),
  new Items('Quick Powder', 'IV', '', 'Increases Speed when held by Ditto.'),
  new Items('Rabuta Berry', 'III', '', 'A Berry which is very rare in the Unova region. A maniac will buy it for a high price.'),
  new Items('Rage Candy Bar', 'II', '', 'Heals all major status conditions.'),
  new Items('Rare Bone', 'IV', '', 'A bone that is extremely valuable for Pokémon archeology. It can be sold for a high price to shops.'),
  new Items('Rare Candy', 'I', '', 'A candy that is packed with energy. It raises the level of a single Pokémon by one.'),
  new Items('Rawst Berry', 'III', '', 'If held by a Pokémon, it recovers from a burn.'),
  new Items('Razor Claw', 'IV', '', 'Increases critical-hit ratio.'),
  new Items('Razor Fang', 'IV', '', 'An item to be held by a Pokémon. It may make foes and allies flinch when the holder inflicts damage.'),
  new Items('Razz Berry', 'III', '', 'A Berry which is very rare in the Unova region. A maniac will buy it for a high price.'),
  new Items('Reaper Cloth', 'IV', '', 'A cloth imbued with horrifyingly strong spiritual energy. It is loved by a certain Pokémon.'),
  new Items('Red Apricorn', 'II', '', 'A red Apricorn. It assails your nostrils.'),
  new Items('Red Card', 'V', '', 'A card with a mysterious power. When the holder is struck by a foe, the attacker is removed from battle.'),
  new Items('Red Flute', 'III', '', 'A toy flute made from red glass. A maniac will buy it for a high price.'),
  new Items('Red Nectar', 'VII', '', 'A flower nectar obtained at Ula\'ula Meadow. It changes the form of certain species of Pokémon.'),
  new Items('Red Scarf', 'III', '', 'Raises holder\'s Cool aspect in a Contest.'),
  new Items('Red Shard', 'III', '', 'A small red shard. It appears to be from some sort of implement made long ago.'),
  new Items('Relic Band', 'V', '', 'A bracelet made in a civilization about 3,000 years ago. A maniac will buy it for a high price.'),
  new Items('Relic Copper', 'V', '', 'A copper coin used in a civilization about 3,000 years ago. A maniac will buy it for a high price.'),
  new Items('Relic Crown', 'V', '', 'A crown made in a civilization about 3,000 years ago. A maniac will buy it for a high price.'),
  new Items('Relic Gold', 'V', '', 'A gold coin used in a civilization about 3,000 years ago. A maniac will buy it for a high price.'),
  new Items('Relic Silver', 'V', '', 'A silver coin used in a civilization about 3,000 years ago. A maniac will buy it for a high price.'),
  new Items('Relic Statue', 'V', '', 'A stone figure made in a civilization about 3,000 years ago. A maniac will buy it for a high price.'),
  new Items('Relic Vase', 'V', '', 'A vase made in a civilization about 3,000 years ago. A maniac will buy it for a high price.'),
  new Items('Repeat Ball', 'III', '', 'A somewhat different Poké Ball that works especially well on Pokémon species that were previously caught.'),
  new Items('Repel', 'I', '', 'An item that prevents weak wild Pokémon from appearing for 100 steps after its use.'),
  new Items('Reset Urge', 'V', '', 'When used, it restores any stat changes of an ally Pokémon.'),
  new Items('Resist Wing', 'V', '', 'Increases Defense EVs by 1.'),
  new Items('Reveal Glass', 'V', '', 'A looking glass that reveals the truth. It’s a mysterious glass that returns a Pokémon to its original shape.'),
  new Items('Revival Herb', 'II', '', 'Revives a Pokémon to max HP, but lowers Friendship.'),
  new Items('Revive', 'I', '', 'A medicine that revives a fainted Pokémon. It restores half the Pokémon’s maximum HP.'),
  new Items('Rindo Berry', 'IV', '', 'Weakens a supereffective Grass-type attack against the holding Pokémon.'),
  new Items('Ring Target', 'V', '', 'Moves that would otherwise have no effect will land on the Pokémon that holds it.'),
  new Items('Rock Gem', 'V', '', 'Increases the power of a Rock-type move only once.'),
  new Items('Rock Incense', 'IV', '', 'Increases the power of Rock-type moves.'),
  new Items('Rock Memory', 'VII', '', 'Changes Silvally and its move Multi-Attack to Rock type.'),
  new Items('Rockium Z', 'VII', '', 'Allows the use of Continental Crush, the Rock type Z-Move.'),
  new Items('Rocky Helmet', 'V', '', 'If the holder of this item takes damage, the attacker will also be damaged upon contact.'),
  new Items('Roller Skates', 'VI', '', 'Attaches roller skates to the bottom of your shoes, allowing you to glide quickly around and perform tricks.'),
  new Items('Root Fossil', 'III', '', 'A fossil of an ancient Pokémon that lived in the sea. It appears to be part of a plant root.'),
  new Items('Rose Incense', 'IV', '', 'Increases the power of Grass-type moves.'),
  new Items('Roseli Berry', 'VI', '', 'If held by a Pokémon, this Berry will lessen the damage taken from one supereffective Fairy-type attack.'),
  new Items('Roto Bargain', 'VII', '', 'Reduces the prices of products at Poké Marts by half.'),
  new Items('Roto Boost', 'VII', '', 'Raises all stats of your battling Pokémon.'),
  new Items('Roto Catch', 'VII', '', 'Increases the chance to catch Pokémon a lot.'),
  new Items('Roto Encounter', 'VII', '', 'Increases the chance of encountering high-level wild Pokémon a lot for a certain period of time.'),
  new Items('Roto Exp. Points', 'VII', '', 'Increases the Exp. Points your Pokémon receive after battle a little.'),
  new Items('Roto Friendship', 'VII', '', 'Helps Pokémon in your party grow friendly faster.'),
  new Items('Roto Hatch', 'VII', '', 'Helps Eggs hatch faster.'),
  new Items('Roto HP Restore', 'VII', '', 'Fully restores the HP of your battling Pokémon.'),
  new Items('Roto PP Restore', 'VII', '', 'Fully restores the PP of your battling Pokémon.'),
  new Items('Roto Prize Money', 'VII', '', 'Triples the prize money you receive after battle.'),
  new Items('Roto Stealth', 'VII', '', 'Prevents you from encountering wild Pokémon for a certain period of time.'),
  new Items('Rowap Berry', 'IV', '', 'If held by a Pokémon and a special attack lands, the attacker also takes damage.'),
  new Items('Sablenite', 'VI', '', 'Enables Sableye to Mega Evolve during battle.'),
  new Items('Sachet', 'VI', '', 'A sachet filled with fragrant perfumes that are just slightly too overwhelming. Yet it’s loved by a certain Pokémon.'),
  new Items('Sacred Ash', 'II', '', 'It revives all fainted Pokémon. In doing so, it also fully restores their HP.'),
  new Items('Safari Ball', 'I', '', 'A special Poké Ball that is used only in the Great Marsh. It is decorated in a camouflage pattern.'),
  new Items('Safety Goggles', 'VI', '', 'Prevents damage from weather and powder.'),
  new Items('Salac Berry', 'III', '', 'Raises Speed when HP is low.'),
  new Items('Salamencite', 'VI', '', 'Enables Salamence to Mega Evolve during battle.'),
  new Items('Sceptilite', 'VI', '', 'Enables Sceptile to Mega Evolve during battle.'),
  new Items('Scizorite', 'VI', '', 'Enables Scizor to Mega Evolve during battle.'),
  new Items('Scope Lens', 'III', '', 'Increases critical-hit ratio.'),
  new Items('Sea Incense', 'III', '', 'Increases the power of Water-type moves.'),
  new Items('Shalour Sable', 'VI', '', 'Heals all major status conditions.'),
  new Items('Sharp Beak', 'II', '', 'Increases the power of Flying-type moves.'),
  new Items('Sharpedonite', 'VI', '', 'Enables Sharpedo to Mega Evolve during battle.'),
  new Items('Shed Shell', 'IV', '', 'A tough, discarded carapace to be held by a Pokémon. It enables the holder to switch with a waiting Pokémon in battle.'),
  new Items('Shell Bell', 'III', '', 'An item to be held by a Pokémon. The holder’s HP is restored a little every time it inflicts damage.'),
  new Items('Shiny Charm', 'V', '', 'A shiny charm said to increase the chance of finding a Shiny Pokémon in the wild.'),
  new Items('Shiny Stone', 'IV', '', 'A peculiar stone that makes certain species of Pokémon evolve. It shines with a dazzling light.'),
  new Items('Shoal Salt', 'III', '', 'Pure salt that can be discovered deep inside the Shoal Cave. A maniac will buy it for a high price.'),
  new Items('Shoal Shell', 'III', '', 'A pretty seashell that can be found deep inside the Shoal Cave. A maniac will buy it for a high price.'),
  new Items('Shock Drive', 'V', '', 'Changes Techno Blast to an Electric-type move when held by Genesect.'),
  new Items('Shuca Berry', 'IV', '', 'Weakens a supereffective Ground-type attack against the holding Pokémon.'),
  new Items('Silk Scarf', 'III', '', 'Increases the power of Normal-type moves.'),
  new Items('Silver Leaf', 'II', '', 'A strange, silver-colored leaf.'),
  new Items('Silver Nanab Berry', 'VII', '', 'Greatly calms a Pokémon in battle in Pokémon Let\'s Go.'),
  new Items('Silver Pinap Berry', 'VII', '', 'Greatly increases chance of getting items when a Pokémon is caught in Pokémon Let\'s Go.'),
  new Items('Silver Powder', 'II', '', 'Increases the power of Bug-type moves.'),
  new Items('Silver Razz Berry', 'VII', '', 'Makes a Pokémon easier to catch in Pokémon Let\'s Go.'),
  new Items('Sitrus Berry', 'III', '', 'If held by a Pokémon, it heals the user’s HP a little.'),
  new Items('Skull Fossil', 'IV', '', 'A fossil from a prehistoric Pokémon that lived on the land. It appears to be part of a head.'),
  new Items('Sky Plate', 'IV', '', 'Increases power of Flying-type moves. Changes Arceus\' type to Flying.'),
  new Items('Slowbronite', 'VI', '', 'Enables Slowbro to Mega Evolve during battle.'),
  new Items('Small Bouquet', 'VII', '', 'A gift from your partner in Pokémon Let\'s Go.'),
  new Items('Smart Candy', 'VII', '', 'Increases a Pokémon\'s Special Attack stat by 1.'),
  new Items('Smart Candy L', 'VII', '', 'Increases a Pokémon\'s Special Attack stat by 1. The Pokémon must be level 30.'),
  new Items('Smart Candy XL', 'VII', '', 'Increases a Pokémon\'s Special Attack stat by 1. The Pokémon must be level 60.'),
  new Items('Smoke Ball', 'III', '', 'An item to be held by a Pokémon. It enables the holder to flee from any wild Pokémon without fail.'),
  new Items('Smooth Rock', 'IV', '', 'A Pokémon held item that extends the duration of the move Sandstorm used by the holder.'),
  new Items('Snorlium Z', 'VII', '', 'Allows Snorlax to upgrade Giga Impact to a Z-Move, Pulverizing Pancake.'),
  new Items('Snowball', 'VI', '', 'Raises Attack if hit by an Ice-type move.'),
  new Items('Soda Pop', 'I', '', 'Restores 50 HP.'),
  new Items('Soft Sand', 'II', '', 'Increases the power of Ground-type moves.'),
  new Items('Solganium Z', 'VII', '', 'Allows Solgaleo to upgrade Sunsteel Strike to a Z-Move, Searing Sunraze Smash.'),
  new Items('Soothe Bell', 'II', '', 'An item to be held by a Pokémon. It is a bell with a comforting chime that calms the holder and makes it friendly.'),
  new Items('Soul Dew', 'III', '', 'Increases both Special Attack and Special Defense when held by Latios or Latias.'),
  new Items('Spell Tag', 'II', '', 'Increases the power of Ghost-type moves.'),
  new Items('Spelon Berry', 'III', '', 'A Berry which is very rare in the Unova region. A maniac will buy it for a high price.'),
  new Items('Splash Plate', 'IV', '', 'Increases power of Water-type moves. Changes Arceus\' type to Water.'),
  new Items('Spooky Plate', 'IV', '', 'Increases power of Ghost-type moves. Changes Arceus\' type to Ghost.'),
  new Items('Sport Ball', 'II', '', 'A special Poké Ball for the Bug-Catching Contest.'),
  new Items('Sprinklotad', 'VI', '', 'A watering can shaped like a Lotad. It helps promote the healthy growth of any Berries planted in good, soft soil.'),
  new Items('Stable Mulch', 'IV', '', 'A fertilizer to be spread on soft soil in regions where Berries are grown. A maniac will buy it for a high price.'),
  new Items('Star Piece', 'II', '', 'A shard of a pretty gem that sparkles in a red color. It can be sold at a high price to shops.'),
  new Items('Stardust', 'II', '', 'Lovely, red-colored sand with a loose, silky feel. It can be sold at a high price to shops.'),
  new Items('Starf Berry', 'III', '', 'Sharply raises a random stat when HP is low.'),
  new Items('Steel Gem', 'V', '', 'Increases the power of a Steel-type move only once.'),
  new Items('Steel Memory', 'VII', '', 'Changes Silvally and its move Multi-Attack to Steel type.'),
  new Items('Steelium Z', 'VII', '', 'Allows the use of Corkscrew Crash, the Steel type Z-Move.'),
  new Items('Steelixite', 'VI', '', 'Enables Steelix to Mega Evolve during battle.'),
  new Items('Stick', 'II', '', 'Increases critical-hit ratio when held by Farfetch\'d.'),
  new Items('Sticky Barb', 'IV', '', 'A held item that damages the holder on every turn. It may latch on to foes and allies that touch the holder.'),
  new Items('Stone Plate', 'IV', '', 'Increases power of Rock-type moves. Changes Arceus\' type to Rock.'),
  new Items('Strange Souvenir', 'VI', '', 'An ornament depicting a Pokémon that is venerated as a protector in some region far from Kalos.'),
  new Items('Stretchy Spring', 'VII', '', 'A thin small spring. It’s totally stretched out, and what it’s used for is unknown.'),
  new Items('Sun Stone', 'II', '', 'A peculiar stone that makes certain species of Pokémon evolve. It is as red as the sun.'),
  new Items('Super Lure', 'VII', '', 'A glass bottle of perfume that makes rare Pokémon more likely to appear. It lasts longer than a Lure.'),
  new Items('Super Potion', 'I', '', 'Restores 60 HP.'),
  new Items('Super Repel', 'I', '', 'An item that prevents weak wild Pokémon from appearing for 200 steps after its use.'),
  new Items('Swampertite', 'VI', '', 'Enables Swampert to Mega Evolve during battle.'),
  new Items('Sweet Heart', 'V', '', 'Very sweet chocolate. It restores the HP of one Pokémon by only 20 points.'),
  new Items('Swift Wing', 'V', '', 'Increases Speed EVs by 1.'),
  new Items('Tamato Berry', 'III', '', 'Increases Friendship but lowers Speed EVs.'),
  new Items('Tanga Berry', 'III', '', 'Weakens a supereffective Bug-type attack against the holding Pokémon.'),
  new Items('Tapunium Z', 'VII', '', 'Allows the Tapus to upgrade Nature\'s Madness to a Z-Move, Guardian of Alola.'),
  new Items('Terrain Extender', 'VII', '', 'An item to be held by a Pokémon. It extends the duration of the terrain caused by the holder’s move or Ability.'),
  new Items('Thick Club', 'III', '', 'Increases Attack when held by Cubone or Marowak.'),
  new Items('Thunder Stone', 'I', '', 'A peculiar stone that makes certain species of Pokémon evolve. It has a thunderbolt pattern.'),
  new Items('Timer Ball', 'III', '', 'A somewhat different BALL that becomes progressively better the more turns there are in a battle.'),
  new Items('Tiny Mushroom', 'II', '', 'A small and rare mushroom. It is sought after by collectors.'),
  new Items('TM01', '', '', 'Teaches the move Mega Punch/Dynamic Punch/Focus Punch/Hone Claws/Work Up/Headbutt.'),
  new Items('TM02', '', '', 'Teaches the move Razor Wind/Headbutt/Dragon Claw/Taunt.'),
  new Items('TM03', '', '', 'Teaches the move Swords Dance/Curse/Water Pulse/Psyshock/Helping Hand.'),
  new Items('TM04', '', '', 'Teaches the move Whirlwind/Rollout/Calm Mind/Teleport.'),
  new Items('TM05', '', '', 'Teaches the move Mega Kick/Roar/Rest.'),
  new Items('TM06', '', '', 'Teaches the move Toxic/Light Screen.'),
  new Items('TM07', '', '', 'Teaches the move Horn Drill/Zap Cannon/Hail/Protect.'),
  new Items('TM08', '', '', 'Teaches the move Body Slam/Rock Smash/Bulk Up/Substitute.'),
  new Items('TM09', '', '', 'Teaches the move Take Down/Psych Up/Bullet Seed/Venoshock/Reflect.'),
  new Items('TM10', '', '', 'Teaches the move Double-Edge/Hidden Power/Dig.'),
  new Items('TM11', '', '', 'Teaches the move BubbleBeam/Sunny Day/Will-O-Wisp.'),
  new Items('TM12', '', '', 'Teaches the move Water Gun/Sweet Scent/Taunt/Facade.'),
  new Items('TM13', '', '', 'Teaches the move Snore/Ice Beam/Brick Break.'),
  new Items('TM14', '', '', 'Teaches the move Blizzard/Fly.'),
  new Items('TM15', '', '', 'Teaches the move Hyper Beam/Seismic Toss.'),
  new Items('TM16', '', '', 'Teaches the move Pay Day/Icy Wind/Light Screen/Thunder Wave.'),
  new Items('TM17', '', '', 'Teaches the move Submission/Protect/Dragon Tail.'),
  new Items('TM18', '', '', 'Teaches the move Counter/Rain Dance/U-turn.'),
  new Items('TM19', '', '', 'Teaches the move Seismic Toss/Giga Drain/Telekinesis/Roost/Iron Tail.'),
  new Items('TM20', '', '', 'Teaches the move Rage/Endure/Safeguard/Dark Pulse.'),
  new Items('TM21', '', '', 'Teaches the move Mega Drain/Frustration/Foul Play.'),
  new Items('TM22', '', '', 'Teaches the move SolarBeam/Rock Slide.'),
  new Items('TM23', '', '', 'Teaches the move Dragon Rage/Iron Tail/Smack Down/Thunder Punch.'),
  new Items('TM24', '', '', 'Teaches the move Thunderbolt/DragonBreath/X-Scissor.'),
  new Items('TM25', '', '', 'Teaches the move Thunder/Waterfall.'),
  new Items('TM26', '', '', 'Teaches the move Earthquake/Poison Jab.'),
  new Items('TM27', '', '', 'Teaches the move Fissure/Return/Toxic.'),
  new Items('TM28', '', '', 'Teaches the move Dig/Leech Life/Tri Attack.'),
  new Items('TM29', '', '', 'Teaches the move Psychic/Scald.'),
  new Items('TM30', '', '', 'Teaches the move Teleport/Shadow Ball/Bulk Up.'),
  new Items('TM31', '', '', 'Teaches the move Mimic/Mud-Slap/Brick Break/Fire Punch.'),
  new Items('TM32', '', '', 'Teaches the move Double Team/Dazzling Gleam.'),
  new Items('TM33', '', '', 'Teaches the move Ice Punch/Reflect/Calm Mind.'),
  new Items('TM34', '', '', 'Teaches the move Bide/Swagger/Shock Wave/Sludge Wave/Dragon Pulse.'),
  new Items('TM35', '', '', 'Teaches the move Metronome/Sleep Talk/Flamethrower/Ice Punch.'),
  new Items('TM36', '', '', 'Teaches the move Selfdestruct/Sludge Bomb/Thunderbolt.'),
  new Items('TM37', '', '', 'Teaches the move Egg Bomb/Sandstorm/Flamethrower.'),
  new Items('TM38', '', '', 'Teaches the move Fire Blast/Thunder.'),
  new Items('TM39', '', '', 'Teaches the move Swift/Rock Tomb/Outrage.'),
  new Items('TM40', '', '', 'Teaches the move Skull Bash/Defense Curl/Aerial Ace/Psychic.'),
  new Items('TM41', '', '', 'Teaches the move Softboiled/ThunderPunch/Torment/Earthquake.'),
  new Items('TM42', '', '', 'Teaches the move Dream Eater/Facade/Self-Destruct.'),
  new Items('TM43', '', '', 'Teaches the move Sky Attack/Detect/Secret Power/Flame Charge/Shadow Ball.'),
  new Items('TM44', '', '', 'Teaches the move Rest/Play Rough.'),
  new Items('TM45', '', '', 'Teaches the move Thunder Wave/Attract/Solar Beam.'),
  new Items('TM46', '', '', 'Teaches the move Psywave/Thief/Fire Blast.'),
  new Items('TM47', '', '', 'Teaches the move Explosion/Steel Wing/Low Sweep/Surf.'),
  new Items('TM48', '', '', 'Teaches the move Rock Slide/Fire Punch/Skill Swap/Round/Hyper Beam.'),
  new Items('TM49', '', '', 'Teaches the move Tri Attack/Fury Cutter/Snatch/Echoed Voice/Superpower.'),
  new Items('TM50', '', '', 'Teaches the move Substitute/Nightmare/Overheat/Roost.'),
  new Items('TM51', '', '', 'Teaches the move Roost/Ally Switch/Steel Wing/Blizzard.'),
  new Items('TM52', '', '', 'Teaches the move Focus Blast/Sludge Bomb.'),
  new Items('TM53', '', '', 'Teaches the move Energy Ball/Mega Drain.'),
  new Items('TM54', '', '', 'Teaches the move False Swipe/Flash Cannon.'),
  new Items('TM55', '', '', 'Teaches the move Brine/Scald/Ice Beam.'),
  new Items('TM56', '', '', 'Teaches the move Fling/Stealth Rock.'),
  new Items('TM57', '', '', 'Teaches the move Charge Beam/Pay Day.'),
  new Items('TM58', '', '', 'Teaches the move Endure/Sky Drop/Drill Run.'),
  new Items('TM59', '', '', 'Teaches the move Dragon Pulse/Incinerate/Brutal Swing/Dream Eater.'),
  new Items('TM60', '', '', 'Teaches the move Drain Punch/Quash/Megahorn.'),
  new Items('TM61', '', '', 'Teaches the move Will-O-Wisp.'),
  new Items('TM62', '', '', 'Teaches the move Silver Wind/Acrobatics.'),
  new Items('TM63', '', '', 'Teaches the move Embargo.'),
  new Items('TM64', '', '', 'Teaches the move Explosion.'),
  new Items('TM65', '', '', 'Teaches the move Shadow Claw.'),
  new Items('TM66', '', '', 'Teaches the move Payback.'),
  new Items('TM67', '', '', 'Teaches the move Recycle/Retaliate/Smart Strike.'),
  new Items('TM68', '', '', 'Teaches the move Giga Impact.'),
  new Items('TM69', '', '', 'Teaches the move Rock Polish.'),
  new Items('TM70', '', '', 'Teaches the move Flash/Aurora Veil.'),
  new Items('TM71', '', '', 'Teaches the move Stone Edge.'),
  new Items('TM72', '', '', 'Teaches the move Avalanche/Volt Switch.'),
  new Items('TM73', '', '', 'Teaches the move Thunder Wave.'),
  new Items('TM74', '', '', 'Teaches the move Gyro Ball.'),
  new Items('TM75', '', '', 'Teaches the move Swords Dance.'),
  new Items('TM76', '', '', 'Teaches the move Stealth Rock/Struggle Bug/Fly.'),
  new Items('TM77', '', '', 'Teaches the move Psych Up.'),
  new Items('TM78', '', '', 'Teaches the move Captivate/Bulldoze.'),
  new Items('TM79', '', '', 'Teaches the move Dark Pulse/Frost Breath.'),
  new Items('TM80', '', '', 'Teaches the move Rock Slide.'),
  new Items('TM81', '', '', 'Teaches the move X-Scissor.'),
  new Items('TM82', '', '', 'Teaches the move Sleep Talk/Dragon Tail.'),
  new Items('TM83', '', '', 'Teaches the move Natural Gift/Work Up/Infestation.'),
  new Items('TM84', '', '', 'Teaches the move Poison Jab.'),
  new Items('TM85', '', '', 'Teaches the move Dream Eater.'),
  new Items('TM86', '', '', 'Teaches the move Grass Knot.'),
  new Items('TM87', '', '', 'Teaches the move Swagger.'),
  new Items('TM88', '', '', 'Teaches the move Pluck/Sleep Talk.'),
  new Items('TM89', '', '', 'Teaches the move U-turn.'),
  new Items('TM90', '', '', 'Teaches the move Substitute.'),
  new Items('TM91', '', '', 'Teaches the move Flash Cannon.'),
  new Items('TM92', '', '', 'Teaches the move Trick Room.'),
  new Items('TM93', '', '', 'Teaches the move Wild Charge.'),
  new Items('TM94', '', '', 'Teaches the move Rock Smash/Surf.'),
  new Items('TM95', '', '', 'Teaches the move Snarl.'),
  new Items('TM96', '', '', 'Teaches the move Nature Power.'),
  new Items('TM97', '', '', 'Teaches the move Dark Pulse.'),
  new Items('TM98', '', '', 'Teaches the move Power-Up Punch/Waterfall.'),
  new Items('TM99', '', '', 'Teaches the move Dazzling Gleam.'),
  new Items('TM100', '', '', 'Teaches the move Confide.'),
  new Items('TMV Pass', '', '', 'A commuter pass that allows the holder to ride the TMV between Lumiose City and Kiloude City at any time.'),
  new Items('Tough Candy', '', '', 'Increases a Pokémon\'s Defense stat by 1.'),
  new Items('Tough Candy L', '', '', 'Increases a Pokémon\'s Defense stat by 1. The Pokémon must be level 30.'),
  new Items('Tough Candy XL', '', '', 'Increases a Pokémon\'s Defense stat by 1. The Pokémon must be level 60.'),
  new Items('Toxic Orb', '', '', 'An item to be held by a Pokémon. It is a bizarre orb that badly poisons the holder in battle.'),
  new Items('Toxic Plate', '', '', 'Increases power of Poison-type moves. Changes Arceus\' type to Poison.'),
  new Items('Tropical Shell', '', '', 'A beautiful white shell that may have drifted from a sea in a warm region.'),
  new Items('Twisted Spoon', '', '', 'Increases the power of Psychic-type moves.'),
  new Items('Tyranitarite', '', '', 'Enables Tyranitar to Mega Evolve during battle.'),
  new Items('Ultra Ball', '', '', 'An ultra-performance Ball that provides a higher Pokémon catch rate than a Great Ball.'),
  new Items('Ultranecrozium Z', '', '', 'Allows Ultra Necrozma to upgrade Photon Geyser to a Z-Move, Light That Burns the Sky.'),
  new Items('Up-Grade', '', '', 'A transparent device filled with all sorts of data. It was produced by Silph Co.'),
  new Items('Venusaurite', '', '', 'Enables Venusaur to Mega Evolve during battle.'),
  new Items('Wacan Berry', '', '', 'Weakens a supereffective Electric-type attack against the holding Pokémon.'),
  new Items('Water Gem', '', '', 'Increases the power of a Water-type move only once.'),
  new Items('Water Memory', '', '', 'Changes Silvally and its move Multi-Attack to Water type.'),
  new Items('Water Stone', '', '', 'A peculiar stone that makes certain species of Pokémon evolve. It is a clear, light blue.'),
  new Items('Waterium Z', '', '', 'Allows the use of Hydro Vortex, the Water type Z-Move.'),
  new Items('Watmel Berry', '', '', 'A Berry which is very rare in the Unova region. A maniac will buy it for a high price.'),
  new Items('Wave Incense', '', '', 'Increases the power of Water-type moves.'),
  new Items('Weakness Policy', '', '', 'Sharply raises Attack and Special Attack if hit by a super-effective move.'),
  new Items('Wepear Berry', '', '', 'A Berry which is very rare in the Unova region. A maniac will buy it for a high price.'),
  new Items('Whipped Dream', '', '', 'A soft and sweet treat made of fluffy, puffy, whipped and whirled cream. It’s loved by a certain Pokémon.'),
  new Items('White Apricorn', '', '', 'A white Apricorn. It doesn’t smell like anything.'),
  new Items('White Flute', '', '', 'A toy flute made from white glass. A maniac will buy it for a high price.'),
  new Items('White Herb', '', '', 'An item to be held by a Pokémon. It restores any lowered stat in battle. It can be used only once.'),
  new Items('Wide Lens', '', '', 'Increases the accuracy of moves.'),
  new Items('Wiki Berry', '', '', 'Restores HP if it\'s low, but may cause confusion.'),
  new Items('Wise Glasses', '', '', 'Increases the power of Special-category moves.'),
  new Items('X Accuracy', '', '', 'Raises Accuracy of a Pokémon in battle.'),
  new Items('X Accuracy 2', '', '', 'Sharply raises Accuracy of a Pokémon in battle.'),
  new Items('X Accuracy 3', '', '', 'Drastically raises Accuracy of a Pokémon in battle.'),
  new Items('X Accuracy 6', '', '', 'Immensely raises Accuracy of a Pokémon in battle.'),
  new Items('X Attack', '', '', 'Raises Attack of a Pokémon in battle.'),
  new Items('X Attack 2', '', '', 'Sharply raises Attack of a Pokémon in battle.'),
  new Items('X Attack 3', '', '', 'Drastically raises Attack of a Pokémon in battle.'),
  new Items('X Attack 6', '', '', 'Immensely raises Attack of a Pokémon in battle.'),
  new Items('X Defense', '', '', 'Raises Defense of a Pokémon in battle.'),
  new Items('X Defense 2', '', '', 'Sharply raises Defense of a Pokémon in battle.'),
  new Items('X Defense 3', '', '', 'Drastically raises Defense of a Pokémon in battle.'),
  new Items('X Defense 6', '', '', 'Immensely raises Defense of a Pokémon in battle.'),
  new Items('X Sp. Atk', '', '', 'Raises Special Attack of a Pokémon in battle.'),
  new Items('X Sp. Atk 2', '', '', 'Sharply raises Special Attack of a Pokémon in battle.'),
  new Items('X Sp. Atk 3', '', '', 'Drastically raises Special Attack of a Pokémon in battle.'),
  new Items('X Sp. Atk 6', '', '', 'Immensely raises Special Attack of a Pokémon in battle.'),
  new Items('X Sp. Def', '', '', 'Raises Special Defense of a Pokémon in battle.'),
  new Items('X Sp. Def 2', '', '', 'Sharply raises Special Defense of a Pokémon in battle.'),
  new Items('X Sp. Def 3', '', '', 'Drastically raises Special Defense of a Pokémon in battle.'),
  new Items('X Sp. Def 6', '', '', 'Immensely raises Special Defense of a Pokémon in battle.'),
  new Items('X Speed', '', '', 'Raises Speed of a Pokémon in battle.'),
  new Items('X Speed 2', '', '', 'Sharply raises Speed of a Pokémon in battle.'),
  new Items('X Speed 3', '', '', 'Drastically raises Speed of a Pokémon in battle.'),
  new Items('X Speed 6', '', '', 'Immensely raises Speed of a Pokémon in battle.'),
  new Items('Yache Berry', '', '', 'Weakens a supereffective Ice-type attack against the holding Pokémon.'),
  new Items('Yellow Apricorn', '', '', 'A yellow Apricorn. It has an invigorating scent.'),
  new Items('Yellow Flute', '', '', 'A toy flute made from yellow glass. A maniac will buy it for a high price.'),
  new Items('Yellow Nectar', '', '', 'A flower nectar obtained at Melemele Meadow. It changes the form of certain species of Pokémon.'),
  new Items('Yellow Scarf', '', '', 'Raises holder\'s Tough aspect in a Contest.'),
  new Items('Yellow Shard', '', '', 'A small yellow shard. It appears to be from some sort of implement made long ago.'),
  new Items('Zap Plate', '', '', 'Increases power of Electric-type moves. Changes Arceus\' type to Electric.'),
  new Items('Zinc', '', '', 'Increases Special Defense EVs by 10.'),
  new Items('Zoom Lens', '', '', 'Raises a move\'s accuracy if the holder moves after its target.')
]


function loadItems() {
  $('#Center').text("Pokémon Item List");
  $('#items-container').empty().append(`<div class="container mt-4"><div class="row"><div class="col-md-3"><h4 class="KalosTextStyle">Name</h4></div><div class="col-md-1"><h4 class="KalosTextStyle">Gen</h4></div><div class="col-md-3"><h4 style="font-style: italic; text-align: center;" class="pr-3">Category</h4></div><div class="col-md-5"><h4 class="KalosTextStyle pr-5">Description</h4></div></div></div>`);

  for (var j = 0; j < itemList.length; j++) {
    itemList[j].loadItemsToPage();
  }
}
