var johtoPokemonList = [
  new Pokemon(1, 152, 'Chikorita', ['Grass'], 'Chikorita Image'),
  new Pokemon(2, 153, 'Bayleef', ['Grass'], 'Bayleef Image'),
  new Pokemon(3, 154, 'Meganium', ['Grass'], 'Meganium Image'),
  new Pokemon(4, 155, 'Cyndaquil', ['Fire'], 'Cyndaquil Image'),
  new Pokemon(5, 156, 'Quilava', ['Fire'], 'Quilava Image'),
  new Pokemon(6, 157, 'Typhlosion', ['Fire'], 'Typhlosion Image'),
  new Pokemon(7, 158, 'Totodile', ['Water'], 'Totodile Image'),
  new Pokemon(8, 159, 'Croconaw', ['Water'], 'Croconaw Image'),
  new Pokemon(9, 160, 'Feraligatr', ['Water'], 'Feraligatr Image'),
  new Pokemon(10, 16, 'Pidgey', ['Normal', 'Flying'], 'Pidgey Image'),
  new Pokemon(11, 17, 'Pigeotto', ['Normal', 'Flying'], 'Pigeotto Image'),
  new Pokemon(12, 18, 'Pidgeot', ['Normal', 'Flying'], 'Pidgeot Image'),
  new Pokemon(13, 21, 'Spearow', ['Normal', 'Flying'], 'Spearow Image'),
  new Pokemon(14, 22, 'Fearow', ['Normal', 'Flying'], 'Fearow Image'),
  new Pokemon(15, 163, 'Hoothoot', ['Normal', 'Flying'], 'Hoothoot Image'),
  new Pokemon(16, 164, 'Noctowl', ['Normal', 'Flying'], 'Noctowl Image'),
  new Pokemon(17, 19, 'Rattata', ['Normal'], 'Rattata Image'),
  new Pokemon(18, 20, 'Raticate', ['Normal'], 'Raticate Image'),
  new Pokemon(19, 161, 'Sentret', ['Normal'], 'Sentret Image'),
  new Pokemon(20, 162, 'Furret', ['Normal'], 'Furret Image'),
  new Pokemon(21, 172, 'Pichu', ['Electric'], 'Pichu Image'),
  new Pokemon(22, 25, 'Pikachu', ['Electric'], 'Pikachu Image'),
  new Pokemon(23, 26, 'Raichu', ['Electric'], 'Raichu Image'),
  new Pokemon(24, 10, 'Caterpie', ['Bug'], 'Caterpie Image'),
  new Pokemon(25, 11, 'Metapod', ['Bug'], 'Metapod Image'),
  new Pokemon(26, 12, 'Butterfree', ['Bug', 'Flying'], 'Butterfree Image'),
  new Pokemon(27, 13, 'Weedle', ['Bug', 'Poison'], 'Weedle Image'),
  new Pokemon(28, 14, 'Kakuna', ['Bug', 'Poison'], 'Kakuna Image'),
  new Pokemon(29, 15, 'Beedrill', ['Bug', 'Poison'], 'Beedrill Image'),
  new Pokemon(30, 165, 'Ledyba', ['Bug', 'Flying'], 'Ledyba Image'),
  new Pokemon(31, 166, 'Ledian', ['Bug', 'Flying'], 'Ledian Image'),
  new Pokemon(32, 167, 'Spinarak', ['Bug', 'Poison'], 'Spinarak Image'),
  new Pokemon(33, 168, 'Ariados', ['Bug', 'Poison'], 'Ariados Image'),
  new Pokemon(34, 74, 'Geodude', ['Rock', 'Ground'], 'Geodude Image'),
  new Pokemon(35, 75, 'Graveler', ['Rock', 'Ground'], 'Graveler Image'),
  new Pokemon(36, 76, 'Golem', ['Rock', 'Ground'], 'Golem Image'),
  new Pokemon(37, 41, 'Zubat', ['Poison', 'Flying'], 'Zubat Image'),
  new Pokemon(38, 42, 'Golbat', ['Poison', 'Flying'], 'Golbat Image'),
  new Pokemon(39, 169, 'Crobat', ['Poison', 'Flying'], 'Crobat Image'),
  new Pokemon(40, 173, 'Cleffa', ['Normal'], 'Cleffa Image'),
  new Pokemon(41, 35, 'Clefairy', ['Normal'], 'Clefairy Image'),
  new Pokemon(42, 36, 'Clefable', ['Normal'], 'Clefable Image'),
  new Pokemon(43, 174, 'Igglybuff', ['Normal'], 'Igglybuff Image'),
  new Pokemon(44, 39, 'Jigglypuff', ['Normal'], 'Jigglypuff Image'),
  new Pokemon(45, 40, 'Wigglytuff', ['Normal'], 'Wigglytuff Image'),
  new Pokemon(46, 175, 'Togepi', ['Normal'], 'Togepi Image'),
  new Pokemon(47, 176, 'Togetic', ['Normal', 'Flying'], 'Togetic Image'),
  new Pokemon(48, 27, 'Sandshrew', ['Ground'], 'Sandshrew Image'),
  new Pokemon(49, 28, 'Sandslash', ['Ground'], 'Sandslash Image'),
  new Pokemon(50, 23, 'Ekans', ['Poison'], 'Ekans Image'),
  new Pokemon(51, 24, 'Arbok', ['Poison'], 'Arbok Image'),
  new Pokemon(52, 206, 'Dunsparce', ['Normal'], 'Dunsparce Image'),
  new Pokemon(53, 179, 'Mareep', ['Electric'], 'Mareep Image'),
  new Pokemon(54, 180, 'Flaaffy', ['Electric'], 'Flaaffy Image'),
  new Pokemon(55, 181, 'Ampharos', ['Electric'], 'Ampharos Image'),
  new Pokemon(56, 194, 'Wooper', ['Water', 'Ground'], 'Wooper Image'),
  new Pokemon(57, 195, 'Quagsire', ['Water', 'Ground'], 'Quagsire Image'),
  new Pokemon(58, 92, 'Gastly', ['Ghost', 'Poison'], 'Gastly Image'),
  new Pokemon(59, 93, 'Haunter', ['Ghost', 'Poison'], 'Haunter Image'),
  new Pokemon(60, 94, 'Gengar', ['Ghost', 'Poison'], 'Gengar Image'),
  new Pokemon(61, 201, 'Unown', ['Psychic'], 'Unown Image'),
  new Pokemon(62, 95, 'Onix', ['Rock', 'Ground'], 'Onix Image'),
  new Pokemon(63, 208, 'Steelix', ['Steel', 'Ground'], 'Steelix Image'),
  new Pokemon(64, 69, 'Bellsprout', ['Grass', 'Poison'], 'Bellsprout Image'),
  new Pokemon(65, 70, 'Weepinbell', ['Grass', 'Poison'], 'Weepinbell Image'),
  new Pokemon(66, 71, 'Victreebel', ['Grass', 'Poison'], 'Victreebel Image'),
  new Pokemon(67, 187, 'Hoppip', ['Grass', 'Flying'], 'Hoppip Image'),
  new Pokemon(68, 188, 'Skiploom', ['Grass', 'Flying'], 'Skiploom Image'),
  new Pokemon(69, 189, 'Jumpluff', ['Grass', 'Flying'], 'Jumpluff Image'),
  new Pokemon(70, 46, 'Paras', ['Bug', 'Grass'], 'Paras Image'),
  new Pokemon(71, 47, 'Parasect', ['Bug', 'Grass'], 'Parasect Image'),
  new Pokemon(72, 60, 'Poliwag', ['Water'], 'Poliwag Image'),
  new Pokemon(73, 61, 'Poliwhirl', ['Water'], 'Poliwhirl Image'),
  new Pokemon(74, 62, 'Poliwrath', ['Water', 'Fighting'], 'Poliwrath Image'),
  new Pokemon(75, 186, 'Politoed', ['Water'], 'Politoed Image'),
  new Pokemon(76, 129, 'Magikarp', ['Water'], 'Magikarp Image'),
  new Pokemon(77, 130, 'Gyarados', ['Water', 'Flying'], 'Gyrados Image'),
  new Pokemon(78, 118, 'Goldeen', ['Water'], 'Goldeen Image'),
  new Pokemon(79, 119, 'Seaking', ['Water'], 'Seaking Image'),
  new Pokemon(80, 79, 'Slowpoke', ['Water', 'Psychic'], 'Slowpoke Image'),
  new Pokemon(81, 80, 'Slowbro', ['Water', 'Psychic'], 'Slowbro Image'),
  new Pokemon(82, 199, 'Slowking', ['Water', 'Psychic'], 'Slowking Image'),
  new Pokemon(83, 43, 'Oddish', ['Grass', 'Poison'], 'Oddish Image'),
  new Pokemon(84, 44, 'Gloom', ['Grass', 'Poison'], 'Gloom Image'),
  new Pokemon(85, 45, 'Vileplume', ['Grass', 'Poison'], 'Vileplume Image'),
  new Pokemon(86, 182, 'Bellossom', ['Grass'], 'Bellossom Image'),
  new Pokemon(87, 96, 'Drowzee', ['Psychic'], 'Drowzee Image'),
  new Pokemon(88, 97, 'Hypno', ['Psychic'], 'Hypno Image'),
  new Pokemon(89, 63, 'Abra', ['Psychic'], 'Abra Image'),
  new Pokemon(90, 64, 'Kadabra', ['Psychic'], 'Kadabra Image'),
  new Pokemon(91, 65, 'Alakazam', ['Psychic'], 'Alakazam Image'),
  new Pokemon(92, 132, 'Ditto', ['Normal'], 'Ditto Image'),
  new Pokemon(93, 204, 'Pineco', ['Bug'], 'Pineco Image'),
  new Pokemon(94, 205, 'Forretress', ['Bug', 'Steel'], 'Forretress Image'),
  new Pokemon(95, 29, 'Nidoran♀', ['Poison'], 'Nidoran♀ Image'),
  new Pokemon(96, 30, 'Nidorina', ['Poison'], 'Nidorina Image'),
  new Pokemon(97, 31, 'Nidoqueen', ['Poison', 'Ground'], 'Nidoqueen Image'),
  new Pokemon(98, 32, 'Nidoran♂', ['Poison'], 'Nidoran♂ Image'),
  new Pokemon(99, 33, 'Nidorino', ['Poison'], 'Nidorino Image'),
  new Pokemon(100, 34, 'Nidoking', ['Poison', 'Ground'], 'Nidoking Image'),
  new Pokemon(101, 193, 'Yanma', ['Bug', 'Flying'], 'Yanma Image'),
  new Pokemon(102, 469, 'Yanmega', ['Bug', 'Flying'], 'Yanmega Image'),
  new Pokemon(103, 191, 'Sunkern', ['Grass'], 'Sunkern Image'),
  new Pokemon(104, 192, 'Sunflora', ['Grass'], 'Sunflora Image'),
  new Pokemon(105, 102, 'Exeggcute', ['Grass', 'Psychic'], 'Exeggcute Image'),
  new Pokemon(106, 103, 'Exeggutor', ['Grass', 'Psychic'], 'Exeggutor Image'),
  new Pokemon(107, 185, 'Sudowoodo', ['Rock'], 'Sudowoodo Image'),
  new Pokemon(108, 202, 'Wobbuffet', ['Psychic'], 'Wobbuffet Image'),
  new Pokemon(109, 48, 'Venonat', ['Bug', 'Poison'], 'Venonat Image'),
  new Pokemon(110, 49, 'Venomoth', ['Bug', 'Poison'], 'Venomoth Image'),
  new Pokemon(111, 123, 'Scyther', ['Bug', 'Flying'], 'Scyther Image'),
  new Pokemon(112, 212, 'Scizor', ['Bug', 'Steel'], 'Scizor Image'),
  new Pokemon(113, 127, 'Pinsir', ['Bug'], 'Pinsir Image'),
  new Pokemon(114, 214, 'Heracross', ['Bug', 'Fighting'], 'Heracross Image'),
  new Pokemon(115, 109, 'Koffing', ['Poison'], 'Koffing Image'),
  new Pokemon(116, 110, 'Weezing', ['Poison'], 'Weezing Image'),
  new Pokemon(117, 88, 'Grimer', ['Poison'], 'Grimer Image'),
  new Pokemon(118, 89, 'Muk', ['Poison'], 'Muk Image'),
  new Pokemon(119, 81, 'Magnemite', ['Electric', 'Steel'], 'Magnemite Image'),
  new Pokemon(120, 82, 'Magneton', ['Electric', 'Steel'], 'Magneton Image'),
  new Pokemon(121, 100, 'Voltorb', ['Electric'], 'Voltorb Image'),
  new Pokemon(122, 101, 'Electrode', ['Electric'], 'Electrode Image'),
  new Pokemon(123, 190, 'Aipom', ['Normal'], 'Aipom Image'),
  new Pokemon(124, 424, 'Ambipom', ['Normal'], 'Ambipom Image'),
  new Pokemon(125, 209, 'Snubbull', ['Normal'], 'Snubbull Image'),
  new Pokemon(126, 210, 'Granbull', ['Normal'], 'Granbull Image'),
  new Pokemon(127, 37, 'Vulpix', ['Fire'], 'Vulpix Image'),
  new Pokemon(128, 38, 'Ninetails', ['Fire'], 'Ninetails Image'),
  new Pokemon(129, 58, 'Growlithe', ['Fire'], 'Growlithe Image'),
  new Pokemon(130, 59, 'Arcanine', ['Fire'], 'Arcanine Image'),
  new Pokemon(131, 234, 'Stantler', ['Normal'], 'Stantler Image'),
  new Pokemon(132, 183, 'Marill', ['Water'], 'Marill Image'),
  new Pokemon(133, 184, 'Azumarill', ['Water'], 'Azumarill Image'),
  new Pokemon(134, 50, 'Diglett', ['Ground'], 'Diglett Image'),
  new Pokemon(135, 51, 'Dugtrio', ['Ground'], 'Dugtrio Image'),
  new Pokemon(136, 56, 'Mankey', ['Fighting'], 'Mankey Image'),
  new Pokemon(137, 57, 'Primeape', ['Fighting'], 'Primeape Image'),
  new Pokemon(138, 52, 'Meowth', ['Normal'], 'Meowth Image'),
  new Pokemon(139, 53, 'Persian', ['Normal'], 'Persian Image'),
  new Pokemon(140, 54, 'Psyduck', ['Water'], 'Psyduck Image'),
  new Pokemon(141, 55, 'Golduck', ['Water'], 'Golduck Image'),
  new Pokemon(142, 66, 'Machop', ['Fighting'], 'Machop Image'),
  new Pokemon(143, 67, 'Machoke', ['Fighting'], 'Machoke Image'),
  new Pokemon(144, 68, 'Machamp', ['Fighting'], 'Machamp Image'),
  new Pokemon(145, 236, 'Tyrogue', ['Fighting'], 'Tyrogue Image'),
  new Pokemon(146, 106, 'Hitmonlee', ['Fighting'], 'Hitmonlee Image'),
  new Pokemon(147, 107, 'Hitmonchan', ['Fighting'], 'Hitmonchan Image'),
  new Pokemon(148, 237, 'Hitmontop', ['Fighting'], 'Hitmontop Image'),
  new Pokemon(149, 203, 'Girafarig', ['Normal', 'Psychic'], 'Girafarig Image'),
  new Pokemon(150, 128, 'Tauros', ['Normal'], 'Tauros Image'),
  new Pokemon(151, 241, 'Miltank', ['Normal'], 'Miltank Image'),
  new Pokemon(152, 240, 'Magby', ['Fire'], 'Magby Image'),
  new Pokemon(153, 126, 'Magmar', ['Fire'], 'Magmar Image'),
  new Pokemon(154, 238, 'Smoochum', ['Ice', 'Psychic'], 'Smoochum Image'),
  new Pokemon(155, 124, 'Jynx', ['Ice', 'Psychic'], 'Jynx Image'),
  new Pokemon(156, 239, 'Elekid', ['Electric'], 'Elekid Image'),
  new Pokemon(157, 125, 'Electabuzz', ['Electric'], 'Electabuzz Image'),
  new Pokemon(158, 122, 'Mr. Mime', ['Psychic'], 'Mr. Mime Image'),
  new Pokemon(159, 235, 'Smeargle', ['Normal'], 'Smeargle Image'),
  new Pokemon(160, 83, 'Farfetch\'d', ['Normal', 'Flying'], 'Farfetch\'d Image'),
  new Pokemon(161, 177, 'Natu', ['Psychic', 'Flying'], 'Natu Image'),
  new Pokemon(162, 178, 'Xatu', ['Psychic', 'Flying'], 'Xatu Image'),
  new Pokemon(163, 211, 'Qwilfish', ['Water', 'Poison'], 'Qwilfish Image'),
  new Pokemon(164, 72, 'Tentacool', ['Water', 'Poison'], 'Tentacool Image'),
  new Pokemon(165, 73, 'Tentacruel', ['Water', 'Poison'], 'Tentacruel Image'),
  new Pokemon(166, 98, 'Krabby', ['Water'], 'Krabby Image'),
  new Pokemon(167, 99, 'Kingler', ['Water'], 'Kingler Image'),
  new Pokemon(168, 213, 'Shuckle', ['Bug', 'Rock'], 'Shuckle Image'),
  new Pokemon(169, 120, 'Staryu', ['Water'], 'Staryu Image'),
  new Pokemon(170, 121, 'Starmie', ['Water', 'Psychic'], 'Starmie Image'),
  new Pokemon(171, 90, 'Shellder', ['Water'], 'Shellder Image'),
  new Pokemon(172, 91, 'Cloyster', ['Water', 'Ice'], 'Cloyster Image'),
  new Pokemon(173, 222, 'Corsola', ['Water', 'Rock'], 'Corsola Image'),
  new Pokemon(174, 223, 'Remoraid', ['Water'], 'Remoraid Image'),
  new Pokemon(175, 224, 'Octillery', ['Water'], 'Octillery Image'),
  new Pokemon(176, 170, 'Chinchou', ['Water', 'Electric'], 'Chinchou Image'),
  new Pokemon(177, 171, 'Lanturn', ['Water', 'Electric'], 'Lanturn Image'),
  new Pokemon(178, 86, 'Seel', ['Water'], 'Seel Image'),
  new Pokemon(179, 87, 'Dewgong', ['Water', 'Ice'], 'Dewgong Image'),
  new Pokemon(180, 108, 'Lickitung', ['Normal'], 'Lickitung Image'),
  new Pokemon(181, 463, 'Lickilicky', ['Normal'], 'Lickilicky Image'),
  new Pokemon(182, 114, 'Tangela', ['Grass'], 'Tangela Image'),
  new Pokemon(183, 465, 'Tangrowth', ['Grass'], 'Tangrowth Image'),
  new Pokemon(184, 133, 'Eevee', ['Normal'], 'Eevee Image'),
  new Pokemon(185, 134, 'Vaporeon', ['Water'], 'Vaporeon Image'),
  new Pokemon(186, 135, 'Jolteon', ['Electric'], 'Jolteon Image'),
  new Pokemon(187, 136, 'Flareon', ['Fire'], 'Flareon Image'),
  new Pokemon(188, 196, 'Espeon', ['Psychic'], 'Espeon Image'),
  new Pokemon(189, 197, 'Umbreon', ['Dark'], 'Umbreon Image'),
  new Pokemon(190, 116, 'Horsea', ['Water'], 'Horsea Image'),
  new Pokemon(191, 117, 'Seadra', ['Water'], 'Seadra Image'),
  new Pokemon(192, 230, 'Kingdra', ['Water', 'Dragon'], 'Kingdra Image'),
  new Pokemon(193, 207, 'Gligar', ['Ground', 'Flying'], 'Gligar Image'),
  new Pokemon(194, 225, 'Delibird', ['Ice', 'Flying'], 'Delibird Image'),
  new Pokemon(195, 220, 'Swinub', ['Ice', 'Ground'], 'Swinub Image'),
  new Pokemon(196, 221, 'Piloswine', ['Ice', 'Ground'], 'Piloswine Image'),
  new Pokemon(197, 473, 'Mamoswine', ['Ice', 'Ground'], 'Mamoswine Image'),
  new Pokemon(198, 216, 'Teddiursa', ['Normal'], 'Teddiursa Image'),
  new Pokemon(199, 217, 'Ursaring', ['Normal'], 'Ursaring Image'),
  new Pokemon(200, 231, 'Phanpy', ['Ground'], 'Phanpy Image'),
  new Pokemon(201, 232, 'Donphan', ['Ground'], 'Donphan Image'),
  new Pokemon(202, 226, 'Mantine', ['Water', 'Flying'], 'Mantine Image'),
  new Pokemon(203, 227, 'Skarmory', ['Steel', 'Flying'], 'Skarmory Image'),
  new Pokemon(204, 84, 'Doduo', ['Normal', 'Flying'], 'Doduo Image'),
  new Pokemon(205, 85, 'Dodrio', ['Normal', 'Flying'], 'Dodrio Image'),
  new Pokemon(206, 77, 'Ponyta', ['Fire'], 'Ponyta Image'),
  new Pokemon(207, 78, 'Rapidash', ['Fire'], 'Rapidash Image'),
  new Pokemon(208, 104, 'Cubone', ['Ground'], 'Cubone Image'),
  new Pokemon(209, 105, 'Marowak', ['Ground'], 'Marowak Image'),
  new Pokemon(210, 115, 'Kangaskhan', ['Normal'], 'Kangaskhan Image'),
  new Pokemon(211, 111, 'Rhyhorn', ['Ground', 'Rock'], 'Rhyhorn Image'),
  new Pokemon(212, 112, 'Rhydon', ['Ground', 'Rock'], 'Rhydon Image'),
  new Pokemon(213, 198, 'Murkrow', ['Dark', 'Flying'], 'Murkrow Image'),
  new Pokemon(214, 228, 'Houndour', ['Dark', 'Fire'], 'Houndour Image'),
  new Pokemon(215, 229, 'Houndoom', ['Dark', 'Fire'], 'Houndoom Image'),
  new Pokemon(216, 218, 'Slugma', ['Fire'], 'Slugma Image'),
  new Pokemon(217, 219, 'Magcargo', ['Fire', 'Rock'], 'Magcargo Image'),
  new Pokemon(218, 215, 'Sneasel', ['Dark', 'Ice'], 'Sneasel Image'),
  new Pokemon(219, 200, 'Misdreavus', ['Ghost'], 'Misdreavus Image'),
  new Pokemon(220, 137, 'Porygon', ['Normal'], 'Porygon Image'),
  new Pokemon(221, 233, 'Porygon2', ['Normal'], 'Porygon2 Image'),
  new Pokemon(222, 113, 'Chansey', ['Normal'], 'Chansey Image'),
  new Pokemon(223, 242, 'Blissey', ['Normal'], 'Blissey Image'),
  new Pokemon(224, 131, 'Lapras', ['Water', 'Ice'], 'Lapras Image'),
  new Pokemon(225, 138, 'Omanyte', ['Rock', 'Water'], 'Omanyte Image'),
  new Pokemon(226, 139, 'Omastar', ['Rock', 'Water'], 'Omastar Image'),
  new Pokemon(227, 140, 'Kabuto', ['Rock', 'Water'], 'Kabuto Image'),
  new Pokemon(228, 141, 'Kabutops', ['Rock', 'Water'], 'Kabutops Image'),
  new Pokemon(229, 142, 'Aerodactyl', ['Rock', 'Flying'], 'Aerodactyl Image'),
  new Pokemon(230, 143, 'Snorlax', ['Normal'], 'Snorlax Image'),
  new Pokemon(231, 1, 'Bulbasaur', ['Grass', 'Poison'], 'Bulbasaur Image'),
  new Pokemon(232, 2, 'Ivysaur', ['Grass', 'Poison'], 'Ivysaur Image'),
  new Pokemon(233, 3, 'Venusaur', ['Grass', 'Poison'], 'Venusaur Image'),
  new Pokemon(234, 4, 'Charmander', ['Fire'], 'Charmander Image'),
  new Pokemon(235, 5, 'Charmeleon', ['Fire'], 'Charmeleon Image'),
  new Pokemon(236, 6, 'Charizard', ['Fire'], 'Charizard Image'),
  new Pokemon(237, 7, 'Squirtle', ['Water'], 'Squirtle Image'),
  new Pokemon(238, 8, 'Wartortle', ['Water'], 'Wartortle Image'),
  new Pokemon(239, 9, 'Blastoise', ['Water'], 'Blastoise Image'),
  new Pokemon(240, 144, 'Articuno', ['Ice', 'Flying'], 'Articuno Image'),
  new Pokemon(241, 145, 'Zapdos', ['Electric', 'Flying'], 'Zapdos Image'),
  new Pokemon(242, 146, 'Moltres', ['Fire', 'Flying'], 'Moltres Image'),
  new Pokemon(243, 243, 'Raikou', ['Electric'], 'Raikou Image'),
  new Pokemon(244, 244, 'Entei', ['Fire'], 'Entei Image'),
  new Pokemon(245, 245, 'Suicune', ['Water'], 'Suicune Image'),
  new Pokemon(246, 147, 'Dratini', ['Dragon'], 'Dratini Image'),
  new Pokemon(247, 148, 'Dragonair', ['Dragon'], 'Dragonair Image'),
  new Pokemon(248, 149, 'Dragonite', ['Dragon', 'Flying'], 'Dragonite Image'),
  new Pokemon(249, 246, 'Larvitar', ['Rock', 'Ground'], 'Larvitar Image'),
  new Pokemon(250, 247, 'Pupitar', ['Rock', 'Ground'], 'Pupitar Image'),
  new Pokemon(251, 248, 'Tyranitar', ['Rock', 'Dark'], 'Tyranitar Image'),
  new Pokemon(252, 249, 'Lugia', ['Psychic', 'Flying'], 'Lugia Image'),
  new Pokemon(253, 250, 'Ho-Oh', ['Fire', 'Flying'], 'Ho-Oh Image'),
  new Pokemon(254, 150, 'Mewtwo', ['Psychic'], 'Mewtwo Image'),
  new Pokemon(255, 151, 'Mew', ['Psychic'], 'Mew Image'),
  new Pokemon(256, 251, 'Celebi', ['Psychic', 'Grass'], 'Celebi Image')
]

function loadJohto() {
  $('#Center').text("Johto Pokémon List by Pokédex Number");
  $('#pokemon-container').empty();
  for (var display of johtoPokemonList) {
    display.loadToPage();
    display.ShowTypes();
  }
}
