var johtoPokemonList = [
  new Pokemon(1, 152, 'Chikorita', ['Grass'], 'Chikorita Image'),
  new Pokemon(2, 153, 'Bayleef', ['Grass'], 'Bayleef Image'),
  new Pokemon(3, 154, 'Meganium', ['Grass'], 'Meganium Image'),
  new Pokemon(4, 155, 'Cyndaquil', ['Fire'], 'Cyndaquil Image'),
  new Pokemon(5, 156, 'Quilava', ['Fire'], 'Quilava Image'),
  new Pokemon(6, 157, 'Typhlosion', ['Fire'], 'Typhlosion Image'),
  new Pokemon(7, 158, 'Totodile', ['Water'], 'Totodile Image'),
  new Pokemon(8, 159, 'Croconaw', ['Water'], 'Croconaw Image'),
  new Pokemon(9, 160, 'Feraligatr', ['Water'], 'Feraligatr Image'),
  new Pokemon(10, 16, 'Pidgey', ['Normal', 'Flying'], 'Pidgey Image'),
  new Pokemon(11, 17, 'Pigeotto', ['Normal', 'Flying'], 'Pigeotto Image'),
  new Pokemon(12, 18, 'Pidgeot', ['Normal', 'Flying'], 'Pidgeot Image'),
  new Pokemon(13, 21, 'Spearow', ['Normal', 'Flying'], 'Spearow Image'),
  new Pokemon(14, 22, 'Fearow', ['Normal', 'Flying'], 'Fearow Image'),
  new Pokemon(15, 163, 'Hoothoot', ['Normal', 'Flying'], 'Hoothoot Image'),
  new Pokemon(16, 164, 'Noctowl', ['Normal', 'Flying'], 'Noctowl Image'),
  new Pokemon(17, 19, 'Rattata', ['Normal'], 'Rattata Image'),
  new Pokemon(18, 20, 'Raticate', ['Normal'], 'Raticate Image'),
  new Pokemon(19, 161, 'Sentret', ['Normal'], 'Sentret Image'),
  new Pokemon(20, 162, 'Furret', ['Normal'], 'Furret Image'),
  new Pokemon(21, 172, 'Pichu', ['Electric'], 'Pichu Image'),
  new Pokemon(22, 25, 'Pikachu', ['Electric'], 'Pikachu Image'),
  new Pokemon(23, 26, 'Raichu', ['Electric'], 'Raichu Image'),
  new Pokemon(24, 10, 'Caterpie', ['Bug'], 'Caterpie Image'),
  new Pokemon(25, 11, 'Metapod', ['Bug'], 'Metapod Image'),
  new Pokemon(26, 12, 'Butterfree', ['Bug', 'Flying'], 'Butterfree Image'),
  new Pokemon(27, 13, 'Weedle', ['Bug', 'Poison'], 'Weedle Image'),
  new Pokemon(28, 14, 'Kakuna', ['Bug', 'Poison'], 'Kakuna Image'),
  new Pokemon(29, 15, 'Beedrill', ['Bug', 'Poison'], 'Beedrill Image'),
  new Pokemon(30, 165, 'Ledyba', ['Bug', 'Flying'], 'Ledyba Image'),
  new Pokemon(31, 166, 'Ledian', ['Bug', 'Flying'], 'Ledian Image'),
  new Pokemon(32, 167, 'Spinarak', ['Bug', 'Poison'], 'Spinarak Image'),
  new Pokemon(33, 168, 'Ariados', ['Bug', 'Poison'], 'Ariados Image'),
  new Pokemon(34, 74, 'Geodude', ['Rock', 'Ground'], 'Geodude Image'),
  new Pokemon(35, 75, 'Graveler', ['Rock', 'Ground'], 'Graveler Image'),
  new Pokemon(36, 76, 'Golem', ['Rock', 'Ground'], 'Golem Image'),
  new Pokemon(37, 41, 'Zubat', ['Poison', 'Flying'], 'Zubat Image'),
  new Pokemon(38, 42, 'Golbat', ['Poison', 'Flying'], 'Golbat Image'),
  new Pokemon(39, 169, 'Crobat', ['Poison', 'Flying'], 'Crobat Image'),
  new Pokemon(40, 173, 'Cleffa', ['Normal'], 'Cleffa Image'),
  new Pokemon(41, 35, 'Clefairy', ['Normal'], 'Clefairy Image'),
  new Pokemon(42, 36, 'Clefable', ['Normal'], 'Clefable Image'),
  new Pokemon(43, 174, 'Igglybuff', ['Normal'], 'Igglybuff Image'),
  new Pokemon(44, 39, 'Jigglypuff', ['Normal'], 'Jigglypuff Image'),
  new Pokemon(45, 40, 'Wigglytuff', ['Normal'], 'Wigglytuff Image'),
  new Pokemon(46, 175, 'Togepi', ['Normal'], 'Togepi Image'),
  new Pokemon(47, 176, 'Togetic', ['Normal', 'Flying'], 'Togetic Image'),
  new Pokemon(48, 27, 'Sandshrew', ['Ground'], 'Sandshrew Image'),
  new Pokemon(49, 28, 'Sandslash', ['Ground'], 'Sandslash Image'),
  new Pokemon(50, 23, 'Ekans', ['Poison'], 'Ekans Image'),
  new Pokemon(51, 24, 'Arbok', ['Poison'], 'Arbok Image'),
  new Pokemon(52, 206, 'Dunsparce', ['Normal'], 'Dunsparce Image'),
  new Pokemon(53, 179, 'Mareep', ['Electric'], 'Mareep Image'),
  new Pokemon(54, 180, 'Flaaffy', ['Electric'], 'Flaaffy Image'),
  new Pokemon(55, 181, 'Ampharos', ['Electric'], 'Ampharos Image'),
  new Pokemon(56, 194, 'Wooper', ['Water', 'Ground'], 'Wooper Image'),
  new Pokemon(57, 195, 'Quagsire', ['Water', 'Ground'], 'Quagsire Image'),
  new Pokemon(58, 92, 'Gastly', ['Ghost', 'Poison'], 'Gastly Image'),
  new Pokemon(59, 93, 'Haunter', ['Ghost', 'Poison'], 'Haunter Image'),
  new Pokemon(60, 94, 'Gengar', ['Ghost', 'Poison'], 'Gengar Image'),
  new Pokemon(61, 201, 'Unown', ['Psychic'], 'Unown Image'),
  new Pokemon(62, 95, 'Onix', ['Rock', 'Ground'], 'Onix Image'),
  new Pokemon(63, 208, 'Steelix', ['Steel', 'Ground'], 'Steelix Image'),
  new Pokemon(64, 69, 'Bellsprout', ['Grass', 'Poison'], 'Bellsprout Image'),
  new Pokemon(65, 70, 'Weepinbell', ['Grass', 'Poison'], 'Weepinbell Image'),
  new Pokemon(66, 71, 'Victreebel', ['Grass', 'Poison'], 'Victreebel Image'),
  new Pokemon(67, 187, 'Hoppip', ['Grass', 'Flying'], 'Hoppip Image'),
  new Pokemon(68, 188, 'Skiploom', ['Grass', 'Flying'], 'Skiploom Image'),
  new Pokemon(69, 189, 'Jumpluff', ['Grass', 'Flying'], 'Jumpluff Image'),
  new Pokemon(70, 46, 'Paras', ['Bug', 'Grass'], 'Paras Image'),
  new Pokemon(71, 47, 'Parasect', ['Bug', 'Grass'], 'Parasect Image'),
  new Pokemon(72, 60, 'Poliwag', ['Water'], 'Poliwag Image'),
  new Pokemon(73, 61, 'Poliwhirl', ['Water'], 'Poliwhirl Image'),
  new Pokemon(74, 62, 'Poliwrath', ['Water', 'Fighting'], 'Poliwrath Image'),
  new Pokemon(75, 186, 'Politoed', ['Water'], 'Politoed Image'),
  new Pokemon(76, 129, 'Magikarp', ['Water'], 'Magikarp Image'),
  new Pokemon(77, 130, 'Gyarados', ['Water', 'Flying'], 'Gyrados Image'),
  new Pokemon(78, 118, 'Goldeen', ['Water'], 'Goldeen Image'),
  new Pokemon(79, 119, 'Seaking', ['Water'], 'Seaking Image'),
  new Pokemon(80, 79, 'Slowpoke', ['Water', 'Psychic'], 'Slowpoke Image'),
  new Pokemon(81, 80, 'Slowbro', ['Water', 'Psychic'], 'Slowbro Image'),
  new Pokemon(82, 199, 'Slowking', ['Water', 'Psychic'], 'Slowking Image'),
  new Pokemon(83, 43, 'Oddish', ['Grass', 'Poison'], 'Oddish Image'),
  new Pokemon(84, 44, 'Gloom', ['Grass', 'Poison'], 'Gloom Image'),
  new Pokemon(85, 45, 'Vileplume', ['Grass', 'Poison'], 'Vileplume Image'),
  new Pokemon(86, 182, 'Bellossom', ['Grass'], 'Bellossom Image'),
  new Pokemon(87, 96, 'Drowzee', ['Psychic'], 'Drowzee Image'),
  new Pokemon(88, 97, 'Hypno', ['Psychic'], 'Hypno Image'),
  new Pokemon(89, 63, 'Abra', ['Psychic'], 'Abra Image'),
  new Pokemon(90, 64, 'Kadabra', ['Psychic'], 'Kadabra Image'),
  new Pokemon(91, 65, 'Alakazam', ['Psychic'], 'Alakazam Image'),
  new Pokemon(92, 132, 'Ditto', ['Normal'], 'Ditto Image'),
  new Pokemon(93, 204, 'Pineco', ['Bug'], 'Pineco Image'),
  new Pokemon(94, 205, 'Forretress', ['Bug', 'Steel'], 'Forretress Image'),
  new Pokemon(95, 29, 'Nidoran♀', ['Poison'], 'Nidoran♀ Image'),
  new Pokemon(96, 30, 'Nidorina', ['Poison'], 'Nidorina Image'),
  new Pokemon(97, 31, 'Nidoqueen', ['Poison', 'Ground'], 'Nidoqueen Image'),
  new Pokemon(98, 32, 'Nidoran♂', ['Poison'], 'Nidoran♂ Image'),
  new Pokemon(99, 33, 'Nidorino', ['Poison'], 'Nidorino Image'),
  new Pokemon(100, 34, 'Nidoking', ['Poison', 'Ground'], 'Nidoking Image'),
  new Pokemon(101, 193, 'Yanma', ['Bug', 'Flying'], 'Yanma Image'),
  new Pokemon(102, 469, 'Yanmega', ['Bug', 'Flying'], 'Yanmega Image'),
  new Pokemon(103, 191, 'Sunkern', ['Grass'], 'Sunkern Image'),
  new Pokemon(104, 192, 'Sunflora', ['Grass'], 'Sunflora Image'),
  new Pokemon(105, 102, 'Exeggcute', ['Grass', 'Psychic'], 'Exeggcute Image'),
  new Pokemon(106, 103, 'Exeggutor', ['Grass', 'Psychic'], 'Exeggutor Image'),
  new Pokemon(107, 185, 'Sudowoodo', ['Rock'], 'Sudowoodo Image'),
  new Pokemon(108, 202, 'Wobbuffet', ['Psychic'], 'Wobbuffet Image'),
  new Pokemon(109, 48, 'Venonat', ['Bug', 'Poison'], 'Venonat Image'),
  new Pokemon(110, 49, 'Venomoth', ['Bug', 'Poison'], 'Venomoth Image'),
]

function loadJohto() {
  for (var display of johtoPokemonList) {
    display.loadToPage();
    display.ShowTypes();
  }
}
