var pokemonList = [
  new Pokemon(650, 'Chespin', ['Grass']),
  new Pokemon(651, 'Quilladin', ['Grass']),
  new Pokemon(652, 'Chesnaught', ['Grass', 'Fighting']),
  new Pokemon(653, 'Fennekin', ['Fire']),
  new Pokemon(654, 'Braixen', ['Fire']),
  new Pokemon(655, 'Delphox', ['Fire', 'Psychic']),
  new Pokemon(656, 'Froakie', ['Water']),
  new Pokemon(657, 'Frogadier', ['Water']),
  new Pokemon(658, 'Greninja', ['Water', 'Dark']),
  new Pokemon(659, 'Bunnelby', ['Normal']),
  new Pokemon(660, 'Diggersby', ['Normal', 'Ground']),
  new Pokemon(263, 'Zigzagoon', ['Normal']),
  new Pokemon(264, 'Linoone', ['Normal']),
  new Pokemon(661, 'Fletchling', ['Normal', 'Flying']),
  new Pokemon(662, 'Fletchinder', ['Fire', 'Flying']),
  new Pokemon(663, 'Talonflame', ['Fire', 'Flying']),
  new Pokemon(16, 'Pidgey', ['Normal', 'Flying']),
  new Pokemon(17, 'Pidgeotto', ['Normal', 'Flying']),
  new Pokemon(18, 'Pidgeot', ['Normal', 'Flying']),
  new Pokemon(664, 'Scatterbug', ['Bug']),
  new Pokemon(665, 'Spewpa', ['Bug']),
  new Pokemon(666, 'Vivillon', ['Bug', 'Flying']),
  new Pokemon(10, 'Caterpie', ['Bug']),
  new Pokemon(11, 'Metapod', ['Bug']),
  new Pokemon(12, 'Butterfree', ['Bug', 'Flying']),
  new Pokemon(13, 'Weedle', ['Bug', 'Poison']),
  new Pokemon(14, 'Kakuna', ['Bug', 'Poison']),
  new Pokemon(15, 'Beedrill', ['Bug', 'Poison']),
  new Pokemon(511, 'Pansage', ['Grass']),
  new Pokemon(512, 'Simisage', ['Grass']),
  new Pokemon(513, 'Pansear', ['Fire']),
  new Pokemon(514, 'Simisear', ['Fire']),
  new Pokemon(515, 'Panpour', ['Water']),
  new Pokemon(516, 'Simipour', ['Water']),
  new Pokemon(172, 'Pichu', ['Electric']),
  new Pokemon(25, 'Pikachu', ['Electric']),
  new Pokemon(26, 'Raichu', ['Electric']),
  new Pokemon(399, 'Bidoof', ['Normal']),
  new Pokemon(400, 'Bibarel', ['Normal', 'Water']),
  new Pokemon(206, 'Dunsparce', ['Normal']),
  new Pokemon(298, 'Azurill', ['Normal', 'Fairy']),
  new Pokemon(183, 'Marill', ['Water', 'Fairy']),
  new Pokemon(184, 'Azumarill', ['Water', 'Fairy']),
  new Pokemon(412, 'Burmy', ['Bug']),
  new Pokemon(413, 'Wormadam', ['Bug', 'Grass']),
  new Pokemon(414, 'Mothim', ['Bug', 'Flying']),
  new Pokemon(283, 'Surskit', ['Bug', 'Water']),
  new Pokemon(284, 'Masquerain', ['Bug', 'Flying']),
  new Pokemon(129, 'Magikarp', ['Water']),
  new Pokemon(130, 'Gyarados', ['Water', 'Flying']),
  new Pokemon(341, 'Corphish', ['Ground']),
  new Pokemon(342, 'Crawdaunt', ['Normal', 'Dark']),
  new Pokemon(118, 'Goldeen', ['Normal']),
  new Pokemon(119, 'Seaking', ['Water']),
  new Pokemon(318, 'Carvanha', ['Water', 'Dark']),
  new Pokemon(319, 'Sharpedo', ['Water', 'Dark']),
  new Pokemon(667, 'Litleo', ['Fire', 'Normal']),
  new Pokemon(668, 'Pyroar', ['Fire', 'Normal']),
  new Pokemon(54, 'Psyduck', ['Water']),
  new Pokemon(55, 'Golduck', ['Water']),
  new Pokemon(83, 'Farfetch\'d', ['Normal', 'Flying']),
  new Pokemon(447, 'Riolu', ['Fighting']),
  new Pokemon(448, 'Lucario', ['Fighting', 'Steel']),
  new Pokemon(280, 'Ralts', ['Psychic', 'Fairy']),
  new Pokemon(281, 'Kirlia', ['Psychic', 'Fairy']),
  new Pokemon(282, 'Gardevoir', ['Psychic', 'Fairy']),
  new Pokemon(475, 'Gallade', ['Psychic', 'Fighting']),
  new Pokemon(669, 'Flabébé', ['Fairy']),
  new Pokemon(670, 'Floette', ['Fairy']),
  new Pokemon(671, 'Florges', ['Fairy']),
  new Pokemon(406, 'Budew', ['Grass', 'Poison']),
  new Pokemon(315, 'Roselia', ['Grass', 'Poison']),
  new Pokemon(407, 'Roserade', ['Grass', 'Poison']),
  new Pokemon(165, 'Ledyba', ['Bug', 'Flying']),
  new Pokemon(166, 'Ledian', ['Bug', 'Flying']),
  new Pokemon(415, 'Combee', ['Bug', 'Flying']),
  new Pokemon(416, 'Vespiquen', ['Bug', 'Flying']),
  new Pokemon(300, 'Skitty', ['Normal']),
  new Pokemon(301, 'Delcatty', ['Normal']),
  new Pokemon(1, 'Bulbasaur', ['Grass', 'Poison']),
  new Pokemon(2, 'Ivysaur', ['Grass', 'Poison']),
  new Pokemon(3, 'Venusaur', ['Grass', 'Poison']),
  new Pokemon(4, "Charmander", ['Fire']),
  new Pokemon(5, 'Charmeleon', ['Fire']),
  new Pokemon(6, 'Charizard', ['Fire', 'Flying']),
  new Pokemon(7, 'Squirtle', ['Water']),
  new Pokemon(8, 'Wartortle', ['Water']),
  new Pokemon(9, 'Blastoise', ['Water']),
  new Pokemon(672, 'Skiddo', ['Grass']),
  new Pokemon(673, 'Gogoat', ['Grass']),
  new Pokemon(674, 'Pancham', ['Fighting']),
  new Pokemon(675, 'Pangoro', ['Fighting', 'Dark']),
  new Pokemon(676, 'Furfrou', ['Normal']),
  new Pokemon(84, 'Doduo', ['Normal', 'Flying']),
  new Pokemon(85, 'Dodrio', ['Normal', 'Flying']),
  new Pokemon(311, 'Plusle', ['Electric']),
  new Pokemon(312, 'Minun', ['Electric']),
  new Pokemon(316, 'Gulpin', ['Poison']),
  new Pokemon(317, 'Swalot', ['Poison']),
  new Pokemon(559, 'Scraggy', ['Dark', 'Fighting']),
  new Pokemon(560, 'Scrafty', ['Dark', 'Fighting']),
  new Pokemon(63, 'Abra', ['Psychic']),
  new Pokemon(64, 'Kadabra', ['Psychic']),
  new Pokemon(65, 'Alakazam', ['Psychic']),
  new Pokemon(43, 'Oddish', ['Grass', 'Poison']),
  new Pokemon(44, 'Gloom', ['Grass', 'Poison']),
  new Pokemon(45, 'Vileplume', ['Grass', 'Poison']),
  new Pokemon(182, 'Bellossom', ['Grass']),
  new Pokemon(161, 'Sentret', ['Normal']),
  new Pokemon(162, 'Furret', ['Normal']),
  new Pokemon(290, 'Nincada', ['Bug', 'Ground']),
  new Pokemon(291, 'Ninjask', ['Bug', 'Flying']),
  new Pokemon(292, 'Shedinja', ['Bug', 'Ghost']),
  new Pokemon(677, 'Espurr', ['Psychic']),
  new Pokemon(678, 'Meowstic', ['Psychic']),
  new Pokemon(352, 'Kecleon', ['Normal']),
  new Pokemon(679, 'Honedge', ['Steel', 'Ghost']),
  new Pokemon(680, 'Doublade', ['Steel', 'Ghost']),
  new Pokemon(681, 'Aegislash', ['Steel', 'Ghost']),
  new Pokemon(543, 'Venipede', ['Bug', 'Poison']),
  new Pokemon(544, 'Whirlipede', ['Bug', 'Poison']),
  new Pokemon(545, 'Scolipede', ['Psychic', 'Fairy']),
  new Pokemon(531, 'Audino', ['Normal']),
  new Pokemon(235, 'Smeargle', ['Normal']),
  new Pokemon(453, 'Croagunk', ['Poison', 'Fighting']),
  new Pokemon(454, 'Toxicroak', ['Poison', 'Fighting']),
  new Pokemon(580, 'Ducklett', ['Water', 'Flying']),
  new Pokemon(581, 'Swanna', ['Water', 'Flying']),
  new Pokemon(682, 'Spritzee', ['Fairy']),
  new Pokemon(683, 'Aromatisse', ['Fairy']),
  new Pokemon(684, 'Swirlix', ['Fairy']),
  new Pokemon(685, 'Slurpuff', ['Fairy']),
  new Pokemon(313, 'Volbeat', ['Bug']),
  new Pokemon(314, 'Illumise', ['Bug']),
  new Pokemon(187, 'Hoppip', ['Grass', 'Flying']),
  new Pokemon(188, 'Skiploom', ['Grass', 'Flying']),
  new Pokemon(189, 'Jumpluff', ['Grass', 'Flying']),
  new Pokemon(446, 'Munchlax', ['Normal']),
  new Pokemon(143, 'Snorlax', ['Normal']),
  new Pokemon(293, 'Whismur', ['Normal']),
  new Pokemon(294, 'Loudred', ['Normal']),
  new Pokemon(295, 'Exploud', ['Normal']),
  new Pokemon(307, 'Meditite', ['Fighting', 'Psychic']),
  new Pokemon(308, 'Medicham', ['Fighting', 'Psychic']),
  new Pokemon(41, 'Zubat', ['Poison', 'Flying']),
  new Pokemon(42, 'Golbat', ['Poison', 'Flying']),
  new Pokemon(169, 'Crobat', ['Poison', 'Flying']),
  new Pokemon(610, 'Axew', ['Dragon']),
  new Pokemon(611, 'Fraxure', ['Dragon']),
  new Pokemon(612, 'Haxorus', ['Dragon']),
  new Pokemon(719, 'Diancie', ['Rock', 'Fairy']),
  new Pokemon(720, 'Hoopa', ['Psychic', 'Ghost']),
  new Pokemon(721, 'Volcanion', ['Fire', 'Water']),
  new Pokemon(425, 'Drifloon', ['Ghost', 'Flying']),
  new Pokemon(426, 'Drifblim', ['Ghost', 'Flying']),
  new Pokemon(619, 'Mienfoo', ['Fighting']),
  new Pokemon(620, 'Mienshao', ['Fighting']),
  new Pokemon(335, 'Zangoose', ['Normal']),
  new Pokemon(336, 'Seviper', ['Poison']),
  new Pokemon(325, 'Spoink', ['Psychic']),
  new Pokemon(326, 'Grumpig', ['Psychic']),
  new Pokemon(359, 'Absol', ['Dark']),
  new Pokemon(686, 'Inkay', ['Dark', 'Psychic']),
  new Pokemon(687, 'Malamar', ['Dark', 'Psychic']),
  new Pokemon(337, 'Lunatone', ['Rock', 'Psychic']),
  new Pokemon(338, 'Solrock', ['Rock', 'Psychic']),
  new Pokemon(371, 'Bagon', ['Dragon']),
  new Pokemon(372, 'Shelgon', ['Dragon']),
  new Pokemon(373, 'Salamance', ['Dragon', 'Flying']),
  new Pokemon(278, 'Wingull', ['Water', 'Flying']),
  new Pokemon(279, 'Pelipper', ['Water', 'Flying']),
  new Pokemon(276, 'Taillow', ['Normal', 'Flying']),
  new Pokemon(277, 'Swellow', ['Normal', 'Flying']),
  new Pokemon(688, 'Binacle', ['Rock', 'Water']),
  new Pokemon(689, 'Barbaracle', ['Rock', 'Water']),
  new Pokemon(557, 'Dwebble', ['Bug', 'Rock']),
  new Pokemon(558, 'Crustle', ['Bug', 'Rock']),
  new Pokemon(72, 'Tentacool', ['Water', 'Poison']),
  new Pokemon(73, 'Tentacruel', ['Water', 'Poison']),
  new Pokemon(320, 'Wailmer', ['Water']),
  new Pokemon(321, 'Wailord', ['Water']),
  new Pokemon(370, 'Pansage', ['Grass']),
  new Pokemon(690, 'Simisage', ['Grass']),
  new Pokemon(691, 'Pansear', ['Fire']),
  new Pokemon(692, 'Simisear', ['Fire']),
  new Pokemon(693, 'Panpour', ['Water']),
  new Pokemon(120, 'Simipour', ['Water']),
  new Pokemon(121, 'Pichu', ['Electric']),
  new Pokemon(90, 'Pikachu', ['Electric']),
  new Pokemon(91, 'Raichu', ['Electric']),
  new Pokemon(211, 'Bidoof', ['Normal']),
  new Pokemon(116, 'Bibarel', ['Normal', 'Water']),
  new Pokemon(117, 'Dunsparce', ['Normal']),
  new Pokemon(230, 'Azurill', ['Normal', 'Fairy']),
  new Pokemon(369, 'Marill', ['Water', 'Fairy']),
  new Pokemon(551, 'Azumarill', ['Water', 'Fairy']),
  new Pokemon(552, 'Burmy', ['Bug']),
  new Pokemon(553, 'Wormadam', ['Bug', 'Grass']),
  new Pokemon(694, 'Mothim', ['Bug', 'Flying']),
  new Pokemon(695, 'Surskit', ['Bug', 'Water']),
  new Pokemon(449, 'Masquerain', ['Bug', 'Flying']),
  new Pokemon(450, 'Magikarp', ['Water']),
  new Pokemon(111, 'Gyarados', ['Water', 'Flying']),
  new Pokemon(112, 'Corphish', ['Ground']),
  new Pokemon(464, 'Crawdaunt', ['Normal', 'Dark']),
  new Pokemon(95, 'Goldeen', ['Normal']),
  new Pokemon(208, 'Seaking', ['Water']),
  new Pokemon(527, 'Carvanha', ['Water', 'Dark']),
  new Pokemon(528, 'Sharpedo', ['Water', 'Dark']),
  new Pokemon(66, 'Litleo', ['Fire', 'Normal']),
  new Pokemon(67, 'Pyroar', ['Fire', 'Normal']),
  new Pokemon(68, 'Psyduck', ['Water']),
  new Pokemon(104, 'Golduck', ['Water']),
  new Pokemon(105, 'Farfetch\'d', ['Normal', 'Flying']),
  new Pokemon(115, 'Riolu', ['Fighting']),
  new Pokemon(303, 'Lucario', ['Fighting', 'Steel']),
  new Pokemon(696, 'Ralts', ['Psychic', 'Fairy']),
  new Pokemon(697, 'Kirlia', ['Psychic', 'Fairy']),
  new Pokemon(698, 'Gardevoir', ['Psychic', 'Fairy']),
  new Pokemon(699, 'Gallade', ['Psychic', 'Fighting']),
  new Pokemon(142, 'Flabébé', ['Fairy']),
  new Pokemon(597, 'Floette', ['Fairy']),
  new Pokemon(598, 'Florges', ['Fairy']),
  new Pokemon(209, 'Budew', ['Grass', 'Poison']),
  new Pokemon(210, 'Roselia', ['Grass', 'Poison']),
  new Pokemon(309, 'Roserade', ['Grass', 'Poison']),
  new Pokemon(310, 'Ledyba', ['Bug', 'Flying']),
  new Pokemon(228, 'Ledian', ['Bug', 'Flying']),
  new Pokemon(229, 'Combee', ['Bug', 'Flying']),
  new Pokemon(133, 'Vespiquen', ['Bug', 'Flying']),
  new Pokemon(134, 'Skitty', ['Normal']),
  new Pokemon(135, 'Delcatty', ['Normal']),
  new Pokemon(136, 'Bulbasaur', ['Grass', 'Poison']),
  new Pokemon(196, 'Ivysaur', ['Grass', 'Poison']),
  new Pokemon(197, 'Venusaur', ['Grass', 'Poison']),
  new Pokemon(470, "Charmander", ['Fire']),
  new Pokemon(471, 'Charmeleon', ['Fire']),
  new Pokemon(700, 'Charizard', ['Fire', 'Flying']),
  new Pokemon(587, 'Squirtle', ['Water']),
  new Pokemon(193, 'Wartortle', ['Water']),
  new Pokemon(469, 'Blastoise', ['Water']),
  new Pokemon(701, 'Skiddo', ['Grass']),
  new Pokemon(561, 'Gogoat', ['Grass']),
  new Pokemon(622, 'Pancham', ['Fighting']),
  new Pokemon(623, 'Pangoro', ['Fighting', 'Dark']),
  new Pokemon(299, 'Furfrou', ['Normal']),
  new Pokemon(476, 'Doduo', ['Normal', 'Flying']),
  new Pokemon(296, 'Dodrio', ['Normal', 'Flying']),
  new Pokemon(297, 'Plusle', ['Electric']),
  new Pokemon(538, 'Minun', ['Electric']),
  new Pokemon(539, 'Gulpin', ['Poison']),
  new Pokemon(396, 'Swalot', ['Poison']),
  new Pokemon(397, 'Scraggy', ['Dark', 'Fighting']),
  new Pokemon(398, 'Scrafty', ['Dark', 'Fighting']),
  new Pokemon(434, 'Abra', ['Psychic']),
  new Pokemon(435, 'Kadabra', ['Psychic']),
  new Pokemon(29, 'Alakazam', ['Psychic']),
  new Pokemon(30, 'Oddish', ['Grass', 'Poison']),
  new Pokemon(31, 'Gloom', ['Grass', 'Poison']),
  new Pokemon(32, 'Vileplume', ['Grass', 'Poison']),
  new Pokemon(33, 'Bellossom', ['Grass']),
  new Pokemon(34, 'Sentret', ['Normal']),
  new Pokemon(702, 'Furret', ['Normal']),
  new Pokemon(433, 'Nincada', ['Bug', 'Ground']),
  new Pokemon(358, 'Ninjask', ['Bug', 'Flying']),
  new Pokemon(439, 'Shedinja', ['Bug', 'Ghost']),
  new Pokemon(122, 'Espurr', ['Psychic']),
  new Pokemon(577, 'Meowstic', ['Psychic']),
  new Pokemon(578, 'Kecleon', ['Normal']),
  new Pokemon(579, 'Honedge', ['Steel', 'Ghost']),
  new Pokemon(360, 'Doublade', ['Steel', 'Ghost']),
  new Pokemon(202, 'Aegislash', ['Steel', 'Ghost']),
  new Pokemon(524, 'Venipede', ['Bug', 'Poison']),
  new Pokemon(525, 'Whirlipede', ['Bug', 'Poison']),
  new Pokemon(526, 'Scolipede', ['Psychic', 'Fairy']),
  new Pokemon(302, 'Audino', ['Normal']),
  new Pokemon(703, 'Smeargle', ['Normal']),
  new Pokemon(128, 'Croagunk', ['Poison', 'Fighting']),
  new Pokemon(241, 'Toxicroak', ['Poison', 'Fighting']),
  new Pokemon(179, 'Ducklett', ['Water', 'Flying']),
  new Pokemon(180, 'Swanna', ['Water', 'Flying']),
  new Pokemon(181, 'Spritzee', ['Fairy']),
  new Pokemon(127, 'Aromatisse', ['Fairy']),
  new Pokemon(214, 'Swirlix', ['Fairy']),
  new Pokemon(417, 'Slurpuff', ['Fairy']),
  new Pokemon(79, 'Volbeat', ['Bug']),
  new Pokemon(80, 'Illumise', ['Bug']),
  new Pokemon(199, 'Hoppip', ['Grass', 'Flying']),
  new Pokemon(102, 'Skiploom', ['Grass', 'Flying']),
  new Pokemon(103, 'Jumpluff', ['Grass', 'Flying']),
  new Pokemon(441, 'Munchlax', ['Normal']),
  new Pokemon(458, 'Snorlax', ['Normal']),
  new Pokemon(226, 'Whismur', ['Normal']),
  new Pokemon(366, 'Loudred', ['Normal']),
  new Pokemon(367, 'Exploud', ['Normal']),
  new Pokemon(368, 'Meditite', ['Fighting', 'Psychic']),
  new Pokemon(223, 'Medicham', ['Fighting', 'Psychic']),
  new Pokemon(224, 'Zubat', ['Poison', 'Flying']),
  new Pokemon(222, 'Golbat', ['Poison', 'Flying']),
  new Pokemon(170, 'Chinchou', ['Water', 'Electric']),
  new Pokemon(171, 'Lanturn', ['Water', 'Electric']),
  new Pokemon(594, 'Alomomola', ['Water']),
  new Pokemon(131, 'Lapras', ['Water', 'Ice']),
  new Pokemon(144, 'Articuno', ['Ice', 'Flying']),
  new Pokemon(145, 'Zapdos', ['Electric', 'Flying']),
  new Pokemon(146, 'Moltres', ['Fire', 'Flying'])
]

var regions = ["The Central Kalos Pokédex", "The Coastal Kalos Pokédex", "The Mountain Kalos Pokédex"]
var ids = ["Central", "Coastal", "Mountain"]

function loadKalos() {
  $('#Center').text("The Kalos Pokémon List by Pokédex Number");
  $('#pokemon-container').empty();
  var j = 0;
  var regionCount = 153;
  for (var i = 0; i < regions.length; i++) {
    $(`#${ids[i]}`).append(`<span style="color: red;">${regions[i]}</span>`);
    for (j; j < regionCount; j++) {
      pokemonList[j].loadToPage();
      pokemonList[j].ShowTypes();
    }
    regionCount += 153;
  }
}
