/* eslint-disable no-unused-vars */
const moveList = [
  new Moves('TM01', 'Mega Punch', 'Normal'),
  new Moves('TM02', 'Razor Wind', 'Normal'),
  new Moves('TM03', 'Swords Dance', 'Normal'),
  new Moves('TM04', 'Whirlwind', 'Normal'),
  new Moves('TM05', 'Mega Kick', 'Normal'),
  new Moves('TM06', 'Toxic', 'Poison'),
  new Moves('TM07', 'Horn Drill', 'Normal'),
  new Moves('TM08', 'Body Slam', 'Normal'),
  new Moves('TM09', 'Take Down', 'Normal'),
  new Moves('TM10', 'Double-Edge', 'Normal'),
  new Moves('TM11', 'BubbleBeam', 'Water'),
  new Moves('TM12', 'Water Gun', 'Water'),
  new Moves('TM13', 'Ice Beam', 'Ice'),
  new Moves('TM14', 'Blizzard', 'Ice'),
  new Moves('TM15', 'Hyper Beam', 'Normal'),
  new Moves('TM16', 'Pay Day', 'Normal'),
  new Moves('TM17', 'Submission', 'Fighting'),
  new Moves('TM18', 'Counter', 'Fighting'),
  new Moves('TM19', 'Seismic Toss', 'Fighting'),
  new Moves('TM20', 'Rage', 'Normal'),
  new Moves('TM21', 'Mega Drain', 'Grass'),
  new Moves('TM22', 'Solar Beam', 'Grass'),
  new Moves('TM23', 'Dragon Rage', 'Dragon'),
  new Moves('TM24', 'Thunderbolt', 'Electric'),
  new Moves('TM25', 'Thunder', 'Electric'),
  new Moves('TM26', 'Earthquake', 'Ground'),
  new Moves('TM27', 'Fissure', 'Ground'),
  new Moves('TM28', 'Dig', 'Ground'),
  new Moves('TM29', 'Psychic', 'Psychic'),
  new Moves('TM30', 'Teleport', 'Psychic'),
  new Moves('TM31', 'Mimic', 'Normal'),
  new Moves('TM32', 'Double Team', 'Normal'),
  new Moves('TM33', 'Reflect', 'Psychic'),
  new Moves('TM34', 'Bide', 'Normal'),
  new Moves('TM35', 'Metronome', 'Normal'),
  new Moves('TM36', 'Selfdestruct', 'Normal'),
  new Moves('TM37', 'Egg Bomb', 'Normal'),
  new Moves('TM38', 'Fire Blast', 'Fire'),
  new Moves('TM39', 'Swift', 'Normal'),
  new Moves('TM40', 'Skull Bash', 'Normal'),
  new Moves('TM41', 'Softboiled', 'Normal'),
  new Moves('TM42', 'Dream Eater', 'Psychic'),
  new Moves('TM43', 'Sky Attack', 'Flying'),
  new Moves('TM44', 'Rest', 'Psychic'),
  new Moves('TM45', 'Thunder Wave', 'Electric'),
  new Moves('TM46', 'Psywave', 'Psychic'),
  new Moves('TM47', 'Explosion', 'Normal'),
  new Moves('TM48', 'Rock Slide', 'Rock'),
  new Moves('TM49', 'Tri Attack', 'Normal'),
  new Moves('TM50', 'Substitute', 'Normal'),
  new Moves('TM01', 'DynamicPunch', 'Fighting'),
  new Moves('TM02', 'Headbutt', 'Normal'),
  new Moves('TM03', 'Curse', 'Ghost'),
  new Moves('TM04', 'Rollout', 'Rock'),
  new Moves('TM05', 'Roar', 'Normal'),
  new Moves('TM06', 'Toxic', 'Poison'),
  new Moves('TM07', 'Zap Cannon', 'Electric'),
  new Moves('TM08', 'Rock Smash', 'Fighting'),
  new Moves('TM09', 'Psych Up', 'Normal'),
  new Moves('TM10', 'Hidden Power', 'Normal'),
  new Moves('TM11', 'Sunny Day', 'Fire'),
  new Moves('TM12', 'Sweet Scent', 'Normal'),
  new Moves('TM13', 'Snore', 'Normal'),
  new Moves('TM14', 'Blizzard', 'Ice'),
  new Moves('TM15', 'Hyper Beam', 'Normal'),
  new Moves('TM16', 'Icy Wind', 'Ice'),
  new Moves('TM17', 'Protect', 'Normal'),
  new Moves('TM18', 'Rain Dance', 'Water'),
  new Moves('TM19', 'Giga Drain', 'Grass'),
  new Moves('TM20', 'Endure', 'Normal'),
  new Moves('TM21', 'Frustration', 'Normal'),
  new Moves('TM22', 'Solar Beam', 'Grass'),
  new Moves('TM23', 'Iron Tail', 'Steel'),
  new Moves('TM24', 'DragonBreath', 'Dragon'),
  new Moves('TM25', 'Thunder', 'Electric'),
  new Moves('TM26', 'Earthquake', 'Ground'),
  new Moves('TM27', 'Return', 'Normal'),
  new Moves('TM28', 'Dig', 'Ground'),
  new Moves('TM29', 'Psychic', 'Psychic'),
  new Moves('TM30', 'Shadow Ball', 'Ghost'),
  new Moves('TM31', 'Mud-Slap', 'Ground'),
  new Moves('TM32', 'Double Team', 'Normal'),
  new Moves('TM33', 'Ice Punch', 'Ice'),
  new Moves('TM34', 'Swagger', 'Normal'),
  new Moves('TM35', 'Sleep Talk', 'Normal'),
  new Moves('TM36', 'Sludge Bomb', 'Poison'),
  new Moves('TM37', 'Sandstorm', 'Ground'),
  new Moves('TM38', 'Fire Blast', 'Fire'),
  new Moves('TM39', 'Swift', 'Normal'),
  new Moves('TM40', 'Defense Curl', 'Normal'),
  new Moves('TM41', 'ThunderPunch', 'Electric'),
  new Moves('TM42', 'Dream Eater', 'Psychic'),
  new Moves('TM43', 'Detect', 'Fighting'),
  new Moves('TM44', 'Rest', 'Psychic'),
  new Moves('TM45', 'Attract', 'Normal'),
  new Moves('TM46', 'Thief', 'Dark'),
  new Moves('TM47', 'Steel Wing', 'Steel'),
  new Moves('TM48', 'Fire Punch', 'Fire'),
  new Moves('TM49', 'Fury Cutter', 'Bug'),
  new Moves('TM50', 'Nightmare', 'Ghost'),
  new Moves('TM01', 'Focus Punch', 'Fighting'),
  new Moves('TM02', 'Dragon Claw', 'Dragon'),
  new Moves('TM03', 'Water Pulse', 'Water'),
  new Moves('TM04', 'Calm Mind', 'Psychic'),
  new Moves('TM05', 'Roar', 'Normal'),
  new Moves('TM06', 'Toxic', 'Poison'),
  new Moves('TM07', 'Hail', 'Ice'),
  new Moves('TM08', 'Bulk Up', 'Fighting'),
  new Moves('TM09', 'Bullet Seed', 'Grass'),
  new Moves('TM10', 'Hidden Power', 'Normal'),
  new Moves('TM11', 'Sunny Day', 'Fire'),
  new Moves('TM12', 'Taunt', 'Dark'),
  new Moves('TM13', 'Ice Beam', 'Ice'),
  new Moves('TM14', 'Blizzard', 'Ice'),
  new Moves('TM15', 'Hyper Beam', 'Normal'),
  new Moves('TM16', 'Light Screen', 'Psychic'),
  new Moves('TM17', 'Protect', 'Normal'),
  new Moves('TM18', 'Rain Dance', 'Water'),
  new Moves('TM19', 'Giga Drain', 'Grass'),
  new Moves('TM20', 'Safeguard', 'Normal'),
  new Moves('TM21', 'Frustration', 'Normal'),
  new Moves('TM22', 'Solar Beam', 'Grass'),
  new Moves('TM23', 'Iron Tail', 'Steel'),
  new Moves('TM24', 'Thunderbolt', 'Electric'),
  new Moves('TM25', 'Thunder', 'Electric'),
  new Moves('TM26', 'Earthquake', 'Ground'),
  new Moves('TM27', 'Return', 'Normal'),
  new Moves('TM28', 'Dig', 'Ground'),
  new Moves('TM29', 'Psychic', 'Psychic'),
  new Moves('TM30', 'Shadow Ball', 'Ghost'),
  new Moves('TM31', 'Brick Break', 'Fighting'),
  new Moves('TM32', 'Double Team', 'Normal'),
  new Moves('TM33', 'Reflect', 'Psychic'),
  new Moves('TM34', 'Shock Wave', 'Electric'),
  new Moves('TM35', 'Flamethrower', 'Fire'),
  new Moves('TM36', 'Sludge Bomb', 'Poison'),
  new Moves('TM37', 'Sandstorm', 'Ground'),
  new Moves('TM38', 'Fire Blast', 'Fire'),
  new Moves('TM39', 'Rock Tomb', 'Ground'),
  new Moves('TM40', 'Aerial Ace', 'Flying'),
  new Moves('TM41', 'Torment', 'Dark'),
  new Moves('TM42', 'Facade', 'Normal'),
  new Moves('TM43', 'Secret Power', 'Normal'),
  new Moves('TM44', 'Rest', 'Psychic'),
  new Moves('TM45', 'Attract', 'Normal'),
  new Moves('TM46', 'Theif', 'Dark'),
  new Moves('TM47', 'Steel Wing', 'Steel'),
  new Moves('TM48', 'Skill Swap', 'Psychic'),
  new Moves('TM49', 'Snatch', 'Dark'),
  new Moves('TM50', 'Overheat', 'Fire'),
  new Moves('TM01', 'Focus Punch', 'Fighting'),
  new Moves('TM02', 'Dragon Claw', 'Dragon'),
  new Moves('TM03', 'Water Pulse', 'Water'),
  new Moves('TM04', 'Calm Mind', 'Psychic'),
  new Moves('TM05', 'Roar', 'Normal'),
  new Moves('TM06', 'Toxic', 'Poison'),
  new Moves('TM07', 'Hail', 'Ice'),
  new Moves('TM08', 'Bulk Up', 'Fighting'),
  new Moves('TM09', 'Bullet Seed', 'Grass'),
  new Moves('TM10', 'Hidden Power', 'Normal'),
  new Moves('TM11', 'Sunny Day', 'Fire'),
  new Moves('TM12', 'Taunt', 'Dark'),
  new Moves('TM13', 'Ice Beam', 'Ice'),
  new Moves('TM14', 'Blizzard', 'Ice'),
  new Moves('TM15', 'Hyper Beam', 'Normal'),
  new Moves('TM16', 'Light Screen', 'Psychic'),
  new Moves('TM17', 'Protect', 'Normal'),
  new Moves('TM18', 'Rain Dance', 'Water'),
  new Moves('TM19', 'Giga Drain', 'Grass'),
  new Moves('TM20', 'Safeguard', 'Normal'),
  new Moves('TM21', 'Frustration', 'Normal'),
  new Moves('TM22', 'Solar Beam', 'Grass'),
  new Moves('TM23', 'Iron Tail', 'Steel'),
  new Moves('TM24', 'Thunderbolt', 'Electric'),
  new Moves('TM25', 'Thunder', 'Electric'),
  new Moves('TM26', 'Earthquake', 'Ground'),
  new Moves('TM27', 'Return', 'Normal'),
  new Moves('TM28', 'Dig', 'Ground'),
  new Moves('TM29', 'Psychic', 'Psychic'),
  new Moves('TM30', 'Shadow Ball', 'Ghost'),
  new Moves('TM31', 'Brick Break', 'Fighting'),
  new Moves('TM32', 'Double Team', 'Normal'),
  new Moves('TM33', 'Reflect', 'Psychic'),
  new Moves('TM34', 'Shock Wave', 'Electric'),
  new Moves('TM35', 'Flamethrower', 'Fire'),
  new Moves('TM36', 'Sludge Bomb', 'Poison'),
  new Moves('TM37', 'Sandstorm', 'Ground'),
  new Moves('TM38', 'Fire Blast', 'Fire'),
  new Moves('TM39', 'Rock Tomb', 'Rock'),
  new Moves('TM40', 'Aerial Ace', 'Flying'),
  new Moves('TM41', 'Torment', 'Dark'),
  new Moves('TM42', 'Facade', 'Normal'),
  new Moves('TM43', 'Secret Power', 'Normal'),
  new Moves('TM44', 'Rest', 'Psychic'),
  new Moves('TM45', 'Attract', 'Normal'),
  new Moves('TM46', 'Thief', 'Dark'),
  new Moves('TM47', 'Steel Wing', 'Steel'),
  new Moves('TM48', 'Skill Swap', 'Psychic'),
  new Moves('TM49', 'Snatch', 'Dark'),
  new Moves('TM50', 'Overheat', 'Fire'),
  new Moves('TM51', 'Roost', 'Flying'),
  new Moves('TM52', 'Focus Blast', 'Fighting'),
  new Moves('TM53', 'Energy Ball', 'Grass'),
  new Moves('TM54', 'False Swipe', 'Normal'),
  new Moves('TM55', 'Brine', 'Water'),
  new Moves('TM56', 'Fling', 'Dark'),
  new Moves('TM57', 'Charge Beam', 'Electric'),
  new Moves('TM58', 'Endure', 'Normal'),
  new Moves('TM59', 'Dragon Pulse', 'Dragon'),
  new Moves('TM60', 'Drain Punch', 'Fighting'),
  new Moves('TM61', 'Will-O-Wisp', 'Fire'),
  new Moves('TM62', 'Silver Wind', 'Bug'),
  new Moves('TM63', 'Embargo', 'Dark'),
  new Moves('TM64', 'Explosion', 'Normal'),
  new Moves('TM65', 'Shadow Claw', 'Ghost'),
  new Moves('TM66', 'Payback', 'Dark'),
  new Moves('TM67', 'Recycle', 'Normal'),
  new Moves('TM68', 'Giga Impact', 'Normal'),
  new Moves('TM69', 'Rock Polish', 'Rock'),
  new Moves('TM70', 'Flash', 'Normal'),
  new Moves('TM71', 'Stone Edge', 'Rock'),
  new Moves('TM72', 'Avalanche', 'Ice'),
  new Moves('TM73', 'Thunder Wave', 'Electric'),
  new Moves('TM74', 'Gyro Ball', 'Steel'),
  new Moves('TM75', 'Swords Dance', 'Normal'),
  new Moves('TM76', 'Stealth Rock', 'Rock'),
  new Moves('TM77', 'Psych Up', 'Normal'),
  new Moves('TM78', 'Captivate', 'Normal'),
  new Moves('TM79', 'Dark Pulse', 'Dark'),
  new Moves('TM80', 'Rock Slide', 'Rock'),
  new Moves('TM81', 'X-Scissor', 'Bug'),
  new Moves('TM82', 'Sleep Talk', 'Normal'),
  new Moves('TM83', 'Natural Gift', 'Normal'),
  new Moves('TM84', 'Poison Jab', 'Poison'),
  new Moves('TM85', 'Dream Eater', 'Psychic'),
  new Moves('TM86', 'Grass Knot', 'Grass'),
  new Moves('TM87', 'Swagger', 'Normal'),
  new Moves('TM88', 'Pluck', 'Flying'),
  new Moves('TM89', 'U-Turn', 'Bug'),
  new Moves('TM90', 'Substitute', 'Normal'),
  new Moves('TM91', 'Flash Cannon', 'Steel'),
  new Moves('TM92', 'Trick Room', 'Psychic'),
  new Moves('TM01', 'Hone Claws', 'Dark'),
  new Moves('TM02', 'Dragon Claw', 'Dragon'),
  new Moves('TM03', 'Psyshock', 'Psychic'),
  new Moves('TM04', 'Calm Mind', 'Psychic'),
  new Moves('TM05', 'Roar', 'Normal'),
  new Moves('TM06', 'Toxic', 'Poison'),
  new Moves('TM07', 'Hail', 'Ice'),
  new Moves('TM08', 'Bulk Up', 'Fighting'),
  new Moves('TM09', 'Venoshock', 'Poison'),
  new Moves('TM10', 'Hidden Power', 'Normal'),
  new Moves('TM11', 'Sunny Day', 'Fire'),
  new Moves('TM12', 'Taunt', 'Dark'),
  new Moves('TM13', 'Ice Beam', 'Ice'),
  new Moves('TM14', 'Blizzard', 'Ice'),
  new Moves('TM15', 'Hyper Beam', 'Normal'),
  new Moves('TM16', 'Light Screen', 'Psychic'),
  new Moves('TM17', 'Protect', 'Normal'),
  new Moves('TM18', 'Rain Dance', 'Water'),
  new Moves('TM19', 'Telekinesis', 'Psychic'),
  new Moves('TM20', 'Safeguard', 'Normal'),
  new Moves('TM21', 'Frustration', 'Normal'),
  new Moves('TM22', 'Solar Beam', 'Grass'),
  new Moves('TM23', 'Smack Down', 'Rock'),
  new Moves('TM24', 'Thunderbolt', 'Electric'),
  new Moves('TM25', 'Thunder', 'Electric'),
  new Moves('TM26', 'Earthquake', 'Ground'),
  new Moves('TM27', 'Return', 'Normal'),
  new Moves('TM28', 'Dig', 'Ground'),
  new Moves('TM29', 'Psychic', 'Psychic'),
  new Moves('TM30', 'Shadow Ball', 'Ghost'),
  new Moves('TM31', 'Brick Break', 'Fighting'),
  new Moves('TM32', 'Double Team', 'Normal'),
  new Moves('TM33', 'Reflect', 'Psychic'),
  new Moves('TM34', 'Sludge Wave', 'Poison'),
  new Moves('TM35', 'Flamethrower', 'Fire'),
  new Moves('TM36', 'Sludge Bomb', 'Poison'),
  new Moves('TM37', 'Sandstorm', 'Ground'),
  new Moves('TM38', 'Fire Blast', 'Fire'),
  new Moves('TM39', 'Rock Tomb', 'Rock'),
  new Moves('TM40', 'Aerial Ace', 'Flying'),
  new Moves('TM41', 'Torment', 'Dark'),
  new Moves('TM42', 'Facade', 'Normal'),
  new Moves('TM43', 'Flame Charge', 'Fire'),
  new Moves('TM44', 'Rest', 'Psychic'),
  new Moves('TM45', 'Attract', 'Normal'),
  new Moves('TM46', 'Thief', 'Dark'),
  new Moves('TM47', 'Low Sweep', 'Fighting'),
  new Moves('TM48', 'Round', 'Normal'),
  new Moves('TM49', 'Echoed Voice', 'Normal'),
  new Moves('TM50', 'Overheat', 'Fire'),
  new Moves('TM51', 'Ally Switch', 'Psychic'),
  new Moves('TM52', 'Focus Blast', 'Fighting'),
  new Moves('TM53', 'Energy Ball', 'Grass'),
  new Moves('TM54', 'False Swipe', 'Normal'),
  new Moves('TM55', 'Scald', 'Water'),
  new Moves('TM56', 'Fling', 'Dark'),
  new Moves('TM57', 'Charge Beam', 'Electric'),
  new Moves('TM58', 'Sky Drop', 'Flying'),
  new Moves('TM59', 'Incinerate', 'Fire'),
  new Moves('TM60', 'Quash', 'Dark'),
  new Moves('TM61', 'Will-O-Wisp', 'Fire'),
  new Moves('TM62', 'Acrobatics', 'Flying'),
  new Moves('TM63', 'Embargo', 'Dark'),
  new Moves('TM64', 'Explosion', 'Normal'),
  new Moves('TM65', 'Shadow Claw', 'Ghost'),
  new Moves('TM66', 'Payback', 'Dark'),
  new Moves('TM67', 'Retaliate', 'Normal'),
  new Moves('TM68', 'Giga Impact', 'Normal'),
  new Moves('TM69', 'Rock Polish', 'Rock'),
  new Moves('TM70', 'Flash', 'Normal'),
  new Moves('TM71', 'Stone Edge', 'Rock'),
  new Moves('TM72', 'Volt Switch', 'Electric'),
  new Moves('TM73', 'Thunder Wave', 'Electric'),
  new Moves('TM74', 'Gyro Ball', 'Steel'),
  new Moves('TM75', 'Swords Dance', 'Normal'),
  new Moves('TM76', 'Struggle Bug', 'Bug'),
  new Moves('TM77', 'Psych Up', 'Normal'),
  new Moves('TM78', 'Bulldoze', 'Ground'),
  new Moves('TM79', 'Frost Breath', 'Ice'),
  new Moves('TM80', 'Rock Slide', 'Rock'),
  new Moves('TM81', 'X-Scissor', 'Bug'),
  new Moves('TM82', 'Dragon Tail', 'Dragon'),
  new Moves('TM83', 'Work Up', 'Normal'),
  new Moves('TM84', 'Poison Jab', 'Poison'),
  new Moves('TM85', 'Dream Eater', 'Psychic'),
  new Moves('TM86', 'Grass Knot', 'Grass'),
  new Moves('TM87', 'Swagger', 'Normal'),
  new Moves('TM88', 'Pluck', 'Flying'),
  new Moves('TM89', 'U-Turn', 'Bug'),
  new Moves('TM90', 'Substitute', 'Normal'),
  new Moves('TM91', 'Flash Cannon', 'Steel'),
  new Moves('TM92', 'Trick Room', 'Psychic'),
  new Moves('TM93', 'Wild Charge', 'Electric'),
  new Moves('TM94', 'Rock Smash', 'Fighting'),
  new Moves('TM95', 'Snarl', 'Dark'),
  new Moves('TM01', 'Hone Claws', 'Dark'),
  new Moves('TM02', 'Dragon Claw', 'Dragon'),
  new Moves('TM03', 'Psyshock', 'Psychic'),
  new Moves('TM04', 'Calm Mind', 'Psychic'),
  new Moves('TM05', 'Roar', 'Normal'),
  new Moves('TM06', 'Toxic', 'Poison'),
  new Moves('TM07', 'Hail', 'Ice'),
  new Moves('TM08', 'Bulk Up', 'Fighting'),
  new Moves('TM09', 'Venoshock', 'Poison'),
  new Moves('TM10', 'Hidden Power', 'Normal'),
  new Moves('TM11', 'Sunny Day', 'Fire'),
  new Moves('TM12', 'Taunt', 'Dark'),
  new Moves('TM13', 'Ice Beam', 'Ice'),
  new Moves('TM14', 'Blizzard', 'Ice'),
  new Moves('TM15', 'Hyper Beam', 'Normal'),
  new Moves('TM16', 'Light Screen', 'Psychic'),
  new Moves('TM17', 'Protect', 'Normal'),
  new Moves('TM18', 'Rain Dance', 'Water'),
  new Moves('TM19', 'Roost', 'Flying'),
  new Moves('TM20', 'Safeguard', 'Normal'),
  new Moves('TM21', 'Frustration', 'Normal'),
  new Moves('TM22', 'Solar Beam', 'Grass'),
  new Moves('TM23', 'Smack Down', 'Rock'),
  new Moves('TM24', 'Thunderbolt', 'Electric'),
  new Moves('TM25', 'Thunder', 'Electric'),
  new Moves('TM26', 'Earthquake', 'Ground'),
  new Moves('TM27', 'Return', 'Normal'),
  new Moves('TM28', 'Dig', 'Ground'),
  new Moves('TM29', 'Psychic', 'Psychic'),
  new Moves('TM30', 'Shadow Ball', 'Ghost'),
  new Moves('TM31', 'Brick Break', 'Fighting'),
  new Moves('TM32', 'Double Team', 'Normal'),
  new Moves('TM33', 'Reflect', 'Psychic'),
  new Moves('TM34', 'Sludge Wave', 'Poison'),
  new Moves('TM35', 'Flamethrower', 'Fire'),
  new Moves('TM36', 'Sludge Bomb', 'Poison'),
  new Moves('TM37', 'Sandstorm', 'Ground'),
  new Moves('TM38', 'Fire Blast', 'Fire'),
  new Moves('TM39', 'Rock Tomb', 'Rock'),
  new Moves('TM40', 'Aerial Ace', 'Flying'),
  new Moves('TM41', 'Torment', 'Dark'),
  new Moves('TM42', 'Facade', 'Normal'),
  new Moves('TM43', 'Flame Charge', 'Fire'),
  new Moves('TM44', 'Rest', 'Psychic'),
  new Moves('TM45', 'Attract', 'Normal'),
  new Moves('TM46', 'Thief', 'Dark'),
  new Moves('TM47', 'Low Sweep', 'Fighting'),
  new Moves('TM48', 'Round', 'Normal'),
  new Moves('TM49', 'Echoed Voice', 'Normal'),
  new Moves('TM50', 'Overheat', 'Fire'),
  new Moves('TM51', 'Steel Wing', 'Steel'),
  new Moves('TM52', 'Focus Blast', 'Fighting'),
  new Moves('TM53', 'Energy Ball', 'Grass'),
  new Moves('TM54', 'False Swipe', 'Normal'),
  new Moves('TM55', 'Scald', 'Water'),
  new Moves('TM56', 'Fling', 'Dark'),
  new Moves('TM57', 'Charge Beam', 'Electric'),
  new Moves('TM58', 'Sky Drop', 'Flying'),
  new Moves('TM59', 'Incinerate', 'Fire'),
  new Moves('TM60', 'Quash', 'Dark'),
  new Moves('TM61', 'Will-O-Wisp', 'Fire'),
  new Moves('TM62', 'Acrobatics', 'Flying'),
  new Moves('TM63', 'Embargo', 'Dark'),
  new Moves('TM64', 'Explosion', 'Normal'),
  new Moves('TM65', 'Shadow Claw', 'Ghost'),
  new Moves('TM66', 'Payback', 'Dark'),
  new Moves('TM67', 'Retaliate', 'Normal'),
  new Moves('TM68', 'Giga Impact', 'Normal'),
  new Moves('TM69', 'Rock Polish', 'Rock'),
  new Moves('TM70', 'Flash', 'Normal'),
  new Moves('TM71', 'Stone Edge', 'Rock'),
  new Moves('TM72', 'Volt Switch', 'Electric'),
  new Moves('TM73', 'Thunder Wave', 'Electric'),
  new Moves('TM74', 'Gyro Ball', 'Steel'),
  new Moves('TM75', 'Swords Dance', 'Normal'),
  new Moves('TM76', 'Struggle Bug', 'Bug'),
  new Moves('TM77', 'Psych Up', 'Normal'),
  new Moves('TM78', 'Bulldoze', 'Ground'),
  new Moves('TM79', 'Frost Breath', 'Ice'),
  new Moves('TM80', 'Rock Slide', 'Rock'),
  new Moves('TM81', 'X-Scissor', 'Bug'),
  new Moves('TM82', 'Dragon Tail', 'Dragon'),
  new Moves('TM83', 'Infestation', 'Bug'),
  new Moves('TM84', 'Poison Jab', 'Poison'),
  new Moves('TM85', 'Dream Eater', 'Psychic'),
  new Moves('TM86', 'Grass Knot', 'Grass'),
  new Moves('TM87', 'Swagger', 'Normal'),
  new Moves('TM88', 'Sleep Talk', 'Normal'),
  new Moves('TM89', 'U-Turn', 'Bug'),
  new Moves('TM90', 'Substitute', 'Normal'),
  new Moves('TM91', 'Flash Cannon', 'Steel'),
  new Moves('TM92', 'Trick Room', 'Psychic'),
  new Moves('TM93', 'Wild Charge', 'Electric'),
  new Moves('TM94', ['Rock Smash', 'Secret Power'], ['Fighting', 'Normal']),
  new Moves('TM95', 'Snarl', 'Dark'),
  new Moves('TM96', 'Nature Power', 'Normal'),
  new Moves('TM97', 'Dark Pulse', 'Dark'),
  new Moves('TM98', 'Power-Up Punch', 'Fighting'),
  new Moves('TM99', 'Dazzling Gleam', 'Fairy'),
  new Moves('TM100', 'Confide', 'Normal'),
  new Moves('TM01', ['Work Up', 'Headbutt'], ['Normal', 'Normal']),
  new Moves('TM02', ['Dragon Claw', 'Taunt'], ['Dragon', 'Dark']),
  new Moves('TM03', ['Psyshock', 'Helping Hand'], ['Psychic', 'Normal']),
  new Moves('TM04', ['Calm Mind', 'Teleport'], ['Psychic', 'Psychic']),
  new Moves('TM05', ['Roar', 'Rest'], ['Normal', 'Psychic']),
  new Moves('TM06', ['Toxic', 'Light Screen'], ['Poison', 'Psychic']),
  new Moves('TM07', ['Hail', 'Protect'], ['Ice', 'Normal']),
  new Moves('TM08', ['Bulk Up', 'Substitute'], ['Fighting', 'Normal']),
  new Moves('TM09', ['Venoshock', 'Reflect'], ['Poison', 'Psychic']),
  new Moves('TM10', ['Hidden Power', 'Dig'], ['Normal', 'Ground']),
  new Moves('TM11', ['Sunny Day', 'Will-O-Wisp'], ['Fire', 'Fire']),
  new Moves('TM12', ['Taunt', 'Facade'], ['Dark', 'Normal']),
  new Moves('TM13', ['Ice Beam', 'Brick Break'], ['Ice', 'Fighting']),
  new Moves('TM14', ['Blizzard', 'Fly'], ['Ice', 'Flying']),
  new Moves('TM15', ['Hyper Beam', 'Seismic Toss'], ['Normal', 'Fighting']),
  new Moves('TM16', ['Light Screen', 'Thunder Wave'], ['Psychic', 'Electric']),
  new Moves('TM17', ['Protect', 'Dragon Tail'], ['Normal', 'Dragon']),
  new Moves('TM18', ['Rain Dance', 'U-Turn'], ['Water', 'Bug']),
  new Moves('TM19', ['Roost', 'Iron Tail'], ['Flying', 'Steel']),
  new Moves('TM20', ['Safeguard', 'Dark Pulse'], ['Normal', 'Dark']),
  new Moves('TM21', ['Frustration', 'Foul Play'], ['Normal', 'Dark']),
  new Moves('TM22', ['Solar Beam', 'Rock Slide'], ['Grass', 'Rock']),
  new Moves('TM23', ['Smack Down', 'Thunder Punch'], ['Rock', 'Electric']),
  new Moves('TM24', ['Thunderbolt', 'X-Scissor'], ['Electric', 'Bug']),
  new Moves('TM25', ['Thunder', 'Waterfall'], ['Electric', 'Water']),
  new Moves('TM26', ['Earthquake', 'Poison Jab'], ['Ground', 'Poison']),
  new Moves('TM27', ['Return', 'Toxic'], ['Normal', 'Poison']),
  new Moves('TM28', ['Leech Life', 'Tri Attack'], ['Bug', 'Normal']),
  new Moves('TM29', ['Psychic', 'Scald'], ['Psychic', 'Water']),
  new Moves('TM30', ['Shadow Ball', 'Bulk Up'], ['Ghost', 'Fighting']),
  new Moves('TM31', ['Brick Break', 'Fire Punch'], ['Fighting', 'Fire']),
  new Moves('TM32', ['Double Team', 'Dazzling Gleam'], ['Normal', 'Fairy']),
  new Moves('TM33', ['Reflect', 'Calm Mind'], ['Psychic', 'Psychic']),
  new Moves('TM34', ['Sludge Wave', 'Dragon Pulse'], ['Poison', 'Dragon']),
  new Moves('TM35', ['Flamethrower', 'Ice Punch'], ['Fire', 'Ice']),
  new Moves('TM36', ['Sludge Bomb', 'Thunderbolt'], ['Poison', 'Electric']),
  new Moves('TM37', ['Sandstorm', 'Flamethrower'], ['Ground', 'Fire']),
  new Moves('TM38', ['Fire Blast', 'Thunder'], ['Fire', 'Electric']),
  new Moves('TM39', ['Rock Tomb', 'Outrage'], ['Rock', 'Dragon']),
  new Moves('TM40', ['Aerial Ace', 'Psychic'], ['Flying', 'Psychic']),
  new Moves('TM41', ['Torment', 'Earthquake'], ['Dark', 'Ground']),
  new Moves('TM42', ['Facade', 'Self-Destruct'], ['Normal', 'Normal']),
  new Moves('TM43', ['Flame Charge', 'Shadow Ball'], ['Fire', 'Ghost']),
  new Moves('TM44', ['Rest', 'Play Rough'], ['Psychic', 'Fairy']),
  new Moves('TM45', ['Attract', 'Solar Beam'], ['Normal', 'Grass']),
  new Moves('TM46', ['Thief', 'Fire Blast'], ['Dark', 'Fire']),
  new Moves('TM47', ['Low Sweep', 'Surf'], ['Fighting', 'Water']),
  new Moves('TM48', ['Round', 'Hyper Beam'], ['Normal', 'Normal']),
  new Moves('TM49', ['Echoed Voice', 'Superpower'], ['Normal', 'Fighting']),
  new Moves('TM50', ['Overheat', 'Roost'], ['Fire', 'Flying']),
  new Moves('TM51', ['Steel Wing', 'Blizzard'], ['Steel', 'Ice']),
  new Moves('TM52', ['Focus Blast', 'Sludge Bomb'], ['Fighting', 'Poison']),
  new Moves('TM53', ['Energy Ball', 'Mega Drain'], ['Grass', 'Grass']),
  new Moves('TM54', ['False Swipe', 'Flash Cannon'], ['Normal', 'Steel']),
  new Moves('TM55', ['Scald', 'Ice Beam'], ['Water', 'Ice']),
  new Moves('TM56', ['Fling', 'Stealth Rock'], ['Dark', 'Rock']),
  new Moves('TM57', ['Charge Beam', 'Payday'], ['Electric', 'Normal']),
  new Moves('TM58', ['Sky Drop', 'Drill Run'], ['Flying', 'Ground']),
  new Moves('TM59', ['Brutal Swing', 'Dream Eater'], ['Dark', 'Psychic']),
  new Moves('TM60', ['Quash', 'Megahorn'], ['Dark', 'Bug']),
  new Moves('TM61', 'Will-O-Wisp', 'Fire'),
  new Moves('TM62', 'Acrobatics', 'Flying'),
  new Moves('TM63', 'Embargo', 'Dark'),
  new Moves('TM64', 'Explosion', 'Normal'),
  new Moves('TM65', 'Shadow Claw', 'Ghost'),
  new Moves('TM66', 'Payback', 'Dark'),
  new Moves('TM67', 'Smart Strike', 'Steel'),
  new Moves('TM68', 'Giga Impact', 'Normal'),
  new Moves('TM69', 'Rock Polish', 'Rock'),
  new Moves('TM70', 'Aurora Veil', 'Ice'),
  new Moves('TM71', 'Stone Edge', 'Rock'),
  new Moves('TM72', 'Volt Switch', 'Electric'),
  new Moves('TM73', 'Thunder Wave', 'Electric'),
  new Moves('TM74', 'Gyro Ball', 'Steel'),
  new Moves('TM75', 'Swords Dance', 'Normal'),
  new Moves('TM76', 'Fly', 'Flying'),
  new Moves('TM77', 'Psych Up', 'Normal'),
  new Moves('TM78', 'Bulldoze', 'Ground'),
  new Moves('TM79', 'Frost Breath', 'Ice'),
  new Moves('TM80', 'Rock Slide', 'Rock'),
  new Moves('TM81', 'X-Scissor', 'Bug'),
  new Moves('TM82', 'Dragon Tail', 'Dragon'),
  new Moves('TM83', 'Infestation', 'Bug'),
  new Moves('TM84', 'Poison Jab', 'Poison'),
  new Moves('TM85', 'Dream Eater', 'Psychic'),
  new Moves('TM86', 'Grass Knot', 'Grass'),
  new Moves('TM87', 'Swagger', 'Normal'),
  new Moves('TM88', 'Sleep Talk', 'Normal'),
  new Moves('TM89', 'U-Turn', 'Bug'),
  new Moves('TM90', 'Substitute', 'Normal'),
  new Moves('TM91', 'Flash Cannon', 'Steel'),
  new Moves('TM92', 'Trick Room', 'Psychic'),
  new Moves('TM93', 'Wild Charge', 'Electric'),
  new Moves('TM94', 'Surf', 'Water'),
  new Moves('TM95', 'Snarl', 'Dark'),
  new Moves('TM96', 'Nature Power', 'Normal'),
  new Moves('TM97', 'Dark Pulse', 'Dark'),
  new Moves('TM98', 'Waterfall', 'Water'),
  new Moves('TM99', 'Dazzling Gleam', 'Fairy'),
  new Moves('TM100', 'Confide', 'Normal'),
];

const ids = ['Gen1', 'Gen2', 'Gen3', 'Gen4', 'Gen5', 'Gen6', 'Gen7'];
const moves = [50, 50, 50, 92, 95, 100, 100];
let counter = 0;

function loadMoves() {
  counter = 0;

  $('#Center').text('Pokémon Move List');
  $('#myInput').val('',);
  $('#moves-container').empty().append(`<div id="ids1" style="width: 100%;"><h4 class="KalosTextStyle">
  Gen 1 Moves</h4><span class="container d-flex justify-content-around flex-wrap" id="Gen1"></span></div><div id="ids2" style="width: 100%;">
  <h4 class="KalosTextStyle">Gen 2 Moves</h4><span class="container d-flex justify-content-around flex-wrap" id="Gen2"></span></div>
  <div id="ids3" style="width: 100%;"><h4 class="KalosTextStyle">Gen 3 Moves</h4><span class="container d-flex justify-content-around flex-wrap" id="Gen3">
  </span></div><div id="ids4" style="width: 100%;"><h4 class="KalosTextStyle">Gen 4 Moves</h4><span class="container d-flex justify-content-around flex-wrap" id="Gen4">
  </span></div><div id="ids5" style="width: 100%;"><h4 class="KalosTextStyle">Gen 5 Moves</h4><span class="container d-flex justify-content-around flex-wrap" id="Gen5">
  </span></div><div id="ids6" style="width: 100%;"><h4 class="KalosTextStyle">Gen 6 Moves</h4><span class="container d-flex justify-content-around flex-wrap" id="Gen6">
  </span></div><div id="ids7" style="width: 100%;"><h4 class="KalosTextStyle">Gen 7 Moves</h4><span class="container d-flex justify-content-around flex-wrap" id="Gen7">
  </span></div>`);

  for (let j = 0; j < ids.length; j++) {
    $('#' + ids[j]).append(`<div class="container mt-4"><div class="row"><div class="col-md-5"><h4 class="KalosTextStyle">Name</h4></div><div class="col-md-3">
    <h4 style="font-style: italic; text-align: center;" class="pr-3">TM</h4></div><div class="col-md-3"><h4 style="font-style: italic; text-align: center;" class="pr-3">
    Type</h4></div></div>`);
    for (let i = counter; i < moves[j] + counter; i++) {
      moveList[i].loadMovesToPage(ids[j]);
    }

    counter += moves[j];
  }
}
