/* eslint-disable no-unused-vars */
const pokemonList = [
  new Pokemon(1, 'Bulbasaur', ['Grass', 'Poison']),
  new Pokemon(2, 'Ivysaur', ['Grass', 'Poison']),
  new Pokemon(3, 'Venusaur', ['Grass', 'Poison']),
  new Pokemon(4, 'Charmander', ['Fire']),
  new Pokemon(5, 'Charmeleon', ['Fire']),
  new Pokemon(6, 'Charizard', ['Fire', 'Flying']),
  new Pokemon(7, 'Squirtle', ['Water']),
  new Pokemon(8, 'Wartortle', ['Water']),
  new Pokemon(9, 'Blastoise', ['Water']),
  new Pokemon(10, 'Caterpie', ['Bug']),
  new Pokemon(11, 'Metapod', ['Bug']),
  new Pokemon(12, 'Butterfree', ['Bug', 'Flying']),
  new Pokemon(13, 'Weedle', ['Bug', 'Poison']),
  new Pokemon(14, 'Kakuna', ['Bug', 'Poison']),
  new Pokemon(15, 'Beedrill', ['Bug', 'Poison']),
  new Pokemon(16, 'Pidgey', ['Normal', 'Flying']),
  new Pokemon(17, 'Pidgeotto', ['Normal', 'Flying']),
  new Pokemon(18, 'Pidgeot', ['Normal', 'Flying']),
  new Pokemon(19, 'Rattata', ['Normal']),
  new Pokemon(20, 'Raticate', ['Normal']),
  new Pokemon(21, 'Spearow', ['Normal', 'Flying']),
  new Pokemon(22, 'Fearow', ['Normal', 'Flying']),
  new Pokemon(23, 'Ekans', ['Poison']),
  new Pokemon(24, 'Arbok', ['Poison']),
  new Pokemon(25, 'Pikachu', ['Electric']),
  new Pokemon(26, 'Raichu', ['Electric']),
  new Pokemon(27, 'Sandshrew', ['Ground']),
  new Pokemon(28, 'Sandslash', ['Ground']),
  new Pokemon(29, 'Nidoran♀', ['Poison']),
  new Pokemon(30, 'Nidorina', ['Poison']),
  new Pokemon(31, 'Nidoqueen', ['Poison', 'Ground']),
  new Pokemon(32, 'Nidoran♂', ['Poison']),
  new Pokemon(33, 'Nidorino', ['Poison']),
  new Pokemon(34, 'Nidoking', ['Poison', 'Ground']),
  new Pokemon(35, 'Clefairy', ['Normal']),
  new Pokemon(36, 'Clefable', ['Normal']),
  new Pokemon(37, 'Vulpix', ['Fire']),
  new Pokemon(38, 'Ninetales', ['Fire']),
  new Pokemon(39, 'Jigglypuff', ['Normal']),
  new Pokemon(40, 'Wigglytuff', ['Normal']),
  new Pokemon(41, 'Zubat', ['Poison', 'Flying']),
  new Pokemon(42, 'Golbat', ['Poison', 'Flying']),
  new Pokemon(43, 'Oddish', ['Grass', 'Poison']),
  new Pokemon(44, 'Gloom', ['Grass', 'Poison']),
  new Pokemon(45, 'Vileplume', ['Grass', 'Poison']),
  new Pokemon(46, 'Paras', ['Bug', 'Grass']),
  new Pokemon(47, 'Parasect', ['Bug', 'Grass']),
  new Pokemon(48, 'Venonat', ['Bug', 'Poison']),
  new Pokemon(49, 'Venomoth', ['Bug', 'Poison']),
  new Pokemon(50, 'Diglett', ['Ground']),
  new Pokemon(51, 'Dugtrio', ['Ground']),
  new Pokemon(52, 'Meowth', ['Normal']),
  new Pokemon(53, 'Persian', ['Normal']),
  new Pokemon(54, 'Psyduck', ['Water']),
  new Pokemon(55, 'Golduck', ['Water']),
  new Pokemon(56, 'Mankey', ['Fighting']),
  new Pokemon(57, 'Primeape', ['Fighting']),
  new Pokemon(58, 'Growlithe', ['Fire']),
  new Pokemon(59, 'Arcanine', ['Fire']),
  new Pokemon(60, 'Poliwag', ['Water']),
  new Pokemon(61, 'Poliwhirl', ['Water']),
  new Pokemon(62, 'Poliwrath', ['Water', 'Fighting']),
  new Pokemon(63, 'Abra', ['Psychic']),
  new Pokemon(64, 'Kadabra', ['Psychic']),
  new Pokemon(65, 'Alakazam', ['Psychic']),
  new Pokemon(66, 'Machop', ['Fighting']),
  new Pokemon(67, 'Machoke', ['Fighting']),
  new Pokemon(68, 'Machamp', ['Fighting']),
  new Pokemon(69, 'Bellsprout', ['Grass', 'Poison']),
  new Pokemon(70, 'Weepinbell', ['Grass', 'Poison']),
  new Pokemon(71, 'Victreebel', ['Grass', 'Poison']),
  new Pokemon(72, 'Tentacool', ['Water', 'Poison']),
  new Pokemon(73, 'Tentacruel', ['Water', 'Poison']),
  new Pokemon(74, 'Geodude', ['Rock', 'Ground']),
  new Pokemon(75, 'Graveler', ['Rock', 'Ground']),
  new Pokemon(76, 'Golem', ['Rock', 'Ground']),
  new Pokemon(77, 'Ponyta', ['Fire']),
  new Pokemon(78, 'Rapidash', ['Fire']),
  new Pokemon(79, 'Slowpoke', ['Water', 'Psychic']),
  new Pokemon(80, 'Slowbro', ['Water', 'Psychic']),
  new Pokemon(81, 'Magnemite', ['Electric', 'Steel']),
  new Pokemon(82, 'Magneton', ['Electric', 'Steel']),
  new Pokemon(83, 'Farfetch' + '\'' + 'd', ['Normal', 'Flying']),
  new Pokemon(84, 'Doduo', ['Normal', 'Flying']),
  new Pokemon(85, 'Dodrio', ['Normal', 'Flying']),
  new Pokemon(86, 'Seel', ['Water']),
  new Pokemon(87, 'Dewgong', ['Water', 'Ice']),
  new Pokemon(88, 'Grimer', ['Poison']),
  new Pokemon(89, 'Muk', ['Poison']),
  new Pokemon(90, 'Shellder', ['Water']),
  new Pokemon(91, 'Cloyster', ['Water', 'Ice']),
  new Pokemon(92, 'Gastly', ['Ghost', 'Poison']),
  new Pokemon(93, 'Haunter', ['Ghost', 'Poison']),
  new Pokemon(94, 'Gengar', ['Ghost', 'Poison']),
  new Pokemon(95, 'Onix', ['Rock', 'Ground']),
  new Pokemon(96, 'Drowzee', ['Psychic']),
  new Pokemon(97, 'Hypno', ['Psychic']),
  new Pokemon(98, 'Krabby', ['Water']),
  new Pokemon(99, 'Kingler', ['Water']),
  new Pokemon(100, 'Voltorb', ['Electric']),
  new Pokemon(101, 'Electrode', ['Electric']),
  new Pokemon(102, 'Exeggcute', ['Grass', 'Psychic']),
  new Pokemon(103, 'Exeggutor', ['Grass', 'Psychic']),
  new Pokemon(104, 'Cubone', ['Ground']),
  new Pokemon(105, 'Marowak', ['Ground']),
  new Pokemon(106, 'Hitmonlee', ['Fighting']),
  new Pokemon(107, 'Hitmonchan', ['Fighting']),
  new Pokemon(108, 'Lickitung', ['Normal']),
  new Pokemon(109, 'Koffing', ['Poison']),
  new Pokemon(110, 'Weezing', ['Poison']),
  new Pokemon(111, 'Rhyhorn', ['Ground', 'Rock']),
  new Pokemon(112, 'Rhydon', ['Ground', 'Rock']),
  new Pokemon(113, 'Chansey', ['Normal']),
  new Pokemon(114, 'Tangela', ['Grass']),
  new Pokemon(115, 'Kangaskhan', ['Normal']),
  new Pokemon(116, 'Horsea', ['Water']),
  new Pokemon(117, 'Seadra', ['Water']),
  new Pokemon(118, 'Goldeen', ['Water']),
  new Pokemon(119, 'Seaking', ['Water']),
  new Pokemon(120, 'Staryu', ['Water']),
  new Pokemon(121, 'Starmie', ['Water', 'Psychic']),
  new Pokemon(122, 'Mr. Mime', ['Psychic']),
  new Pokemon(123, 'Scyther', ['Bug', 'Flying']),
  new Pokemon(124, 'Jynx', ['Ice', 'Psychic']),
  new Pokemon(125, 'Electabuzz', ['Electric']),
  new Pokemon(126, 'Magmar', ['Fire']),
  new Pokemon(127, 'Pinsir', ['Bug']),
  new Pokemon(128, 'Tauros', ['Normal']),
  new Pokemon(129, 'Magikarp', ['Water']),
  new Pokemon(130, 'Gyarados', ['Water', 'Flying']),
  new Pokemon(131, 'Lapras', ['Water', 'Ice']),
  new Pokemon(132, 'Ditto', ['Normal']),
  new Pokemon(133, 'Eevee', ['Normal']),
  new Pokemon(134, 'Vaporeon', ['Water']),
  new Pokemon(135, 'Jolteon', ['Electric']),
  new Pokemon(136, 'Flareon', ['Fire']),
  new Pokemon(137, 'Porygon', ['Normal']),
  new Pokemon(138, 'Omanyte', ['Rock', 'Water']),
  new Pokemon(139, 'Omastar', ['Rock', 'Water']),
  new Pokemon(140, 'Kabuto', ['Rock', 'Water']),
  new Pokemon(141, 'Kabutops', ['Rock', 'Flying']),
  new Pokemon(142, 'Aerodactyl', ['Rock', 'Flying']),
  new Pokemon(143, 'Snorlax', ['Normal']),
  new Pokemon(144, 'Articuno', ['Ice', 'Flying']),
  new Pokemon(145, 'Zapdos', ['Electric', 'Flying']),
  new Pokemon(146, 'Moltres', ['Fire', 'Flying']),
  new Pokemon(147, 'Dratini', ['Dragon']),
  new Pokemon(148, 'Dragonair', ['Dragon']),
  new Pokemon(149, 'Dragonite', ['Dragon', 'Flying']),
  new Pokemon(150, 'Mewtwo', ['Psychic']),
  new Pokemon(151, 'Mew', ['Psychic']),
  new Pokemon(152, 'Chikorita', ['Grass']),
  new Pokemon(153, 'Bayleef', ['Grass']),
  new Pokemon(154, 'Meganium', ['Grass']),
  new Pokemon(155, 'Cyndaquil', ['Fire']),
  new Pokemon(156, 'Quilava', ['Fire']),
  new Pokemon(157, 'Typhlosion', ['Fire']),
  new Pokemon(158, 'Totodile', ['Water']),
  new Pokemon(159, 'Croconaw', ['Water']),
  new Pokemon(160, 'Feraligatr', ['Water']),
  new Pokemon(161, 'Sentret', ['Normal']),
  new Pokemon(162, 'Furret', ['Normal']),
  new Pokemon(163, 'Hoothoot', ['Normal', 'Flying']),
  new Pokemon(164, 'Noctowl', ['Normal', 'Flying']),
  new Pokemon(165, 'Ledyba', ['Bug', 'Flying']),
  new Pokemon(166, 'Ledian', ['Bug', 'Flying']),
  new Pokemon(167, 'Spinarak', ['Bug', 'Poison']),
  new Pokemon(168, 'Ariados', ['Bug', 'Poison']),
  new Pokemon(169, 'Crobat', ['Poison', 'Flying']),
  new Pokemon(170, 'Chinchou', ['Water', 'Electric']),
  new Pokemon(171, 'Lanturn', ['Water', 'Electric']),
  new Pokemon(172, 'Pichu', ['Electric']),
  new Pokemon(173, 'Cleffa', ['Normal']),
  new Pokemon(174, 'Igglybuff', ['Normal']),
  new Pokemon(175, 'Togepi', ['Normal']),
  new Pokemon(176, 'Togetic', ['Normal', 'Flying']),
  new Pokemon(177, 'Natu', ['Psychic', 'Flying']),
  new Pokemon(178, 'Xatu', ['Psychic', 'Flying']),
  new Pokemon(179, 'Mareep', ['Electric']),
  new Pokemon(180, 'Flaaffy', ['Electric']),
  new Pokemon(181, 'Ampharos', ['Electric']),
  new Pokemon(182, 'Bellossom', ['Grass']),
  new Pokemon(183, 'Marill', ['Water']),
  new Pokemon(184, 'Azumarill', ['Water']),
  new Pokemon(185, 'Sudowoodo', ['Rock']),
  new Pokemon(186, 'Politoed', ['Water']),
  new Pokemon(187, 'Hoppip', ['Grass', 'Flying']),
  new Pokemon(188, 'Skiploom', ['Grass', 'Flying']),
  new Pokemon(189, 'Jumpluff', ['Grass', 'Flying']),
  new Pokemon(190, 'Aipom', ['Normal']),
  new Pokemon(191, 'Sunkern', ['Grass']),
  new Pokemon(192, 'Sunflora', ['Grass']),
  new Pokemon(193, 'Yanma', ['Bug', 'Flying']),
  new Pokemon(194, 'Wooper', ['Water', 'Ground']),
  new Pokemon(195, 'Quagsire', ['Water', 'Ground']),
  new Pokemon(196, 'Espeon', ['Psychic']),
  new Pokemon(197, 'Umbreon', ['Dark']),
  new Pokemon(198, 'Murkrow', ['Dark', 'Flying']),
  new Pokemon(199, 'Slowking', ['Water', 'Psychic']),
  new Pokemon(200, 'Misdreavus', ['Ghost']),
  new Pokemon(201, 'Unown', ['Psychic']),
  new Pokemon(202, 'Wobbuffet', ['Psychic']),
  new Pokemon(203, 'Girafarig', ['Normal', 'Psychic']),
  new Pokemon(204, 'Pineco', ['Bug']),
  new Pokemon(205, 'Forretress', ['Bug', 'Steel']),
  new Pokemon(206, 'Dunsparce', ['Normal']),
  new Pokemon(207, 'Gligar', ['Ground', 'Flying']),
  new Pokemon(208, 'Steelix', ['Steel', 'Ground']),
  new Pokemon(209, 'Snubbull', ['Normal']),
  new Pokemon(210, 'Granbull', ['Normal']),
  new Pokemon(211, 'Qwilfish', ['Water', 'Poison']),
  new Pokemon(212, 'Scizor', ['Bug', 'Steel']),
  new Pokemon(213, 'Shuckle', ['Bug', 'Rock']),
  new Pokemon(214, 'Heracross', ['Bug', 'Fighting']),
  new Pokemon(215, 'Sneasel', ['Dark', 'Ice']),
  new Pokemon(216, 'Teddiursa', ['Normal']),
  new Pokemon(469, 'Yanmega', ['Bug', 'Flying']),
  new Pokemon(217, 'Ursaring', ['Normal']),
  new Pokemon(218, 'Slugma', ['Fire']),
  new Pokemon(219, 'Magcargo', ['Fire', 'Rock']),
  new Pokemon(220, 'Swinub', ['Ice', 'Ground']),
  new Pokemon(221, 'Piloswine', ['Ice', 'Ground']),
  new Pokemon(222, 'Corsola', ['Water', 'Rock']),
  new Pokemon(223, 'Remoraid', ['Water']),
  new Pokemon(224, 'Octillery', ['Water']),
  new Pokemon(225, 'Delibird', ['Ice', 'Flying']),
  new Pokemon(226, 'Mantine', ['Water', 'Flying']),
  new Pokemon(227, 'Skarmory', ['Steel', 'Flying']),
  new Pokemon(228, 'Houndour', ['Dark', 'Fire']),
  new Pokemon(229, 'Houndoom', ['Dark', 'Fire']),
  new Pokemon(230, 'Kingdra', ['Water', 'Dragon']),
  new Pokemon(231, 'Phanpy', ['Ground']),
  new Pokemon(232, 'Donphan', ['Ground']),
  new Pokemon(233, 'Porygon2', ['Normal']),
  new Pokemon(234, 'Stantler', ['Normal']),
  new Pokemon(235, 'Smeargle', ['Normal']),
  new Pokemon(236, 'Tyrogue', ['Fighting']),
  new Pokemon(237, 'Hitmontop', ['Fighting']),
  new Pokemon(238, 'Smoochum', ['Ice', 'Psychic']),
  new Pokemon(239, 'Elekid', ['Electric']),
  new Pokemon(240, 'Magby', ['Fire']),
  new Pokemon(241, 'Miltank', ['Normal']),
  new Pokemon(242, 'Blissey', ['Normal']),
  new Pokemon(243, 'Raikou', ['Electric']),
  new Pokemon(244, 'Entei', ['Fire']),
  new Pokemon(245, 'Suicune', ['Water']),
  new Pokemon(246, 'Larvitar', ['Rock', 'Ground']),
  new Pokemon(247, 'Pupitar', ['Rock', 'Ground']),
  new Pokemon(248, 'Tyranitar', ['Rock', 'Dark']),
  new Pokemon(249, 'Lugia', ['Psychic', 'Flying']),
  new Pokemon(250, 'Ho-Oh', ['Fire', 'Flying']),
  new Pokemon(251, 'Celebi', ['Psychic', 'Grass']),
  new Pokemon(252, 'Treecko', ['Grass']),
  new Pokemon(253, 'Grovyle', ['Grass']),
  new Pokemon(254, 'Sceptile', ['Grass']),
  new Pokemon(255, 'Torchic', ['Fire']),
  new Pokemon(256, 'Combusken', ['Fire', 'Fighting']),
  new Pokemon(257, 'Blaziken', ['Fire', 'Fighting']),
  new Pokemon(258, 'Mudkip', ['Water']),
  new Pokemon(259, 'Marshtomp', ['Water', 'Ground']),
  new Pokemon(260, 'Swampert', ['Water', 'Ground']),
  new Pokemon(261, 'Poochyena', ['Dark']),
  new Pokemon(262, 'Mightyena', ['Dark']),
  new Pokemon(263, 'Zigzagoon', ['Normal']),
  new Pokemon(264, 'Linoone', ['Normal']),
  new Pokemon(265, 'Wurmple', ['Bug']),
  new Pokemon(266, 'Silcoon', ['Bug']),
  new Pokemon(267, 'Beautifly', ['Bug', 'Flying']),
  new Pokemon(268, 'Cascoon', ['Bug']),
  new Pokemon(269, 'Dustox', ['Bug', 'Poison']),
  new Pokemon(270, 'Lotad', ['Water', 'Grass']),
  new Pokemon(271, 'Lombre', ['Water', 'Grass']),
  new Pokemon(272, 'Ludicolo', ['Water', 'Grass']),
  new Pokemon(273, 'Seedot', ['Grass']),
  new Pokemon(274, 'Nuzleaf', ['Grass', 'Dark']),
  new Pokemon(275, 'Shiftry', ['Grass', 'Dark']),
  new Pokemon(276, 'Taillow', ['Normal', 'Flying']),
  new Pokemon(277, 'Swellow', ['Normal', 'Flying']),
  new Pokemon(278, 'Wingull', ['Water', 'Flying']),
  new Pokemon(279, 'Pelipper', ['Water', 'Flying']),
  new Pokemon(280, 'Ralts', ['Psychic', 'Fairy']),
  new Pokemon(281, 'Kirlia', ['Psychic', 'Fairy']),
  new Pokemon(282, 'Gardevoir', ['Psychic', 'Fairy']),
  new Pokemon(283, 'Surskit', ['Bug', 'Water']),
  new Pokemon(284, 'Masquerain', ['Bug', 'Flying']),
  new Pokemon(285, 'Shroomish', ['Grass']),
  new Pokemon(286, 'Breloom', ['Grass', 'Fighting']),
  new Pokemon(287, 'Slakoth', ['Normal']),
  new Pokemon(288, 'Vigoroth', ['Normal']),
  new Pokemon(289, 'Slaking', ['Normal']),
  new Pokemon(290, 'Nincada', ['Bug', 'Ground']),
  new Pokemon(291, 'Ninjask', ['Bug', 'Flying']),
  new Pokemon(292, 'Shedinja', ['Bug', 'Ghost']),
  new Pokemon(293, 'Whismur', ['Normal']),
  new Pokemon(294, 'Loudred', ['Normal']),
  new Pokemon(295, 'Exploud', ['Normal']),
  new Pokemon(296, 'Makuhita', ['Fighting']),
  new Pokemon(297, 'Hariyama', ['Fighting']),
  new Pokemon(298, 'Azurill', ['Normal', 'Fairy']),
  new Pokemon(299, 'Nosepass', ['Rock']),
  new Pokemon(300, 'Skitty', ['Normal']),
  new Pokemon(301, 'Delcatty', ['Normal']),
  new Pokemon(302, 'Sableye', ['Dark', 'Ghost']),
  new Pokemon(303, 'Mawile', ['Steel', 'Fairy']),
  new Pokemon(304, 'Aron', ['Steel', 'Rock']),
  new Pokemon(305, 'Lairon', ['Steel', 'Rock']),
  new Pokemon(306, 'Aggron', ['Steel', 'Rock']),
  new Pokemon(307, 'Meditite', ['Fighting', 'Psychic']),
  new Pokemon(308, 'Medicham', ['Fighting', 'Psychic']),
  new Pokemon(309, 'Electrike', ['Electric']),
  new Pokemon(310, 'Manectric', ['Electric']),
  new Pokemon(311, 'Plusle', ['Electric']),
  new Pokemon(312, 'Minun', ['Electric']),
  new Pokemon(313, 'Volbeat', ['Bug']),
  new Pokemon(314, 'Illumise', ['Bug']),
  new Pokemon(315, 'Roselia', ['Grass', 'Poison']),
  new Pokemon(316, 'Gulpin', ['Poison']),
  new Pokemon(317, 'Swalot', ['Poison']),
  new Pokemon(318, 'Carvanha', ['Water', 'Dark']),
  new Pokemon(319, 'Sharpedo', ['Water', 'Dark']),
  new Pokemon(320, 'Wailmer', ['Water']),
  new Pokemon(321, 'Wailord', ['Water']),
  new Pokemon(322, 'Numel', ['Fire', 'Ground']),
  new Pokemon(323, 'Camerupt', ['Fire', 'Ground']),
  new Pokemon(324, 'Torkoal', ['Fire']),
  new Pokemon(325, 'Spoink', ['Psychic']),
  new Pokemon(326, 'Grumpig', ['Psychic']),
  new Pokemon(327, 'Spinda', ['Normal']),
  new Pokemon(328, 'Trapinch', ['Ground']),
  new Pokemon(329, 'Vibrava', ['Ground', 'Dragon']),
  new Pokemon(330, 'Flygon', ['Ground', 'Dragon']),
  new Pokemon(331, 'Cacnea', ['Grass']),
  new Pokemon(332, 'Cacturne', ['Grass', 'Dark']),
  new Pokemon(333, 'Swablu', ['Normal', 'Flying']),
  new Pokemon(334, 'Altaria', ['Dragon', 'Flying']),
  new Pokemon(335, 'Zangoose', ['Normal']),
  new Pokemon(336, 'Seviper', ['Poison']),
  new Pokemon(337, 'Lunatone', ['Rock', 'Psychic']),
  new Pokemon(338, 'Solrock', ['Rock', 'Psychic']),
  new Pokemon(339, 'Barboach', ['Water', 'Ground']),
  new Pokemon(340, 'Whiscash', ['Water', 'Ground']),
  new Pokemon(341, 'Corphish', ['Water']),
  new Pokemon(342, 'Crawdaunt', ['Water', 'Dark']),
  new Pokemon(343, 'Baltoy', ['Ground', 'Psychic']),
  new Pokemon(344, 'Claydol', ['Ground', 'Psychic']),
  new Pokemon(345, 'Lileep', ['Rock', 'Grass']),
  new Pokemon(346, 'Cradily', ['Rock', 'Grass']),
  new Pokemon(347, 'Anorith', ['Rock', 'Bug']),
  new Pokemon(348, 'Armaldo', ['Rock', 'Bug']),
  new Pokemon(349, 'Feebas', ['Water']),
  new Pokemon(350, 'Milotic', ['Water']),
  new Pokemon(351, 'Castform', ['Normal']),
  new Pokemon(352, 'Kecleon', ['Normal']),
  new Pokemon(353, 'Shuppet', ['Ghost']),
  new Pokemon(354, 'Banette', ['Ghost']),
  new Pokemon(355, 'Duskull', ['Ghost']),
  new Pokemon(356, 'Dusclops', ['Ghost']),
  new Pokemon(357, 'Tropius', ['Grass', 'Flying']),
  new Pokemon(358, 'Chimecho', ['Psychic']),
  new Pokemon(359, 'Absol', ['Dark']),
  new Pokemon(360, 'Wynaut', ['Psychic']),
  new Pokemon(361, 'Snorunt', ['Ice']),
  new Pokemon(362, 'Glalie', ['Ice']),
  new Pokemon(363, 'Spheal', ['Ice', 'Water']),
  new Pokemon(364, 'Sealeo', ['Ice', 'Water']),
  new Pokemon(365, 'Walrein', ['Ice', 'Water']),
  new Pokemon(366, 'Clamperl', ['Water']),
  new Pokemon(367, 'Huntail', ['Water']),
  new Pokemon(368, 'Gorebyss', ['Water']),
  new Pokemon(369, 'Relicanth', ['Water', 'Rock']),
  new Pokemon(370, 'Luvdisc', ['Water']),
  new Pokemon(371, 'Bagon', ['Dragon']),
  new Pokemon(372, 'Shelgon', ['Dragon']),
  new Pokemon(373, 'Salamence', ['Dragon', 'Flying']),
  new Pokemon(374, 'Beldum', ['Steel', 'Psychic']),
  new Pokemon(375, 'Metang', ['Steel', 'Psychic']),
  new Pokemon(376, 'Metagross', ['Steel', 'Psychic']),
  new Pokemon(377, 'Regirock', ['Rock']),
  new Pokemon(378, 'Regice', ['Ice']),
  new Pokemon(379, 'Registeel', ['Steel']),
  new Pokemon(380, 'Latias', ['Dragon', 'Psychic']),
  new Pokemon(381, 'Latios', ['Dragon', 'Psychic']),
  new Pokemon(382, 'Kyogre', ['Water']),
  new Pokemon(383, 'Groudon', ['Ground']),
  new Pokemon(384, 'Rayquaza', ['Dragon', 'Flying']),
  new Pokemon(385, 'Jirachi', ['Steel', 'Psychic']),
  new Pokemon(386, 'Deoxys', ['Psychic']),
  new Pokemon(387, 'Turtwig', ['Grass']),
  new Pokemon(388, 'Grotle', ['Grass']),
  new Pokemon(389, 'Torterra', ['Grass', 'Ground']),
  new Pokemon(390, 'Chimchar', ['Fire']),
  new Pokemon(391, 'Monferno', ['Fire', 'Fighting']),
  new Pokemon(392, 'Infernape', ['Fire', 'Fighting']),
  new Pokemon(393, 'Piplup', ['Water']),
  new Pokemon(394, 'Prinplup', ['Water']),
  new Pokemon(395, 'Empoleon', ['Water', 'Steel']),
  new Pokemon(396, 'Starly', ['Normal', 'Flying']),
  new Pokemon(397, 'Staravia', ['Normal', 'Flying']),
  new Pokemon(398, 'Staraptor', ['Normal', 'Flying']),
  new Pokemon(399, 'Bidoof', ['Normal']),
  new Pokemon(400, 'Bibarel', ['Normal', 'Water']),
  new Pokemon(401, 'Kricketot', ['Bug']),
  new Pokemon(402, 'Kricketune', ['Bug']),
  new Pokemon(403, 'Shinx', ['Electric']),
  new Pokemon(404, 'Luxio', ['Electric']),
  new Pokemon(405, 'Luxray', ['Electric']),
  new Pokemon(406, 'Budew', ['Grass', 'Poison']),
  new Pokemon(407, 'Roserade', ['Grass', 'Poison']),
  new Pokemon(408, 'Cranidos', ['Rock']),
  new Pokemon(409, 'Rampardos', ['Rock']),
  new Pokemon(410, 'Shieldon', ['Rock', 'Steel']),
  new Pokemon(411, 'Bastiodon', ['Rock', 'Steel']),
  new Pokemon(412, 'Burmy', ['Bug']),
  new Pokemon(413, 'Wormadam', ['Bug', 'Grass']),
  new Pokemon(414, 'Mothim', ['Bug', 'Flying']),
  new Pokemon(415, 'Combee', ['Bug', 'Flying']),
  new Pokemon(416, 'Vespiquen', ['Bug', 'Flying']),
  new Pokemon(417, 'Pachirisu', ['Electric']),
  new Pokemon(418, 'Buizel', ['Water']),
  new Pokemon(419, 'Floatzel', ['Water']),
  new Pokemon(420, 'Cherubi', ['Grass']),
  new Pokemon(421, 'Cherrim', ['Grass']),
  new Pokemon(422, 'Shellos', ['Water']),
  new Pokemon(423, 'Gastrodon', ['Water', 'Ground']),
  new Pokemon(424, 'Ambipom', ['Normal']),
  new Pokemon(425, 'Drifloon', ['Ghost', 'Flying']),
  new Pokemon(426, 'Drifblim', ['Ghost', 'Flying']),
  new Pokemon(427, 'Buneary', ['Normal']),
  new Pokemon(428, 'Lopunny', ['Normal']),
  new Pokemon(429, 'Mismagius', ['Ghost']),
  new Pokemon(430, 'Honchkrow', ['Dark', 'Flying']),
  new Pokemon(431, 'Glameow', ['Normal']),
  new Pokemon(432, 'Purugly', ['Normal']),
  new Pokemon(433, 'Chingling', ['Psychic']),
  new Pokemon(434, 'Stunky', ['Poison', 'Dark']),
  new Pokemon(435, 'Skuntank', ['Poison', 'Dark']),
  new Pokemon(436, 'Bronzor', ['Steel', 'Psychic']),
  new Pokemon(437, 'Bronzong', ['Steel', 'Psychic']),
  new Pokemon(438, 'Bonsly', ['Rock']),
  new Pokemon(439, 'Mime Jr.', ['Psychic', 'Fairy']),
  new Pokemon(440, 'Happiny', ['Normal']),
  new Pokemon(441, 'Chatot', ['Normal', 'Flying']),
  new Pokemon(442, 'Spiritomb', ['Ghost', 'Dark']),
  new Pokemon(443, 'Gible', ['Dragon', 'Ground']),
  new Pokemon(444, 'Gabite', ['Dragon', 'Ground']),
  new Pokemon(445, 'Garchomp', ['Dragon', 'Ground']),
  new Pokemon(446, 'Munchlax', ['Normal']),
  new Pokemon(447, 'Riolu', ['Fighting']),
  new Pokemon(448, 'Lucario', ['Fighting', 'Steel']),
  new Pokemon(449, 'Hippopotas', ['Ground']),
  new Pokemon(450, 'Hippowdon', ['Ground']),
  new Pokemon(451, 'Skorupi', ['Poison', 'Bug']),
  new Pokemon(452, 'Drapion', ['Poison', 'Dark']),
  new Pokemon(453, 'Croagunk', ['Poison', 'Fighting']),
  new Pokemon(454, 'Toxicroak', ['Poison', 'Fighting']),
  new Pokemon(455, 'Carnivine', ['Grass']),
  new Pokemon(456, 'Finneon', ['Water']),
  new Pokemon(457, 'Lumineon', ['Water']),
  new Pokemon(458, 'Mantyke', ['Water', 'Flying']),
  new Pokemon(459, 'Snover', ['Grass', 'Ice']),
  new Pokemon(460, 'Abomasnow', ['Grass', 'Ice']),
  new Pokemon(461, 'Weavile', ['Dark', 'Ice']),
  new Pokemon(462, 'Magnezone', ['Electric', 'Steel']),
  new Pokemon(463, 'Lickilicky', ['Normal']),
  new Pokemon(464, 'Rhyperior', ['Ground', 'Rock']),
  new Pokemon(465, 'Tangrowth', ['Grass']),
  new Pokemon(466, 'Electivire', ['Electric']),
  new Pokemon(467, 'Magmortar', ['Fire']),
  new Pokemon(468, 'Togekiss', ['Normal', 'Flying']),
  new Pokemon(469, 'Yanmega', ['Bug', 'Flying']),
  new Pokemon(470, 'Leafeon', ['Grass']),
  new Pokemon(471, 'Glaceon', ['Ice']),
  new Pokemon(472, 'Gliscor', ['Ground', 'Flying']),
  new Pokemon(473, 'Mamoswine', ['Ice', 'Ground']),
  new Pokemon(474, 'Porygon-Z', ['Normal']),
  new Pokemon(475, 'Gallade', ['Psychic', 'Fighting']),
  new Pokemon(476, 'Probopass', ['Rock', 'Steel']),
  new Pokemon(477, 'Dusknoir', ['Ghost']),
  new Pokemon(478, 'Froslass', ['Ice', 'Ghost']),
  new Pokemon(479, 'Rotom', ['Electric', 'Ghost']),
  new Pokemon(480, 'Uxie', ['Psychic'], ''),
  new Pokemon(481, 'Mesprit', ['Psychic']),
  new Pokemon(482, 'Azelf', ['Psychic']),
  new Pokemon(483, 'Dialga', ['Steel', 'Dragon']),
  new Pokemon(484, 'Palkia', ['Water', 'Dragon']),
  new Pokemon(485, 'Heatran', ['Fire', 'Steel']),
  new Pokemon(486, 'Regigigas', ['Normal']),
  new Pokemon(487, 'Giratina', ['Ghost', 'Dragon']),
  new Pokemon(488, 'Cresselia', ['Psychic']),
  new Pokemon(489, 'Phione', ['Water']),
  new Pokemon(490, 'Manaphy', ['Water']),
  new Pokemon(491, 'Darkrai', ['Dark']),
  new Pokemon(492, 'Shaymin', ['Grass']),
  new Pokemon(493, 'Arceus', ['Normal']),
  new Pokemon(494, 'Victini', ['Psychic', 'Fire']),
  new Pokemon(495, 'Snivy', ['Grass']),
  new Pokemon(496, 'Servine', ['Grass']),
  new Pokemon(497, 'Serperior', ['Grass']),
  new Pokemon(498, 'Tepig', ['Fire']),
  new Pokemon(499, 'Pignite', ['Fire', 'Fighting']),
  new Pokemon(500, 'Emboar', ['Fire', 'Fighting']),
  new Pokemon(501, 'Oshawott', ['Water']),
  new Pokemon(502, 'Dewott', ['Water']),
  new Pokemon(503, 'Samurott', ['Water']),
  new Pokemon(504, 'Patrat', ['Normal']),
  new Pokemon(505, 'Watchog', ['Normal']),
  new Pokemon(506, 'Lillipup', ['Normal']),
  new Pokemon(507, 'Herdier', ['Normal']),
  new Pokemon(508, 'Stoutland', ['Normal']),
  new Pokemon(509, 'Purrloin', ['Dark']),
  new Pokemon(510, 'Liepard', ['Dark']),
  new Pokemon(511, 'Pansage', ['Grass']),
  new Pokemon(512, 'Simisage', ['Grass']),
  new Pokemon(513, 'Pansear', ['Fire']),
  new Pokemon(514, 'Simisear', ['Fire']),
  new Pokemon(515, 'Panpour', ['Water']),
  new Pokemon(516, 'Simipour', ['Water']),
  new Pokemon(517, 'Munna', ['Psychic']),
  new Pokemon(518, 'Musharna', ['Psychic']),
  new Pokemon(519, 'Pidove', ['Normal', 'Flying']),
  new Pokemon(520, 'Tranquill', ['Normal', 'Flying']),
  new Pokemon(521, 'Unfezant', ['Normal', 'Flying']),
  new Pokemon(522, 'Blitzle', ['Electric']),
  new Pokemon(523, 'Zebstrika', ['Electric']),
  new Pokemon(524, 'Roggenrola', ['Rock']),
  new Pokemon(525, 'Boldore', ['Rock']),
  new Pokemon(526, 'Gigalith', ['Rock']),
  new Pokemon(527, 'Woobat', ['Psychic', 'Flying']),
  new Pokemon(528, 'Swoobat', ['Psychic', 'Flying']),
  new Pokemon(529, 'Drilbur', ['Ground']),
  new Pokemon(530, 'Excadrill', ['Ground', 'Steel']),
  new Pokemon(531, 'Audino', ['Normal']),
  new Pokemon(532, 'Timburr', ['Fighting']),
  new Pokemon(533, 'Gurdurr', ['Fighting']),
  new Pokemon(534, 'Conkeldurr', ['Fighting']),
  new Pokemon(535, 'Tympole', ['Water']),
  new Pokemon(536, 'Palpitoad', ['Water', 'Ground']),
  new Pokemon(537, 'Seismitoad', ['Water', 'Ground']),
  new Pokemon(538, 'Throh', ['Fighting']),
  new Pokemon(539, 'Sawk', ['Fighting']),
  new Pokemon(540, 'Sewaddle', ['Bug', 'Grass']),
  new Pokemon(541, 'Swadloon', ['Bug', 'Grass']),
  new Pokemon(542, 'Leavanny', ['Bug', 'Grass']),
  new Pokemon(543, 'Venipede', ['Bug', 'Poison']),
  new Pokemon(544, 'Whirlipede', ['Bug', 'Poison']),
  new Pokemon(545, 'Scolipede', ['Bug', 'Poison']),
  new Pokemon(546, 'Cottonee', ['Grass']),
  new Pokemon(547, 'Whimsicott', ['Grass']),
  new Pokemon(548, 'Petilil', ['Grass']),
  new Pokemon(549, 'Lilligant', ['Grass']),
  new Pokemon(550, 'Basculin', ['Water']),
  new Pokemon(551, 'Sandile', ['Ground', 'Dark']),
  new Pokemon(552, 'Krokorok', ['Ground', 'Dark']),
  new Pokemon(553, 'Krookodile', ['Ground', 'Dark']),
  new Pokemon(554, 'Darumaka', ['Fire']),
  new Pokemon(555, 'Darmanitan', ['Fire']),
  new Pokemon(556, 'Maractus', ['Grass']),
  new Pokemon(557, 'Dwebble', ['Bug', 'Rock']),
  new Pokemon(558, 'Crustle', ['Bug', 'Rock']),
  new Pokemon(559, 'Scraggy', ['Dark', 'Fighting']),
  new Pokemon(560, 'Scrafty', ['Dark', 'Fighting']),
  new Pokemon(561, 'Sigilyph', ['Psychic', 'Flying']),
  new Pokemon(562, 'Yamask', ['Ghost']),
  new Pokemon(563, 'Cofagrigus', ['Ghost']),
  new Pokemon(564, 'Tirtouga', ['Water', 'Rock']),
  new Pokemon(565, 'Carracosta', ['Water', 'Rock']),
  new Pokemon(566, 'Archen', ['Rock', 'Flying']),
  new Pokemon(567, 'Archeops', ['Rock', 'Flying']),
  new Pokemon(568, 'Trubbish', ['Poison']),
  new Pokemon(569, 'Garbodor', ['Poison']),
  new Pokemon(570, 'Zorua', ['Dark']),
  new Pokemon(571, 'Zoroark', ['Dark']),
  new Pokemon(572, 'Minccino', ['Normal']),
  new Pokemon(573, 'Cinccino', ['Normal']),
  new Pokemon(574, 'Gothita', ['Psychic']),
  new Pokemon(575, 'Gothorita', ['Psychic']),
  new Pokemon(576, 'Gothitelle', ['Psychic']),
  new Pokemon(577, 'Solosis', ['Psychic']),
  new Pokemon(578, 'Duosion', ['Psychic']),
  new Pokemon(579, 'Reuniclus', ['Psychic']),
  new Pokemon(580, 'Ducklett', ['Water', 'Flying']),
  new Pokemon(581, 'Swanna', ['Water', 'Flying']),
  new Pokemon(582, 'Vanillite', ['Ice']),
  new Pokemon(583, 'Vanillish', ['Ice']),
  new Pokemon(584, 'Vanilluxe', ['Ice']),
  new Pokemon(585, 'Deerling', ['Normal', 'Grass']),
  new Pokemon(586, 'Sawsbuck', ['Normal', 'Grass']),
  new Pokemon(587, 'Emolga', ['Electric', 'Flying']),
  new Pokemon(588, 'Karrablast', ['Bug']),
  new Pokemon(589, 'Escavalier', ['Bug', 'Steel']),
  new Pokemon(590, 'Foongus', ['Grass', 'Poison']),
  new Pokemon(591, 'Amoonguss', ['Grass', 'Poison']),
  new Pokemon(592, 'Frillish', ['Water', 'Ghost']),
  new Pokemon(593, 'Jellicent', ['Water', 'Ghost']),
  new Pokemon(594, 'Alomomola', ['Water']),
  new Pokemon(595, 'Joltik', ['Bug', 'Electric']),
  new Pokemon(596, 'Galvantula', ['Bug', 'Electric']),
  new Pokemon(597, 'Ferroseed', ['Grass', 'Steel']),
  new Pokemon(598, 'Ferrothorn', ['Grass', 'Steel']),
  new Pokemon(599, 'Klink', ['Steel']),
  new Pokemon(600, 'Klang', ['Steel']),
  new Pokemon(601, 'Klinklang', ['Steel']),
  new Pokemon(602, 'Tynamo', ['Electric']),
  new Pokemon(603, 'Eelektrik', ['Electric']),
  new Pokemon(604, 'Eelektross', ['Electric']),
  new Pokemon(605, 'Elgyem', ['Psychic']),
  new Pokemon(606, 'Beheeyem', ['Psychic']),
  new Pokemon(607, 'Litwick', ['Ghost', 'Fire']),
  new Pokemon(608, 'Lampent', ['Ghost', 'Fire']),
  new Pokemon(609, 'Chandelure', ['Ghost', 'Fire']),
  new Pokemon(610, 'Axew', ['Dragon']),
  new Pokemon(611, 'Fraxure', ['Dragon']),
  new Pokemon(612, 'Haxorus', ['Dragon']),
  new Pokemon(613, 'Cubchoo', ['Ice']),
  new Pokemon(614, 'Beartic', ['Ice']),
  new Pokemon(615, 'Cryogonal', ['Ice']),
  new Pokemon(616, 'Shelmet', ['Bug']),
  new Pokemon(617, 'Accelgor', ['Bug']),
  new Pokemon(618, 'Stunfisk', ['Ground', 'Electric']),
  new Pokemon(619, 'Mienfoo', ['Fighting']),
  new Pokemon(620, 'Mienshao', ['Fighting']),
  new Pokemon(621, 'Druddigon', ['Dragon']),
  new Pokemon(622, 'Golett', ['Ground', 'Ghost']),
  new Pokemon(623, 'Golurk', ['Ground', 'Ghost']),
  new Pokemon(624, 'Pawniard', ['Dark', 'Steel']),
  new Pokemon(625, 'Bisharp', ['Dark', 'Steel']),
  new Pokemon(626, 'Bouffalant', ['Normal']),
  new Pokemon(627, 'Rufflet', ['Normal', 'Flying']),
  new Pokemon(628, 'Braviary', ['Normal', 'Flying']),
  new Pokemon(629, 'Vullaby', ['Dark', 'Flying']),
  new Pokemon(630, 'Mandibuzz', ['Dark', 'Flying']),
  new Pokemon(631, 'Heatmor', ['Fire']),
  new Pokemon(632, 'Durant', ['Bug', 'Steel']),
  new Pokemon(633, 'Deino', ['Dark', 'Dragon']),
  new Pokemon(634, 'Zweilous', ['Dark', 'Dragon']),
  new Pokemon(635, 'Hydreigon', ['Dark', 'Dragon']),
  new Pokemon(636, 'Larvesta', ['Bug', 'Fire']),
  new Pokemon(637, 'Volcarona', ['Bug', 'Fire']),
  new Pokemon(638, 'Cobalion', ['Steel', 'Fighting']),
  new Pokemon(639, 'Terrakion', ['Rock', 'Fighting']),
  new Pokemon(640, 'Virizon', ['Grass', 'Fighting']),
  new Pokemon(641, 'Tornadus', ['Flying']),
  new Pokemon(642, 'Thundurus', ['Electric', 'Flying']),
  new Pokemon(643, 'Reshiram', ['Dragon', 'Fire']),
  new Pokemon(644, 'Zekrom', ['Dragon', 'Electric']),
  new Pokemon(645, 'Landorus', ['Ground', 'Flying']),
  new Pokemon(646, 'Kyurem', ['Dragon', 'Ice']),
  new Pokemon(647, 'Keldeo', ['Water', 'Fighting']),
  new Pokemon(648, 'Meloetta', ['Normal', 'Psychic']),
  new Pokemon(649, 'Genesect', ['Bug', 'Steel']),
  new Pokemon(650, 'Chespin', ['Grass']),
  new Pokemon(651, 'Quilladin', ['Grass']),
  new Pokemon(652, 'Chesnaught', ['Grass', 'Fighting']),
  new Pokemon(653, 'Fennekin', ['Fire']),
  new Pokemon(654, 'Braixen', ['Fire']),
  new Pokemon(655, 'Delphox', ['Fire', 'Psychic']),
  new Pokemon(656, 'Froakie', ['Water']),
  new Pokemon(657, 'Frogadier', ['Water']),
  new Pokemon(658, 'Greninja', ['Water', 'Dark']),
  new Pokemon(659, 'Bunnelby', ['Normal']),
  new Pokemon(660, 'Diggersby', ['Normal', 'Ground']),
  new Pokemon(661, 'Fletchling', ['Normal', 'Flying']),
  new Pokemon(662, 'Fletchinder', ['Fire', 'Flying']),
  new Pokemon(663, 'Talonflame', ['Fire', 'Flying']),
  new Pokemon(664, 'Scatterbug', ['Bug']),
  new Pokemon(665, 'Spewpa', ['Bug']),
  new Pokemon(666, 'Vivillon', ['Bug', 'Flying']),
  new Pokemon(667, 'Litleo', ['Fire', 'Normal']),
  new Pokemon(668, 'Pyroar', ['Fire', 'Normal']),
  new Pokemon(669, 'Flabébé', ['Fairy']),
  new Pokemon(670, 'Floette', ['Fairy']),
  new Pokemon(671, 'Florges', ['Fairy']),
  new Pokemon(672, 'Skiddo', ['Grass']),
  new Pokemon(673, 'Gogoat', ['Grass']),
  new Pokemon(674, 'Pancham', ['Fighting']),
  new Pokemon(675, 'Pangoro', ['Fighting', 'Dark']),
  new Pokemon(676, 'Furfrou', ['Normal']),
  new Pokemon(677, 'Espurr', ['Psychic']),
  new Pokemon(678, 'Meowstic', ['Psychic']),
  new Pokemon(679, 'Honedge', ['Steel', 'Ghost']),
  new Pokemon(680, 'Doublade', ['Steel', 'Ghost']),
  new Pokemon(681, 'Aegislash', ['Steel', 'Ghost']),
  new Pokemon(682, 'Spritzee', ['Fairy']),
  new Pokemon(683, 'Aromatisse', ['Fairy']),
  new Pokemon(684, 'Swirlix', ['Fairy']),
  new Pokemon(685, 'Slurpuff', ['Fairy']),
  new Pokemon(686, 'Inkay', ['Dark', 'Psychic']),
  new Pokemon(687, 'Malamar', ['Dark', 'Psychic']),
  new Pokemon(688, 'Binacle', ['Rock', 'Water']),
  new Pokemon(689, 'Barbaracle', ['Rock', 'Water']),
  new Pokemon(690, 'Skrelp', ['Poison', 'Water']),
  new Pokemon(691, 'Dragalge', ['Poison', 'Dragon']),
  new Pokemon(692, 'Clauncher', ['Water']),
  new Pokemon(693, 'Clawitzer', ['Water']),
  new Pokemon(694, 'Helioptile', ['Electric', 'Normal']),
  new Pokemon(695, 'Heliolisk', ['Electric', 'Normal']),
  new Pokemon(696, 'Tyrunt', ['Rock', 'Dragon']),
  new Pokemon(697, 'Tyrantrum', ['Rock', 'Dragon']),
  new Pokemon(698, 'Amaura', ['Rock', 'Ice']),
  new Pokemon(699, 'Aurorus', ['Rock', 'Ice']),
  new Pokemon(700, 'Sylveon', ['Fairy']),
  new Pokemon(701, 'Hawlucha', ['Fighting', 'Flying']),
  new Pokemon(702, 'Dedenne', ['Electric', 'Fairy']),
  new Pokemon(703, 'Carbink', ['Rock', 'Fairy']),
  new Pokemon(704, 'Goomy', ['Dragon']),
  new Pokemon(705, 'Sliggoo', ['Dragon']),
  new Pokemon(706, 'Goodra', ['Dragon']),
  new Pokemon(707, 'Klefki', ['Steel', 'Fairy']),
  new Pokemon(708, 'Phantump', ['Ghost', 'Grass']),
  new Pokemon(709, 'Trevenant', ['Ghost', 'Grass']),
  new Pokemon(710, 'Pumpkaboo', ['Ghost', 'Grass']),
  new Pokemon(711, 'Gourgeist', ['Ghost', 'Grass']),
  new Pokemon(712, 'Bergmite', ['Ice']),
  new Pokemon(713, 'Avalugg', ['Ice']),
  new Pokemon(714, 'Noibat', ['Flying', 'Dragon']),
  new Pokemon(715, 'Noivern', ['Flying', 'Dragon']),
  new Pokemon(716, 'Xerneas', ['Fairy']),
  new Pokemon(717, 'Yveltal', ['Dark', 'Flying']),
  new Pokemon(718, 'Zygarde', ['Dragon', 'Ground']),
  new Pokemon(719, 'Diancie', ['Rock', 'Fairy']),
  new Pokemon(720, 'Hoopa', ['Psychic', 'Ghost']),
  new Pokemon(721, 'Volcanion', ['Fire', 'Water']),
  new Pokemon(722, 'Rowlet', ['Grass', 'Flying']),
  new Pokemon(723, 'Dartrix', ['Grass', 'Flying']),
  new Pokemon(724, 'Decidueye', ['Grass', 'Ghost']),
  new Pokemon(725, 'Litten', ['Fire']),
  new Pokemon(726, 'Torracat', ['Fire']),
  new Pokemon(727, 'Incineroar', ['Fire', 'Dark']),
  new Pokemon(728, 'Popplio', ['Water']),
  new Pokemon(729, 'Brionne', ['Water']),
  new Pokemon(730, 'Primarina', ['Water', 'Fairy']),
  new Pokemon(731, 'Pikipek', ['Normal', 'Flying']),
  new Pokemon(732, 'Trumbeak', ['Normal', 'Flying']),
  new Pokemon(733, 'Toucannon', ['Normal', 'Flying']),
  new Pokemon(734, 'Yungoos', ['Normal']),
  new Pokemon(735, 'Gumshoos', ['Normal']),
  new Pokemon(736, 'Grubbin', ['Bug']),
  new Pokemon(737, 'Charjabug', ['Bug', 'Electric']),
  new Pokemon(738, 'Vikavolt', ['Bug', 'Electric']),
  new Pokemon(739, 'Crabrawler', ['Fighting']),
  new Pokemon(740, 'Crabominable', ['Fighting', 'Ice']),
  new Pokemon(741, 'Oricorio', ['Fire', 'Flying']),
  new Pokemon(742, 'Cutiefly', ['Bug', 'Fairy']),
  new Pokemon(743, 'Ribombee', ['Bug', 'Fairy']),
  new Pokemon(744, 'Rockruff', ['Rock']),
  new Pokemon(745, 'Lycanroc', ['Rock']),
  new Pokemon(746, 'Wishiwashi', ['Water']),
  new Pokemon(747, 'Mareanie', ['Poison', 'Water']),
  new Pokemon(748, 'Toxapex', ['Poison', 'Water']),
  new Pokemon(749, 'Mudbray', ['Ground']),
  new Pokemon(750, 'Mudsdale', ['Ground']),
  new Pokemon(751, 'Dewpider', ['Water', 'Bug']),
  new Pokemon(752, 'Araquanid', ['Water', 'Bug']),
  new Pokemon(753, 'Fomantis', ['Grass']),
  new Pokemon(754, 'Lurantis', ['Grass']),
  new Pokemon(755, 'Morelull', ['Grass', 'Fairy']),
  new Pokemon(756, 'Shiinotic', ['Grass', 'Fairy']),
  new Pokemon(757, 'Salandit', ['Poison', 'Fire']),
  new Pokemon(758, 'Salazzle', ['Poison', 'Fire']),
  new Pokemon(759, 'Stufful', ['Normal', 'Fighting']),
  new Pokemon(760, 'Bewear', ['Normal', 'Fighting']),
  new Pokemon(761, 'Bounsweet', ['Grass']),
  new Pokemon(762, 'Steenee', ['Grass']),
  new Pokemon(763, 'Tsareena', ['Grass']),
  new Pokemon(764, 'Comfey', ['Fairy']),
  new Pokemon(765, 'Oranguru', ['Normal', 'Psychic']),
  new Pokemon(766, 'Passimian', ['Fighting']),
  new Pokemon(767, 'Wimpod', ['Bug', 'Water']),
  new Pokemon(768, 'Golisopod', ['Bug', 'Water']),
  new Pokemon(769, 'Sandygast', ['Ghost', 'Ground']),
  new Pokemon(770, 'Palossand', ['Ghost', 'Ground']),
  new Pokemon(771, 'Pyukumuku', ['Water']),
  new Pokemon(772, 'Type: Null', ['Normal']),
  new Pokemon(773, 'Silvally', ['Normal']),
  new Pokemon(774, 'Minior', ['Rock', 'Flying']),
  new Pokemon(775, 'Komala', ['Normal']),
  new Pokemon(776, 'Turtonator', ['Fire', 'Dragon']),
  new Pokemon(777, 'Togedemaru', ['Electric', 'Steel']),
  new Pokemon(778, 'Mimikyu', ['Ghost', 'Fairy']),
  new Pokemon(779, 'Bruxish', ['Water', 'Psychic']),
  new Pokemon(780, 'Drampa', ['Normal', 'Dragon']),
  new Pokemon(781, 'Dhelmise', ['Ghost', 'Grass']),
  new Pokemon(782, 'Jangmo-o', ['Dragon']),
  new Pokemon(783, 'Hakamo-o', ['Dragon', 'Fighting']),
  new Pokemon(784, 'Kommo-o', ['Dragon', 'Fighting']),
  new Pokemon(785, 'Tapu Koko', ['Electric', 'Fairy']),
  new Pokemon(786, 'Tapu Lele', ['Psychic', 'Fairy']),
  new Pokemon(787, 'Tapu Bulu', ['Grass', 'Fairy']),
  new Pokemon(788, 'Tapu Fini', ['Water', 'Fairy']),
  new Pokemon(789, 'Cosmog', ['Psychic']),
  new Pokemon(790, 'Cosmoem', ['Psychic']),
  new Pokemon(791, 'Solgaleo', ['Psychic', 'Steel']),
  new Pokemon(792, 'Lunala', ['Psychic', 'Ghost']),
  new Pokemon(793, 'Nihilego', ['Rock', 'Poison']),
  new Pokemon(794, 'Buzzwole', ['Bug', 'Fighting']),
  new Pokemon(795, 'Pheromosa', ['Bug', 'Fighting']),
  new Pokemon(796, 'Xurkitree', ['Electric']),
  new Pokemon(797, 'Celesteela', ['Steel', 'Flying']),
  new Pokemon(798, 'Kartana', ['Grass', 'Steel']),
  new Pokemon(799, 'Guzzlord', ['Dark', 'Dragon']),
  new Pokemon(800, 'Necrozma', ['Psychic']),
  new Pokemon(801, 'Magearna', ['Steel', 'Fairy']),
  new Pokemon(802, 'Marshadow', ['Fighting', 'Ghost']),
  new Pokemon(803, 'Poipole', ['Poison']),
  new Pokemon(804, 'Naganadel', ['Poison', 'Dragon']),
  new Pokemon(805, 'Stakataka', ['Rock', 'Steel']),
  new Pokemon(806, 'Blacephalon', ['Fire', 'Ghost']),
  new Pokemon(807, 'Zeraora', ['Electric']),
  new Pokemon(808, 'Meltan', ['Steel']),
  new Pokemon(809, 'Melmetal', ['Steel']),
];

function loadNational() {
  $('#Center').text('The National Pokémon List by Pokédex Number');
  $('#myInput').val('');
  $('#pokemon-container').empty();
  for (const p of pokemonList) {
    p.loadToPage();
    p.showTypes();
  }
}
