var pokemonList = [
  new Pokemon(387, 'Turtwig', ['Grass']),
  new Pokemon(388, 'Grotle', ['Grass']),
  new Pokemon(389, 'Torterra', ['Grass', 'Ground']),
  new Pokemon(390, 'Chimchar', ['Fire']),
  new Pokemon(391, 'Monferno', ['Fire', 'Fighting']),
  new Pokemon(392, 'Infernape', ['Fire', 'Fighting']),
  new Pokemon(393, 'Piplup', ['Water']),
  new Pokemon(394, 'Prinplup', ['Water']),
  new Pokemon(395, 'Empoleon', ['Water', 'Steel']),
  new Pokemon(396, 'Starly', ['Normal', 'Flying']),
  new Pokemon(397, 'Staravia', ['Normal', 'Flying']),
  new Pokemon(398, 'Staraptor', ['Normal', 'Flying']),
  new Pokemon(399, 'Bidoof', ['Normal']),
  new Pokemon(400, 'Bibarel', ['Normal', 'Water']),
  new Pokemon(401, 'Kricketot', ['Bug']),
  new Pokemon(402, 'Kricketune', ['Bug']),
  new Pokemon(403, 'Shinx', ['Electric']),
  new Pokemon(404, 'Luxio', ['Electric']),
  new Pokemon(405, 'Luxray', ['Electric']),
  new Pokemon(63, 'Abra', ['Psychic']),
  new Pokemon(64, 'Kadabra', ['Psychic']),
  new Pokemon(65, 'Alakazam', ['Psychic']),
  new Pokemon(129, 'Magikarp', ['Water']),
  new Pokemon(130, 'Gyarados', ['Water', 'Flying']),
  new Pokemon(406, 'Budew', ['Grass', 'Poison']),
  new Pokemon(315, 'Roselia', ['Grass', 'Poison']),
  new Pokemon(407, 'Roserade', ['Grass', 'Poison']),
  new Pokemon(41, 'Zubat', ['Poison', 'Flying']),
  new Pokemon(42, 'Golbat', ['Poison', 'Flying']),
  new Pokemon(169, 'Crobat', ['Poison', 'Flying']),
  new Pokemon(74, 'Geodude', ['Rock', 'Ground']),
  new Pokemon(75, 'Graveler', ['Rock', 'Ground']),
  new Pokemon(76, 'Golem', ['Rock', 'Ground']),
  new Pokemon(95, 'Onix', ['Rock', 'Ground']),
  new Pokemon(208, 'Steelix', ['Steel', 'Ground']),
  new Pokemon(408, 'Cranidos', ['Rock']),
  new Pokemon(409, 'Rampardos', ['Rock']),
  new Pokemon(410, 'Shieldon', ['Rock', 'Steel']),
  new Pokemon(411, 'Bastiodon', ['Rock', 'Steel']),
  new Pokemon(66, 'Machop', ['Fighting']),
  new Pokemon(67, 'Machoke', ['Fighting']),
  new Pokemon(68, 'Machamp', ['Fighting']),
  new Pokemon(54, 'Psyduck', ['Water']),
  new Pokemon(55, 'Golduck', ['Water']),
  new Pokemon(412, 'Burmy', ['Bug']),
  new Pokemon(413, 'Wormadam', ['Bug', 'Grass']),
  new Pokemon(414, 'Mothim', ['Bug', 'Flying']),
  new Pokemon(265, 'Wurmple', ['Bug']),
  new Pokemon(266, 'Silcoon', ['Bug']),
  new Pokemon(267, 'Beautifly', ['Bug', 'Flying']),
  new Pokemon(268, 'Cascoon', ['Bug']),
  new Pokemon(269, 'Dustox', ['Bug', 'Poison']),
  new Pokemon(415, 'Combee', ['Bug', 'Flying']),
  new Pokemon(416, 'Vespiquen', ['Bug', 'Flying']),
  new Pokemon(417, 'Pachirisu', ['Electric']),
  new Pokemon(418, 'Buizel', ['Water']),
  new Pokemon(419, 'Floatzel', ['Water']),
  new Pokemon(420, 'Cherubi', ['Grass']),
  new Pokemon(421, 'Cherrim', ['Grass']),
  new Pokemon(422, 'Shellos', ['Water']),
  new Pokemon(423, 'Gastrodon', ['Water', 'Ground']),
  new Pokemon(214, 'Heracross', ['Bug', 'Fighting']),
  new Pokemon(190, 'Aipom', ['Normal']),
  new Pokemon(424, 'Ambipom', ['Normal']),
  new Pokemon(425, 'Drifloon', ['Ghost', 'Flying']),
  new Pokemon(426, 'Drifblim', ['Ghost', 'Flying']),
  new Pokemon(427, 'Buneary', ['Normal']),
  new Pokemon(428, 'Lopunny', ['Normal']),
  new Pokemon(92, 'Gastly', ['Ghost', 'Poison']),
  new Pokemon(93, 'Haunter', ['Ghost', 'Poison']),
  new Pokemon(94, 'Gengar', ['Ghost', 'Poison']),
  new Pokemon(200, 'Misdreavus', ['Ghost']),
  new Pokemon(429, 'Mismagius', ['Ghost']),
  new Pokemon(198, 'Murkrow', ['Dark', 'Flying']),
  new Pokemon(430, 'Honchkrow', ['Dark', 'Flying']),
  new Pokemon(431, 'Glameow', ['Normal']),
  new Pokemon(432, 'Purugly', ['Normal']),
  new Pokemon(118, 'Goldeen', ['Water']),
  new Pokemon(119, 'Seaking', ['Water']),
  new Pokemon(339, 'Barboach', ['Water', 'Ground']),
  new Pokemon(340, 'Whiscash', ['Water', 'Ground']),
  new Pokemon(433, 'Chingling', ['Psychic']),
  new Pokemon(358, 'Chimecho', ['Psychic']),
  new Pokemon(434, 'Stunky', ['Poison', 'Dark']),
  new Pokemon(435, 'Skuntank', ['Poison', 'Dark']),
  new Pokemon(307, 'Meditite', ['Fighting', 'Psychic']),
  new Pokemon(308, 'Medicham', ['Fighting', 'Psychic']),
  new Pokemon(436, 'Bronzor', ['Steel', 'Psychic']),
  new Pokemon(437, 'Bronzong', ['Steel', 'Psychic']),
  new Pokemon(77, 'Ponyta', ['Fire']),
  new Pokemon(78, 'Rapidash', ['Fire']),
  new Pokemon(438, 'Bonsly', ['Rock']),
  new Pokemon(185, 'Sudowoodo', ['Rock']),
  new Pokemon(439, 'Mime Jr.', ['Psychic', 'Fairy']),
  new Pokemon(122, 'Mr. Mime', ['Psychic', 'Fairy']),
  new Pokemon(440, 'Happiny', ['Normal']),
  new Pokemon(113, 'Chansey', ['Normal']),
  new Pokemon(242, 'Blissey', ['Normal']),
  new Pokemon(173, 'Cleffa', ['Fairy']),
  new Pokemon(35, 'Clefairy', ['Fairy']),
  new Pokemon(36, 'Clefable', ['Fairy']),
  new Pokemon(441, 'Chatot', ['Normal', 'Flying']),
  new Pokemon(172, 'Pichu', ['Electric']),
  new Pokemon(25, 'Pikachu', ['Electric']),
  new Pokemon(26, 'Raichu', ['Electric']),
  new Pokemon(163, 'Hoothoot', ['Normal', 'Flying']),
  new Pokemon(164, 'Noctowl', ['Normal', 'Flying']),
  new Pokemon(442, 'Spiritomb', ['Ghost', 'Dark']),
  new Pokemon(443, 'Gible', ['Dragon', 'Ground']),
  new Pokemon(444, 'Gabite', ['Dragon', 'Ground']),
  new Pokemon(445, 'Garchomp', ['Dragon', 'Ground']),
  new Pokemon(446, 'Munchlax', ['Normal']),
  new Pokemon(143, 'Snorlax', ['Normal']),
  new Pokemon(201, 'Unown', ['Psychic']),
  new Pokemon(447, 'Riolu', ['Fighting']),
  new Pokemon(448, 'Lucario', ['Fighting', 'Steel']),
  new Pokemon(194, 'Wooper', ['Water', 'Ground']),
  new Pokemon(195, 'Quagsire', ['Normal', 'Ground']),
  new Pokemon(278, 'Wingull', ['Water', 'Flying']),
  new Pokemon(279, 'Pelipper', ['Water', 'Flying']),
  new Pokemon(203, 'Girafarig', ['Normal', 'Psychic']),
  new Pokemon(449, 'Hippopotas', ['Ground']),
  new Pokemon(450, 'Hippowdon', ['Ground']),
  new Pokemon(298, 'Azurill', ['Normal']),
  new Pokemon(183, 'Marill', ['Water']),
  new Pokemon(184, 'Azumarill', ['Water']),
  new Pokemon(451, 'Skorupi', ['Poison', 'Bug']),
  new Pokemon(452, 'Drapion', ['Poison', 'Dark']),
  new Pokemon(453, 'Croagunk', ['Poison', 'Fighting']),
  new Pokemon(454, 'Toxicroak', ['Poison', 'Fighting']),
  new Pokemon(455, 'Carnivine', ['Grass']),
  new Pokemon(223, 'Remoraid', ['Water']),
  new Pokemon(224, 'Octillery', ['Water']),
  new Pokemon(456, 'Finneon', ['Water']),
  new Pokemon(457, 'Lumineon', ['Water']),
  new Pokemon(72, 'Tentacool', ['Water', 'Poison']),
  new Pokemon(73, 'Tentacruel', ['Water', 'Poison']),
  new Pokemon(349, 'Feebas', ['Water']),
  new Pokemon(350, 'Milotic', ['Water']),
  new Pokemon(458, 'Mantyke', ['Water', 'Flying']),
  new Pokemon(226, 'Mantine', ['Water', 'Flying']),
  new Pokemon(459, 'Snover', ['Grass', 'Ice']),
  new Pokemon(460, 'Abomasnow', ['Grass', 'Ice']),
  new Pokemon(215, 'Sneasel', ['Dark', 'Ice']),
  new Pokemon(461, 'Weavile', ['Dark', 'Ice']),
  new Pokemon(480, 'Uxie', ['Psychic'], ''),
  new Pokemon(481, 'Mesprit', ['Psychic']),
  new Pokemon(482, 'Azelf', ['Psychic']),
  new Pokemon(483, 'Dialga', ['Steel', 'Dragon']),
  new Pokemon(484, 'Palkia', ['Water', 'Dragon']),
  new Pokemon(490, 'Manaphy', ['Water']),
  new Pokemon(479, 'Rotom', ['Electric', 'Ghost']),
  new Pokemon(207, 'Gligar', ['Ground', 'Flying']),
  new Pokemon(472, 'Gliscor', ['Ground', 'Flying']),
  new Pokemon(299, 'Nosepass', ['Rock']),
  new Pokemon(476, 'Probopass', ['Rock', 'Steel']),
  new Pokemon(280, 'Ralts', ['Psychic']),
  new Pokemon(281, 'Kirlia', ['Psychic']),
  new Pokemon(282, 'Gardevoir', ['Psychic']),
  new Pokemon(475, 'Gallade', ['Psychic', 'Fighting']),
  new Pokemon(108, 'Lickitung', ['Normal']),
  new Pokemon(463, 'Lickilicky', ['Normal']),
  new Pokemon(133, 'Eevee', ['Normal']),
  new Pokemon(134, 'Vaporeon', ['Water']),
  new Pokemon(135, 'Jolteon', ['Electric']),
  new Pokemon(136, 'Flareon', ['Fire']),
  new Pokemon(196, 'Espeon', ['Psychic']),
  new Pokemon(197, 'Umbreon', ['Dark']),
  new Pokemon(470, 'Leafeon', ['Grass']),
  new Pokemon(471, 'Glaceon', ['Ice']),
  new Pokemon(333, 'Swablu', ['Normal', 'Flying']),
  new Pokemon(334, 'Altaria', ['Dragon', 'Flying']),
  new Pokemon(175, 'Togepi', ['Normal']),
  new Pokemon(176, 'Togetic', ['Normal', 'Flying']),
  new Pokemon(468, 'Togekiss', ['Normal', 'Flying']),
  new Pokemon(228, 'Houndour', ['Dark', 'Fire']),
  new Pokemon(229, 'Houndoom', ['Dark', 'Fire']),
  new Pokemon(81, 'Magnemite', ['Electric', 'Steel']),
  new Pokemon(82, 'Magneton', ['Electric', 'Steel']),
  new Pokemon(462, 'Magnezone', ['Electric', 'Steel']),
  new Pokemon(114, 'Tangela', ['Grass']),
  new Pokemon(465, 'Tangrowth', ['Grass']),
  new Pokemon(193, 'Yanma', ['Bug', 'Flying']),
  new Pokemon(469, 'Yanmega', ['Bug', 'Flying']),
  new Pokemon(357, 'Tropius', ['Grass', 'Flying']),
  new Pokemon(111, 'Rhyhorn', ['Ground', 'Rock']),
  new Pokemon(112, 'Rhydon', ['Ground', 'Rock']),
  new Pokemon(464, 'Rhyperior', ['Ground', 'Rock']),
  new Pokemon(355, 'Duskull', ['Ghost']),
  new Pokemon(356, 'Dusclops', ['Ghost']),
  new Pokemon(477, 'Dusknoir', ['Ghost']),
  new Pokemon(137, 'Porygon', ['Normal']),
  new Pokemon(233, 'Porygon2', ['Normal']),
  new Pokemon(474, 'Porygon-Z', ['Normal']),
  new Pokemon(123, 'Scyther', ['Bug', 'Flying']),
  new Pokemon(212, 'Scizor', ['Bug', 'Steel']),
  new Pokemon(239, 'Elekid', ['Electric']),
  new Pokemon(125, 'Electabuzz', ['Electric']),
  new Pokemon(466, 'Electivire', ['Electric']),
  new Pokemon(240, 'Magby', ['Fire']),
  new Pokemon(126, 'Magmar', ['Fire']),
  new Pokemon(467, 'Magmortar', ['Fire']),
  new Pokemon(220, 'Swinub', ['Ice', 'Ground']),
  new Pokemon(221, 'Piloswine', ['Ice', 'Ground']),
  new Pokemon(473, 'Mamoswine', ['Ice', 'Ground']),
  new Pokemon(361, 'Snorunt', ['Ice']),
  new Pokemon(362, 'Glalie', ['Ice']),
  new Pokemon(478, 'Froslass', ['Ice', 'Ghost']),
  new Pokemon(359, 'Absol', ['Dark']),
  new Pokemon(487, 'Giratina', ['Ghost', 'Dragon'])
]

function loadSinnoh() {
  $('#Center').text("The Sinnoh Pokémon List by Pokédex Number");
  $('#myInput').val('');
  $('#pokemon-container').empty();
  for (var display of pokemonList) {
    display.loadToPage();
    display.ShowTypes();
  }
}
